local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.kanagawa.paper-sunset")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.sunsetGold,
      insert = plt.autumnGreen,
      visual = plt.horizonViolet,
      replace = plt.flareRose,
      command = plt.emberOrange,
    },

    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.oldWhite,
      fg_dimmer = plt.mistGray,
      fg_dark = plt.sumiInk4,
      fg_reverse = plt.sumiInk0,
      bg_m4 = plt.sumiInk0,
      bg_m3 = plt.sumiInk0,
      bg_m2 = plt.sumiInk0,
      bg_m1 = plt.sumiInk1,
      bg_dim = plt.sumiInk1,
      bg = plt.sumiInk0,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = opts.gutter and plt.sumiInk1 or "none",
      bg_cursorline = plt.sumiInk3,
      bg_cursorline_alt = plt.sumiInk2,
      bg_search = plt.waveBlue1,
      bg_visual = plt.sumiInk3,
      bg_statusline = plt.sumiInk1,
      border = plt.sunsetGold,
      header1 = plt.sunsetGold,
      header2 = plt.horizonViolet,
      special = plt.flareRose,
      nontext = plt.sumiInk3,
      whitespace = plt.sumiInk4,
      win_separator = plt.sandTan,
      indent = plt.sumiInk2,
      indent_scope = plt.sunsetGold,
      picker = plt.flareRose,
      yank = plt.emberYellow,
      mark = plt.horizonViolet,
      scrollbar = plt.sumiInk4,
      tabline = {
        bg = plt.sumiInk0,
        fg_selected = plt.fujiWhite,
        bg_selected = plt.sumiInk2,
        fg_inactive = plt.mistGray,
        bg_inactive = plt.sumiInk0,
        fg_alternate = plt.horizonViolet,
        bg_alternate = plt.sumiInk0,
        indicator = plt.sunsetGold,
      },
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = "none",
        fg_border = plt.sumiInk4,
        bg_border = plt.sumiInk1,
        bg = plt.sumiInk1,
        bg_sel = plt.sumiInk3,
        bg_sbar = plt.sumiInk1,
        bg_thumb = plt.sumiInk4,
      },
      float = {
        fg = plt.oldWhite,
        bg = plt.sumiInk1,
        fg_border = plt.sumiInk4,
        bg_border = plt.sumiInk1,
      },
    },

    accent = {
      accent1 = plt.sunsetGold,
      accent2 = plt.horizonViolet,
      accent3 = plt.twilightPink,
      accent4 = plt.duskCoral,
      accent5 = plt.emberOrange,
      invert = plt.sumiInk3,
    },

    rainbow = {
      rainbow1 = plt.flareRose,
      rainbow2 = plt.duskCoral,
      rainbow3 = plt.emberOrange,
      rainbow4 = plt.sunsetGold,
      rainbow5 = plt.autumnGreen,
      rainbow6 = plt.waveAqua1,
      rainbow7 = plt.horizonViolet,
    },

    syn = {
      attribute = plt.sandTan,
      boolean = plt.waveAqua1,
      comment = plt.mistGray,
      constant = plt.sandTan,
      deprecated = plt.mistGray,
      func = plt.horizonViolet,
      identifier = plt.fujiWhite,
      keyword = plt.autumnRed,
      method = plt.horizonViolet,
      number = plt.sunsetGold,
      operator = plt.emberOrange,
      parameter = plt.oldWhite,
      preproc = plt.flareRose,
      punct = plt.emberOrange,
      regex = plt.waveAqua1,
      statement = plt.autumnRed,
      string = plt.twilightPink,
      symbol = plt.flareRose,
      type = plt.horizonViolet,
      variable = plt.fujiWhite,
      special = plt.flareRose,
      special2 = plt.emberOrange,
      special3 = plt.duskCoral,
    },

    vcs = {
      added = plt.autumnGreen,
      removed = plt.flareRose,
      changed = plt.sunsetGold,
    },

    diff = {
      add = plt.autumnGreen,
      change = plt.sunsetGold,
      delete = plt.flareRose,
      text = plt.waveAqua1,
    },

    diag = {
      ok = plt.autumnGreen,
      error = plt.flareRose,
      warning = plt.sunsetGold,
      info = plt.waveAqua1,
      hint = plt.duskCoral,
    },

    term = {
      black = plt.sumiInk0,
      red = plt.flareRose,
      green = plt.autumnGreen,
      yellow = plt.sunsetGold,
      blue = plt.waveBlue2,
      magenta = plt.horizonViolet,
      cyan = plt.waveAqua1,
      white = plt.oldWhite,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.flareRose):brighten(0.2):to_hex(),
      green_bright = color(plt.autumnGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.sunsetGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.waveBlue2):brighten(0.3):to_hex(),
      magenta_bright = color(plt.horizonViolet):brighten(0.2):to_hex(),
      cyan_bright = color(plt.waveAqua1):brighten(0.1):to_hex(),
      white_bright = color(plt.oldWhite):brighten(0.2):to_hex(),
      indexed1 = plt.emberYellow,
      indexed2 = plt.duskCoral,
    },

    treesitter = {
      ["@comment"] = plt.mistGray,
      ["@comment.documentation"] = plt.mistGray,
      ["@comment.error"] = plt.flareRose,
      ["@comment.warning"] = plt.sunsetGold,
      ["@comment.todo"] = plt.waveAqua1,
      ["@comment.note"] = plt.autumnGreen,

      ["@constant"] = plt.sandTan,
      ["@constant.builtin"] = plt.sandTan,
      ["@constant.macro"] = plt.emberYellow,

      ["@string"] = plt.twilightPink,
      ["@string.documentation"] = plt.twilightPink,
      ["@string.regex"] = plt.waveAqua1,
      ["@string.escape"] = plt.emberOrange,
      ["@string.special"] = plt.flareRose,
      ["@string.special.symbol"] = plt.flareRose,
      ["@string.special.url"] = plt.waveBlue2,
      ["@string.special.path"] = plt.twilightPink,

      ["@character"] = plt.twilightPink,
      ["@character.special"] = plt.emberOrange,

      ["@number"] = plt.sunsetGold,
      ["@number.float"] = plt.sunsetGold,

      ["@boolean"] = plt.waveAqua1,

      ["@function"] = plt.horizonViolet,
      ["@function.builtin"] = plt.horizonViolet,
      ["@function.call"] = plt.horizonViolet,
      ["@function.macro"] = plt.flareRose,
      ["@function.method"] = plt.horizonViolet,
      ["@function.method.call"] = plt.horizonViolet,

      ["@constructor"] = plt.horizonViolet,

      ["@parameter"] = plt.oldWhite,
      ["@parameter.builtin"] = plt.fujiWhite,

      ["@keyword"] = plt.autumnRed,
      ["@keyword.coroutine"] = plt.flareRose,
      ["@keyword.function"] = plt.autumnRed,
      ["@keyword.operator"] = plt.emberOrange,
      ["@keyword.return"] = plt.autumnRed,
      ["@keyword.import"] = plt.flareRose,
      ["@keyword.storage"] = plt.autumnRed,
      ["@keyword.repeat"] = plt.autumnRed,
      ["@keyword.conditional"] = plt.autumnRed,
      ["@keyword.exception"] = plt.flareRose,
      ["@keyword.directive"] = plt.flareRose,
      ["@keyword.directive.define"] = plt.flareRose,

      ["@conditional"] = plt.autumnRed,
      ["@conditional.ternary"] = plt.autumnRed,

      ["@repeat"] = plt.autumnRed,

      ["@label"] = plt.duskCoral,

      ["@operator"] = plt.emberOrange,

      ["@exception"] = plt.flareRose,

      ["@variable"] = plt.fujiWhite,
      ["@variable.builtin"] = plt.duskCoral,
      ["@variable.parameter"] = plt.oldWhite,
      ["@variable.member"] = plt.oldWhite,

      ["@type"] = plt.horizonViolet,
      ["@type.builtin"] = plt.horizonViolet,
      ["@type.definition"] = plt.horizonViolet,
      ["@type.qualifier"] = plt.autumnRed,

      ["@attribute"] = plt.sandTan,
      ["@attribute.builtin"] = plt.emberYellow,

      ["@property"] = plt.oldWhite,

      ["@field"] = plt.oldWhite,

      ["@module"] = plt.horizonViolet,
      ["@module.builtin"] = plt.horizonViolet,

      ["@namespace"] = plt.horizonViolet,
      ["@namespace.builtin"] = plt.horizonViolet,

      ["@punctuation.delimiter"] = plt.emberOrange,
      ["@punctuation.bracket"] = plt.sumiInk4,
      ["@punctuation.special"] = plt.flareRose,

      ["@tag"] = plt.autumnRed,
      ["@tag.attribute"] = plt.sandTan,
      ["@tag.delimiter"] = plt.emberOrange,
      ["@tag.builtin"] = plt.autumnRed,

      ["@markup.strong"] = { fg = plt.sunsetGold, bold = true },
      ["@markup.italic"] = { fg = plt.oldWhite, italic = true },
      ["@markup.strikethrough"] = { fg = plt.mistGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.oldWhite, underline = true },
      ["@markup.heading"] = plt.sunsetGold,
      ["@markup.heading.1"] = plt.sunsetGold,
      ["@markup.heading.2"] = plt.emberOrange,
      ["@markup.heading.3"] = plt.duskCoral,
      ["@markup.heading.4"] = plt.horizonViolet,
      ["@markup.heading.5"] = plt.twilightPink,
      ["@markup.heading.6"] = plt.waveAqua1,
      ["@markup.quote"] = plt.mistGray,
      ["@markup.math"] = plt.horizonViolet,
      ["@markup.link"] = plt.waveBlue2,
      ["@markup.link.label"] = plt.horizonViolet,
      ["@markup.link.url"] = plt.waveAqua1,
      ["@markup.raw"] = plt.twilightPink,
      ["@markup.raw.block"] = plt.twilightPink,
      ["@markup.list"] = plt.autumnRed,
      ["@markup.list.checked"] = plt.autumnGreen,
      ["@markup.list.unchecked"] = plt.mistGray,

      ["@diff.plus"] = plt.autumnGreen,
      ["@diff.minus"] = plt.flareRose,
      ["@diff.delta"] = plt.sunsetGold,

      ["@none"] = "none",
      ["@conceal"] = plt.sumiInk4,
      ["@spell"] = plt.fujiWhite,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.oldWhite,
      ["@constructor.python"] = plt.horizonViolet,
      ["@constructor.javascript"] = plt.horizonViolet,
      ["@constructor.typescript"] = plt.horizonViolet,
      ["@namespace.rust"] = plt.horizonViolet,
      ["@type.qualifier.rust"] = plt.autumnRed,
      ["@constant.macro.c"] = plt.emberYellow,
      ["@constant.macro.cpp"] = plt.emberYellow,
      ["@namespace.go"] = plt.horizonViolet,
      ["@property.css"] = plt.horizonViolet,
      ["@type.css"] = plt.autumnRed,
      ["@label.json"] = plt.horizonViolet,
      ["@field.yaml"] = plt.horizonViolet,
      ["@property.toml"] = plt.horizonViolet,
      ["@function.builtin.bash"] = plt.horizonViolet,
      ["@string.regexp"] = plt.waveAqua1,
      ["@character.special.regex"] = plt.emberOrange,
    },

    lsp = {
      ["@lsp.type.class"] = plt.horizonViolet,
      ["@lsp.type.interface"] = plt.horizonViolet,
      ["@lsp.type.struct"] = plt.horizonViolet,
      ["@lsp.type.enum"] = plt.horizonViolet,
      ["@lsp.type.enumMember"] = plt.sandTan,
      ["@lsp.type.property"] = plt.oldWhite,
      ["@lsp.type.namespace"] = plt.horizonViolet,

      ["@lsp.type.macro"] = plt.emberYellow,
      ["@lsp.type.decorator"] = plt.horizonViolet,

      ["@lsp.type.builtinType"] = plt.horizonViolet,
      ["@lsp.type.selfParameter"] = plt.duskCoral,
      ["@lsp.type.typeParameter"] = plt.horizonViolet,

      ["@lsp.type.array"] = plt.horizonViolet,
      ["@lsp.type.object"] = plt.horizonViolet,
      ["@lsp.type.key"] = plt.oldWhite,
      ["@lsp.type.null"] = plt.waveAqua1,
      ["@lsp.type.enumConstant"] = plt.sandTan,

      ["@lsp.type.event"] = plt.horizonViolet,
      ["@lsp.type.regexp"] = plt.waveAqua1,
      ["@lsp.type.unresolvedReference"] = plt.emberYellow,

      ["@lsp.mod.deprecated"] = { fg = plt.mistGray, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.sandTan,
      ["@lsp.mod.async"] = plt.autumnRed,
      ["@lsp.mod.static"] = plt.duskCoral,
      ["@lsp.mod.abstract"] = plt.horizonViolet,
      ["@lsp.mod.defaultLibrary"] = plt.horizonViolet,
      ["@lsp.mod.documentation"] = plt.mistGray,
    },
  }
end

return {
  name = "Kanagawa Paper – Sunset",
  author = "PrismPunk.nvim",
  description = "Soft dusk variant with warm highlights and muted shadows.",

  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInk1,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk4,
    base05 = palette.fujiWhite,
    base06 = palette.oldWhite,
    base07 = palette.softPaper,
    base08 = palette.flareRose,
    base09 = palette.duskCoral,
    base0A = palette.sunsetGold,
    base0B = palette.autumnGreen,
    base0C = palette.waveAqua1,
    base0D = palette.waveBlue2,
    base0E = palette.horizonViolet,
    base0F = palette.emberOrange,
  },

  palette = palette,
  get = M.get,
}
