-- return {
--   name = "Kanagawa Paper Dragon",
--   author = "Port from kanagawa-paper",
--   description = "Exact port of kanagawa-paper dragon theme",

local color = require("prismpunk.utils.color")

local palette = {
  -- Bg Shades
  sumiInkn1 = "#0f0f15",
  sumiInk0 = "#16161D",
  sumiInk1 = "#181820",
  sumiInk2 = "#1a1a22",
  sumiInk3 = "#1F1F28", -- ink bg
  sumiInk4 = "#2A2A37",
  sumiInk5 = "#363646",
  sumiInk6 = "#54546D",

  -- Popup and Floats
  waveBlue1 = "#223249",
  waveBlue2 = "#2D4F67",

  -- Diff and Git
  winterGreen = "#2B3328",
  winterYellow = "#49443C",
  winterRed = "#43242B",
  winterBlue = "#252535",
  autumnGreen = "#76946A",
  autumnRed = "#C34043",
  autumnYellow = "#DCA561",

  -- Diag
  samuraiRed = "#E82424",
  roninYellow = "#FF9E3B",
  waveAqua1 = "#6A9589",
  dragonBlue = "#658594",

  -- Fg and Comments
  oldWhite = "#C8C093",
  fujiWhite = "#DCD7BA",
  fujiGray = "#727169",

  oniViolet = "#957FB8",
  oniViolet2 = "#b8b4d0",
  springViolet1 = "#938AA9",
  springViolet2 = "#9CABCA",
  springBlue = "#7FB4CA",
  crystalBlue = "#7E9CD8",
  lightBlue = "#A3D4D5",
  waveAqua2 = "#7AA89F",

  springGreen = "#98BB6C",
  boatYellow1 = "#938056",
  boatYellow2 = "#C0A36E",
  carpYellow = "#E6C384",

  sakuraPink = "#D27E99",
  waveRed = "#E46876",
  peachRed = "#FF5D62",
  surimiOrange = "#FFA066",
  katanaGray = "#717C7C",

  dragonAqua = "#8ea49e",
  dragonAsh = "#737c73",
  dragonBlack0 = "#0d0c0c",
  dragonBlack1 = "#12120f",
  dragonBlack2 = "#1D1C19",
  dragonBlack3 = "#181616",
  dragonBlack4 = "#282727",
  dragonBlack5 = "#393836",
  dragonBlack6 = "#625e5a",
  dragonBlue2 = "#859fac",
  dragonBlue3 = "#708e9e",
  dragonBlue4 = "#5d7a88",
  dragonBlue5 = "#435965",
  dragonGray = "#a6a69c",
  dragonGray2 = "#9e9b93",
  dragonGray3 = "#7a8382",
  dragonGreen = "#699469",
  dragonGreen2 = "#8a9a7b",
  dragonOrange = "#b6927b",
  dragonOrange2 = "#b98d7b",
  dragonPink = "#a292a3",
  dragonRed = "#c4746e",
  dragonTeal = "#949fb5",
  dragonViolet = "#8992a7",
  dragonWhite = "#c5c9c5",
  dragonYellow = "#c4b28a", -- ink primary accent

  canvasAqua1 = "#7b958e",
  canvasAsh1 = "#637263",
  canvasBlue1 = "#809ba7",
  canvasBlue2 = "#6b8998",
  canvasBlue3 = "#577888",
  canvasBlue4 = "#516e7d",
  canvasBlue5 = "#3a515e",
  canvasCyan1 = "#4a905d",
  canvasGray1 = "#b7b7a9",
  canvasGray2 = "#8e8a80",
  canvasGray3 = "#758380",
  canvasGreen1 = "#7e9579",
  canvasGreen2 = "#7a8c6a",
  canvasOrange1 = "#b28d77",
  canvasOrange2 = "#a8826a",
  canvasPink1 = "#9e7e98",
  canvasPink2 = "#c1b4c1",
  canvasPink3 = "#d4cdd4",
  canvasRed1 = "#c27672",
  canvasTeal1 = "#7e8faf", -- canvas primary accent
  canvasViolet1 = "#7880a5",
  canvasViolet2 = "#9ba1bf",
  canvasYellow1 = "#a7956a",
  canvasYellow2 = "#b4a88a",
  canvasWhite1 = "#cbc8bc",
  canvasWhite2 = "#d1cfc5",
  canvasWhite3 = "#d8d8d2",
  canvasWhite4 = "#e1e1de", -- canvas bg
  canvasWhite5 = "#e6e6e3",
  canvasWhite6 = "#ecece8",

  lotusInk0 = "#3d3d5e",
  lotusInk1 = "#545464",
  lotusInk2 = "#43436c",
  lotusGray = "#dcd7ba",
  lotusGray2 = "#716e61",
  lotusGray3 = "#8a8980",
  lotusWhite0 = "#d5cea3",
  lotusWhite1 = "#dcd5ac",
  lotusWhite2 = "#e5ddb0",
  lotusWhite3 = "#f2ecbc",
  lotusWhite4 = "#e7dba0",
  lotusWhite5 = "#e4d794",
  lotusViolet1 = "#a09cac",
  lotusViolet2 = "#766b90",
  lotusViolet3 = "#c9cbd1",
  lotusViolet4 = "#624c83",
  lotusBlue1 = "#c7d7e0",
  lotusBlue2 = "#b5cbd2",
  lotusBlue3 = "#9fb5c9",
  lotusBlue4 = "#4d699b",
  lotusBlue5 = "#5d57a3",
  lotusGreen = "#6f894e",
  lotusGreen2 = "#6e915f",
  lotusGreen3 = "#b7d0ae",
  lotusPink = "#b35b79",
  lotusOrange = "#cc6d00",
  lotusOrange2 = "#e98a00",
  lotusYellow = "#77713f",
  lotusYellow2 = "#836f4a",
  lotusYellow3 = "#de9800",
  lotusYellow4 = "#f9d791",
  lotusRed = "#c84053",
  lotusRed2 = "#d7474b",
  lotusRed3 = "#e82424",
  lotusRed4 = "#d9a594",
  lotusAqua = "#597b75",
  lotusAqua2 = "#5e857a",
  lotusTeal1 = "#4e8ca2",
  lotusTeal2 = "#6693bf",
  lotusTeal3 = "#5a7785",
  lotusCyan = "#d7e3d8",
}

local M = {}

---@param opts table
---@param palette table
---@return table
---@diagnostic disable-next-line: redefined-local
M.get = function(opts, palette)
  return {
    modes = {
      normal = palette.dragonYellow,
      insert = palette.dragonRed,
      visual = palette.springViolet1,
      replace = palette.dragonRed,
      command = palette.dragonYellow,
    },

    ui = {
      fg = palette.fujiWhite,
      fg_dim = palette.dragonGray2,
      fg_dimmer = palette.dragonBlack5,
      fg_dark = palette.dragonBlack3,
      fg_reverse = palette.dragonBlack2,
      fg_bright = palette.dragonWhite,

      bg = palette.sumiInk3,
      bg_m4 = palette.sumiInkn1,
      bg_m3 = palette.sumiInk0,
      bg_m2 = palette.sumiInk1,
      bg_m1 = palette.sumiInk2,
      bg_dim = palette.sumiInk1,
      bg_p1 = palette.sumiInk4,
      bg_p2 = palette.sumiInk5,
      bg_highlight = palette.sumiInk5,

      bg_gutter = opts.gutter and palette.sumiInk4 or "none",
      bg_cursorline = palette.sumiInk4,
      bg_cursorline_alt = palette.sumiInk5,
      bg_search = palette.springViolet1,
      bg_visual = palette.sumiInk5,
      bg_statusline = palette.sumiInk4,

      border = palette.dragonBlack6,
      header1 = palette.dragonViolet,
      header2 = palette.dragonOrange,
      special = palette.dragonAqua,
      nontext = palette.sumiInk6,
      whitespace = palette.sumiInk6,
      win_separator = palette.dragonViolet,
      indent = palette.sumiInk5,
      indent_scope = palette.dragonViolet,
      picker = palette.dragonRed,
      yank = palette.sumiInk6,
      mark = palette.waveAqua2,
      scrollbar = palette.sumiInk5,

      -- Line numbers
      line_nr = palette.sumiInk6,
      line_nr_dim = palette.sumiInk5,
      line_nr_active = palette.dragonYellow,

      -- Selection and cursor
      selection = palette.sumiInk5,
      cursorline = palette.sumiInk4,

      tabline = {
        bg = palette.sumiInk0,
        fg_selected = palette.dragonWhite,
        bg_selected = palette.sumiInk3,
        fg_inactive = palette.dragonBlack5,
        bg_inactive = palette.sumiInk0,
        fg_alternate = palette.dragonPink,
        bg_alternate = palette.sumiInk0,
        indicator = palette.dragonBlue,
      },
      pmenu = {
        fg = palette.fujiWhite,
        fg_sel = "none",
        fg_border = palette.sumiInk5,
        bg_border = palette.sumiInk4,
        bg = palette.sumiInk4,
        bg_sel = palette.sumiInk5,
        bg_sbar = palette.sumiInk4,
        bg_thumb = palette.sumiInk6,
      },
      float = {
        fg = palette.oldWhite,
        bg = palette.sumiInk4,
        fg_border = palette.sumiInk5,
        bg_border = palette.sumiInk4,
      },
    },

    accent = {
      accent1 = palette.dragonBlue,
      accent2 = palette.dragonOrange,
      accent3 = palette.waveAqua1,
      accent4 = palette.dragonGray3,
      accent5 = palette.dragonRed,
      invert = palette.sumiInk4,
    },

    rainbow = {
      rainbow1 = palette.dragonRed,
      rainbow2 = palette.dragonPink,
      rainbow3 = palette.dragonBlue,
      rainbow4 = palette.dragonOrange2,
      rainbow5 = palette.dragonGreen,
      rainbow6 = palette.dragonAsh,
      rainbow7 = palette.dragonTeal,
    },

    syn = {
      attribute = palette.dragonYellow,
      comment = palette.fujiGray,
      constant = palette.dragonOrange,
      deprecated = palette.katanaGray,
      func = palette.dragonBlue2,
      identifier = palette.dragonYellow,
      keyword = palette.dragonPink,
      member = palette.dragonRed,
      number = palette.dragonPink,
      operator = palette.dragonRed,
      parameter = palette.dragonGray,
      preproc = palette.dragonRed,
      punct = palette.dragonGray2,
      regex = palette.dragonRed,
      statement = palette.dragonViolet,
      string = palette.dragonGreen2,
      symbol = palette.dragonRed,
      type = palette.dragonAqua,
      variable = "none",
      special = palette.dragonYellow,
      special1 = palette.dragonYellow,
      special2 = palette.dragonRed,
      special3 = palette.springViolet1,
      boolean = palette.dragonPink,
    },

    vcs = {
      added = palette.dragonGreen,
      added_light = color(palette.dragonGreen):blend(palette.sumiInk3, 0.9):to_hex(),
      removed = palette.dragonRed,
      removed_light = color(palette.dragonRed):blend(palette.sumiInk3, 0.9):to_hex(),
      changed = palette.dragonYellow,
      changed_light = color(palette.dragonYellow):blend(palette.sumiInk3, 0.9):to_hex(),
    },

    git = {
      add = palette.dragonGreen,
      add_inline = color(palette.dragonGreen):blend(palette.sumiInk3, 0.8):to_hex(),
      delete = palette.dragonRed,
      delete_inline = color(palette.dragonRed):blend(palette.sumiInk3, 0.8):to_hex(),
      change = palette.dragonYellow,
      change_inline = color(palette.dragonYellow):blend(palette.sumiInk3, 0.8):to_hex(),
    },

    diff = {
      add = palette.dragonGreen,
      add_light = color(palette.dragonGreen):blend(palette.sumiInk3, 0.9):to_hex(),
      delete = palette.dragonRed,
      delete_light = color(palette.dragonRed):blend(palette.sumiInk3, 0.9):to_hex(),
      change = palette.dragonYellow,
      change_light = color(palette.dragonYellow):blend(palette.sumiInk3, 0.9):to_hex(),
      text = palette.dragonBlue,
      text_light = color(palette.dragonBlue):blend(palette.sumiInk3, 0.9):to_hex(),
    },

    diag = {
      ok = palette.dragonGreen,
      ok_light = color(palette.dragonGreen):blend(palette.sumiInk3, 0.92):to_hex(),
      error = palette.dragonRed,
      error_light = color(palette.dragonRed):blend(palette.sumiInk3, 0.92):to_hex(),
      warning = palette.dragonYellow,
      warning_light = color(palette.dragonYellow):blend(palette.sumiInk3, 0.92):to_hex(),
      info = palette.dragonBlue,
      info_light = color(palette.dragonBlue):blend(palette.sumiInk3, 0.92):to_hex(),
      hint = palette.dragonAqua,
      hint_light = color(palette.dragonAqua):blend(palette.sumiInk3, 0.92):to_hex(),
    },

    term = {
      black = palette.dragonBlack5,
      red = palette.dragonRed,
      green = palette.dragonGreen,
      yellow = palette.dragonYellow,
      blue = palette.dragonBlue5,
      magenta = palette.dragonPink,
      cyan = palette.dragonAqua,
      white = palette.oldWhite,
      black_bright = color(palette.dragonBlack5):brighten(0.6):to_hex(),
      red_bright = color(palette.dragonRed):brighten(0.2):to_hex(),
      green_bright = color(palette.dragonGreen):brighten(0.1):to_hex(),
      yellow_bright = color(palette.dragonYellow):brighten(0.2):to_hex(),
      blue_bright = color(palette.dragonBlue5):brighten(0.3):to_hex(),
      magenta_bright = color(palette.dragonPink):brighten(0.2):to_hex(),
      cyan_bright = color(palette.dragonAqua):brighten(0.1):to_hex(),
      white_bright = color(palette.oldWhite):brighten(0.2):to_hex(),
      indexed1 = palette.dragonOrange,
      indexed2 = palette.dragonRed,
    },
  }
end

return {
  name = "Kanagawa Paper - Dragon",
  author = "Kanagawa Paper",
  description = "Dark theme inspired by the colors of the dragon",

  base16 = {
    base00 = palette.sumiInk3,
    base01 = palette.sumiInk4,
    base02 = palette.sumiInk5,
    base03 = palette.sumiInk6,
    base04 = palette.dragonGray2,
    base05 = palette.fujiWhite,
    base06 = palette.oldWhite,
    base07 = palette.dragonWhite,
    base08 = palette.dragonRed,
    base09 = palette.dragonOrange,
    base0A = palette.dragonYellow,
    base0B = palette.dragonGreen,
    base0C = palette.dragonAqua,
    base0D = palette.dragonBlue,
    base0E = palette.dragonViolet,
    base0F = palette.dragonPink,
  },

  palette = palette,

  get = M.get,
}
