local palette = {
    sumiInk0     = "#0B0A10",
    sumiInk1     = "#16151E",
    sumiInk2     = "#1F1D27",
    sumiInk3     = "#2A2834",
    sumiInk4     = "#34323E",
    sumiInk5     = "#3F3D4B",
    sumiInk6     = "#4B4858",

    fujiWhite    = "#DCD7BA",
    oldWhite     = "#C8C093",
    dragonGray   = "#727169",
    dragonGray2  = "#9C9A91",
    dragonBlack2 = "#1C1B24",
    dragonBlack3 = "#1A1921",
    dragonBlack5 = "#131217",
    dragonBlack6 = "#0E0D12",

    dragonRed      = "#C84053",
    dragonPink     = "#D16D9E",
    dragonYellow   = "#C0A36E",
    dragonOrange   = "#FFA066",
    dragonGreen    = "#76946A",
    dragonBlue     = "#7E9CD8",
    dragonViolet   = "#957FB8",
    dragonAqua     = "#6A9589",
}

return {
    name = "Kanagawa Paper – Edo",
    author = "PrismPunk.nvim",
    description = "Dark ink and soft paper tones inspired by Kanagawa-Paper, translated into Pantheon format.",

    base16 = {
        base00 = palette.sumiInk0,
        base01 = palette.sumiInk1,
        base02 = palette.sumiInk2,
        base03 = palette.sumiInk3,
        base04 = palette.sumiInk4,
        base05 = palette.dragonGray,
        base06 = palette.fujiWhite,
        base07 = palette.oldWhite,
        base08 = palette.dragonRed,
        base09 = palette.dragonOrange,
        base0A = palette.dragonYellow,
        base0B = palette.dragonGreen,
        base0C = palette.dragonAqua,
        base0D = palette.dragonBlue,
        base0E = palette.dragonViolet,
        base0F = palette.dragonPink,
    },

    palette = palette,

    semantic = {
        syn = {
            string        = palette.dragonGreen,
            number        = palette.dragonPink,
            boolean       = palette.dragonAqua,
            keyword       = palette.dragonPink,
            operator      = palette.dragonRed,
            func          = palette.dragonBlue,
            type          = palette.dragonAqua,
            variable      = palette.fujiWhite,
            comment       = palette.dragonGray2,
            constant      = palette.dragonOrange,
            special       = palette.dragonYellow,
            string_escape = palette.dragonYellow,
            type_builtin  = palette.dragonViolet,
            method        = palette.dragonBlue,
            attribute     = palette.dragonYellow,
            punctuation   = palette.dragonGray,
        },

        ui = {
            bg             = palette.sumiInk0,
            bg_dim         = palette.sumiInk1,
            bg_highlight   = palette.sumiInk2,
            fg             = palette.fujiWhite,
            fg_dim         = palette.dragonGray2,
            fg_bright      = palette.oldWhite,
            border         = palette.dragonBlack6,
            float          = palette.sumiInk3,
            selection      = palette.sumiInk4,
            cursorline     = palette.sumiInk3,
            line_nr        = palette.dragonGray,
            line_nr_active = palette.dragonBlue,
            line_nr_dim    = palette.dragonGray2,
            nontext        = palette.sumiInk5,
            msg_area       = palette.sumiInk4,
            mode_msg       = palette.dragonYellow,
            title          = palette.dragonViolet,
            spell_bad      = palette.dragonRed,
            spell_cap      = palette.dragonYellow,
            spell_rare     = palette.dragonBlue,
            spell_local    = palette.dragonAqua,
            folded         = palette.dragonGray2,
            fold_column    = palette.sumiInk4,
        },

        diag = {
            error               = palette.dragonRed,
            warning             = palette.dragonYellow,
            info                = palette.dragonBlue,
            hint                = palette.dragonAqua,
            ok                  = palette.dragonGreen,
            virtual_text_error   = palette.dragonRed,
            virtual_text_warning = palette.dragonYellow,
            virtual_text_info    = palette.dragonBlue,
            virtual_text_hint    = palette.dragonAqua,
            virtual_text_ok      = palette.dragonGreen,
        },

        git = {
            add           = palette.dragonGreen,
            change        = palette.dragonYellow,
            delete        = palette.dragonRed,
            add_inline    = palette.dragonGreen,
            change_inline = palette.dragonOrange,
            delete_inline = palette.dragonRed,
        },

        diff = {
            add    = palette.dragonGreen,
            change = palette.dragonYellow,
            delete = palette.dragonRed,
            text   = palette.dragonBlue,
        },
    },
}
