local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.kanagawa.paper-dawn")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.autumnRed,
      insert = plt.autumnGreen,
      visual = plt.waveBlue1,
      replace = plt.paleCoral,
      command = plt.mellowGold,
    },

    ui = {
      fg = plt.sumiInkSoft,
      fg_dim = plt.graphiteGray,
      fg_dimmer = plt.inkGray,
      fg_dark = plt.earlyMist,
      fg_reverse = plt.paperWhite,
      bg_m4 = plt.paperWhite,
      bg_m3 = plt.paperWhite,
      bg_m2 = plt.paperWhite,
      bg_m1 = plt.lightBeige,
      bg_dim = plt.lightBeige,
      bg = plt.paperWhite,
      bg_p1 = plt.warmIvory,
      bg_p2 = plt.shadowBeige,
      bg_gutter = opts.gutter and plt.lightBeige or "none",
      bg_cursorline = plt.lightBeige,
      bg_cursorline_alt = plt.warmIvory,
      bg_search = plt.amberDawn,
      bg_visual = plt.shadowBeige,
      bg_statusline = plt.warmIvory,
      border = plt.sandTan,
      header1 = plt.autumnRed,
      header2 = plt.springViolet2,
      special = plt.blushPink,
      nontext = plt.shadowBeige,
      whitespace = plt.inkGray,
      win_separator = plt.inkGray,
      indent = plt.warmIvory,
      indent_scope = plt.sandTan,
      picker = plt.paleCoral,
      yank = plt.waveAqua1,
      mark = plt.springViolet1,
      scrollbar = plt.inkGray,
      tabline = {
        bg = plt.paperWhite,
        fg_selected = plt.sumiInkSoft,
        bg_selected = plt.warmIvory,
        fg_inactive = plt.inkGray,
        bg_inactive = plt.paperWhite,
        fg_alternate = plt.waveBlue1,
        bg_alternate = plt.paperWhite,
        indicator = plt.autumnRed,
      },
      pmenu = {
        fg = plt.sumiInkSoft,
        fg_sel = "none",
        fg_border = plt.inkGray,
        bg_border = plt.warmIvory,
        bg = plt.warmIvory,
        bg_sel = plt.shadowBeige,
        bg_sbar = plt.warmIvory,
        bg_thumb = plt.inkGray,
      },
      float = {
        fg = plt.graphiteGray,
        bg = plt.warmIvory,
        fg_border = plt.inkGray,
        bg_border = plt.warmIvory,
      },
    },

    accent = {
      accent1 = plt.autumnRed,
      accent2 = plt.mellowGold,
      accent3 = plt.sandTan,
      accent4 = plt.waveBlue1,
      accent5 = plt.springViolet1,
      invert = plt.shadowBeige,
    },

    rainbow = {
      rainbow1 = plt.autumnRed,
      rainbow2 = plt.mellowGold,
      rainbow3 = plt.amberDawn,
      rainbow4 = plt.autumnGreen,
      rainbow5 = plt.waveBlue1,
      rainbow6 = plt.waveAqua1,
      rainbow7 = plt.springViolet1,
    },

    syn = {
      attribute = plt.sandTan,
      boolean = plt.waveAqua1,
      comment = plt.earlyMist,
      constant = plt.sandTan,
      deprecated = plt.inkGray,
      func = plt.waveBlue1,
      identifier = plt.graphiteGray,
      keyword = plt.autumnRed,
      method = plt.waveBlue1,
      number = plt.mellowGold,
      operator = plt.mellowGold,
      parameter = plt.graphiteGray,
      preproc = plt.blushPink,
      punct = plt.inkGray,
      regex = plt.waveAqua1,
      statement = plt.autumnRed,
      string = plt.paleCoral,
      symbol = plt.blushPink,
      type = plt.springViolet1,
      variable = plt.graphiteGray,
      special = plt.blushPink,
      special2 = plt.mellowGold,
      special3 = plt.springViolet2,
    },

    vcs = {
      added = plt.autumnGreen,
      removed = plt.autumnRed,
      changed = plt.mellowGold,
    },

    diff = {
      add = plt.autumnGreen,
      change = plt.mellowGold,
      delete = plt.autumnRed,
      text = plt.morningSky,
    },

    diag = {
      ok = plt.waveAqua1,
      error = plt.autumnRed,
      warning = plt.mellowGold,
      info = plt.morningSky,
      hint = plt.autumnGreen,
    },

    term = {
      black = plt.shadowBeige,
      red = plt.autumnRed,
      green = plt.autumnGreen,
      yellow = plt.mellowGold,
      blue = plt.waveBlue1,
      magenta = plt.springViolet1,
      cyan = plt.waveAqua1,
      white = plt.graphiteGray,
      black_bright = color(plt.shadowBeige):darken(0.2):to_hex(),
      red_bright = color(plt.autumnRed):brighten(0.2):to_hex(),
      green_bright = color(plt.autumnGreen):brighten(0.2):to_hex(),
      yellow_bright = color(plt.mellowGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.waveBlue1):brighten(0.2):to_hex(),
      magenta_bright = color(plt.springViolet1):brighten(0.2):to_hex(),
      cyan_bright = color(plt.waveAqua1):brighten(0.2):to_hex(),
      white_bright = color(plt.graphiteGray):brighten(0.2):to_hex(),
      indexed1 = plt.paleCoral,
      indexed2 = plt.blushPink,
    },

    treesitter = {
      ["@comment"] = plt.earlyMist,
      ["@comment.documentation"] = plt.earlyMist,
      ["@comment.error"] = plt.autumnRed,
      ["@comment.warning"] = plt.mellowGold,
      ["@comment.todo"] = plt.morningSky,
      ["@comment.note"] = plt.autumnGreen,

      ["@constant"] = plt.sandTan,
      ["@constant.builtin"] = plt.sandTan,
      ["@constant.macro"] = plt.mellowGold,

      ["@string"] = plt.paleCoral,
      ["@string.documentation"] = plt.paleCoral,
      ["@string.regex"] = plt.waveAqua1,
      ["@string.escape"] = plt.mellowGold,
      ["@string.special"] = plt.blushPink,
      ["@string.special.symbol"] = plt.blushPink,
      ["@string.special.url"] = plt.waveAqua1,
      ["@string.special.path"] = plt.waveBlue1,

      ["@character"] = plt.paleCoral,
      ["@character.special"] = plt.mellowGold,

      ["@number"] = plt.mellowGold,
      ["@number.float"] = plt.mellowGold,

      ["@boolean"] = plt.waveAqua1,

      ["@function"] = plt.waveBlue1,
      ["@function.builtin"] = plt.waveBlue1,
      ["@function.call"] = plt.waveBlue1,
      ["@function.macro"] = plt.blushPink,
      ["@function.method"] = plt.waveBlue1,
      ["@function.method.call"] = plt.waveBlue1,

      ["@constructor"] = plt.springViolet1,

      ["@parameter"] = plt.graphiteGray,
      ["@parameter.builtin"] = plt.inkGray,

      ["@keyword"] = plt.autumnRed,
      ["@keyword.coroutine"] = plt.roseDust,
      ["@keyword.function"] = plt.autumnRed,
      ["@keyword.operator"] = plt.mellowGold,
      ["@keyword.return"] = plt.autumnRed,
      ["@keyword.import"] = plt.blushPink,
      ["@keyword.storage"] = plt.autumnRed,
      ["@keyword.repeat"] = plt.autumnRed,
      ["@keyword.conditional"] = plt.autumnRed,
      ["@keyword.exception"] = plt.paleCoral,
      ["@keyword.directive"] = plt.blushPink,
      ["@keyword.directive.define"] = plt.blushPink,

      ["@conditional"] = plt.autumnRed,
      ["@conditional.ternary"] = plt.autumnRed,

      ["@repeat"] = plt.autumnRed,

      ["@label"] = plt.roseDust,

      ["@operator"] = plt.mellowGold,

      ["@exception"] = plt.paleCoral,

      ["@variable"] = plt.graphiteGray,
      ["@variable.builtin"] = plt.roseDust,
      ["@variable.parameter"] = plt.graphiteGray,
      ["@variable.member"] = plt.inkGray,

      ["@type"] = plt.springViolet1,
      ["@type.builtin"] = plt.springViolet1,
      ["@type.definition"] = plt.springViolet1,
      ["@type.qualifier"] = plt.autumnRed,

      ["@attribute"] = plt.sandTan,
      ["@attribute.builtin"] = plt.mellowGold,

      ["@property"] = plt.inkGray,

      ["@field"] = plt.inkGray,

      ["@module"] = plt.springViolet1,
      ["@module.builtin"] = plt.springViolet1,

      ["@namespace"] = plt.springViolet1,
      ["@namespace.builtin"] = plt.springViolet1,

      ["@punctuation.delimiter"] = plt.inkGray,
      ["@punctuation.bracket"] = plt.inkGray,
      ["@punctuation.special"] = plt.blushPink,

      ["@tag"] = plt.autumnRed,
      ["@tag.attribute"] = plt.sandTan,
      ["@tag.delimiter"] = plt.inkGray,
      ["@tag.builtin"] = plt.autumnRed,

      ["@markup.strong"] = { fg = plt.autumnRed, bold = true },
      ["@markup.italic"] = { fg = plt.inkGray, italic = true },
      ["@markup.strikethrough"] = { fg = plt.earlyMist, strikethrough = true },
      ["@markup.underline"] = { fg = plt.inkGray, underline = true },
      ["@markup.heading"] = plt.autumnRed,
      ["@markup.heading.1"] = plt.autumnRed,
      ["@markup.heading.2"] = plt.mellowGold,
      ["@markup.heading.3"] = plt.amberDawn,
      ["@markup.heading.4"] = plt.autumnGreen,
      ["@markup.heading.5"] = plt.waveBlue1,
      ["@markup.heading.6"] = plt.springViolet1,
      ["@markup.quote"] = plt.earlyMist,
      ["@markup.math"] = plt.springViolet1,
      ["@markup.link"] = plt.waveAqua1,
      ["@markup.link.label"] = plt.waveBlue1,
      ["@markup.link.url"] = plt.waveAqua1,
      ["@markup.raw"] = plt.paleCoral,
      ["@markup.raw.block"] = plt.paleCoral,
      ["@markup.list"] = plt.autumnRed,
      ["@markup.list.checked"] = plt.autumnGreen,
      ["@markup.list.unchecked"] = plt.inkGray,

      ["@diff.plus"] = plt.autumnGreen,
      ["@diff.minus"] = plt.autumnRed,
      ["@diff.delta"] = plt.mellowGold,

      ["@none"] = "none",
      ["@conceal"] = plt.inkGray,
      ["@spell"] = plt.graphiteGray,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.inkGray,
      ["@constructor.python"] = plt.springViolet1,
      ["@constructor.javascript"] = plt.springViolet1,
      ["@constructor.typescript"] = plt.springViolet1,
      ["@namespace.rust"] = plt.springViolet1,
      ["@type.qualifier.rust"] = plt.autumnRed,
      ["@constant.macro.c"] = plt.mellowGold,
      ["@constant.macro.cpp"] = plt.mellowGold,
      ["@namespace.go"] = plt.springViolet1,
      ["@property.css"] = plt.waveBlue1,
      ["@type.css"] = plt.autumnRed,
      ["@label.json"] = plt.waveBlue1,
      ["@field.yaml"] = plt.waveBlue1,
      ["@property.toml"] = plt.waveBlue1,
      ["@function.builtin.bash"] = plt.waveBlue1,
      ["@string.regexp"] = plt.waveAqua1,
      ["@character.special.regex"] = plt.mellowGold,
    },

    lsp = {
      ["@lsp.type.class"] = plt.springViolet1,
      ["@lsp.type.interface"] = plt.springViolet1,
      ["@lsp.type.struct"] = plt.springViolet1,
      ["@lsp.type.enum"] = plt.springViolet1,
      ["@lsp.type.enumMember"] = plt.sandTan,
      ["@lsp.type.property"] = plt.inkGray,
      ["@lsp.type.namespace"] = plt.springViolet1,

      ["@lsp.type.macro"] = plt.mellowGold,
      ["@lsp.type.decorator"] = plt.springViolet1,

      ["@lsp.type.builtinType"] = plt.springViolet1,
      ["@lsp.type.selfParameter"] = plt.roseDust,
      ["@lsp.type.typeParameter"] = plt.springViolet1,

      ["@lsp.type.array"] = plt.springViolet1,
      ["@lsp.type.object"] = plt.springViolet1,
      ["@lsp.type.key"] = plt.inkGray,
      ["@lsp.type.null"] = plt.waveAqua1,
      ["@lsp.type.enumConstant"] = plt.sandTan,

      ["@lsp.type.event"] = plt.springViolet1,
      ["@lsp.type.regexp"] = plt.waveAqua1,
      ["@lsp.type.unresolvedReference"] = plt.mellowGold,

      ["@lsp.mod.deprecated"] = { fg = plt.inkGray, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.sandTan,
      ["@lsp.mod.async"] = plt.autumnRed,
      ["@lsp.mod.static"] = plt.roseDust,
      ["@lsp.mod.abstract"] = plt.springViolet1,
      ["@lsp.mod.defaultLibrary"] = plt.springViolet1,
      ["@lsp.mod.documentation"] = plt.earlyMist,
    },
  }
end

return {
  name = "Kanagawa Paper – Dawn",
  author = "PrismPunk.nvim",
  description = "Light mode – serene parchment with soft warmth and subtle ink contrast.",

  base16 = {
    base00 = palette.paperWhite,
    base01 = palette.lightBeige,
    base02 = palette.warmIvory,
    base03 = palette.shadowBeige,
    base04 = palette.inkGray,
    base05 = palette.graphiteGray,
    base06 = palette.sumiInkSoft,
    base07 = palette.springViolet2,
    base08 = palette.autumnRed,
    base09 = palette.mellowGold,
    base0A = palette.amberDawn,
    base0B = palette.autumnGreen,
    base0C = palette.waveAqua1,
    base0D = palette.waveBlue1,
    base0E = palette.springViolet1,
    base0F = palette.sandTan,
  },

  palette = palette,
  get = M.get,
}
