local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.dc.watchmen.dr-manhattan")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.quantumBlueCore,
      insert = plt.nuclearGlow,
      visual = plt.atomicCyan,
      replace = plt.martianRed,
      command = plt.hydrogenWhite,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.bg_alt3,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.detachedGray,
      header1 = plt.quantumBlueBright,
      header2 = plt.hydrogenWhite,
      special = plt.atomicCyan,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.detachedGray,
      indent = plt.bg_lighter,
      indent_scope = plt.quantumBlueCore,
      picker = plt.omniscientViolet,
      yank = plt.nuclearGlowBright,
      mark = plt.tachyonBlue,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.quantumBlueBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.quantumBlueCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.detachedGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.detachedGrayLight,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.detachedGray,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.quantumBlueCore,
      accent2 = plt.nuclearGlow,
      accent3 = plt.atomicCyan,
      accent4 = plt.hydrogenWhite,
      accent5 = plt.timelessPurple,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.quantumBlueBright,
      rainbow2 = plt.nuclearGlowBright,
      rainbow3 = plt.atomicCyanBright,
      rainbow4 = plt.hydrogenWhiteBright,
      rainbow5 = plt.timelessPurpleBright,
      rainbow6 = plt.omniscientVioletBright,
      rainbow7 = plt.tachyonBlueBright,
    },

    syn = {
      attribute = plt.hydrogenWhite,
      boolean = plt.atomicCyan,
      comment = plt.detachedGray,
      constant = plt.hydrogenWhiteCore,
      deprecated = plt.detachedGrayDark,
      func = plt.nuclearGlow,
      identifier = plt.fg_lightest,
      keyword = plt.quantumBlueCore,
      method = plt.nuclearGlowBright,
      number = plt.hydrogenWhiteCore,
      operator = plt.atomicCyan,
      parameter = plt.fg_mid,
      preproc = plt.timelessPurple,
      punct = plt.fg_dark,
      regex = plt.omniscientViolet,
      statement = plt.quantumBlueCore,
      string = plt.nuclearGlow,
      symbol = plt.hydrogenWhite,
      type = plt.tachyonBlue,
      variable = plt.fg_lightest,
      special = plt.atomicCyan,
      special2 = plt.omniscientViolet,
      special3 = plt.timelessPurple,
    },

    vcs = {
      added = plt.nuclearGlow,
      removed = plt.martianRed,
      changed = plt.hydrogenWhite,
    },

    diff = {
      add = plt.nuclearGlow,
      change = plt.hydrogenWhite,
      delete = plt.martianRed,
      text = plt.atomicCyan,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.dangerRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.atomicCyan,
    },

    term = {
      black = plt.bg_darkest,
      red = plt.martianRedCore,
      green = plt.successGreen,
      yellow = plt.warningAmber,
      blue = plt.quantumBlueCore,
      magenta = plt.omniscientVioletCore,
      cyan = plt.atomicCyanCore,
      white = plt.hydrogenWhiteCore,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.martianRedBright):brighten(0.2):to_hex(),
      green_bright = color(plt.successGreen):brighten(0.2):to_hex(),
      yellow_bright = color(plt.warningAmber):brighten(0.2):to_hex(),
      blue_bright = color(plt.quantumBlueBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.omniscientVioletBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.atomicCyanBright):brighten(0.2):to_hex(),
      white_bright = color(plt.hydrogenWhiteBright):brighten(0.2):to_hex(),
      indexed1 = plt.hydrogenWhite,
      indexed2 = plt.martianRed,
    },

    treesitter = {
      ["@comment"] = plt.detachedGray,
      ["@comment.documentation"] = plt.detachedGrayLight,
      ["@comment.error"] = plt.dangerRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.hydrogenWhite,
      ["@comment.note"] = plt.atomicCyan,

      ["@constant"] = plt.hydrogenWhiteCore,
      ["@constant.builtin"] = plt.hydrogenWhiteCore,
      ["@constant.macro"] = plt.hydrogenWhite,

      ["@string"] = plt.nuclearGlow,
      ["@string.documentation"] = plt.nuclearGlow,
      ["@string.regex"] = plt.omniscientViolet,
      ["@string.escape"] = plt.hydrogenWhiteBright,
      ["@string.special"] = plt.nuclearGlowBright,
      ["@string.special.symbol"] = plt.hydrogenWhite,
      ["@string.special.url"] = plt.quantumBlue,
      ["@string.special.path"] = plt.nuclearGlow,

      ["@character"] = plt.nuclearGlow,
      ["@character.special"] = plt.hydrogenWhite,

      ["@number"] = plt.hydrogenWhiteCore,
      ["@number.float"] = plt.hydrogenWhiteCore,

      ["@boolean"] = plt.atomicCyan,

      ["@function"] = plt.nuclearGlow,
      ["@function.builtin"] = plt.nuclearGlow,
      ["@function.call"] = plt.nuclearGlow,
      ["@function.macro"] = plt.timelessPurple,
      ["@function.method"] = plt.nuclearGlowBright,
      ["@function.method.call"] = plt.nuclearGlowBright,

      ["@constructor"] = plt.tachyonBlue,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.quantumBlueCore,
      ["@keyword.coroutine"] = plt.timelessPurple,
      ["@keyword.function"] = plt.quantumBlueCore,
      ["@keyword.operator"] = plt.atomicCyan,
      ["@keyword.return"] = plt.quantumBlueCore,
      ["@keyword.import"] = plt.timelessPurple,
      ["@keyword.storage"] = plt.quantumBlueCore,
      ["@keyword.repeat"] = plt.quantumBlueCore,
      ["@keyword.conditional"] = plt.quantumBlueCore,
      ["@keyword.exception"] = plt.martianRed,
      ["@keyword.directive"] = plt.timelessPurple,
      ["@keyword.directive.define"] = plt.timelessPurple,

      ["@conditional"] = plt.quantumBlueCore,
      ["@conditional.ternary"] = plt.quantumBlueCore,

      ["@repeat"] = plt.quantumBlueCore,

      ["@label"] = plt.hydrogenWhite,

      ["@operator"] = plt.atomicCyan,

      ["@exception"] = plt.martianRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.quantumBlueBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.tachyonBlue,
      ["@type.builtin"] = plt.tachyonBlue,
      ["@type.definition"] = plt.tachyonBlue,
      ["@type.qualifier"] = plt.quantumBlueCore,

      ["@attribute"] = plt.hydrogenWhite,
      ["@attribute.builtin"] = plt.hydrogenWhite,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.tachyonBlue,
      ["@module.builtin"] = plt.tachyonBlue,

      ["@namespace"] = plt.tachyonBlue,
      ["@namespace.builtin"] = plt.tachyonBlue,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.atomicCyan,

      ["@tag"] = plt.quantumBlueCore,
      ["@tag.attribute"] = plt.hydrogenWhite,
      ["@tag.delimiter"] = plt.atomicCyan,
      ["@tag.builtin"] = plt.quantumBlueCore,

      ["@markup.strong"] = { fg = plt.quantumBlueBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.detachedGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.atomicCyan, underline = true },
      ["@markup.heading"] = plt.quantumBlueBright,
      ["@markup.heading.1"] = plt.quantumBlueBright,
      ["@markup.heading.2"] = plt.hydrogenWhite,
      ["@markup.heading.3"] = plt.nuclearGlow,
      ["@markup.heading.4"] = plt.atomicCyan,
      ["@markup.heading.5"] = plt.timelessPurple,
      ["@markup.heading.6"] = plt.omniscientViolet,
      ["@markup.quote"] = plt.detachedGray,
      ["@markup.math"] = plt.hydrogenWhiteCore,
      ["@markup.link"] = plt.quantumBlue,
      ["@markup.link.label"] = plt.quantumBlueBright,
      ["@markup.link.url"] = plt.quantumBlue,
      ["@markup.raw"] = plt.nuclearGlow,
      ["@markup.raw.block"] = plt.nuclearGlow,
      ["@markup.list"] = plt.quantumBlueCore,
      ["@markup.list.checked"] = plt.nuclearGlow,
      ["@markup.list.unchecked"] = plt.detachedGray,

      ["@diff.plus"] = plt.nuclearGlow,
      ["@diff.minus"] = plt.martianRed,
      ["@diff.delta"] = plt.hydrogenWhite,

      ["@none"] = "none",
      ["@conceal"] = plt.bg_lightest,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.tachyonBlue,
      ["@constructor.javascript"] = plt.tachyonBlue,
      ["@constructor.typescript"] = plt.tachyonBlue,
      ["@namespace.rust"] = plt.tachyonBlue,
      ["@type.qualifier.rust"] = plt.quantumBlueCore,
      ["@constant.macro.c"] = plt.hydrogenWhite,
      ["@constant.macro.cpp"] = plt.hydrogenWhite,
      ["@namespace.go"] = plt.tachyonBlue,
      ["@property.css"] = plt.nuclearGlowBright,
      ["@type.css"] = plt.quantumBlueCore,
      ["@label.json"] = plt.hydrogenWhite,
      ["@field.yaml"] = plt.nuclearGlowBright,
      ["@property.toml"] = plt.nuclearGlowBright,
      ["@function.builtin.bash"] = plt.nuclearGlow,
      ["@string.regexp"] = plt.omniscientViolet,
      ["@character.special.regex"] = plt.hydrogenWhite,
    },

    lsp = {
      ["@lsp.type.class"] = plt.tachyonBlue,
      ["@lsp.type.interface"] = plt.tachyonBlue,
      ["@lsp.type.struct"] = plt.tachyonBlue,
      ["@lsp.type.enum"] = plt.tachyonBlue,
      ["@lsp.type.enumMember"] = plt.hydrogenWhiteCore,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.tachyonBlue,

      ["@lsp.type.macro"] = plt.hydrogenWhite,
      ["@lsp.type.decorator"] = plt.hydrogenWhite,

      ["@lsp.type.builtinType"] = plt.tachyonBlue,
      ["@lsp.type.selfParameter"] = plt.quantumBlueBright,
      ["@lsp.type.typeParameter"] = plt.tachyonBlue,

      ["@lsp.type.array"] = plt.tachyonBlue,
      ["@lsp.type.object"] = plt.tachyonBlue,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.hydrogenWhiteCore,
      ["@lsp.type.enumConstant"] = plt.hydrogenWhiteCore,

      ["@lsp.type.event"] = plt.tachyonBlue,
      ["@lsp.type.regexp"] = plt.omniscientViolet,
      ["@lsp.type.unresolvedReference"] = plt.tachyonBlue,

      ["@lsp.mod.deprecated"] = { fg = plt.detachedGrayDark, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.hydrogenWhiteCore,
      ["@lsp.mod.async"] = plt.quantumBlueCore,
      ["@lsp.mod.static"] = plt.quantumBlueBright,
      ["@lsp.mod.abstract"] = plt.tachyonBlue,
      ["@lsp.mod.defaultLibrary"] = plt.tachyonBlue,
      ["@lsp.mod.documentation"] = plt.detachedGrayLight,
    },
  }
end

return {
  name = "Watchmen – Dr. Manhattan",
  author = "PrismPunk.nvim",
  description = "Quantum god — omnipotent, detached, perceiving all time simultaneously.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.detachedGray,
    base04 = palette.detachedGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.martianRed,
    base09 = palette.warningAmber,
    base0A = palette.hydrogenWhite,
    base0B = palette.nuclearGlow,
    base0C = palette.atomicCyan,
    base0D = palette.quantumBlueCore,
    base0E = palette.timelessPurple,
    base0F = palette.marsRock,
  },

  palette = palette,
  get = M.get,
}
