local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.dc.watchmen.nite-owl")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.owlBrownCore,
      insert = plt.nightVisionCore,
      visual = plt.nightPurpleCore,
      replace = plt.dangerRedCore,
      command = plt.twilightVioletCore,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.nightPurpleDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.owlGray,
      header1 = plt.nightPurpleBright,
      header2 = plt.crimsonAlertBright,
      special = plt.owlshipMagenta,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.owlGray,
      indent = plt.bg_lighter,
      indent_scope = plt.nightPurpleCore,
      picker = plt.twilightViolet,
      yank = plt.nightVisionBright,
      mark = plt.owlshipMagenta,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.nightPurpleBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.nightPurpleCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.owlGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.owlGrayLight,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.owlGray,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.nightPurpleCore,
      accent2 = plt.dangerRedCore,
      accent3 = plt.amberGlowCore,
      accent4 = plt.twilightVioletCore,
      accent5 = plt.owlshipMagentaCore,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.nightPurpleBright,
      rainbow2 = plt.crimsonAlertBright,
      rainbow3 = plt.amberGlowBright,
      rainbow4 = plt.nightVisionBright,
      rainbow5 = plt.twilightVioletBright,
      rainbow6 = plt.owlshipMagentaBright,
      rainbow7 = plt.owlBrownBright,
    },

    syn = {
      attribute = plt.owlshipMagenta,
      boolean = plt.twilightViolet,
      comment = plt.owlGray,
      constant = plt.vintageMap,
      deprecated = plt.owlGrayDark,
      func = plt.nightVisionCore,
      identifier = plt.fg_lightest,
      keyword = plt.nightPurpleCore,
      method = plt.nightVisionBright,
      number = plt.vintageMap,
      operator = plt.crimsonAlertCore,
      parameter = plt.fg_mid,
      preproc = plt.twilightVioletCore,
      punct = plt.fg_dark,
      regex = plt.owlshipMagenta,
      statement = plt.nightPurpleCore,
      string = plt.nightVisionCore,
      symbol = plt.amberGlow,
      type = plt.tacticalOliveCore,
      variable = plt.fg_lightest,
      special = plt.owlshipMagenta,
      special2 = plt.twilightViolet,
      special3 = plt.crimsonAlert,
    },

    vcs = {
      added = plt.nightVisionCore,
      removed = plt.dangerRedCore,
      changed = plt.amberGlowCore,
    },

    diff = {
      add = plt.nightVisionCore,
      change = plt.amberGlowCore,
      delete = plt.dangerRedCore,
      text = plt.owlshipMagenta,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.owlshipMagenta,
    },

    term = {
      black = plt.bg_darkest,
      red = plt.dangerRedCore,
      green = plt.nightVisionCore,
      yellow = plt.amberGlowCore,
      blue = plt.techBlueCore,
      magenta = plt.nightPurpleCore,
      cyan = plt.blueprintCyanCore,
      white = plt.vintageMapCore,
      black_bright = color(plt.bg_darkest):brighten(0.5):to_hex(),
      red_bright = color(plt.dangerRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.nightVisionBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.amberGlowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.techBlueBright):brighten(0.15):to_hex(),
      magenta_bright = color(plt.nightPurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.blueprintCyanBright):brighten(0.15):to_hex(),
      white_bright = color(plt.vintageMapBright):brighten(0.15):to_hex(),
      indexed1 = plt.crimsonAlert,
      indexed2 = plt.nightPurple,
    },

    treesitter = {
      ["@comment"] = plt.owlGray,
      ["@comment.documentation"] = plt.owlGrayLight,
      ["@comment.error"] = plt.errorRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.crimsonAlertBright,
      ["@comment.note"] = plt.owlshipMagenta,

      ["@constant"] = plt.vintageMap,
      ["@constant.builtin"] = plt.vintageMapCore,
      ["@constant.macro"] = plt.owlshipMagenta,

      ["@string"] = plt.nightVisionCore,
      ["@string.documentation"] = plt.nightVisionCore,
      ["@string.regex"] = plt.owlshipMagenta,
      ["@string.escape"] = plt.crimsonAlertBright,
      ["@string.special"] = plt.nightVisionBright,
      ["@string.special.symbol"] = plt.owlshipMagenta,
      ["@string.special.url"] = plt.twilightViolet,
      ["@string.special.path"] = plt.nightVisionCore,

      ["@character"] = plt.nightVisionCore,
      ["@character.special"] = plt.crimsonAlert,

      ["@number"] = plt.vintageMap,
      ["@number.float"] = plt.vintageMapCore,

      ["@boolean"] = plt.twilightViolet,

      ["@function"] = plt.nightVisionCore,
      ["@function.builtin"] = plt.nightVisionCore,
      ["@function.call"] = plt.nightVisionCore,
      ["@function.macro"] = plt.twilightVioletCore,
      ["@function.method"] = plt.nightVisionBright,
      ["@function.method.call"] = plt.nightVisionBright,

      ["@constructor"] = plt.tacticalOliveCore,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.nightPurpleCore,
      ["@keyword.coroutine"] = plt.twilightVioletCore,
      ["@keyword.function"] = plt.nightPurpleCore,
      ["@keyword.operator"] = plt.crimsonAlertCore,
      ["@keyword.return"] = plt.nightPurpleCore,
      ["@keyword.import"] = plt.twilightVioletCore,
      ["@keyword.storage"] = plt.nightPurpleCore,
      ["@keyword.repeat"] = plt.nightPurpleCore,
      ["@keyword.conditional"] = plt.nightPurpleCore,
      ["@keyword.exception"] = plt.dangerRedCore,
      ["@keyword.directive"] = plt.twilightVioletCore,
      ["@keyword.directive.define"] = plt.twilightVioletCore,

      ["@conditional"] = plt.nightPurpleCore,
      ["@conditional.ternary"] = plt.nightPurpleCore,

      ["@repeat"] = plt.nightPurpleCore,

      ["@label"] = plt.owlshipMagenta,

      ["@operator"] = plt.crimsonAlertCore,

      ["@exception"] = plt.dangerRedCore,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.nightPurpleBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.tacticalOliveCore,
      ["@type.builtin"] = plt.tacticalOliveCore,
      ["@type.definition"] = plt.tacticalOliveCore,
      ["@type.qualifier"] = plt.nightPurpleCore,

      ["@attribute"] = plt.owlshipMagenta,
      ["@attribute.builtin"] = plt.owlshipMagenta,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.tacticalOliveCore,
      ["@module.builtin"] = plt.tacticalOliveCore,

      ["@namespace"] = plt.tacticalOliveCore,
      ["@namespace.builtin"] = plt.tacticalOliveCore,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.crimsonAlertCore,

      ["@tag"] = plt.nightPurpleCore,
      ["@tag.attribute"] = plt.owlshipMagenta,
      ["@tag.delimiter"] = plt.crimsonAlertCore,
      ["@tag.builtin"] = plt.nightPurpleCore,

      ["@markup.strong"] = { fg = plt.crimsonAlertBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.owlGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.owlshipMagenta, underline = true },
      ["@markup.heading"] = plt.nightPurpleBright,
      ["@markup.heading.1"] = plt.nightPurpleBright,
      ["@markup.heading.2"] = plt.crimsonAlertBright,
      ["@markup.heading.3"] = plt.owlshipMagentaBright,
      ["@markup.heading.4"] = plt.twilightVioletBright,
      ["@markup.heading.5"] = plt.amberGlow,
      ["@markup.heading.6"] = plt.nightVisionCore,
      ["@markup.quote"] = plt.owlGray,
      ["@markup.math"] = plt.vintageMap,
      ["@markup.link"] = plt.twilightViolet,
      ["@markup.link.label"] = plt.twilightVioletBright,
      ["@markup.link.url"] = plt.twilightViolet,
      ["@markup.raw"] = plt.nightVisionCore,
      ["@markup.raw.block"] = plt.nightVisionCore,
      ["@markup.list"] = plt.nightPurpleCore,
      ["@markup.list.checked"] = plt.nightVisionCore,
      ["@markup.list.unchecked"] = plt.owlGray,

      ["@diff.plus"] = plt.nightVisionCore,
      ["@diff.minus"] = plt.dangerRedCore,
      ["@diff.delta"] = plt.amberGlowCore,

      ["@none"] = "none",
      ["@conceal"] = plt.bg_lightest,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.tacticalOliveCore,
      ["@constructor.javascript"] = plt.tacticalOliveCore,
      ["@constructor.typescript"] = plt.tacticalOliveCore,
      ["@namespace.rust"] = plt.tacticalOliveCore,
      ["@type.qualifier.rust"] = plt.nightPurpleCore,
      ["@constant.macro.c"] = plt.owlshipMagenta,
      ["@constant.macro.cpp"] = plt.owlshipMagenta,
      ["@namespace.go"] = plt.tacticalOliveCore,
      ["@property.css"] = plt.nightVisionBright,
      ["@type.css"] = plt.nightPurpleCore,
      ["@label.json"] = plt.owlshipMagenta,
      ["@field.yaml"] = plt.nightVisionBright,
      ["@property.toml"] = plt.nightVisionBright,
      ["@function.builtin.bash"] = plt.nightVisionCore,
      ["@string.regexp"] = plt.owlshipMagenta,
      ["@character.special.regex"] = plt.crimsonAlert,
    },

    lsp = {
      ["@lsp.type.class"] = plt.tacticalOliveCore,
      ["@lsp.type.interface"] = plt.tacticalOliveCore,
      ["@lsp.type.struct"] = plt.tacticalOliveCore,
      ["@lsp.type.enum"] = plt.tacticalOliveCore,
      ["@lsp.type.enumMember"] = plt.vintageMapCore,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.tacticalOliveCore,

      ["@lsp.type.macro"] = plt.owlshipMagenta,
      ["@lsp.type.decorator"] = plt.owlshipMagenta,

      ["@lsp.type.builtinType"] = plt.tacticalOliveCore,
      ["@lsp.type.selfParameter"] = plt.nightPurpleBright,
      ["@lsp.type.typeParameter"] = plt.tacticalOliveCore,

      ["@lsp.type.array"] = plt.tacticalOliveCore,
      ["@lsp.type.object"] = plt.tacticalOliveCore,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.vintageMapCore,
      ["@lsp.type.enumConstant"] = plt.vintageMapCore,

      ["@lsp.type.event"] = plt.tacticalOliveCore,
      ["@lsp.type.regexp"] = plt.owlshipMagenta,
      ["@lsp.type.unresolvedReference"] = plt.tacticalOliveCore,

      ["@lsp.mod.deprecated"] = { fg = plt.owlGrayDark, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.vintageMapCore,
      ["@lsp.mod.async"] = plt.nightPurpleCore,
      ["@lsp.mod.static"] = plt.nightPurpleBright,
      ["@lsp.mod.abstract"] = plt.tacticalOliveCore,
      ["@lsp.mod.defaultLibrary"] = plt.tacticalOliveCore,
      ["@lsp.mod.documentation"] = plt.owlGrayLight,
    },
  }
end

return {
  name = "Watchmen – Nite Owl",
  author = "PrismPunk.nvim",
  description = "Tech-savvy nostalgia — warm browns, purple mysteries, crimson alerts, and night-vision green.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.owlGray,
    base04 = palette.owlGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.dangerRedCore,
    base09 = palette.crimsonAlertCore,
    base0A = palette.amberGlowCore,
    base0B = palette.nightVisionCore,
    base0C = palette.blueprintCyanCore,
    base0D = palette.twilightVioletCore,
    base0E = palette.nightPurpleCore,
    base0F = palette.owlshipMagentaCore,
  },

  palette = palette,
  get = M.get,
}
