local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.dc.watchmen.ozymandias")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.imperialPurpleCore,
      insert = plt.utopianTealCore,
      visual = plt.royalGoldCore,
      replace = plt.chaosRedCore,
      command = plt.mastermindVioletCore,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.royalGoldDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.coldGray,
      header1 = plt.royalGoldBright,
      header2 = plt.imperialPurpleBright,
      special = plt.calculatedCyan,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.coldGray,
      indent = plt.bg_lighter,
      indent_scope = plt.imperialPurpleCore,
      picker = plt.mastermindViolet,
      yank = plt.royalGoldBright,
      mark = plt.calculatedCyan,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.royalGoldBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.imperialPurpleCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.coldGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.coldGrayLight,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.coldGray,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.imperialPurpleCore,
      accent2 = plt.royalGoldCore,
      accent3 = plt.mastermindVioletCore,
      accent4 = plt.calculatedCyanCore,
      accent5 = plt.utopianTealCore,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.imperialPurpleBright,
      rainbow2 = plt.royalGoldBright,
      rainbow3 = plt.mastermindVioletBright,
      rainbow4 = plt.calculatedCyanBright,
      rainbow5 = plt.utopianTealBright,
      rainbow6 = plt.logicBlueBright,
      rainbow7 = plt.strategicAmberBright,
    },

    syn = {
      attribute = plt.royalGold,
      boolean = plt.calculatedCyan,
      comment = plt.coldGray,
      constant = plt.intelligenceWhite,
      deprecated = plt.coldGrayDark,
      func = plt.utopianTealCore,
      identifier = plt.fg_lightest,
      keyword = plt.imperialPurpleCore,
      method = plt.utopianTealBright,
      number = plt.intelligenceWhite,
      operator = plt.royalGoldCore,
      parameter = plt.fg_mid,
      preproc = plt.mastermindVioletCore,
      punct = plt.fg_dark,
      regex = plt.calculatedCyan,
      statement = plt.imperialPurpleCore,
      string = plt.utopianTealCore,
      symbol = plt.royalGold,
      type = plt.logicBlueCore,
      variable = plt.fg_lightest,
      special = plt.calculatedCyan,
      special2 = plt.mastermindViolet,
      special3 = plt.royalGold,
    },

    vcs = {
      added = plt.schemeGreenCore,
      removed = plt.chaosRedCore,
      changed = plt.strategicAmberCore,
    },

    diff = {
      add = plt.schemeGreenCore,
      change = plt.strategicAmberCore,
      delete = plt.chaosRedCore,
      text = plt.calculatedCyan,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.calculatedCyan,
    },

    term = {
      black = plt.bg_darkest,
      red = plt.chaosRedCore,
      green = plt.schemeGreenCore,
      yellow = plt.strategicAmberCore,
      blue = plt.logicBlueCore,
      magenta = plt.imperialPurpleCore,
      cyan = plt.calculatedCyanCore,
      white = plt.intelligenceWhiteCore,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.chaosRedBright):brighten(0.18):to_hex(),
      green_bright = color(plt.schemeGreenBright):brighten(0.18):to_hex(),
      yellow_bright = color(plt.strategicAmberBright):brighten(0.18):to_hex(),
      blue_bright = color(plt.logicBlueBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.imperialPurpleBright):brighten(0.18):to_hex(),
      cyan_bright = color(plt.calculatedCyanBright):brighten(0.18):to_hex(),
      white_bright = color(plt.intelligenceWhiteBright):brighten(0.12):to_hex(),
      indexed1 = plt.royalGold,
      indexed2 = plt.chaosRed,
    },

    treesitter = {
      ["@comment"] = plt.coldGray,
      ["@comment.documentation"] = plt.coldGrayLight,
      ["@comment.error"] = plt.errorRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.royalGoldBright,
      ["@comment.note"] = plt.calculatedCyan,

      ["@constant"] = plt.intelligenceWhite,
      ["@constant.builtin"] = plt.intelligenceWhiteCore,
      ["@constant.macro"] = plt.royalGold,

      ["@string"] = plt.utopianTealCore,
      ["@string.documentation"] = plt.utopianTealCore,
      ["@string.regex"] = plt.calculatedCyan,
      ["@string.escape"] = plt.royalGoldBright,
      ["@string.special"] = plt.utopianTealBright,
      ["@string.special.symbol"] = plt.royalGold,
      ["@string.special.url"] = plt.logicBlue,
      ["@string.special.path"] = plt.utopianTealCore,

      ["@character"] = plt.utopianTealCore,
      ["@character.special"] = plt.royalGold,

      ["@number"] = plt.intelligenceWhite,
      ["@number.float"] = plt.intelligenceWhiteCore,

      ["@boolean"] = plt.calculatedCyan,

      ["@function"] = plt.utopianTealCore,
      ["@function.builtin"] = plt.utopianTealCore,
      ["@function.call"] = plt.utopianTealCore,
      ["@function.macro"] = plt.mastermindVioletCore,
      ["@function.method"] = plt.utopianTealBright,
      ["@function.method.call"] = plt.utopianTealBright,

      ["@constructor"] = plt.logicBlueCore,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.imperialPurpleCore,
      ["@keyword.coroutine"] = plt.mastermindVioletCore,
      ["@keyword.function"] = plt.imperialPurpleCore,
      ["@keyword.operator"] = plt.royalGoldCore,
      ["@keyword.return"] = plt.imperialPurpleCore,
      ["@keyword.import"] = plt.mastermindVioletCore,
      ["@keyword.storage"] = plt.imperialPurpleCore,
      ["@keyword.repeat"] = plt.imperialPurpleCore,
      ["@keyword.conditional"] = plt.imperialPurpleCore,
      ["@keyword.exception"] = plt.chaosRedCore,
      ["@keyword.directive"] = plt.mastermindVioletCore,
      ["@keyword.directive.define"] = plt.mastermindVioletCore,

      ["@conditional"] = plt.imperialPurpleCore,
      ["@conditional.ternary"] = plt.imperialPurpleCore,

      ["@repeat"] = plt.imperialPurpleCore,

      ["@label"] = plt.royalGold,

      ["@operator"] = plt.royalGoldCore,

      ["@exception"] = plt.chaosRedCore,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.imperialPurpleBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.logicBlueCore,
      ["@type.builtin"] = plt.logicBlueCore,
      ["@type.definition"] = plt.logicBlueCore,
      ["@type.qualifier"] = plt.imperialPurpleCore,

      ["@attribute"] = plt.royalGold,
      ["@attribute.builtin"] = plt.royalGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.logicBlueCore,
      ["@module.builtin"] = plt.logicBlueCore,

      ["@namespace"] = plt.logicBlueCore,
      ["@namespace.builtin"] = plt.logicBlueCore,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.royalGoldCore,

      ["@tag"] = plt.imperialPurpleCore,
      ["@tag.attribute"] = plt.royalGold,
      ["@tag.delimiter"] = plt.royalGoldCore,
      ["@tag.builtin"] = plt.imperialPurpleCore,

      ["@markup.strong"] = { fg = plt.royalGoldBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.coldGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.calculatedCyan, underline = true },
      ["@markup.heading"] = plt.royalGoldBright,
      ["@markup.heading.1"] = plt.royalGoldBright,
      ["@markup.heading.2"] = plt.imperialPurpleBright,
      ["@markup.heading.3"] = plt.mastermindVioletBright,
      ["@markup.heading.4"] = plt.calculatedCyanBright,
      ["@markup.heading.5"] = plt.utopianTealBright,
      ["@markup.heading.6"] = plt.logicBlueBright,
      ["@markup.quote"] = plt.coldGray,
      ["@markup.math"] = plt.intelligenceWhite,
      ["@markup.link"] = plt.logicBlue,
      ["@markup.link.label"] = plt.logicBlueBright,
      ["@markup.link.url"] = plt.logicBlue,
      ["@markup.raw"] = plt.utopianTealCore,
      ["@markup.raw.block"] = plt.utopianTealCore,
      ["@markup.list"] = plt.imperialPurpleCore,
      ["@markup.list.checked"] = plt.schemeGreenCore,
      ["@markup.list.unchecked"] = plt.coldGray,

      ["@diff.plus"] = plt.schemeGreenCore,
      ["@diff.minus"] = plt.chaosRedCore,
      ["@diff.delta"] = plt.strategicAmberCore,

      ["@none"] = "none",
      ["@conceal"] = plt.bg_lightest,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.logicBlueCore,
      ["@constructor.javascript"] = plt.logicBlueCore,
      ["@constructor.typescript"] = plt.logicBlueCore,
      ["@namespace.rust"] = plt.logicBlueCore,
      ["@type.qualifier.rust"] = plt.imperialPurpleCore,
      ["@constant.macro.c"] = plt.royalGold,
      ["@constant.macro.cpp"] = plt.royalGold,
      ["@namespace.go"] = plt.logicBlueCore,
      ["@property.css"] = plt.utopianTealBright,
      ["@type.css"] = plt.imperialPurpleCore,
      ["@label.json"] = plt.royalGold,
      ["@field.yaml"] = plt.utopianTealBright,
      ["@property.toml"] = plt.utopianTealBright,
      ["@function.builtin.bash"] = plt.utopianTealCore,
      ["@string.regexp"] = plt.calculatedCyan,
      ["@character.special.regex"] = plt.royalGold,
    },

    lsp = {
      ["@lsp.type.class"] = plt.logicBlueCore,
      ["@lsp.type.interface"] = plt.logicBlueCore,
      ["@lsp.type.struct"] = plt.logicBlueCore,
      ["@lsp.type.enum"] = plt.logicBlueCore,
      ["@lsp.type.enumMember"] = plt.intelligenceWhiteCore,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.logicBlueCore,

      ["@lsp.type.macro"] = plt.royalGold,
      ["@lsp.type.decorator"] = plt.royalGold,

      ["@lsp.type.builtinType"] = plt.logicBlueCore,
      ["@lsp.type.selfParameter"] = plt.imperialPurpleBright,
      ["@lsp.type.typeParameter"] = plt.logicBlueCore,

      ["@lsp.type.array"] = plt.logicBlueCore,
      ["@lsp.type.object"] = plt.logicBlueCore,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.intelligenceWhiteCore,
      ["@lsp.type.enumConstant"] = plt.intelligenceWhiteCore,

      ["@lsp.type.event"] = plt.logicBlueCore,
      ["@lsp.type.regexp"] = plt.calculatedCyan,
      ["@lsp.type.unresolvedReference"] = plt.logicBlueCore,

      ["@lsp.mod.deprecated"] = { fg = plt.coldGrayDark, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.intelligenceWhiteCore,
      ["@lsp.mod.async"] = plt.imperialPurpleCore,
      ["@lsp.mod.static"] = plt.imperialPurpleBright,
      ["@lsp.mod.abstract"] = plt.logicBlueCore,
      ["@lsp.mod.defaultLibrary"] = plt.logicBlueCore,
      ["@lsp.mod.documentation"] = plt.coldGrayLight,
    },
  }
end

return {
  name = "Watchmen – Ozymandias",
  author = "PrismPunk.nvim",
  description = "Genius strategist — imperial purple, royal gold, calculated perfection.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.coldGray,
    base04 = palette.coldGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.chaosRedCore,
    base09 = palette.strategicAmberCore,
    base0A = palette.royalGoldCore,
    base0B = palette.utopianTealCore,
    base0C = palette.calculatedCyanCore,
    base0D = palette.logicBlueCore,
    base0E = palette.imperialPurpleCore,
    base0F = palette.mastermindVioletCore,
  },

  palette = palette,
  get = M.get,
}
