local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.dc.watchmen.rorschach")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.maskWhiteCore,
      insert = plt.sterileGreenCore,
      visual = plt.blotGrayCore,
      replace = plt.bloodRedCore,
      command = plt.coldBlueCore,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.blotGrayDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.justiceGray,
      header1 = plt.maskWhiteBright,
      header2 = plt.starkGrayLight,
      special = plt.coldBlue,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.justiceGray,
      indent = plt.bg_lighter,
      indent_scope = plt.shiftingPatternCore,
      picker = plt.coldBlue,
      yank = plt.starkGrayLight,
      mark = plt.bloodRed,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.starkGrayLight,
        bg_alternate = plt.bg_darkest,
        indicator = plt.maskWhiteCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.justiceGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.starkGray,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.justiceGray,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.maskWhiteCore,
      accent2 = plt.bloodRedCore,
      accent3 = plt.justiceGrayCore,
      accent4 = plt.coldBlueCore,
      accent5 = plt.shiftingPatternCore,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.maskWhiteBright,
      rainbow2 = plt.starkGrayLight,
      rainbow3 = plt.justiceGrayBright,
      rainbow4 = plt.blotGrayBright,
      rainbow5 = plt.shiftingPatternBright,
      rainbow6 = plt.coldBlueBright,
      rainbow7 = plt.bloodRedBright,
    },

    syn = {
      attribute = plt.starkGray,
      boolean = plt.coldBlue,
      comment = plt.justiceGray,
      constant = plt.maskWhiteCore,
      deprecated = plt.voidGray,
      func = plt.fg_lightest,
      identifier = plt.fg_light,
      keyword = plt.shiftingPatternCore,
      method = plt.fg_lightest,
      number = plt.maskWhiteCore,
      operator = plt.starkGray,
      parameter = plt.fg_mid,
      preproc = plt.coldBlueCore,
      punct = plt.fg_dark,
      regex = plt.blotGray,
      statement = plt.shiftingPatternCore,
      string = plt.fg_light,
      symbol = plt.starkGray,
      type = plt.coldBlueCore,
      variable = plt.fg_light,
      special = plt.coldBlue,
      special2 = plt.sterileGreen,
      special3 = plt.bloodRed,
    },

    vcs = {
      added = plt.sterileGreenCore,
      removed = plt.bloodRedCore,
      changed = plt.starkGray,
    },

    diff = {
      add = plt.sterileGreenCore,
      change = plt.starkGray,
      delete = plt.bloodRedCore,
      text = plt.coldBlue,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.coldBlue,
    },

    term = {
      black = plt.inkBlackCore,
      red = plt.bloodRedCore,
      green = plt.sterileGreenCore,
      yellow = plt.warningAmber,
      blue = plt.coldBlueCore,
      magenta = plt.shiftingPatternCore,
      cyan = plt.blotGrayCore,
      white = plt.maskWhiteCore,
      black_bright = color(plt.inkBlackBright):brighten(0.3):to_hex(),
      red_bright = color(plt.bloodRedBright):brighten(0.2):to_hex(),
      green_bright = color(plt.sterileGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.warningAmber):brighten(0.3):to_hex(),
      blue_bright = color(plt.coldBlueBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.shiftingPatternBright):brighten(0.3):to_hex(),
      cyan_bright = color(plt.blotGrayBright):brighten(0.3):to_hex(),
      white_bright = plt.maskWhiteBright,
      indexed1 = plt.maskWhite,
      indexed2 = plt.bloodRed,
    },

    treesitter = {
      ["@comment"] = plt.justiceGray,
      ["@comment.documentation"] = plt.starkGray,
      ["@comment.error"] = plt.errorRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.bloodRedBright,
      ["@comment.note"] = plt.coldBlue,

      ["@constant"] = plt.maskWhiteCore,
      ["@constant.builtin"] = plt.maskWhiteCore,
      ["@constant.macro"] = plt.starkGray,

      ["@string"] = plt.fg_light,
      ["@string.documentation"] = plt.fg_light,
      ["@string.regex"] = plt.blotGray,
      ["@string.escape"] = plt.maskWhiteBright,
      ["@string.special"] = plt.fg_lightest,
      ["@string.special.symbol"] = plt.starkGray,
      ["@string.special.url"] = plt.coldBlue,
      ["@string.special.path"] = plt.fg_light,

      ["@character"] = plt.fg_light,
      ["@character.special"] = plt.starkGray,

      ["@number"] = plt.maskWhiteCore,
      ["@number.float"] = plt.maskWhiteCore,

      ["@boolean"] = plt.coldBlue,

      ["@function"] = plt.fg_lightest,
      ["@function.builtin"] = plt.fg_lightest,
      ["@function.call"] = plt.fg_lightest,
      ["@function.macro"] = plt.coldBlueCore,
      ["@function.method"] = plt.fg_lightest,
      ["@function.method.call"] = plt.fg_lightest,

      ["@constructor"] = plt.coldBlueCore,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.shiftingPatternCore,
      ["@keyword.coroutine"] = plt.coldBlueCore,
      ["@keyword.function"] = plt.shiftingPatternCore,
      ["@keyword.operator"] = plt.starkGray,
      ["@keyword.return"] = plt.shiftingPatternCore,
      ["@keyword.import"] = plt.coldBlueCore,
      ["@keyword.storage"] = plt.shiftingPatternCore,
      ["@keyword.repeat"] = plt.shiftingPatternCore,
      ["@keyword.conditional"] = plt.shiftingPatternCore,
      ["@keyword.exception"] = plt.bloodRedCore,
      ["@keyword.directive"] = plt.coldBlueCore,
      ["@keyword.directive.define"] = plt.coldBlueCore,

      ["@conditional"] = plt.shiftingPatternCore,
      ["@conditional.ternary"] = plt.shiftingPatternCore,

      ["@repeat"] = plt.shiftingPatternCore,

      ["@label"] = plt.starkGray,

      ["@operator"] = plt.starkGray,

      ["@exception"] = plt.bloodRedCore,

      ["@variable"] = plt.fg_light,
      ["@variable.builtin"] = plt.maskWhiteCore,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.coldBlueCore,
      ["@type.builtin"] = plt.coldBlueCore,
      ["@type.definition"] = plt.coldBlueCore,
      ["@type.qualifier"] = plt.shiftingPatternCore,

      ["@attribute"] = plt.starkGray,
      ["@attribute.builtin"] = plt.starkGray,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.coldBlueCore,
      ["@module.builtin"] = plt.coldBlueCore,

      ["@namespace"] = plt.coldBlueCore,
      ["@namespace.builtin"] = plt.coldBlueCore,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.starkGray,

      ["@tag"] = plt.shiftingPatternCore,
      ["@tag.attribute"] = plt.starkGray,
      ["@tag.delimiter"] = plt.starkGray,
      ["@tag.builtin"] = plt.shiftingPatternCore,

      ["@markup.strong"] = { fg = plt.maskWhiteBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.justiceGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.coldBlue, underline = true },
      ["@markup.heading"] = plt.maskWhiteBright,
      ["@markup.heading.1"] = plt.maskWhiteBright,
      ["@markup.heading.2"] = plt.starkGrayLight,
      ["@markup.heading.3"] = plt.justiceGrayBright,
      ["@markup.heading.4"] = plt.blotGrayBright,
      ["@markup.heading.5"] = plt.coldBlueBright,
      ["@markup.heading.6"] = plt.sterileGreenBright,
      ["@markup.quote"] = plt.justiceGray,
      ["@markup.math"] = plt.maskWhiteCore,
      ["@markup.link"] = plt.coldBlue,
      ["@markup.link.label"] = plt.coldBlueBright,
      ["@markup.link.url"] = plt.coldBlue,
      ["@markup.raw"] = plt.fg_light,
      ["@markup.raw.block"] = plt.fg_light,
      ["@markup.list"] = plt.shiftingPatternCore,
      ["@markup.list.checked"] = plt.sterileGreenCore,
      ["@markup.list.unchecked"] = plt.justiceGray,

      ["@diff.plus"] = plt.sterileGreenCore,
      ["@diff.minus"] = plt.bloodRedCore,
      ["@diff.delta"] = plt.starkGray,

      ["@none"] = "none",
      ["@conceal"] = plt.bg_lightest,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.coldBlueCore,
      ["@constructor.javascript"] = plt.coldBlueCore,
      ["@constructor.typescript"] = plt.coldBlueCore,
      ["@namespace.rust"] = plt.coldBlueCore,
      ["@type.qualifier.rust"] = plt.shiftingPatternCore,
      ["@constant.macro.c"] = plt.starkGray,
      ["@constant.macro.cpp"] = plt.starkGray,
      ["@namespace.go"] = plt.coldBlueCore,
      ["@property.css"] = plt.fg_lightest,
      ["@type.css"] = plt.shiftingPatternCore,
      ["@label.json"] = plt.starkGray,
      ["@field.yaml"] = plt.fg_lightest,
      ["@property.toml"] = plt.fg_lightest,
      ["@function.builtin.bash"] = plt.fg_lightest,
      ["@string.regexp"] = plt.blotGray,
      ["@character.special.regex"] = plt.starkGray,
    },

    lsp = {
      ["@lsp.type.class"] = plt.coldBlueCore,
      ["@lsp.type.interface"] = plt.coldBlueCore,
      ["@lsp.type.struct"] = plt.coldBlueCore,
      ["@lsp.type.enum"] = plt.coldBlueCore,
      ["@lsp.type.enumMember"] = plt.maskWhiteCore,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.coldBlueCore,

      ["@lsp.type.macro"] = plt.starkGray,
      ["@lsp.type.decorator"] = plt.starkGray,

      ["@lsp.type.builtinType"] = plt.coldBlueCore,
      ["@lsp.type.selfParameter"] = plt.maskWhiteCore,
      ["@lsp.type.typeParameter"] = plt.coldBlueCore,

      ["@lsp.type.array"] = plt.coldBlueCore,
      ["@lsp.type.object"] = plt.coldBlueCore,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.maskWhiteCore,
      ["@lsp.type.enumConstant"] = plt.maskWhiteCore,

      ["@lsp.type.event"] = plt.coldBlueCore,
      ["@lsp.type.regexp"] = plt.blotGray,
      ["@lsp.type.unresolvedReference"] = plt.coldBlueCore,

      ["@lsp.mod.deprecated"] = { fg = plt.voidGray, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.maskWhiteCore,
      ["@lsp.mod.async"] = plt.shiftingPatternCore,
      ["@lsp.mod.static"] = plt.maskWhiteCore,
      ["@lsp.mod.abstract"] = plt.coldBlueCore,
      ["@lsp.mod.defaultLibrary"] = plt.coldBlueCore,
      ["@lsp.mod.documentation"] = plt.starkGray,
    },
  }
end

return {
  name = "Watchmen – Rorschach",
  author = "PrismPunk.nvim",
  description = "Black and white morality — no compromise, absolute justice, shifting ink patterns.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.justiceGray,
    base04 = palette.starkGray,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.bloodRedCore,
    base09 = palette.warningAmber,
    base0A = palette.starkGray,
    base0B = palette.sterileGreenCore,
    base0C = palette.blotGrayCore,
    base0D = palette.coldBlueCore,
    base0E = palette.shiftingPatternCore,
    base0F = palette.maskWhiteCore,
  },

  palette = palette,
  get = M.get,
}
