local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.dc.watchmen.silk-spectre")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.velvetPurpleCore,
      insert = plt.silkPinkCore,
      visual = plt.neonPinkCore,
      replace = plt.lipstickRedCore,
      command = plt.champagneGoldCore,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.seductionMagentaDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.noirGray,
      header1 = plt.champagneGoldBright,
      header2 = plt.silkPinkBright,
      special = plt.empowermentCyan,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.noirGray,
      indent = plt.bg_lighter,
      indent_scope = plt.velvetPurpleCore,
      picker = plt.neonPink,
      yank = plt.champagneGoldBright,
      mark = plt.seductionMagenta,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.silkPinkBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.velvetPurpleCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.noirGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.noirGrayLight,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.noirGray,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.silkPinkCore,
      accent2 = plt.velvetPurpleCore,
      accent3 = plt.champagneGoldCore,
      accent4 = plt.neonPinkCore,
      accent5 = plt.empowermentCyanCore,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.silkPinkBright,
      rainbow2 = plt.velvetPurpleBright,
      rainbow3 = plt.champagneGoldBright,
      rainbow4 = plt.neonPinkBright,
      rainbow5 = plt.empowermentCyanBright,
      rainbow6 = plt.lipstickRedBright,
      rainbow7 = plt.midnightVioletBright,
    },

    syn = {
      attribute = plt.champagneGold,
      boolean = plt.empowermentCyan,
      comment = plt.noirGray,
      constant = plt.laceWhite,
      deprecated = plt.noirGrayDark,
      func = plt.silkPinkCore,
      identifier = plt.fg_lightest,
      keyword = plt.velvetPurpleCore,
      method = plt.silkPinkBright,
      number = plt.laceWhite,
      operator = plt.neonPinkCore,
      parameter = plt.fg_mid,
      preproc = plt.midnightVioletCore,
      punct = plt.fg_dark,
      regex = plt.seductionMagenta,
      statement = plt.velvetPurpleCore,
      string = plt.silkPinkCore,
      symbol = plt.champagneGold,
      type = plt.empowermentCyanCore,
      variable = plt.fg_lightest,
      special = plt.neonPink,
      special2 = plt.empowermentCyan,
      special3 = plt.champagneGold,
    },

    vcs = {
      added = plt.successGreen,
      removed = plt.lipstickRedCore,
      changed = plt.strengthAmberCore,
    },

    diff = {
      add = plt.successGreen,
      change = plt.strengthAmberCore,
      delete = plt.lipstickRedCore,
      text = plt.empowermentCyan,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.empowermentCyan,
    },

    term = {
      black = plt.bg_darkest,
      red = plt.lipstickRedCore,
      green = plt.successGreen,
      yellow = plt.champagneGoldCore,
      blue = plt.independenceBlueCore,
      magenta = plt.velvetPurpleCore,
      cyan = plt.empowermentCyanCore,
      white = plt.laceWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.lipstickRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.successGreen):brighten(0.2):to_hex(),
      yellow_bright = color(plt.champagneGoldBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.independenceBlueBright):brighten(0.15):to_hex(),
      magenta_bright = color(plt.velvetPurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.empowermentCyanBright):brighten(0.15):to_hex(),
      white_bright = color(plt.laceWhiteBright):brighten(0.1):to_hex(),
      indexed1 = plt.neonPink,
      indexed2 = plt.champagneGold,
    },

    treesitter = {
      ["@comment"] = plt.noirGray,
      ["@comment.documentation"] = plt.noirGrayLight,
      ["@comment.error"] = plt.errorRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.champagneGoldBright,
      ["@comment.note"] = plt.empowermentCyan,

      ["@constant"] = plt.laceWhite,
      ["@constant.builtin"] = plt.laceWhiteCore,
      ["@constant.macro"] = plt.champagneGold,

      ["@string"] = plt.silkPinkCore,
      ["@string.documentation"] = plt.silkPinkCore,
      ["@string.regex"] = plt.seductionMagenta,
      ["@string.escape"] = plt.neonPinkBright,
      ["@string.special"] = plt.silkPinkBright,
      ["@string.special.symbol"] = plt.champagneGold,
      ["@string.special.url"] = plt.independenceBlue,
      ["@string.special.path"] = plt.silkPinkCore,

      ["@character"] = plt.silkPinkCore,
      ["@character.special"] = plt.neonPink,

      ["@number"] = plt.laceWhite,
      ["@number.float"] = plt.laceWhiteCore,

      ["@boolean"] = plt.empowermentCyan,

      ["@function"] = plt.silkPinkCore,
      ["@function.builtin"] = plt.silkPinkCore,
      ["@function.call"] = plt.silkPinkCore,
      ["@function.macro"] = plt.midnightVioletCore,
      ["@function.method"] = plt.silkPinkBright,
      ["@function.method.call"] = plt.silkPinkBright,

      ["@constructor"] = plt.empowermentCyanCore,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.velvetPurpleCore,
      ["@keyword.coroutine"] = plt.midnightVioletCore,
      ["@keyword.function"] = plt.velvetPurpleCore,
      ["@keyword.operator"] = plt.neonPinkCore,
      ["@keyword.return"] = plt.velvetPurpleCore,
      ["@keyword.import"] = plt.midnightVioletCore,
      ["@keyword.storage"] = plt.velvetPurpleCore,
      ["@keyword.repeat"] = plt.velvetPurpleCore,
      ["@keyword.conditional"] = plt.velvetPurpleCore,
      ["@keyword.exception"] = plt.lipstickRedCore,
      ["@keyword.directive"] = plt.midnightVioletCore,
      ["@keyword.directive.define"] = plt.midnightVioletCore,

      ["@conditional"] = plt.velvetPurpleCore,
      ["@conditional.ternary"] = plt.velvetPurpleCore,

      ["@repeat"] = plt.velvetPurpleCore,

      ["@label"] = plt.champagneGold,

      ["@operator"] = plt.neonPinkCore,

      ["@exception"] = plt.lipstickRedCore,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.velvetPurpleBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.empowermentCyanCore,
      ["@type.builtin"] = plt.empowermentCyanCore,
      ["@type.definition"] = plt.empowermentCyanCore,
      ["@type.qualifier"] = plt.velvetPurpleCore,

      ["@attribute"] = plt.champagneGold,
      ["@attribute.builtin"] = plt.champagneGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.empowermentCyanCore,
      ["@module.builtin"] = plt.empowermentCyanCore,

      ["@namespace"] = plt.empowermentCyanCore,
      ["@namespace.builtin"] = plt.empowermentCyanCore,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.neonPinkCore,

      ["@tag"] = plt.velvetPurpleCore,
      ["@tag.attribute"] = plt.champagneGold,
      ["@tag.delimiter"] = plt.neonPinkCore,
      ["@tag.builtin"] = plt.velvetPurpleCore,

      ["@markup.strong"] = { fg = plt.neonPinkBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.noirGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.empowermentCyan, underline = true },
      ["@markup.heading"] = plt.champagneGoldBright,
      ["@markup.heading.1"] = plt.champagneGoldBright,
      ["@markup.heading.2"] = plt.silkPinkBright,
      ["@markup.heading.3"] = plt.velvetPurpleBright,
      ["@markup.heading.4"] = plt.neonPinkBright,
      ["@markup.heading.5"] = plt.empowermentCyanBright,
      ["@markup.heading.6"] = plt.midnightVioletBright,
      ["@markup.quote"] = plt.noirGray,
      ["@markup.math"] = plt.laceWhite,
      ["@markup.link"] = plt.independenceBlue,
      ["@markup.link.label"] = plt.independenceBlueBright,
      ["@markup.link.url"] = plt.independenceBlue,
      ["@markup.raw"] = plt.silkPinkCore,
      ["@markup.raw.block"] = plt.silkPinkCore,
      ["@markup.list"] = plt.velvetPurpleCore,
      ["@markup.list.checked"] = plt.successGreen,
      ["@markup.list.unchecked"] = plt.noirGray,

      ["@diff.plus"] = plt.successGreen,
      ["@diff.minus"] = plt.lipstickRedCore,
      ["@diff.delta"] = plt.strengthAmberCore,

      ["@none"] = "none",
      ["@conceal"] = plt.bg_lightest,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.empowermentCyanCore,
      ["@constructor.javascript"] = plt.empowermentCyanCore,
      ["@constructor.typescript"] = plt.empowermentCyanCore,
      ["@namespace.rust"] = plt.empowermentCyanCore,
      ["@type.qualifier.rust"] = plt.velvetPurpleCore,
      ["@constant.macro.c"] = plt.champagneGold,
      ["@constant.macro.cpp"] = plt.champagneGold,
      ["@namespace.go"] = plt.empowermentCyanCore,
      ["@property.css"] = plt.silkPinkBright,
      ["@type.css"] = plt.velvetPurpleCore,
      ["@label.json"] = plt.champagneGold,
      ["@field.yaml"] = plt.silkPinkBright,
      ["@property.toml"] = plt.silkPinkBright,
      ["@function.builtin.bash"] = plt.silkPinkCore,
      ["@string.regexp"] = plt.seductionMagenta,
      ["@character.special.regex"] = plt.neonPink,
    },

    lsp = {
      ["@lsp.type.class"] = plt.empowermentCyanCore,
      ["@lsp.type.interface"] = plt.empowermentCyanCore,
      ["@lsp.type.struct"] = plt.empowermentCyanCore,
      ["@lsp.type.enum"] = plt.empowermentCyanCore,
      ["@lsp.type.enumMember"] = plt.laceWhiteCore,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.empowermentCyanCore,

      ["@lsp.type.macro"] = plt.champagneGold,
      ["@lsp.type.decorator"] = plt.champagneGold,

      ["@lsp.type.builtinType"] = plt.empowermentCyanCore,
      ["@lsp.type.selfParameter"] = plt.velvetPurpleBright,
      ["@lsp.type.typeParameter"] = plt.empowermentCyanCore,

      ["@lsp.type.array"] = plt.empowermentCyanCore,
      ["@lsp.type.object"] = plt.empowermentCyanCore,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.laceWhiteCore,
      ["@lsp.type.enumConstant"] = plt.laceWhiteCore,

      ["@lsp.type.event"] = plt.empowermentCyanCore,
      ["@lsp.type.regexp"] = plt.seductionMagenta,
      ["@lsp.type.unresolvedReference"] = plt.empowermentCyanCore,

      ["@lsp.mod.deprecated"] = { fg = plt.noirGrayDark, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.laceWhiteCore,
      ["@lsp.mod.async"] = plt.velvetPurpleCore,
      ["@lsp.mod.static"] = plt.velvetPurpleBright,
      ["@lsp.mod.abstract"] = plt.empowermentCyanCore,
      ["@lsp.mod.defaultLibrary"] = plt.empowermentCyanCore,
      ["@lsp.mod.documentation"] = plt.noirGrayLight,
    },
  }
end

return {
  name = "Watchmen – Silk Spectre",
  author = "PrismPunk.nvim",
  description = "Feminine power and elegance — silk pink, velvet purple, champagne gold, neon rebellion.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.noirGray,
    base04 = palette.noirGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.lipstickRedCore,
    base09 = palette.strengthAmberCore,
    base0A = palette.champagneGoldCore,
    base0B = palette.silkPinkCore,
    base0C = palette.empowermentCyanCore,
    base0D = palette.independenceBlueCore,
    base0E = palette.velvetPurpleCore,
    base0F = palette.seductionMagentaCore,
  },

  palette = palette,
  get = M.get,
}
