local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.dc.watchmen.the-comedian")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.combatOliveCore,
      insert = plt.warYellowCore,
      visual = plt.bloodOrangeCore,
      replace = plt.brutalityCore,
      command = plt.cynicalGrayCore,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.muzzleFlashDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.gunmetalGray,
      header1 = plt.warYellowBright,
      header2 = plt.bloodOrangeBright,
      special = plt.cynicalGray,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.gunmetalGray,
      indent = plt.bg_lighter,
      indent_scope = plt.combatOliveCore,
      picker = plt.bloodOrange,
      yank = plt.muzzleFlashBright,
      mark = plt.badgeGold,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.warYellowBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.combatOliveCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.gunmetalGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.gunmetalGrayBright,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.gunmetalGray,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.combatOliveCore,
      accent2 = plt.warYellowCore,
      accent3 = plt.bloodOrangeCore,
      accent4 = plt.brutalityCore,
      accent5 = plt.cynicalGrayCore,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.warYellowBright,
      rainbow2 = plt.bloodOrangeBright,
      rainbow3 = plt.combatOliveBright,
      rainbow4 = plt.muzzleFlashBright,
      rainbow5 = plt.cynicalGrayBright,
      rainbow6 = plt.sarcasticRedBright,
      rainbow7 = plt.badgeGoldBright,
    },

    syn = {
      attribute = plt.badgeGold,
      boolean = plt.cynicalGray,
      comment = plt.gunmetalGray,
      constant = plt.fg_light,
      deprecated = plt.gunmetalGrayDark,
      func = plt.warYellowCore,
      identifier = plt.fg_lightest,
      keyword = plt.combatOliveCore,
      method = plt.warYellowBright,
      number = plt.fg_light,
      operator = plt.bloodOrangeCore,
      parameter = plt.fg_mid,
      preproc = plt.cynicalGrayCore,
      punct = plt.fg_dark,
      regex = plt.mockeryGold,
      statement = plt.combatOliveCore,
      string = plt.warYellowCore,
      symbol = plt.badgeGold,
      type = plt.smokeGreenCore,
      variable = plt.fg_lightest,
      special = plt.muzzleFlash,
      special2 = plt.cynicalGray,
      special3 = plt.sarcasticRed,
    },

    vcs = {
      added = plt.smokeGreenCore,
      removed = plt.sarcasticRedCore,
      changed = plt.muzzleFlashCore,
    },

    diff = {
      add = plt.smokeGreenCore,
      change = plt.muzzleFlashCore,
      delete = plt.sarcasticRedCore,
      text = plt.cynicalGray,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.cynicalGray,
    },

    term = {
      black = plt.bg_darkest,
      red = plt.sarcasticRedCore,
      green = plt.combatOliveCore,
      yellow = plt.warYellowCore,
      blue = plt.cynicalGrayCore,
      magenta = plt.jokePurpleCore,
      cyan = plt.gunmetalGrayCore,
      white = plt.fg_light,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.sarcasticRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.combatOliveBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.warYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.cynicalGrayBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.jokePurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.gunmetalGrayBright):brighten(0.2):to_hex(),
      white_bright = color(plt.fg_lightest):brighten(0.1):to_hex(),
      indexed1 = plt.bloodOrange,
      indexed2 = plt.brutality,
    },

    treesitter = {
      ["@comment"] = plt.gunmetalGray,
      ["@comment.documentation"] = plt.gunmetalGrayBright,
      ["@comment.error"] = plt.errorRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.muzzleFlashBright,
      ["@comment.note"] = plt.cynicalGray,

      ["@constant"] = plt.fg_light,
      ["@constant.builtin"] = plt.fg_light,
      ["@constant.macro"] = plt.badgeGold,

      ["@string"] = plt.warYellowCore,
      ["@string.documentation"] = plt.warYellowCore,
      ["@string.regex"] = plt.mockeryGold,
      ["@string.escape"] = plt.muzzleFlashBright,
      ["@string.special"] = plt.warYellowBright,
      ["@string.special.symbol"] = plt.badgeGold,
      ["@string.special.url"] = plt.cynicalGray,
      ["@string.special.path"] = plt.warYellowCore,

      ["@character"] = plt.warYellowCore,
      ["@character.special"] = plt.bloodOrange,

      ["@number"] = plt.fg_light,
      ["@number.float"] = plt.fg_light,

      ["@boolean"] = plt.cynicalGray,

      ["@function"] = plt.warYellowCore,
      ["@function.builtin"] = plt.warYellowCore,
      ["@function.call"] = plt.warYellowCore,
      ["@function.macro"] = plt.cynicalGrayCore,
      ["@function.method"] = plt.warYellowBright,
      ["@function.method.call"] = plt.warYellowBright,

      ["@constructor"] = plt.smokeGreenCore,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.combatOliveCore,
      ["@keyword.coroutine"] = plt.cynicalGrayCore,
      ["@keyword.function"] = plt.combatOliveCore,
      ["@keyword.operator"] = plt.bloodOrangeCore,
      ["@keyword.return"] = plt.combatOliveCore,
      ["@keyword.import"] = plt.cynicalGrayCore,
      ["@keyword.storage"] = plt.combatOliveCore,
      ["@keyword.repeat"] = plt.combatOliveCore,
      ["@keyword.conditional"] = plt.combatOliveCore,
      ["@keyword.exception"] = plt.sarcasticRedCore,
      ["@keyword.directive"] = plt.cynicalGrayCore,
      ["@keyword.directive.define"] = plt.cynicalGrayCore,

      ["@conditional"] = plt.combatOliveCore,
      ["@conditional.ternary"] = plt.combatOliveCore,

      ["@repeat"] = plt.combatOliveCore,

      ["@label"] = plt.badgeGold,

      ["@operator"] = plt.bloodOrangeCore,

      ["@exception"] = plt.sarcasticRedCore,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.combatOliveBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.smokeGreenCore,
      ["@type.builtin"] = plt.smokeGreenCore,
      ["@type.definition"] = plt.smokeGreenCore,
      ["@type.qualifier"] = plt.combatOliveCore,

      ["@attribute"] = plt.badgeGold,
      ["@attribute.builtin"] = plt.badgeGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.smokeGreenCore,
      ["@module.builtin"] = plt.smokeGreenCore,

      ["@namespace"] = plt.smokeGreenCore,
      ["@namespace.builtin"] = plt.smokeGreenCore,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.bloodOrangeCore,

      ["@tag"] = plt.combatOliveCore,
      ["@tag.attribute"] = plt.badgeGold,
      ["@tag.delimiter"] = plt.bloodOrangeCore,
      ["@tag.builtin"] = plt.combatOliveCore,

      ["@markup.strong"] = { fg = plt.bloodOrangeBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.gunmetalGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.cynicalGray, underline = true },
      ["@markup.heading"] = plt.warYellowBright,
      ["@markup.heading.1"] = plt.warYellowBright,
      ["@markup.heading.2"] = plt.bloodOrangeBright,
      ["@markup.heading.3"] = plt.muzzleFlashBright,
      ["@markup.heading.4"] = plt.combatOliveBright,
      ["@markup.heading.5"] = plt.cynicalGrayBright,
      ["@markup.heading.6"] = plt.sarcasticRedBright,
      ["@markup.quote"] = plt.gunmetalGray,
      ["@markup.math"] = plt.fg_light,
      ["@markup.link"] = plt.cynicalGray,
      ["@markup.link.label"] = plt.cynicalGrayBright,
      ["@markup.link.url"] = plt.cynicalGray,
      ["@markup.raw"] = plt.warYellowCore,
      ["@markup.raw.block"] = plt.warYellowCore,
      ["@markup.list"] = plt.combatOliveCore,
      ["@markup.list.checked"] = plt.smokeGreenCore,
      ["@markup.list.unchecked"] = plt.gunmetalGray,

      ["@diff.plus"] = plt.smokeGreenCore,
      ["@diff.minus"] = plt.sarcasticRedCore,
      ["@diff.delta"] = plt.muzzleFlashCore,

      ["@none"] = "none",
      ["@conceal"] = plt.bg_lightest,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.smokeGreenCore,
      ["@constructor.javascript"] = plt.smokeGreenCore,
      ["@constructor.typescript"] = plt.smokeGreenCore,
      ["@namespace.rust"] = plt.smokeGreenCore,
      ["@type.qualifier.rust"] = plt.combatOliveCore,
      ["@constant.macro.c"] = plt.badgeGold,
      ["@constant.macro.cpp"] = plt.badgeGold,
      ["@namespace.go"] = plt.smokeGreenCore,
      ["@property.css"] = plt.warYellowBright,
      ["@type.css"] = plt.combatOliveCore,
      ["@label.json"] = plt.badgeGold,
      ["@field.yaml"] = plt.warYellowBright,
      ["@property.toml"] = plt.warYellowBright,
      ["@function.builtin.bash"] = plt.warYellowCore,
      ["@string.regexp"] = plt.mockeryGold,
      ["@character.special.regex"] = plt.bloodOrange,
    },

    lsp = {
      ["@lsp.type.class"] = plt.smokeGreenCore,
      ["@lsp.type.interface"] = plt.smokeGreenCore,
      ["@lsp.type.struct"] = plt.smokeGreenCore,
      ["@lsp.type.enum"] = plt.smokeGreenCore,
      ["@lsp.type.enumMember"] = plt.fg_light,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.smokeGreenCore,

      ["@lsp.type.macro"] = plt.badgeGold,
      ["@lsp.type.decorator"] = plt.badgeGold,

      ["@lsp.type.builtinType"] = plt.smokeGreenCore,
      ["@lsp.type.selfParameter"] = plt.combatOliveBright,
      ["@lsp.type.typeParameter"] = plt.smokeGreenCore,

      ["@lsp.type.array"] = plt.smokeGreenCore,
      ["@lsp.type.object"] = plt.smokeGreenCore,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.fg_light,
      ["@lsp.type.enumConstant"] = plt.fg_light,

      ["@lsp.type.event"] = plt.smokeGreenCore,
      ["@lsp.type.regexp"] = plt.mockeryGold,
      ["@lsp.type.unresolvedReference"] = plt.smokeGreenCore,

      ["@lsp.mod.deprecated"] = { fg = plt.gunmetalGrayDark, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.fg_light,
      ["@lsp.mod.async"] = plt.combatOliveCore,
      ["@lsp.mod.static"] = plt.combatOliveBright,
      ["@lsp.mod.abstract"] = plt.smokeGreenCore,
      ["@lsp.mod.defaultLibrary"] = plt.smokeGreenCore,
      ["@lsp.mod.documentation"] = plt.gunmetalGrayBright,
    },
  }
end

return {
  name = "Watchmen – The Comedian",
  author = "PrismPunk.nvim",
  description = "War and dark humor — combat olive, war yellow, blood orange, brutal cynicism.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.gunmetalGray,
    base04 = palette.gunmetalGrayBright,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.sarcasticRedCore,
    base09 = palette.bloodOrangeCore,
    base0A = palette.warYellowCore,
    base0B = palette.combatOliveCore,
    base0C = palette.cynicalGrayCore,
    base0D = palette.smokeGreenCore,
    base0E = palette.jokePurpleCore,
    base0F = palette.brutalityCore,
  },

  palette = palette,
  get = M.get,
}
