local palette = {
  cosmicBlack = "#0b0810",
  voidBlack = "#110c14",
  starlightGray = "#14131a",
  nebulaGray = "#1b1825",

  warriorRed = "#c73a3a",
  royalBlue = "#274f87",
  goddessGold = "#ffcf4a",
  lassoGlow = "#ffd78a",
  shieldBronze = "#b07a2d",

  sandBeige = "#d9c9b0",
  stoneGray = "#b8bfc9",
  shadowGray = "#3a3740",
  dimGray = "#66646b",

  accentPearl = "#fff5e6",
  accentCrimson = "#ff7a7a",
  accentAzure = "#66a2ff",

  lightGray = "#eadee6",
  dangerRed = "#e05454",
  infoBlue = "#61afef",

  fierceRed = "#f52a12",
  truthBlue = "#1564a0",
  divineGold = "#ecc466",
  amazonianPink = "#f6576d",
  heroicGray = "#838f9c",
  peaceCyan = "#83c8ea",
  deepRed = "#a31a2f",
  libertyBlue = "#3f6cb8",
  valorYellow = "#efd108",
  courageBronze = "#9a9a9a",
}

return {
  name = "Justice League - Wonder Woman",
  author = "Pantheon.nvim",
  description = "Warrior of truth — regal, fierce, and divine.",

  base16 = {
    base00 = palette.cosmicBlack,
    base01 = palette.voidBlack,
    base02 = palette.starlightGray,
    base03 = palette.shadowGray,
    base04 = palette.dimGray,
    base05 = palette.stoneGray,
    base06 = palette.lightGray,
    base07 = palette.accentPearl,
    base08 = palette.warriorRed,
    base09 = palette.lassoGlow,
    base0A = palette.goddessGold,
    base0B = palette.royalBlue,
    base0C = palette.accentAzure,
    base0D = palette.royalBlue,
    base0E = palette.shieldBronze,
    base0F = palette.sandBeige,
  },

  palette = palette,

  semantic = {
    syn = {
      string = palette.goddessGold,
      number = palette.lassoGlow,
      boolean = palette.royalBlue,
      keyword = palette.warriorRed,
      operator = palette.shieldBronze,
      func = palette.accentAzure,
      type = palette.accentPearl,
      variable = palette.stoneGray,
      comment = palette.shadowGray,
      constant = palette.sandBeige,
      special = palette.warriorRed,
      string_escape = palette.shieldBronze,
      type_builtin = palette.accentAzure,
      method = palette.accentAzure,
      attribute = palette.sandBeige,
      punctuation = palette.dimGray,
    },

    ui = {
      bg = palette.cosmicBlack,
      bg_dim = palette.voidBlack,
      bg_highlight = palette.starlightGray,
      fg = palette.stoneGray,
      fg_dim = palette.dimGray,
      fg_bright = palette.lightGray,
      border = palette.goddessGold,
      float = palette.voidBlack,
      selection = palette.nebulaGray,
      cursorline = palette.voidBlack,
      line_nr = palette.shadowGray,
      line_nr_active = palette.royalBlue,
      line_nr_dim = palette.dimGray,
      nontext = palette.nebulaGray,
      msg_area = palette.shadowGray,
      mode_msg = palette.royalBlue,
      title = palette.goddessGold,
      spell_bad = palette.dangerRed,
      spell_cap = palette.lassoGlow,
      spell_rare = palette.infoBlue,
      spell_local = palette.goddessGold,
      folded = palette.dimGray,
      fold_column = palette.shadowGray,
    },

    diag = {
      error = palette.dangerRed,
      warning = palette.lassoGlow,
      info = palette.infoBlue,
      hint = palette.goddessGold,
      ok = palette.royalBlue,
      virtual_text_error = palette.dangerRed,
      virtual_text_warning = palette.lassoGlow,
      virtual_text_info = palette.infoBlue,
      virtual_text_hint = palette.goddessGold,
      virtual_text_ok = palette.royalBlue,
    },

    git = {
      add = palette.royalBlue,
      change = palette.goddessGold,
      delete = palette.dangerRed,
      add_inline = palette.royalBlue,
      change_inline = palette.goddessGold,
      delete_inline = palette.dangerRed,
    },

    diff = {
      add = palette.royalBlue,
      change = palette.shieldBronze,
      delete = palette.dangerRed,
      text = palette.accentAzure,
    },
  },
}
