local palette = {
  cosmicBlack = "#05060b",
  voidBlack = "#0a0d14",
  starlightGray = "#11151f",
  nebulaGray = "#1a1f28",
  batCape = "#080808",
  batSuit = "#141414",
  batEmblem = "#c5a700",
  batGloves = "#1a1a1a",
  batBoots = "#1a1a1a",
  batBelt = "#bfa334",
  batHighlight = "#323940",
  shadowGray = "#3b424d",
  dimGray = "#525860",
  stoneGray = "#a3abb5",
  lightGray = "#c0c5cd",
  dangerRed = "#d05c6b",
  infoBlue = "#57a7e0",
  tealGlow = "#00c199",
}

return {
  name = "Batman Dark Knight",
  author = "PrismPunk.nvim",
  palette = palette,

  base16 = {
    base00 = palette.cosmicBlack,
    base01 = palette.voidBlack,
    base02 = palette.starlightGray,
    base03 = palette.shadowGray,
    base04 = palette.dimGray,
    base05 = palette.stoneGray,
    base06 = palette.lightGray,
    base07 = palette.batEmblem,
    base08 = palette.dangerRed,
    base09 = palette.batBelt,
    base0A = palette.batEmblem,
    base0B = palette.tealGlow,
    base0C = palette.tealGlow,
    base0D = palette.infoBlue,
    base0E = palette.batHighlight,
    base0F = palette.batGloves,
  },

  semantic = {
    syn = {
      string = palette.batHighlight,
      number = palette.batBelt,
      boolean = palette.batEmblem,
      keyword = palette.batSuit,
      operator = palette.tealGlow,
      func = palette.infoBlue,
      type = palette.batBelt,
      variable = palette.stoneGray,
      comment = palette.shadowGray,
      constant = palette.batEmblem,
      special = palette.batHighlight,
    },
    ui = {
      bg = palette.cosmicBlack,
      bg_dim = palette.voidBlack,
      bg_highlight = palette.starlightGray,
      fg = palette.stoneGray,
      fg_dim = palette.dimGray,
      fg_bright = palette.batEmblem,
      border = palette.batSuit,
      float = palette.voidBlack,
      selection = palette.nebulaGray,
      cursorline = palette.voidBlack,
      line_nr = palette.shadowGray,
      line_nr_active = palette.batHighlight,
    },
    diag = {
      error = palette.dangerRed,
      warning = palette.batBelt,
      info = palette.infoBlue,
      hint = palette.tealGlow,
    },
    git = {
      add = palette.batEmblem,
      change = palette.batHighlight,
      delete = palette.dangerRed,
    },
    diff = {
      add = palette.batEmblem,
      change = palette.batSuit,
      delete = palette.dangerRed,
      text = palette.infoBlue,
    },
  },
}
