local palette = {
  cosmicBlack = "#050508",
  voidBlack = "#0a0a0f",
  starlightGray = "#12121a",
  nebulaGray = "#1b1b26",
  batSuit = "#0c0c0c",
  batRed = "#ff0000",
  batTech = "#1a1a1f",
  shadowGray = "#3a3f4c",
  dimGray = "#565c64",
  stoneGray = "#abb2bf",
  lightGray = "#c8ccd4",
  dangerRed = "#e06c75",
  infoBlue = "#61afef",
  tealGlow = "#00ddaa",
}

return {
  name = "Batman Beyond",
  author = "PrismPunk.nvim",
  palette = palette,
  base16 = {
    base00 = palette.cosmicBlack,
    base01 = palette.voidBlack,
    base02 = palette.starlightGray,
    base03 = palette.shadowGray,
    base04 = palette.dimGray,
    base05 = palette.stoneGray,
    base06 = palette.lightGray,
    base07 = palette.batRed,
    base08 = palette.dangerRed,
    base09 = palette.batRed,
    base0A = palette.batRed,
    base0B = palette.tealGlow,
    base0C = palette.tealGlow,
    base0D = palette.infoBlue,
    base0E = palette.batTech,
    base0F = palette.batSuit,
  },
  semantic = {
    syn = {
      string = palette.batTech,
      number = palette.batRed,
      boolean = palette.batRed,
      keyword = palette.batSuit,
      operator = palette.tealGlow,
      func = palette.infoBlue,
      type = palette.batRed,
      variable = palette.stoneGray,
      comment = palette.shadowGray,
      constant = palette.batRed,
      special = palette.batTech,
    },
    ui = {
      bg = palette.cosmicBlack,
      bg_dim = palette.voidBlack,
      bg_highlight = palette.starlightGray,
      fg = palette.stoneGray,
      fg_dim = palette.dimGray,
      fg_bright = palette.batRed,
      border = palette.batSuit,
      float = palette.voidBlack,
      selection = palette.nebulaGray,
      cursorline = palette.voidBlack,
      line_nr = palette.shadowGray,
      line_nr_active = palette.batTech,
    },
    diag = {
      error = palette.dangerRed,
      warning = palette.batRed,
      info = palette.infoBlue,
      hint = palette.tealGlow,
    },
    git = {
      add = palette.batRed,
      change = palette.batTech,
      delete = palette.dangerRed,
    },
    diff = {
      add = palette.batRed,
      change = palette.batSuit,
      delete = palette.dangerRed,
      text = palette.infoBlue,
    },
  },
}
