local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.dc.league-of-assasins.ras-al-ghul")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.lazarusGreenCore,
      insert = plt.immortalTealCore,
      visual = plt.demonGoldCore,
      replace = plt.leagueRedCore,
      command = plt.eternalBlueCore,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.lazarusGreenDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.lazarusGreenCore,
      header1 = plt.demonGoldBright,
      header2 = plt.immortalTealBright,
      special = plt.immortalTeal,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.lazarusGreenCore,
      indent = plt.bg_lighter,
      indent_scope = plt.lazarusGreenCore,
      picker = plt.pitGreen,
      yank = plt.demonGoldBright,
      mark = plt.immortalTeal,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.demonGoldBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.lazarusGreenCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.shadowGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.shadowGrayLight,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.lazarusGreenCore,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.lazarusGreenCore,
      accent2 = plt.demonGoldCore,
      accent3 = plt.immortalTealCore,
      accent4 = plt.eternalBlueCore,
      accent5 = plt.wisdomVioletCore,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.lazarusGreenBright,
      rainbow2 = plt.demonGoldBright,
      rainbow3 = plt.immortalTealBright,
      rainbow4 = plt.eternalBlueBright,
      rainbow5 = plt.pitGreenBright,
      rainbow6 = plt.wisdomVioletBright,
      rainbow7 = plt.ancientBronzeBright,
    },

    syn = {
      attribute = plt.demonGold,
      boolean = plt.demonGold,
      comment = plt.shadowGray,
      constant = plt.demonGold,
      deprecated = plt.shadowGrayDark,
      func = plt.eternalBlueCore,
      identifier = plt.fg_lightest,
      keyword = plt.lazarusGreenCore,
      method = plt.eternalBlueBright,
      number = plt.demonGold,
      operator = plt.immortalTealCore,
      parameter = plt.fg_mid,
      preproc = plt.wisdomVioletCore,
      punct = plt.fg_dark,
      regex = plt.pitGreen,
      statement = plt.lazarusGreenCore,
      string = plt.lazarusGreenCore,
      symbol = plt.demonGold,
      type = plt.demonGoldCore,
      variable = plt.fg_light,
      special = plt.immortalTeal,
      special2 = plt.wisdomViolet,
      special3 = plt.ancientBronze,
    },

    vcs = {
      added = plt.lazarusGreenCore,
      removed = plt.leagueRedCore,
      changed = plt.demonGoldCore,
    },

    diff = {
      add = plt.lazarusGreenCore,
      change = plt.demonGoldCore,
      delete = plt.leagueRedCore,
      text = plt.immortalTeal,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.immortalTeal,
    },

    term = {
      black = plt.bg_darkest,
      red = plt.leagueRedCore,
      green = plt.lazarusGreenCore,
      yellow = plt.demonGoldCore,
      blue = plt.eternalBlueCore,
      magenta = plt.wisdomVioletCore,
      cyan = plt.immortalTealCore,
      white = plt.fg_mid,
      black_bright = color(plt.bg_darker):brighten(0.6):to_hex(),
      red_bright = color(plt.leagueRedBright):brighten(0.18):to_hex(),
      green_bright = color(plt.lazarusGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.demonGoldBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.eternalBlueBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.wisdomVioletBright):brighten(0.18):to_hex(),
      cyan_bright = color(plt.immortalTealBright):brighten(0.18):to_hex(),
      white_bright = color(plt.fg_lightest):brighten(0.12):to_hex(),
      indexed1 = plt.demonGold,
      indexed2 = plt.leagueRed,
    },

    treesitter = {
      ["@comment"] = plt.shadowGray,
      ["@comment.documentation"] = plt.shadowGrayLight,
      ["@comment.error"] = plt.errorRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.demonGoldBright,
      ["@comment.note"] = plt.immortalTeal,

      ["@constant"] = plt.demonGold,
      ["@constant.builtin"] = plt.demonGoldCore,
      ["@constant.macro"] = plt.ancientBronze,

      ["@string"] = plt.lazarusGreenCore,
      ["@string.documentation"] = plt.lazarusGreenCore,
      ["@string.regex"] = plt.pitGreen,
      ["@string.escape"] = plt.immortalTealBright,
      ["@string.special"] = plt.lazarusGreenBright,
      ["@string.special.symbol"] = plt.demonGold,
      ["@string.special.url"] = plt.eternalBlue,
      ["@string.special.path"] = plt.lazarusGreenCore,

      ["@character"] = plt.lazarusGreenCore,
      ["@character.special"] = plt.demonGold,

      ["@number"] = plt.demonGold,
      ["@number.float"] = plt.demonGoldCore,

      ["@boolean"] = plt.demonGold,

      ["@function"] = plt.eternalBlueCore,
      ["@function.builtin"] = plt.eternalBlueCore,
      ["@function.call"] = plt.eternalBlueCore,
      ["@function.macro"] = plt.wisdomVioletCore,
      ["@function.method"] = plt.eternalBlueBright,
      ["@function.method.call"] = plt.eternalBlueBright,

      ["@constructor"] = plt.demonGoldCore,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.lazarusGreenCore,
      ["@keyword.coroutine"] = plt.wisdomVioletCore,
      ["@keyword.function"] = plt.lazarusGreenCore,
      ["@keyword.operator"] = plt.immortalTealCore,
      ["@keyword.return"] = plt.lazarusGreenCore,
      ["@keyword.import"] = plt.wisdomVioletCore,
      ["@keyword.storage"] = plt.lazarusGreenCore,
      ["@keyword.repeat"] = plt.lazarusGreenCore,
      ["@keyword.conditional"] = plt.lazarusGreenCore,
      ["@keyword.exception"] = plt.leagueRedCore,
      ["@keyword.directive"] = plt.wisdomVioletCore,
      ["@keyword.directive.define"] = plt.wisdomVioletCore,

      ["@conditional"] = plt.lazarusGreenCore,
      ["@conditional.ternary"] = plt.lazarusGreenCore,

      ["@repeat"] = plt.lazarusGreenCore,

      ["@label"] = plt.demonGold,

      ["@operator"] = plt.immortalTealCore,

      ["@exception"] = plt.leagueRedCore,

      ["@variable"] = plt.fg_light,
      ["@variable.builtin"] = plt.lazarusGreenBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.demonGoldCore,
      ["@type.builtin"] = plt.demonGoldCore,
      ["@type.definition"] = plt.demonGoldCore,
      ["@type.qualifier"] = plt.lazarusGreenCore,

      ["@attribute"] = plt.demonGold,
      ["@attribute.builtin"] = plt.demonGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.demonGoldCore,
      ["@module.builtin"] = plt.demonGoldCore,

      ["@namespace"] = plt.demonGoldCore,
      ["@namespace.builtin"] = plt.demonGoldCore,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.immortalTealCore,

      ["@tag"] = plt.lazarusGreenCore,
      ["@tag.attribute"] = plt.demonGold,
      ["@tag.delimiter"] = plt.immortalTealCore,
      ["@tag.builtin"] = plt.lazarusGreenCore,

      ["@markup.strong"] = { fg = plt.demonGoldBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.shadowGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.immortalTeal, underline = true },
      ["@markup.heading"] = plt.demonGoldBright,
      ["@markup.heading.1"] = plt.demonGoldBright,
      ["@markup.heading.2"] = plt.immortalTealBright,
      ["@markup.heading.3"] = plt.lazarusGreenBright,
      ["@markup.heading.4"] = plt.eternalBlueBright,
      ["@markup.heading.5"] = plt.wisdomVioletBright,
      ["@markup.heading.6"] = plt.pitGreenBright,
      ["@markup.quote"] = plt.shadowGray,
      ["@markup.math"] = plt.demonGold,
      ["@markup.link"] = plt.eternalBlue,
      ["@markup.link.label"] = plt.eternalBlueBright,
      ["@markup.link.url"] = plt.eternalBlue,
      ["@markup.raw"] = plt.lazarusGreenCore,
      ["@markup.raw.block"] = plt.lazarusGreenCore,
      ["@markup.list"] = plt.lazarusGreenCore,
      ["@markup.list.checked"] = plt.lazarusGreenCore,
      ["@markup.list.unchecked"] = plt.shadowGray,

      ["@diff.plus"] = plt.lazarusGreenCore,
      ["@diff.minus"] = plt.leagueRedCore,
      ["@diff.delta"] = plt.demonGoldCore,

      ["@none"] = "none",
      ["@conceal"] = plt.bg_lightest,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.demonGoldCore,
      ["@constructor.javascript"] = plt.demonGoldCore,
      ["@constructor.typescript"] = plt.demonGoldCore,
      ["@namespace.rust"] = plt.demonGoldCore,
      ["@type.qualifier.rust"] = plt.lazarusGreenCore,
      ["@constant.macro.c"] = plt.ancientBronze,
      ["@constant.macro.cpp"] = plt.ancientBronze,
      ["@namespace.go"] = plt.demonGoldCore,
      ["@property.css"] = plt.eternalBlueBright,
      ["@type.css"] = plt.lazarusGreenCore,
      ["@label.json"] = plt.demonGold,
      ["@field.yaml"] = plt.eternalBlueBright,
      ["@property.toml"] = plt.eternalBlueBright,
      ["@function.builtin.bash"] = plt.eternalBlueCore,
      ["@string.regexp"] = plt.pitGreen,
      ["@character.special.regex"] = plt.demonGold,
    },

    lsp = {
      ["@lsp.type.class"] = plt.demonGoldCore,
      ["@lsp.type.interface"] = plt.demonGoldCore,
      ["@lsp.type.struct"] = plt.demonGoldCore,
      ["@lsp.type.enum"] = plt.demonGoldCore,
      ["@lsp.type.enumMember"] = plt.demonGold,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.demonGoldCore,

      ["@lsp.type.macro"] = plt.ancientBronze,
      ["@lsp.type.decorator"] = plt.ancientBronze,

      ["@lsp.type.builtinType"] = plt.demonGoldCore,
      ["@lsp.type.selfParameter"] = plt.lazarusGreenBright,
      ["@lsp.type.typeParameter"] = plt.demonGoldCore,

      ["@lsp.type.array"] = plt.demonGoldCore,
      ["@lsp.type.object"] = plt.demonGoldCore,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.demonGold,
      ["@lsp.type.enumConstant"] = plt.demonGold,

      ["@lsp.type.event"] = plt.demonGoldCore,
      ["@lsp.type.regexp"] = plt.pitGreen,
      ["@lsp.type.unresolvedReference"] = plt.demonGoldCore,

      ["@lsp.mod.deprecated"] = { fg = plt.shadowGrayDark, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.demonGold,
      ["@lsp.mod.async"] = plt.lazarusGreenCore,
      ["@lsp.mod.static"] = plt.lazarusGreenBright,
      ["@lsp.mod.abstract"] = plt.demonGoldCore,
      ["@lsp.mod.defaultLibrary"] = plt.demonGoldCore,
      ["@lsp.mod.documentation"] = plt.shadowGrayLight,
    },
  }
end

return {
  name = "Batman – Ra's Al Ghul",
  author = "PrismPunk.nvim",
  description = "Immortal demon — Lazarus green, ancient gold, eternal wisdom, League of Assassins.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.shadowGray,
    base04 = palette.shadowGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.leagueRedCore,
    base09 = palette.ancientBronzeCore,
    base0A = palette.demonGoldCore,
    base0B = palette.lazarusGreenCore,
    base0C = palette.immortalTealCore,
    base0D = palette.eternalBlueCore,
    base0E = palette.wisdomVioletCore,
    base0F = palette.pitGreenCore,
  },

  palette = palette,
  get = M.get,
}
