local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.dc.arkham-asylum.hush")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.hush_red,
      insert = plt.gauze_white,
      visual = plt.grudge_red,
      replace = plt.wound_red,
      command = plt.scalpel_steel,
    },

    ui = {
      fg = plt.gauze_white,
      fg_dim = plt.bone_white,
      fg_dimmer = plt.antiseptic_white,
      fg_dark = plt.sterile_gray,
      fg_reverse = plt.void_black,

      bg_m4 = plt.bandage_glow,
      bg_m3 = plt.elliot_core,
      bg_m2 = plt.operating_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.operating_night,
      bg_p2 = plt.elliot_core,
      bg_gutter = opts.gutter and plt.elliot_core or "none",
      bg_cursorline = plt.elliot_core,
      bg_cursorline_alt = plt.operating_night,
      bg_search = plt.cold_metal,
      bg_visual = plt.grudge_red,
      bg_statusline = plt.elliot_core,

      border = plt.suture_gray,
      header1 = plt.hush_red,
      header2 = plt.scalpel_steel,
      special = plt.arterial_red,
      nontext = plt.operating_night,
      whitespace = plt.bandage_glow,
      win_separator = plt.suture_gray,
      indent = plt.operating_night,
      indent_scope = plt.cold_metal,
      picker = plt.gauze_white,
      yank = plt.wound_red,
      mark = plt.hush_red,
      scrollbar = plt.elliot_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.gauze_white,
        bg_selected = plt.elliot_core,
        fg_inactive = plt.antiseptic_white,
        bg_inactive = plt.void_black,
        fg_alternate = plt.hush_red,
        bg_alternate = plt.void_black,
        indicator = plt.scalpel_steel,
      },

      pmenu = {
        fg = plt.gauze_white,
        fg_sel = "none",
        fg_border = plt.elliot_core,
        bg_border = plt.elliot_core,
        bg = plt.elliot_core,
        bg_sel = plt.operating_night,
        bg_sbar = plt.elliot_core,
        bg_thumb = plt.suture_gray,
      },

      float = {
        fg = plt.gauze_white,
        bg = plt.operating_night,
        fg_border = plt.elliot_core,
        bg_border = plt.operating_night,
      },
    },

    accent = {
      accent1 = plt.hush_red,
      accent2 = plt.scalpel_steel,
      accent3 = plt.suture_gray,
      accent4 = plt.grudge_red,
      accent5 = plt.cold_metal,
      invert = plt.elliot_core,
    },

    rainbow = {
      rainbow1 = plt.hush_red,
      rainbow2 = plt.grudge_red,
      rainbow3 = plt.wound_red,
      rainbow4 = plt.scalpel_steel,
      rainbow5 = plt.cold_metal,
      rainbow6 = plt.suture_gray,
      rainbow7 = plt.sterile_gray,
    },

    syn = {
      attribute = plt.gauze_white,
      boolean = plt.grudge_red,
      comment = plt.antiseptic_white,
      constant = plt.suture_gray,
      deprecated = plt.bandage_glow,
      func = plt.hush_red,
      identifier = plt.gauze_white,
      keyword = plt.hush_red,
      method = plt.scalpel_steel,
      number = plt.wound_red,
      operator = plt.cold_metal,
      parameter = plt.bone_white,
      preproc = plt.grudge_red,
      punct = plt.gauze_white,
      regex = plt.cold_metal,
      statement = plt.hush_red,
      string = plt.suture_gray,
      symbol = plt.gauze_white,
      type = plt.scalpel_steel,
      variable = plt.gauze_white,
      special = plt.arterial_red,
      special2 = plt.cold_metal,
      special3 = plt.wound_red,
    },

    vcs = { added = plt.cold_metal, removed = plt.grudge_red, changed = plt.suture_gray },
    diff = { add = plt.cold_metal, change = plt.scalpel_steel, delete = plt.wound_red, text = plt.hush_red },
    diag = {
      ok = plt.cold_metal,
      error = plt.wound_red,
      warning = plt.grudge_red,
      info = plt.hush_red,
      hint = plt.suture_gray,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_gray,
      yellow = plt.term_gray,
      blue = plt.term_gray,
      magenta = plt.term_red,
      cyan = plt.term_white,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_gray_bright,
      yellow_bright = plt.term_gray_bright,
      blue_bright = plt.term_gray_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_white,
      white_bright = "#ffffff",
      indexed1 = plt.hush_red,
      indexed2 = plt.scalpel_steel,
    },

    treesitter = {
      ["@comment"] = plt.antiseptic_white,
      ["@comment.documentation"] = plt.bone_white,
      ["@comment.error"] = plt.wound_red,
      ["@comment.warning"] = plt.grudge_red,
      ["@comment.todo"] = plt.hush_red,
      ["@comment.note"] = plt.cold_metal,

      ["@constant"] = plt.suture_gray,
      ["@constant.builtin"] = plt.suture_gray,
      ["@constant.macro"] = plt.wound_red,

      ["@string"] = plt.suture_gray,
      ["@string.documentation"] = plt.suture_gray,
      ["@string.regex"] = plt.cold_metal,
      ["@string.escape"] = plt.scalpel_steel,
      ["@string.special"] = plt.grudge_red,
      ["@string.special.symbol"] = plt.gauze_white,
      ["@string.special.url"] = plt.suture_gray,
      ["@string.special.path"] = plt.suture_gray,

      ["@character"] = plt.suture_gray,
      ["@character.special"] = plt.scalpel_steel,

      ["@number"] = plt.wound_red,
      ["@number.float"] = plt.wound_red,

      ["@boolean"] = plt.grudge_red,

      ["@function"] = plt.hush_red,
      ["@function.builtin"] = plt.hush_red,
      ["@function.call"] = plt.hush_red,
      ["@function.macro"] = plt.scalpel_steel,
      ["@function.method"] = plt.scalpel_steel,
      ["@function.method.call"] = plt.scalpel_steel,

      ["@constructor"] = plt.gauze_white,

      ["@parameter"] = plt.bone_white,
      ["@parameter.builtin"] = plt.gauze_white,

      ["@keyword"] = plt.hush_red,
      ["@keyword.coroutine"] = plt.grudge_red,
      ["@keyword.function"] = plt.hush_red,
      ["@keyword.operator"] = plt.cold_metal,
      ["@keyword.return"] = plt.hush_red,
      ["@keyword.import"] = plt.suture_gray,
      ["@keyword.storage"] = plt.hush_red,
      ["@keyword.repeat"] = plt.hush_red,
      ["@keyword.conditional"] = plt.hush_red,
      ["@keyword.exception"] = plt.wound_red,
      ["@keyword.directive"] = plt.grudge_red,
      ["@keyword.directive.define"] = plt.grudge_red,

      ["@conditional"] = plt.hush_red,
      ["@conditional.ternary"] = plt.hush_red,

      ["@repeat"] = plt.hush_red,

      ["@label"] = plt.suture_gray,

      ["@operator"] = plt.cold_metal,

      ["@exception"] = plt.wound_red,

      ["@variable"] = plt.gauze_white,
      ["@variable.builtin"] = plt.suture_gray,
      ["@variable.parameter"] = plt.bone_white,
      ["@variable.member"] = plt.gauze_white,

      ["@type"] = plt.scalpel_steel,
      ["@type.builtin"] = plt.scalpel_steel,
      ["@type.definition"] = plt.scalpel_steel,
      ["@type.qualifier"] = plt.hush_red,

      ["@attribute"] = plt.gauze_white,
      ["@attribute.builtin"] = plt.suture_gray,

      ["@property"] = plt.gauze_white,
      ["@field"] = plt.gauze_white,
      ["@module"] = plt.gauze_white,
      ["@module.builtin"] = plt.gauze_white,
      ["@namespace"] = plt.gauze_white,
      ["@namespace.builtin"] = plt.gauze_white,

      ["@punctuation.delimiter"] = plt.gauze_white,
      ["@punctuation.bracket"] = plt.cold_metal,
      ["@punctuation.special"] = plt.scalpel_steel,

      ["@tag"] = plt.hush_red,
      ["@tag.attribute"] = plt.suture_gray,
      ["@tag.delimiter"] = plt.gauze_white,
      ["@tag.builtin"] = plt.hush_red,

      ["@markup.strong"] = { fg = plt.hush_red, bold = true },
      ["@markup.italic"] = { fg = plt.gauze_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.bandage_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.grudge_red, underline = true },
      ["@markup.heading"] = plt.hush_red,
      ["@markup.heading.1"] = plt.hush_red,
      ["@markup.heading.2"] = plt.grudge_red,
      ["@markup.heading.3"] = plt.wound_red,
      ["@markup.heading.4"] = plt.scalpel_steel,
      ["@markup.heading.5"] = plt.cold_metal,
      ["@markup.heading.6"] = plt.suture_gray,
      ["@markup.quote"] = plt.antiseptic_white,
      ["@markup.math"] = plt.cold_metal,
      ["@markup.link"] = plt.suture_gray,
      ["@markup.link.label"] = plt.gauze_white,
      ["@markup.link.url"] = plt.cold_metal,
      ["@markup.raw"] = plt.suture_gray,
      ["@markup.raw.block"] = plt.suture_gray,
      ["@markup.list"] = plt.hush_red,
      ["@markup.list.checked"] = plt.cold_metal,
      ["@markup.list.unchecked"] = plt.bone_white,

      ["@diff.plus"] = plt.cold_metal,
      ["@diff.minus"] = plt.grudge_red,
      ["@diff.delta"] = plt.suture_gray,

      ["@none"] = "none",
      ["@conceal"] = plt.suture_gray,
      ["@spell"] = plt.gauze_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.gauze_white,
      ["@constructor.python"] = plt.hush_red,
      ["@constructor.javascript"] = plt.hush_red,
      ["@constructor.typescript"] = plt.hush_red,
      ["@namespace.rust"] = plt.gauze_white,
      ["@type.qualifier.rust"] = plt.hush_red,
      ["@constant.macro.c"] = plt.wound_red,
      ["@constant.macro.cpp"] = plt.wound_red,
      ["@namespace.go"] = plt.gauze_white,
      ["@property.css"] = plt.suture_gray,
      ["@type.css"] = plt.hush_red,
      ["@label.json"] = plt.gauze_white,
      ["@field.yaml"] = plt.bone_white,
      ["@property.toml"] = plt.bone_white,
      ["@function.builtin.bash"] = plt.scalpel_steel,
      ["@string.regexp"] = plt.cold_metal,
      ["@character.special.regex"] = plt.scalpel_steel,
    },

    lsp = {
      ["@lsp.type.class"] = plt.scalpel_steel,
      ["@lsp.type.interface"] = plt.scalpel_steel,
      ["@lsp.type.struct"] = plt.scalpel_steel,
      ["@lsp.type.enum"] = plt.scalpel_steel,
      ["@lsp.type.enumMember"] = plt.suture_gray,
      ["@lsp.type.property"] = plt.gauze_white,
      ["@lsp.type.namespace"] = plt.gauze_white,

      ["@lsp.type.macro"] = plt.wound_red,
      ["@lsp.type.decorator"] = plt.hush_red,

      ["@lsp.type.builtinType"] = plt.scalpel_steel,
      ["@lsp.type.selfParameter"] = plt.hush_red,
      ["@lsp.type.typeParameter"] = plt.scalpel_steel,

      ["@lsp.type.array"] = plt.scalpel_steel,
      ["@lsp.type.object"] = plt.scalpel_steel,
      ["@lsp.type.key"] = plt.gauze_white,
      ["@lsp.type.null"] = plt.suture_gray,
      ["@lsp.type.enumConstant"] = plt.suture_gray,

      ["@lsp.type.event"] = plt.scalpel_steel,
      ["@lsp.type.regexp"] = plt.cold_metal,
      ["@lsp.type.unresolvedReference"] = plt.wound_red,

      ["@lsp.mod.deprecated"] = { fg = plt.bandage_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.suture_gray,
      ["@lsp.mod.async"] = plt.hush_red,
      ["@lsp.mod.static"] = plt.scalpel_steel,
      ["@lsp.mod.abstract"] = plt.scalpel_steel,
      ["@lsp.mod.defaultLibrary"] = plt.scalpel_steel,
      ["@lsp.mod.documentation"] = plt.antiseptic_white,
    },
  }
end

return {
  name = "Hush – Thomas Elliot",
  author = "PrismPunk.nvim",
  description = "A childhood betrayal carved into flesh. "
    .. "Cold scalpels, blood that won’t clot, antiseptic white bandages over a face that screams in silence. "
    .. "He doesn’t speak. He just cuts. Again. And again. And again.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.operating_night,
    base02 = palette.elliot_core,
    base03 = palette.bandage_glow,
    base04 = palette.cold_metal,
    base05 = palette.bone_white,
    base06 = palette.gauze_white,
    base07 = palette.gauze_white,
    base08 = palette.grudge_red,
    base09 = palette.wound_red,
    base0A = palette.suture_gray,
    base0B = palette.sterile_gray,
    base0C = palette.hush_red,
    base0D = palette.scalpel_steel,
    base0E = palette.arterial_red,
    base0F = palette.cold_metal,
  },

  palette = palette,
  get = M.get,
}
