local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.tmnt.april-oneal")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.reporterYellowCore,
      insert = plt.pressPassGreen,
      visual = plt.microphoneBlue,
      replace = plt.newsRed,
      command = plt.truthOrange,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.newsroom,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.cameraGray,
      header1 = plt.reporterYellowBright,
      header2 = plt.truthOrange,
      special = plt.channelSix,
      nontext = plt.headlineBlackDeep,
      whitespace = plt.bg_lightest,
      win_separator = plt.cameraGray,
      indent = plt.bg_lighter,
      indent_scope = plt.reporterYellowCore,
      picker = plt.investigatePurple,
      yank = plt.studioLights,
      mark = plt.channelSixBright,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.jacketYellowBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.reporterYellowCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.cameraGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.cameraGrayLight,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.cameraGray,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.reporterYellowCore,
      accent2 = plt.truthOrange,
      accent3 = plt.channelSix,
      accent4 = plt.investigatePurple,
      accent5 = plt.pressPassGreen,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.reporterYellowBright,
      rainbow2 = plt.truthOrangeBright,
      rainbow3 = plt.channelSixBright,
      rainbow4 = plt.pressPassGreenBright,
      rainbow5 = plt.investigatePurpleBright,
      rainbow6 = plt.microphoneBlueBright,
      rainbow7 = plt.newsRedBright,
    },

    syn = {
      attribute = plt.truthOrange,
      boolean = plt.newsRed,
      comment = plt.cameraGray,
      constant = plt.notebookPaper,
      deprecated = plt.cameraGrayDark,
      func = plt.channelSix,
      identifier = plt.fg_lightest,
      keyword = plt.reporterYellowCore,
      method = plt.channelSixBright,
      number = plt.truthOrange,
      operator = plt.pressPassGreen,
      parameter = plt.fg_mid,
      preproc = plt.investigatePurple,
      punct = plt.fg_dark,
      regex = plt.investigatePurpleDeep,
      statement = plt.reporterYellowCore,
      string = plt.pressPassGreen,
      symbol = plt.jacketYellow,
      type = plt.microphoneBlue,
      variable = plt.fg_lightest,
      special = plt.channelSix,
      special2 = plt.truthOrange,
      special3 = plt.investigatePurple,
    },

    vcs = {
      added = plt.pressPassGreen,
      removed = plt.newsRed,
      changed = plt.truthOrange,
    },

    diff = {
      add = plt.pressPassGreen,
      change = plt.truthOrange,
      delete = plt.newsRed,
      text = plt.channelSix,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.dangerRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.channelSix,
    },

    term = {
      black = plt.newsroom,
      red = plt.newsRedCore,
      green = plt.pressPassGreenCore,
      yellow = plt.reporterYellowCore,
      blue = plt.microphoneBlueCore,
      magenta = plt.investigatePurpleCore,
      cyan = plt.channelSixCore,
      white = plt.notebookPaper,
      black_bright = color(plt.newsroom):brighten(0.6):to_hex(),
      red_bright = color(plt.newsRedBright):brighten(0.2):to_hex(),
      green_bright = color(plt.pressPassGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.jacketYellowBright):brighten(0.2):to_hex(),
      blue_bright = color(plt.microphoneBlueBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.investigatePurpleBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.channelSixBright):brighten(0.2):to_hex(),
      white_bright = color(plt.studioLights):brighten(0.2):to_hex(),
      indexed1 = plt.reporterYellow,
      indexed2 = plt.newsRed,
    },

    treesitter = {
      ["@comment"] = plt.cameraGray,
      ["@comment.documentation"] = plt.cameraGrayLight,
      ["@comment.error"] = plt.dangerRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.truthOrange,
      ["@comment.note"] = plt.channelSix,

      ["@constant"] = plt.notebookPaper,
      ["@constant.builtin"] = plt.notebookPaper,
      ["@constant.macro"] = plt.truthOrange,

      ["@string"] = plt.pressPassGreen,
      ["@string.documentation"] = plt.pressPassGreen,
      ["@string.regex"] = plt.investigatePurpleDeep,
      ["@string.escape"] = plt.jacketYellowBright,
      ["@string.special"] = plt.pressPassGreenBright,
      ["@string.special.symbol"] = plt.jacketYellow,
      ["@string.special.url"] = plt.channelSix,
      ["@string.special.path"] = plt.pressPassGreen,

      ["@character"] = plt.pressPassGreen,
      ["@character.special"] = plt.truthOrange,

      ["@number"] = plt.truthOrange,
      ["@number.float"] = plt.truthOrange,

      ["@boolean"] = plt.newsRed,

      ["@function"] = plt.channelSix,
      ["@function.builtin"] = plt.channelSix,
      ["@function.call"] = plt.channelSix,
      ["@function.macro"] = plt.investigatePurple,
      ["@function.method"] = plt.channelSixBright,
      ["@function.method.call"] = plt.channelSixBright,

      ["@constructor"] = plt.microphoneBlue,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.reporterYellowCore,
      ["@keyword.coroutine"] = plt.investigatePurple,
      ["@keyword.function"] = plt.reporterYellowCore,
      ["@keyword.operator"] = plt.pressPassGreen,
      ["@keyword.return"] = plt.reporterYellowCore,
      ["@keyword.import"] = plt.investigatePurple,
      ["@keyword.storage"] = plt.reporterYellowCore,
      ["@keyword.repeat"] = plt.reporterYellowCore,
      ["@keyword.conditional"] = plt.reporterYellowCore,
      ["@keyword.exception"] = plt.newsRed,
      ["@keyword.directive"] = plt.investigatePurple,
      ["@keyword.directive.define"] = plt.investigatePurple,

      ["@conditional"] = plt.reporterYellowCore,
      ["@conditional.ternary"] = plt.reporterYellowCore,

      ["@repeat"] = plt.reporterYellowCore,

      ["@label"] = plt.truthOrange,

      ["@operator"] = plt.pressPassGreen,

      ["@exception"] = plt.newsRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.jacketYellowBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.microphoneBlue,
      ["@type.builtin"] = plt.microphoneBlue,
      ["@type.definition"] = plt.microphoneBlue,
      ["@type.qualifier"] = plt.reporterYellowCore,

      ["@attribute"] = plt.truthOrange,
      ["@attribute.builtin"] = plt.truthOrange,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.microphoneBlue,
      ["@module.builtin"] = plt.microphoneBlue,

      ["@namespace"] = plt.microphoneBlue,
      ["@namespace.builtin"] = plt.microphoneBlue,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.channelSix,

      ["@tag"] = plt.reporterYellowCore,
      ["@tag.attribute"] = plt.truthOrange,
      ["@tag.delimiter"] = plt.pressPassGreen,
      ["@tag.builtin"] = plt.reporterYellowCore,

      ["@markup.strong"] = { fg = plt.reporterYellowBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.cameraGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.channelSix, underline = true },
      ["@markup.heading"] = plt.reporterYellowBright,
      ["@markup.heading.1"] = plt.reporterYellowBright,
      ["@markup.heading.2"] = plt.truthOrange,
      ["@markup.heading.3"] = plt.channelSix,
      ["@markup.heading.4"] = plt.pressPassGreen,
      ["@markup.heading.5"] = plt.investigatePurple,
      ["@markup.heading.6"] = plt.microphoneBlue,
      ["@markup.quote"] = plt.cameraGray,
      ["@markup.math"] = plt.truthOrange,
      ["@markup.link"] = plt.channelSix,
      ["@markup.link.label"] = plt.channelSixBright,
      ["@markup.link.url"] = plt.channelSix,
      ["@markup.raw"] = plt.pressPassGreen,
      ["@markup.raw.block"] = plt.pressPassGreen,
      ["@markup.list"] = plt.reporterYellowCore,
      ["@markup.list.checked"] = plt.pressPassGreen,
      ["@markup.list.unchecked"] = plt.cameraGray,

      ["@diff.plus"] = plt.pressPassGreen,
      ["@diff.minus"] = plt.newsRed,
      ["@diff.delta"] = plt.truthOrange,

      ["@none"] = "none",
      ["@conceal"] = plt.headlineBlackDeep,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.microphoneBlue,
      ["@constructor.javascript"] = plt.microphoneBlue,
      ["@constructor.typescript"] = plt.microphoneBlue,
      ["@namespace.rust"] = plt.microphoneBlue,
      ["@type.qualifier.rust"] = plt.reporterYellowCore,
      ["@constant.macro.c"] = plt.truthOrange,
      ["@constant.macro.cpp"] = plt.truthOrange,
      ["@namespace.go"] = plt.microphoneBlue,
      ["@property.css"] = plt.channelSixBright,
      ["@type.css"] = plt.reporterYellowCore,
      ["@label.json"] = plt.truthOrange,
      ["@field.yaml"] = plt.channelSixBright,
      ["@property.toml"] = plt.channelSixBright,
      ["@function.builtin.bash"] = plt.channelSix,
      ["@string.regexp"] = plt.investigatePurpleDeep,
      ["@character.special.regex"] = plt.truthOrange,
    },

    lsp = {
      ["@lsp.type.class"] = plt.microphoneBlue,
      ["@lsp.type.interface"] = plt.microphoneBlue,
      ["@lsp.type.struct"] = plt.microphoneBlue,
      ["@lsp.type.enum"] = plt.microphoneBlue,
      ["@lsp.type.enumMember"] = plt.notebookPaper,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.microphoneBlue,

      ["@lsp.type.macro"] = plt.truthOrange,
      ["@lsp.type.decorator"] = plt.truthOrange,

      ["@lsp.type.builtinType"] = plt.microphoneBlue,
      ["@lsp.type.selfParameter"] = plt.jacketYellowBright,
      ["@lsp.type.typeParameter"] = plt.microphoneBlue,

      ["@lsp.type.array"] = plt.microphoneBlue,
      ["@lsp.type.object"] = plt.microphoneBlue,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.notebookPaper,
      ["@lsp.type.enumConstant"] = plt.notebookPaper,

      ["@lsp.type.event"] = plt.microphoneBlue,
      ["@lsp.type.regexp"] = plt.investigatePurpleDeep,
      ["@lsp.type.unresolvedReference"] = plt.microphoneBlue,

      ["@lsp.mod.deprecated"] = { fg = plt.cameraGrayDark, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.notebookPaper,
      ["@lsp.mod.async"] = plt.reporterYellowCore,
      ["@lsp.mod.static"] = plt.jacketYellowBright,
      ["@lsp.mod.abstract"] = plt.microphoneBlue,
      ["@lsp.mod.defaultLibrary"] = plt.microphoneBlue,
      ["@lsp.mod.documentation"] = plt.cameraGrayLight,
    },
  }
end

return {
  name = "TMNT – April O'Neal",
  author = "PrismPunk.nvim",
  description = "Investigative reporter — truth-seeker, brave journalist, Channel 6 News.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.cameraGray,
    base04 = palette.cameraGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.newsRed,
    base09 = palette.truthOrange,
    base0A = palette.reporterYellow,
    base0B = palette.pressPassGreen,
    base0C = palette.channelSix,
    base0D = palette.microphoneBlue,
    base0E = palette.investigatePurple,
    base0F = palette.notebookInk,
  },

  palette = palette,
  get = M.get,
}
