local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.tmnt.leonardo")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.leaderBlueCore,
      insert = plt.disciplineGreen,
      visual = plt.focusCyan,
      replace = plt.dangerRed,
      command = plt.honorGold,
    },
    accent = {
      accent1 = plt.leaderBlueCore,
      accent2 = plt.katanaSilver,
      accent3 = plt.honorGold,
      accent4 = plt.focusCyan,
      accent5 = plt.disciplineGreen,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.leaderBlueBright,
      rainbow2 = plt.focusCyanBright,
      rainbow3 = plt.honorGold,
      rainbow4 = plt.disciplineGreenBright,
      rainbow5 = plt.katanaSilver,
      rainbow6 = plt.strategyPurple,
      rainbow7 = plt.steelBlue,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.steelBlue,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.leaderBlueCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.shadowGrayDark,
      selection = plt.bg_mid,
      win_separator = plt.steelBlue,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.steelBlue,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.steelBlue,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.honorGold,
      boolean = plt.leaderBlueCore,
      comment = plt.shadowGray,
      constant = plt.katanaSilver,
      deprecated = plt.shadowGrayDeep,
      func = plt.focusCyan,
      identifier = plt.fg_lightest,
      keyword = plt.leaderBlueCore,
      method = plt.focusCyanBright,
      number = plt.honorGoldMuted,
      operator = plt.katanaSteel,
      parameter = plt.fg_mid,
      preproc = plt.strategyPurple,
      punct = plt.fg_dark,
      regex = plt.disciplineGreenDeep,
      special = plt.focusCyan,
      statement = plt.leaderBlueCore,
      string = plt.disciplineGreen,
      symbol = plt.honorGold,
      type = plt.katanaSilver,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dangerRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.focusCyan,
    },
    diff = {
      add = plt.disciplineGreen,
      change = plt.honorGold,
      delete = plt.dangerRed,
      text = plt.focusCyan,
    },
    vcs = {
      added = plt.disciplineGreen,
      changed = plt.honorGold,
      removed = plt.dangerRed,
    },
    term = {
      black = plt.ninjaBlack,
      red = plt.dangerRed,
      green = plt.disciplineGreen,
      yellow = plt.honorGold,
      blue = plt.leaderBlueCore,
      magenta = plt.strategyPurple,
      cyan = plt.focusCyan,
      white = plt.katanaSilver,
      black_bright = color(plt.ninjaBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.dangerRed):brighten(0.2):to_hex(),
      green_bright = color(plt.disciplineGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.honorGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.leaderBlueBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.strategyPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.focusCyanBright):brighten(0.2):to_hex(),
      white_bright = color(plt.katanaSilver):brighten(0.2):to_hex(),
    },
  }
end

return {
  name = "TMNT – Leonardo",
  author = "PrismPunk.nvim",
  description = "Leader in blue — disciplined, strategic, honorable.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.shadowGray,
    base04 = palette.shadowGrayDark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.dangerRed,
    base09 = palette.honorGold,
    base0A = palette.honorGoldMuted,
    base0B = palette.disciplineGreen,
    base0C = palette.focusCyan,
    base0D = palette.leaderBlueCore,
    base0E = palette.strategyPurple,
    base0F = palette.dojoWood,
  },
  palette = palette,
  get = M.get,
}
