local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.tmnt.leonardo")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.leaderBlueCore,
      insert = plt.disciplineGreen,
      visual = plt.focusCyan,
      replace = plt.dangerRed,
      command = plt.honorGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.meditationBlue,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.steelBlue,
      header1 = plt.leaderBlueBright,
      header2 = plt.honorGold,
      special = plt.focusCyan,
      nontext = plt.shadowGrayDark,
      whitespace = plt.shadowGrayDeep,
      win_separator = plt.steelBlue,
      indent = plt.bg_lighter,
      indent_scope = plt.leaderBlueCore,
      picker = plt.honorGold,
      yank = plt.honorGoldMuted,
      mark = plt.focusCyan,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.leaderBlueBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.leaderBlueCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.shadowGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.steelBlue,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.steelBlue,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.leaderBlueCore,
      accent2 = plt.katanaSilver,
      accent3 = plt.honorGold,
      accent4 = plt.focusCyan,
      accent5 = plt.disciplineGreen,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.leaderBlueBright,
      rainbow2 = plt.focusCyan,
      rainbow3 = plt.honorGold,
      rainbow4 = plt.disciplineGreen,
      rainbow5 = plt.katanaSilver,
      rainbow6 = plt.strategyPurple,
      rainbow7 = plt.steelBlue,
    },

    syn = {
      attribute = plt.honorGold,
      boolean = plt.leaderBlueCore,
      comment = plt.shadowGray,
      constant = plt.katanaSilver,
      deprecated = plt.shadowGrayDeep,
      func = plt.focusCyan,
      identifier = plt.fg_lightest,
      keyword = plt.leaderBlueCore,
      method = plt.focusCyanBright,
      number = plt.honorGoldMuted,
      operator = plt.katanaSteel,
      parameter = plt.fg_mid,
      preproc = plt.strategyPurple,
      punct = plt.fg_dark,
      regex = plt.disciplineGreen,
      statement = plt.leaderBlueCore,
      string = plt.disciplineGreen,
      symbol = plt.honorGold,
      type = plt.katanaSilver,
      variable = plt.fg_lightest,
      special = plt.focusCyan,
      special2 = plt.honorGold,
      special3 = plt.strategyPurple,
    },

    vcs = {
      added = plt.disciplineGreen,
      removed = plt.dangerRed,
      changed = plt.honorGold,
    },

    diff = {
      add = plt.disciplineGreen,
      change = plt.honorGold,
      delete = plt.dangerRed,
      text = plt.focusCyan,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.dangerRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.focusCyan,
    },

    term = {
      black = plt.ninjaBlack,
      red = plt.dangerRed,
      green = plt.disciplineGreen,
      yellow = plt.honorGold,
      blue = plt.leaderBlueCore,
      magenta = plt.strategyPurple,
      cyan = plt.focusCyan,
      white = plt.katanaSilver,
      black_bright = color(plt.ninjaBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.dangerRed):brighten(0.2):to_hex(),
      green_bright = color(plt.disciplineGreen):brighten(0.2):to_hex(),
      yellow_bright = color(plt.honorGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.leaderBlueBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.strategyPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.focusCyanBright):brighten(0.2):to_hex(),
      white_bright = color(plt.katanaSilver):brighten(0.2):to_hex(),
      indexed1 = plt.honorGold,
      indexed2 = plt.dangerRed,
    },

    treesitter = {
      ["@comment"] = plt.shadowGray,
      ["@comment.documentation"] = plt.shadowGrayDark,
      ["@comment.error"] = plt.dangerRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.honorGold,
      ["@comment.note"] = plt.focusCyan,

      ["@constant"] = plt.katanaSilver,
      ["@constant.builtin"] = plt.katanaSilver,
      ["@constant.macro"] = plt.honorGold,

      ["@string"] = plt.disciplineGreen,
      ["@string.documentation"] = plt.disciplineGreen,
      ["@string.regex"] = plt.disciplineGreenDeep,
      ["@string.escape"] = plt.honorGoldMuted,
      ["@string.special"] = plt.disciplineGreenBright,
      ["@string.special.symbol"] = plt.honorGold,
      ["@string.special.url"] = plt.focusCyan,
      ["@string.special.path"] = plt.disciplineGreen,

      ["@character"] = plt.disciplineGreen,
      ["@character.special"] = plt.honorGold,

      ["@number"] = plt.honorGoldMuted,
      ["@number.float"] = plt.honorGoldMuted,

      ["@boolean"] = plt.leaderBlueCore,

      ["@function"] = plt.focusCyan,
      ["@function.builtin"] = plt.focusCyan,
      ["@function.call"] = plt.focusCyan,
      ["@function.macro"] = plt.strategyPurple,
      ["@function.method"] = plt.focusCyanBright,
      ["@function.method.call"] = plt.focusCyanBright,

      ["@constructor"] = plt.katanaSilver,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.leaderBlueCore,
      ["@keyword.coroutine"] = plt.strategyPurple,
      ["@keyword.function"] = plt.leaderBlueCore,
      ["@keyword.operator"] = plt.katanaSteel,
      ["@keyword.return"] = plt.leaderBlueCore,
      ["@keyword.import"] = plt.strategyPurple,
      ["@keyword.storage"] = plt.leaderBlueCore,
      ["@keyword.repeat"] = plt.leaderBlueCore,
      ["@keyword.conditional"] = plt.leaderBlueCore,
      ["@keyword.exception"] = plt.dangerRed,
      ["@keyword.directive"] = plt.strategyPurple,
      ["@keyword.directive.define"] = plt.strategyPurple,

      ["@conditional"] = plt.leaderBlueCore,
      ["@conditional.ternary"] = plt.leaderBlueCore,

      ["@repeat"] = plt.leaderBlueCore,

      ["@label"] = plt.honorGold,

      ["@operator"] = plt.katanaSteel,

      ["@exception"] = plt.dangerRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.leaderBlueBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.katanaSilver,
      ["@type.builtin"] = plt.katanaSilver,
      ["@type.definition"] = plt.katanaSilver,
      ["@type.qualifier"] = plt.leaderBlueCore,

      ["@attribute"] = plt.honorGold,
      ["@attribute.builtin"] = plt.honorGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.katanaSilver,
      ["@module.builtin"] = plt.katanaSilver,

      ["@namespace"] = plt.katanaSilver,
      ["@namespace.builtin"] = plt.katanaSilver,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.focusCyan,

      ["@tag"] = plt.leaderBlueCore,
      ["@tag.attribute"] = plt.honorGold,
      ["@tag.delimiter"] = plt.katanaSteel,
      ["@tag.builtin"] = plt.leaderBlueCore,

      ["@markup.strong"] = { fg = plt.leaderBlueBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.shadowGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.focusCyan, underline = true },
      ["@markup.heading"] = plt.leaderBlueBright,
      ["@markup.heading.1"] = plt.leaderBlueBright,
      ["@markup.heading.2"] = plt.honorGold,
      ["@markup.heading.3"] = plt.focusCyan,
      ["@markup.heading.4"] = plt.disciplineGreen,
      ["@markup.heading.5"] = plt.katanaSilver,
      ["@markup.heading.6"] = plt.strategyPurple,
      ["@markup.quote"] = plt.shadowGray,
      ["@markup.math"] = plt.honorGoldMuted,
      ["@markup.link"] = plt.focusCyan,
      ["@markup.link.label"] = plt.focusCyanBright,
      ["@markup.link.url"] = plt.focusCyan,
      ["@markup.raw"] = plt.disciplineGreen,
      ["@markup.raw.block"] = plt.disciplineGreen,
      ["@markup.list"] = plt.leaderBlueCore,
      ["@markup.list.checked"] = plt.disciplineGreen,
      ["@markup.list.unchecked"] = plt.shadowGray,

      ["@diff.plus"] = plt.disciplineGreen,
      ["@diff.minus"] = plt.dangerRed,
      ["@diff.delta"] = plt.honorGold,

      ["@none"] = "none",
      ["@conceal"] = plt.shadowGrayDeep,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.katanaSilver,
      ["@constructor.javascript"] = plt.katanaSilver,
      ["@constructor.typescript"] = plt.katanaSilver,
      ["@namespace.rust"] = plt.katanaSilver,
      ["@type.qualifier.rust"] = plt.leaderBlueCore,
      ["@constant.macro.c"] = plt.honorGold,
      ["@constant.macro.cpp"] = plt.honorGold,
      ["@namespace.go"] = plt.katanaSilver,
      ["@property.css"] = plt.focusCyanBright,
      ["@type.css"] = plt.leaderBlueCore,
      ["@label.json"] = plt.honorGold,
      ["@field.yaml"] = plt.focusCyanBright,
      ["@property.toml"] = plt.focusCyanBright,
      ["@function.builtin.bash"] = plt.focusCyan,
      ["@string.regexp"] = plt.disciplineGreenDeep,
      ["@character.special.regex"] = plt.honorGold,
    },

    lsp = {
      ["@lsp.type.class"] = plt.katanaSilver,
      ["@lsp.type.interface"] = plt.katanaSilver,
      ["@lsp.type.struct"] = plt.katanaSilver,
      ["@lsp.type.enum"] = plt.katanaSilver,
      ["@lsp.type.enumMember"] = plt.katanaSilver,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.katanaSilver,

      ["@lsp.type.macro"] = plt.honorGold,
      ["@lsp.type.decorator"] = plt.honorGold,

      ["@lsp.type.builtinType"] = plt.katanaSilver,
      ["@lsp.type.selfParameter"] = plt.leaderBlueBright,
      ["@lsp.type.typeParameter"] = plt.katanaSilver,

      ["@lsp.type.array"] = plt.katanaSilver,
      ["@lsp.type.object"] = plt.katanaSilver,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.katanaSilver,
      ["@lsp.type.enumConstant"] = plt.katanaSilver,

      ["@lsp.type.event"] = plt.katanaSilver,
      ["@lsp.type.regexp"] = plt.disciplineGreenDeep,
      ["@lsp.type.unresolvedReference"] = plt.katanaSilver,

      ["@lsp.mod.deprecated"] = { fg = plt.shadowGrayDeep, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.katanaSilver,
      ["@lsp.mod.async"] = plt.leaderBlueCore,
      ["@lsp.mod.static"] = plt.leaderBlueBright,
      ["@lsp.mod.abstract"] = plt.katanaSilver,
      ["@lsp.mod.defaultLibrary"] = plt.katanaSilver,
      ["@lsp.mod.documentation"] = plt.shadowGrayDark,
    },
  }
end

return {
  name = "TMNT – Leonardo",
  author = "PrismPunk.nvim",
  description = "Leader in blue — disciplined, strategic, honorable.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.shadowGray,
    base04 = palette.shadowGrayDark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.dangerRed,
    base09 = palette.honorGold,
    base0A = palette.honorGoldMuted,
    base0B = palette.disciplineGreen,
    base0C = palette.focusCyan,
    base0D = palette.leaderBlueCore,
    base0E = palette.strategyPurple,
    base0F = palette.dojoWood,
  },

  palette = palette,
  get = M.get,
}
