local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.tmnt.michelangelo")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.partyOrangeCore,
      insert = plt.cowaGreen,
      visual = plt.skateBlue,
      replace = plt.pizzaRed,
      command = plt.cheeseYellow,
    },
    accent = {
      accent1 = plt.partyOrangeCore,
      accent2 = plt.cheeseYellow,
      accent3 = plt.cowaGreen,
      accent4 = plt.skateBlue,
      accent5 = plt.sunsetPink,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.partyOrangeBright,
      rainbow2 = plt.cheeseYellowBright,
      rainbow3 = plt.cowaGreenBright,
      rainbow4 = plt.skateBlueBright,
      rainbow5 = plt.sunsetPinkBright,
      rainbow6 = plt.radicalPurpleBright,
      rainbow7 = plt.pizzaRedBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.nunchuckChain,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.partyOrangeCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lightest,
      selection = plt.bg_mid,
      win_separator = plt.nunchuckChain,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.nunchuckChain,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.nunchuckChain,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.cheeseYellow,
      boolean = plt.skateBlue,
      comment = plt.beachSand,
      constant = plt.sunsetPink,
      deprecated = plt.nunchuckWoodDark,
      func = plt.sunsetPink,
      identifier = plt.fg_lightest,
      keyword = plt.partyOrangeCore,
      method = plt.sunsetPinkBright,
      number = plt.cheeseYellow,
      operator = plt.cowaGreen,
      parameter = plt.fg_mid,
      preproc = plt.radicalPurple,
      punct = plt.fg_dark,
      regex = plt.radicalPurpleDeep,
      special = plt.sunsetPink,
      statement = plt.partyOrangeCore,
      string = plt.cowaGreen,
      symbol = plt.cheeseYellow,
      type = plt.skateBlue,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dangerRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.sunsetPink,
    },
    diff = {
      add = plt.cowaGreen,
      change = plt.cheeseYellow,
      delete = plt.pizzaRed,
      text = plt.skateBlue,
    },
    vcs = {
      added = plt.cowaGreen,
      changed = plt.cheeseYellow,
      removed = plt.pizzaRed,
    },
    term = {
      black = plt.pizzaParlor,
      red = plt.pizzaRed,
      green = plt.cowaGreenCore,
      yellow = plt.cheeseYellowCore,
      blue = plt.skateBlueCore,
      magenta = plt.radicalPurple,
      cyan = plt.tropicalTeal,
      white = plt.fg_light,
      black_bright = color(plt.pizzaParlor):brighten(0.6):to_hex(),
      red_bright = color(plt.pizzaRedBright):brighten(0.2):to_hex(),
      green_bright = color(plt.cowaGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.cheeseYellowBright):brighten(0.2):to_hex(),
      blue_bright = color(plt.skateBlueBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.radicalPurpleBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.surfboardCyan):brighten(0.2):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
    },
  }
end

return {
  name = "TMNT – Michelangelo",
  author = "PrismPunk.nvim",
  description = "Party dude — fun-loving, energetic, cowabunga!",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.beachSand,
    base04 = palette.nunchuckChain,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.pizzaRed,
    base09 = palette.comedyGold,
    base0A = palette.cheeseYellow,
    base0B = palette.cowaGreen,
    base0C = palette.tropicalTeal,
    base0D = palette.skateBlue,
    base0E = palette.radicalPurple,
    base0F = palette.nunchuckWood,
  },
  palette = palette,
  get = M.get,
}
