local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.tmnt.shredder")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.bladeSteelCore,
      insert = plt.evilGreen,
      visual = plt.shadowPurple,
      replace = plt.crimsonRage,
      command = plt.armorSilver,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.footSoldier,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.bladeSteelCore,
      header1 = plt.armorSilverBright,
      header2 = plt.crimsonRage,
      special = plt.vengeanceViolet,
      nontext = plt.helmetDarkDeep,
      whitespace = plt.bg_lightest,
      win_separator = plt.bladeSteelCore,
      indent = plt.bg_lighter,
      indent_scope = plt.bladeSteelCore,
      picker = plt.crimsonRage,
      yank = plt.spikesSilverSharp,
      mark = plt.vengeanceViolet,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.armorSilverBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.bladeSteelCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.shuriken,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bladeSteelCore,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.bladeSteelCore,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.bladeSteelCore,
      accent2 = plt.crimsonRage,
      accent3 = plt.shadowPurple,
      accent4 = plt.armorSilver,
      accent5 = plt.vengeanceViolet,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.armorSilverBright,
      rainbow2 = plt.bladeSteelBright,
      rainbow3 = plt.crimsonRageBright,
      rainbow4 = plt.footClanRedBright,
      rainbow5 = plt.shadowPurpleBright,
      rainbow6 = plt.vengeanceVioletBright,
      rainbow7 = plt.darkPowerBright,
    },

    syn = {
      attribute = plt.crimsonRage,
      boolean = plt.footClanRed,
      comment = plt.shuriken,
      constant = plt.armorSilver,
      deprecated = plt.helmetDark,
      func = plt.shadowPurple,
      identifier = plt.fg_lightest,
      keyword = plt.bladeSteelCore,
      method = plt.shadowPurpleBright,
      number = plt.crimsonRageCore,
      operator = plt.spikesSilver,
      parameter = plt.fg_mid,
      preproc = plt.vengeanceViolet,
      punct = plt.fg_dark,
      regex = plt.darkPowerCore,
      statement = plt.bladeSteelCore,
      string = plt.evilGreen,
      symbol = plt.spikesSilverSharp,
      type = plt.armorSilverCore,
      variable = plt.fg_lightest,
      special = plt.vengeanceViolet,
      special2 = plt.crimsonRage,
      special3 = plt.darkPower,
    },

    vcs = {
      added = plt.evilGreen,
      removed = plt.crimsonRage,
      changed = plt.footClanRed,
    },

    diff = {
      add = plt.evilGreen,
      change = plt.footClanRed,
      delete = plt.crimsonRage,
      text = plt.shadowPurple,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.dangerRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.shadowPurple,
    },

    term = {
      black = plt.helmetDarkDeep,
      red = plt.crimsonRageCore,
      green = plt.evilGreenCore,
      yellow = plt.warningAmber,
      blue = plt.infoBlue,
      magenta = plt.vengeanceVioletCore,
      cyan = plt.shadowPurpleCore,
      white = plt.armorSilver,
      black_bright = color(plt.helmetDarkDeep):brighten(0.6):to_hex(),
      red_bright = color(plt.crimsonRageBright):brighten(0.2):to_hex(),
      green_bright = color(plt.evilGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.warningAmber):brighten(0.2):to_hex(),
      blue_bright = color(plt.infoBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.vengeanceVioletBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.shadowPurpleBright):brighten(0.2):to_hex(),
      white_bright = color(plt.armorSilverBright):brighten(0.2):to_hex(),
      indexed1 = plt.crimsonRage,
      indexed2 = plt.bladeSteelCore,
    },

    treesitter = {
      ["@comment"] = plt.shuriken,
      ["@comment.documentation"] = plt.shurikenSharp,
      ["@comment.error"] = plt.dangerRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.crimsonRage,
      ["@comment.note"] = plt.vengeanceViolet,

      ["@constant"] = plt.armorSilver,
      ["@constant.builtin"] = plt.armorSilver,
      ["@constant.macro"] = plt.crimsonRage,

      ["@string"] = plt.evilGreen,
      ["@string.documentation"] = plt.evilGreen,
      ["@string.regex"] = plt.darkPowerCore,
      ["@string.escape"] = plt.crimsonRageCore,
      ["@string.special"] = plt.evilGreenBright,
      ["@string.special.symbol"] = plt.spikesSilverSharp,
      ["@string.special.url"] = plt.shadowPurple,
      ["@string.special.path"] = plt.evilGreen,

      ["@character"] = plt.evilGreen,
      ["@character.special"] = plt.crimsonRage,

      ["@number"] = plt.crimsonRageCore,
      ["@number.float"] = plt.crimsonRageCore,

      ["@boolean"] = plt.footClanRed,

      ["@function"] = plt.shadowPurple,
      ["@function.builtin"] = plt.shadowPurple,
      ["@function.call"] = plt.shadowPurple,
      ["@function.macro"] = plt.vengeanceViolet,
      ["@function.method"] = plt.shadowPurpleBright,
      ["@function.method.call"] = plt.shadowPurpleBright,

      ["@constructor"] = plt.armorSilverCore,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.bladeSteelCore,
      ["@keyword.coroutine"] = plt.vengeanceViolet,
      ["@keyword.function"] = plt.bladeSteelCore,
      ["@keyword.operator"] = plt.spikesSilver,
      ["@keyword.return"] = plt.bladeSteelCore,
      ["@keyword.import"] = plt.vengeanceViolet,
      ["@keyword.storage"] = plt.bladeSteelCore,
      ["@keyword.repeat"] = plt.bladeSteelCore,
      ["@keyword.conditional"] = plt.bladeSteelCore,
      ["@keyword.exception"] = plt.crimsonRageBright,
      ["@keyword.directive"] = plt.vengeanceViolet,
      ["@keyword.directive.define"] = plt.vengeanceViolet,

      ["@conditional"] = plt.bladeSteelCore,
      ["@conditional.ternary"] = plt.bladeSteelCore,

      ["@repeat"] = plt.bladeSteelCore,

      ["@label"] = plt.crimsonRage,

      ["@operator"] = plt.spikesSilver,

      ["@exception"] = plt.crimsonRageBright,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.bladeSteelBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.armorSilverCore,
      ["@type.builtin"] = plt.armorSilverCore,
      ["@type.definition"] = plt.armorSilverCore,
      ["@type.qualifier"] = plt.bladeSteelCore,

      ["@attribute"] = plt.crimsonRage,
      ["@attribute.builtin"] = plt.crimsonRage,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.armorSilverCore,
      ["@module.builtin"] = plt.armorSilverCore,

      ["@namespace"] = plt.armorSilverCore,
      ["@namespace.builtin"] = plt.armorSilverCore,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.vengeanceViolet,

      ["@tag"] = plt.bladeSteelCore,
      ["@tag.attribute"] = plt.crimsonRage,
      ["@tag.delimiter"] = plt.spikesSilver,
      ["@tag.builtin"] = plt.bladeSteelCore,

      ["@markup.strong"] = { fg = plt.armorSilverBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.shuriken, strikethrough = true },
      ["@markup.underline"] = { fg = plt.vengeanceViolet, underline = true },
      ["@markup.heading"] = plt.armorSilverBright,
      ["@markup.heading.1"] = plt.armorSilverBright,
      ["@markup.heading.2"] = plt.crimsonRage,
      ["@markup.heading.3"] = plt.shadowPurple,
      ["@markup.heading.4"] = plt.footClanRed,
      ["@markup.heading.5"] = plt.vengeanceViolet,
      ["@markup.heading.6"] = plt.darkPower,
      ["@markup.quote"] = plt.shuriken,
      ["@markup.math"] = plt.crimsonRageCore,
      ["@markup.link"] = plt.shadowPurple,
      ["@markup.link.label"] = plt.shadowPurpleBright,
      ["@markup.link.url"] = plt.shadowPurple,
      ["@markup.raw"] = plt.evilGreen,
      ["@markup.raw.block"] = plt.evilGreen,
      ["@markup.list"] = plt.bladeSteelCore,
      ["@markup.list.checked"] = plt.evilGreen,
      ["@markup.list.unchecked"] = plt.shuriken,

      ["@diff.plus"] = plt.evilGreen,
      ["@diff.minus"] = plt.crimsonRage,
      ["@diff.delta"] = plt.footClanRed,

      ["@none"] = "none",
      ["@conceal"] = plt.helmetDarkDeep,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.armorSilverCore,
      ["@constructor.javascript"] = plt.armorSilverCore,
      ["@constructor.typescript"] = plt.armorSilverCore,
      ["@namespace.rust"] = plt.armorSilverCore,
      ["@type.qualifier.rust"] = plt.bladeSteelCore,
      ["@constant.macro.c"] = plt.crimsonRage,
      ["@constant.macro.cpp"] = plt.crimsonRage,
      ["@namespace.go"] = plt.armorSilverCore,
      ["@property.css"] = plt.shadowPurpleBright,
      ["@type.css"] = plt.bladeSteelCore,
      ["@label.json"] = plt.crimsonRage,
      ["@field.yaml"] = plt.shadowPurpleBright,
      ["@property.toml"] = plt.shadowPurpleBright,
      ["@function.builtin.bash"] = plt.shadowPurple,
      ["@string.regexp"] = plt.darkPowerCore,
      ["@character.special.regex"] = plt.crimsonRage,
    },

    lsp = {
      ["@lsp.type.class"] = plt.armorSilverCore,
      ["@lsp.type.interface"] = plt.armorSilverCore,
      ["@lsp.type.struct"] = plt.armorSilverCore,
      ["@lsp.type.enum"] = plt.armorSilverCore,
      ["@lsp.type.enumMember"] = plt.armorSilver,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.armorSilverCore,

      ["@lsp.type.macro"] = plt.crimsonRage,
      ["@lsp.type.decorator"] = plt.crimsonRage,

      ["@lsp.type.builtinType"] = plt.armorSilverCore,
      ["@lsp.type.selfParameter"] = plt.bladeSteelBright,
      ["@lsp.type.typeParameter"] = plt.armorSilverCore,

      ["@lsp.type.array"] = plt.armorSilverCore,
      ["@lsp.type.object"] = plt.armorSilverCore,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.armorSilver,
      ["@lsp.type.enumConstant"] = plt.armorSilver,

      ["@lsp.type.event"] = plt.armorSilverCore,
      ["@lsp.type.regexp"] = plt.darkPowerCore,
      ["@lsp.type.unresolvedReference"] = plt.armorSilverCore,

      ["@lsp.mod.deprecated"] = { fg = plt.helmetDark, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.armorSilver,
      ["@lsp.mod.async"] = plt.bladeSteelCore,
      ["@lsp.mod.static"] = plt.bladeSteelBright,
      ["@lsp.mod.abstract"] = plt.armorSilverCore,
      ["@lsp.mod.defaultLibrary"] = plt.armorSilverCore,
      ["@lsp.mod.documentation"] = plt.shurikenSharp,
    },
  }
end

return {
  name = "TMNT – Shredder",
  author = "PrismPunk.nvim",
  description = "Master of evil — bladed armor, crimson rage, Foot Clan leader.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.shuriken,
    base04 = palette.spikesSilver,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.crimsonRage,
    base09 = palette.footClanRed,
    base0A = palette.warningAmber,
    base0B = palette.evilGreen,
    base0C = palette.shadowPurple,
    base0D = palette.bladeSteelCore,
    base0E = palette.vengeanceViolet,
    base0F = palette.helmetDark,
  },

  palette = palette,
  get = M.get,
}
