local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.aquapunk")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.deepOceanCore,
      insert = plt.aquamarineGreenCore,
      visual = plt.biolumBlueCore,
      replace = plt.anemoneRedCore,
      command = plt.jellyfishPurpleCore,
    },
    accent = {
      accent1 = plt.deepOceanCore,
      accent2 = plt.biolumBlueCore,
      accent3 = plt.aquamarineGreenCore,
      accent4 = plt.coralPinkCore,
      accent5 = plt.jellyfishPurpleCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.biolumBlueBright,
      rainbow2 = plt.aquamarineGreenBright,
      rainbow3 = plt.coralPinkBright,
      rainbow4 = plt.jellyfishPurpleBright,
      rainbow5 = plt.seafoamGreenBright,
      rainbow6 = plt.anglerYellowBright,
      rainbow7 = plt.deepOceanBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.currentGray,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.deepOceanCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lightest,
      selection = plt.bg_mid,
      win_separator = plt.currentGray,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.currentGray,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.currentGrayLight,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.anglerYellowCore,
      boolean = plt.biolumBlueCore,
      comment = plt.currentGray,
      constant = plt.pressureWhiteCore,
      deprecated = plt.depthBlack,
      func = plt.aquamarineGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.deepOceanCore,
      method = plt.aquamarineGreenBright,
      number = plt.pressureWhiteCore,
      operator = plt.coralPinkCore,
      parameter = plt.fg_mid,
      preproc = plt.jellyfishPurpleCore,
      punct = plt.fg_dark,
      regex = plt.trenchVioletCore,
      special = plt.jellyfishPurpleCore,
      statement = plt.deepOceanCore,
      string = plt.aquamarineGreenCore,
      symbol = plt.anglerYellowCore,
      type = plt.biolumBlueCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.jellyfishPurpleCore,
    },
    diff = {
      add = plt.seaweedGreenCore,
      change = plt.anglerYellowCore,
      delete = plt.anemoneRedCore,
      text = plt.jellyfishPurpleCore,
    },
    vcs = {
      added = plt.seaweedGreenCore,
      changed = plt.anglerYellowCore,
      removed = plt.anemoneRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.anemoneRedCore,
      green = plt.aquamarineGreenCore,
      yellow = plt.anglerYellowCore,
      blue = plt.deepOceanCore,
      magenta = plt.jellyfishPurpleCore,
      cyan = plt.biolumBlueCore,
      white = plt.pressureWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.anemoneRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.aquamarineGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.anglerYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.deepOceanBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.jellyfishPurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.biolumBlueBright):brighten(0.15):to_hex(),
      white_bright = plt.pressureWhiteBright,
    },
  }
end

return {
  name = "Punk – Aquapunk",
  author = "PrismPunk.nvim",
  description = "Underwater world — deep ocean, bioluminescent blue, coral pink, aquamarine depths.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.currentGray,
    base04 = palette.currentGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.anemoneRedCore,
    base09 = palette.anglerYellowCore,
    base0A = palette.coralPinkCore,
    base0B = palette.aquamarineGreenCore,
    base0C = palette.biolumBlueCore,
    base0D = palette.deepOceanCore,
    base0E = palette.jellyfishPurpleCore,
    base0F = palette.trenchVioletCore,
  },
  palette = palette,
  get = M.get,
}
