local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.atompunk")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.chromeBlueCore,
      insert = plt.reactorGreenCore,
      visual = plt.atomicOrangeCore,
      replace = plt.raygunRedCore,
      command = plt.turbineYellowCore,
    },
    accent = {
      accent1 = plt.chromeBlueCore,
      accent2 = plt.atomicOrangeCore,
      accent3 = plt.reactorGreenCore,
      accent4 = plt.turbineYellowCore,
      accent5 = plt.jetAgeBlueCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.atomicOrangeBright,
      rainbow2 = plt.chromeBlueBright,
      rainbow3 = plt.reactorGreenBright,
      rainbow4 = plt.turbineYellowBright,
      rainbow5 = plt.jetAgeBlueBright,
      rainbow6 = plt.nucleusVioletBright,
      rainbow7 = plt.radiumGlowBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.steelGray,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.chromeBlueCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lightest,
      selection = plt.bg_mid,
      win_separator = plt.steelGray,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.steelGray,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.steelGrayLight,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.turbineYellowCore,
      boolean = plt.jetAgeBlueCore,
      comment = plt.falloutGray,
      constant = plt.spaceWhiteCore,
      deprecated = plt.retroGray,
      func = plt.reactorGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.chromeBlueCore,
      method = plt.reactorGreenBright,
      number = plt.spaceWhiteCore,
      operator = plt.atomicOrangeCore,
      parameter = plt.fg_mid,
      preproc = plt.nucleusVioletCore,
      punct = plt.fg_dark,
      regex = plt.geigerCore,
      special = plt.jetAgeBlueCore,
      statement = plt.chromeBlueCore,
      string = plt.reactorGreenCore,
      symbol = plt.turbineYellowCore,
      type = plt.rocketSilverCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.jetAgeBlueCore,
    },
    diff = {
      add = plt.reactorGreenCore,
      change = plt.turbineYellowCore,
      delete = plt.raygunRedCore,
      text = plt.jetAgeBlueCore,
    },
    vcs = {
      added = plt.reactorGreenCore,
      changed = plt.turbineYellowCore,
      removed = plt.raygunRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.raygunRedCore,
      green = plt.reactorGreenCore,
      yellow = plt.turbineYellowCore,
      blue = plt.chromeBlueCore,
      magenta = plt.nucleusVioletCore,
      cyan = plt.jetAgeBlueCore,
      white = plt.spaceWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.raygunRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.reactorGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.turbineYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.chromeBlueBright):brighten(0.15):to_hex(),
      magenta_bright = color(plt.nucleusVioletBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.jetAgeBlueBright):brighten(0.15):to_hex(),
      white_bright = plt.spaceWhiteBright,
    },
  }
end

return {
  name = "Punk – Atompunk",
  author = "PrismPunk.nvim",
  description = "1950s retro-futurism — atomic orange, chrome blue, reactor green, jet age optimism.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.falloutGray,
    base04 = palette.steelGray,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.raygunRedCore,
    base09 = palette.atomicOrangeCore,
    base0A = palette.turbineYellowCore,
    base0B = palette.reactorGreenCore,
    base0C = palette.jetAgeBlueCore,
    base0D = palette.chromeBlueCore,
    base0E = palette.nucleusVioletCore,
    base0F = palette.rocketSilverCore,
  },
  palette = palette,
  get = M.get,
}
