local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.biopunk")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.dnaGreenCore,
      insert = plt.cellCyanCore,
      visual = plt.mutationPinkCore,
      replace = plt.tissueRedCore,
      command = plt.enzymeBlueCore,
    },
    accent = {
      accent1 = plt.dnaGreenCore,
      accent2 = plt.mutationPinkCore,
      accent3 = plt.cellCyanCore,
      accent4 = plt.organVioletCore,
      accent5 = plt.petriYellowCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.dnaGreenBright,
      rainbow2 = plt.mutationPinkBright,
      rainbow3 = plt.cellCyanBright,
      rainbow4 = plt.petriYellowBright,
      rainbow5 = plt.enzymeBlueBright,
      rainbow6 = plt.organVioletBright,
      rainbow7 = plt.biohazardOrangeBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.labGray,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.dnaGreenCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lightest,
      selection = plt.bg_mid,
      win_separator = plt.labGray,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.labGray,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.labGrayLight,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.synapseGoldCore,
      boolean = plt.cellCyanCore,
      comment = plt.labGray,
      constant = plt.specimenWhiteCore,
      deprecated = plt.labGrayDark,
      func = plt.cellCyanCore,
      identifier = plt.fg_lightest,
      keyword = plt.dnaGreenCore,
      method = plt.cellCyanBright,
      number = plt.specimenWhiteCore,
      operator = plt.mutationPinkCore,
      parameter = plt.fg_mid,
      preproc = plt.organVioletCore,
      punct = plt.fg_dark,
      regex = plt.enzymeBlueCore,
      special = plt.organVioletCore,
      statement = plt.dnaGreenCore,
      string = plt.cellCyanCore,
      symbol = plt.synapseGoldCore,
      type = plt.cultureMediumCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.organVioletCore,
    },
    diff = {
      add = plt.dnaGreenCore,
      change = plt.synapseGoldCore,
      delete = plt.contaminationRedCore,
      text = plt.organVioletCore,
    },
    vcs = {
      added = plt.dnaGreenCore,
      changed = plt.synapseGoldCore,
      removed = plt.contaminationRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.tissueRedCore,
      green = plt.dnaGreenCore,
      yellow = plt.petriYellowCore,
      blue = plt.enzymeBlueCore,
      magenta = plt.mutationPinkCore,
      cyan = plt.cellCyanCore,
      white = plt.specimenWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.tissueRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.dnaGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.petriYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.enzymeBlueBright):brighten(0.15):to_hex(),
      magenta_bright = color(plt.mutationPinkBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.cellCyanBright):brighten(0.15):to_hex(),
      white_bright = plt.specimenWhiteBright,
    },
  }
end

return {
  name = "Punk – Biopunk",
  author = "PrismPunk.nvim",
  description = "Genetic manipulation — DNA green, mutation pink, cell cyan, organic laboratory.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.labGray,
    base04 = palette.labGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.tissueRedCore,
    base09 = palette.biohazardOrangeCore,
    base0A = palette.petriYellowCore,
    base0B = palette.dnaGreenCore,
    base0C = palette.cellCyanCore,
    base0D = palette.enzymeBlueCore,
    base0E = palette.mutationPinkCore,
    base0F = palette.organVioletCore,
  },
  palette = palette,
  get = M.get,
}
