local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.clockpunk")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.silverGearCore,
      insert = plt.emeraldJewelCore,
      visual = plt.sapphireJewelCore,
      replace = plt.rubyJewelCore,
      command = plt.celestialBlueCore,
    },
    accent = {
      accent1 = plt.silverGearCore,
      accent2 = plt.sapphireJewelCore,
      accent3 = plt.emeraldJewelCore,
      accent4 = plt.whiteGoldCore,
      accent5 = plt.celestialBlueCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.moonsilverBright,
      rainbow2 = plt.whiteGoldBright,
      rainbow3 = plt.sapphireJewelBright,
      rainbow4 = plt.emeraldJewelBright,
      rainbow5 = plt.rubyJewelBright,
      rainbow6 = plt.celestialBlueBright,
      rainbow7 = plt.platinumWhiteBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.mechanismGray,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.silverGearCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lightest,
      selection = plt.bg_mid,
      win_separator = plt.mechanismGray,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.mechanismGray,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.mechanismGrayLight,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.whiteGoldCore,
      boolean = plt.sapphireJewelCore,
      comment = plt.mechanismGray,
      constant = plt.platinumWhiteCore,
      deprecated = plt.shadowBlack,
      func = plt.emeraldJewelCore,
      identifier = plt.fg_lightest,
      keyword = plt.silverGearCore,
      method = plt.emeraldJewelBright,
      number = plt.platinumWhiteCore,
      operator = plt.moonsilverCore,
      parameter = plt.fg_mid,
      preproc = plt.celestialBlueCore,
      punct = plt.fg_dark,
      regex = plt.sapphireJewelCore,
      special = plt.sapphireJewelCore,
      statement = plt.silverGearCore,
      string = plt.emeraldJewelCore,
      symbol = plt.whiteGoldCore,
      type = plt.tickSilverCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.sapphireJewelCore,
    },
    diff = {
      add = plt.emeraldJewelCore,
      change = plt.tockGoldCore,
      delete = plt.rubyJewelCore,
      text = plt.sapphireJewelCore,
    },
    vcs = {
      added = plt.emeraldJewelCore,
      changed = plt.tockGoldCore,
      removed = plt.rubyJewelCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.rubyJewelCore,
      green = plt.emeraldJewelCore,
      yellow = plt.tockGoldCore,
      blue = plt.celestialBlueCore,
      magenta = plt.tickSilverCore,
      cyan = plt.moonsilverCore,
      white = plt.platinumWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.rubyJewelBright):brighten(0.15):to_hex(),
      green_bright = color(plt.emeraldJewelBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.tockGoldBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.celestialBlueBright):brighten(0.15):to_hex(),
      magenta_bright = color(plt.tickSilverBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.moonsilverBright):brighten(0.15):to_hex(),
      white_bright = plt.starlightBright,
    },
  }
end

return {
  name = "Punk – Clockpunk",
  author = "PrismPunk.nvim",
  description = "Renaissance precision — silver gears, jeweled mechanisms, astronomical elegance, celestial time.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.mechanismGray,
    base04 = palette.mechanismGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.rubyJewelCore,
    base09 = palette.tockGoldCore,
    base0A = palette.whiteGoldCore,
    base0B = palette.emeraldJewelCore,
    base0C = palette.moonsilverCore,
    base0D = palette.celestialBlueCore,
    base0E = palette.sapphireJewelCore,
    base0F = palette.silverGearCore,
  },
  palette = palette,
  get = M.get,
}
