local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.cryopunk")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.glacierBlueCore,
      insert = plt.frostCyanCore,
      visual = plt.crystalBlueCore,
      replace = plt.frostbiteRedCore,
      command = plt.arcticWhiteCore,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.iceBlueCore,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.currentGray,
      header1 = plt.glacierBlueBright,
      header2 = plt.frostCyanBright,
      special = plt.frozenPurple,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.currentGray,
      indent = plt.bg_lighter,
      indent_scope = plt.glacierBlueCore,
      picker = plt.iceBlue,
      yank = plt.arcticWhiteBright,
      mark = plt.crystalBlue,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.glacierBlueBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.glacierBlueCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.currentGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.currentGrayLight,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.currentGray,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.glacierBlueCore,
      accent2 = plt.crystalBlueCore,
      accent3 = plt.frostCyanCore,
      accent4 = plt.arcticWhiteCore,
      accent5 = plt.frozenPurpleCore,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.glacierBlueBright,
      rainbow2 = plt.frostCyanBright,
      rainbow3 = plt.crystalBlueBright,
      rainbow4 = plt.arcticWhiteBright,
      rainbow5 = plt.frozenPurpleBright,
      rainbow6 = plt.iceBlueBright,
      rainbow7 = plt.tundraTealBright,
    },

    syn = {
      attribute = plt.iceBlue,
      boolean = plt.crystalBlue,
      comment = plt.permafrostGray,
      constant = plt.blizzardWhite,
      deprecated = plt.voidBlack,
      func = plt.frostCyanCore,
      identifier = plt.fg_lightest,
      keyword = plt.glacierBlueCore,
      method = plt.frostCyanBright,
      number = plt.blizzardWhite,
      operator = plt.arcticWhiteCore,
      parameter = plt.fg_mid,
      preproc = plt.frozenPurpleCore,
      punct = plt.fg_dark,
      regex = plt.icicleViolet,
      statement = plt.glacierBlueCore,
      string = plt.frostCyanCore,
      symbol = plt.iceBlue,
      type = plt.crystalBlueCore,
      variable = plt.fg_lightest,
      special = plt.frozenPurple,
      special2 = plt.tundraTeal,
      special3 = plt.subzeroCyan,
    },

    vcs = {
      added = plt.tundraTealCore,
      removed = plt.frostbiteRedCore,
      changed = plt.iceBlueBright,
    },

    diff = {
      add = plt.tundraTealCore,
      change = plt.iceBlueBright,
      delete = plt.frostbiteRedCore,
      text = plt.frozenPurple,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.frozenPurple,
    },

    term = {
      black = plt.bg_darkest,
      red = plt.frostbiteRedCore,
      green = plt.tundraTealCore,
      yellow = plt.iceBlueCore,
      blue = plt.crystalBlueCore,
      magenta = plt.frozenPurpleCore,
      cyan = plt.frostCyanCore,
      white = plt.blizzardWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.frostbiteRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.tundraTealBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.iceBlueBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.crystalBlueBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.frozenPurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.frostCyanBright):brighten(0.15):to_hex(),
      white_bright = plt.blizzardWhiteBright,
      indexed1 = plt.glacierBlue,
      indexed2 = plt.iceBlue,
    },

    treesitter = {
      ["@comment"] = plt.permafrostGray,
      ["@comment.documentation"] = plt.permafrostGrayLight,
      ["@comment.error"] = plt.errorRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.iceBlueBright,
      ["@comment.note"] = plt.frozenPurple,

      ["@constant"] = plt.blizzardWhite,
      ["@constant.builtin"] = plt.blizzardWhiteCore,
      ["@constant.macro"] = plt.iceBlue,

      ["@string"] = plt.frostCyanCore,
      ["@string.documentation"] = plt.frostCyanCore,
      ["@string.regex"] = plt.icicleViolet,
      ["@string.escape"] = plt.arcticWhiteBright,
      ["@string.special"] = plt.frostCyanBright,
      ["@string.special.symbol"] = plt.iceBlue,
      ["@string.special.url"] = plt.crystalBlue,
      ["@string.special.path"] = plt.frostCyanCore,

      ["@character"] = plt.frostCyanCore,
      ["@character.special"] = plt.iceBlue,

      ["@number"] = plt.blizzardWhite,
      ["@number.float"] = plt.blizzardWhiteCore,

      ["@boolean"] = plt.crystalBlue,

      ["@function"] = plt.frostCyanCore,
      ["@function.builtin"] = plt.frostCyanCore,
      ["@function.call"] = plt.frostCyanCore,
      ["@function.macro"] = plt.frozenPurpleCore,
      ["@function.method"] = plt.frostCyanBright,
      ["@function.method.call"] = plt.frostCyanBright,

      ["@constructor"] = plt.crystalBlueCore,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.glacierBlueCore,
      ["@keyword.coroutine"] = plt.frozenPurpleCore,
      ["@keyword.function"] = plt.glacierBlueCore,
      ["@keyword.operator"] = plt.arcticWhiteCore,
      ["@keyword.return"] = plt.glacierBlueCore,
      ["@keyword.import"] = plt.frozenPurpleCore,
      ["@keyword.storage"] = plt.glacierBlueCore,
      ["@keyword.repeat"] = plt.glacierBlueCore,
      ["@keyword.conditional"] = plt.glacierBlueCore,
      ["@keyword.exception"] = plt.frostbiteRedCore,
      ["@keyword.directive"] = plt.frozenPurpleCore,
      ["@keyword.directive.define"] = plt.frozenPurpleCore,

      ["@conditional"] = plt.glacierBlueCore,
      ["@conditional.ternary"] = plt.glacierBlueCore,

      ["@repeat"] = plt.glacierBlueCore,

      ["@label"] = plt.iceBlue,

      ["@operator"] = plt.arcticWhiteCore,

      ["@exception"] = plt.frostbiteRedCore,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.glacierBlueBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.crystalBlueCore,
      ["@type.builtin"] = plt.crystalBlueCore,
      ["@type.definition"] = plt.crystalBlueCore,
      ["@type.qualifier"] = plt.glacierBlueCore,

      ["@attribute"] = plt.iceBlue,
      ["@attribute.builtin"] = plt.iceBlue,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.crystalBlueCore,
      ["@module.builtin"] = plt.crystalBlueCore,

      ["@namespace"] = plt.crystalBlueCore,
      ["@namespace.builtin"] = plt.crystalBlueCore,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.arcticWhiteCore,

      ["@tag"] = plt.glacierBlueCore,
      ["@tag.attribute"] = plt.iceBlue,
      ["@tag.delimiter"] = plt.arcticWhiteCore,
      ["@tag.builtin"] = plt.glacierBlueCore,

      ["@markup.strong"] = { fg = plt.glacierBlueBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.permafrostGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.frozenPurple, underline = true },
      ["@markup.heading"] = plt.glacierBlueBright,
      ["@markup.heading.1"] = plt.glacierBlueBright,
      ["@markup.heading.2"] = plt.frostCyanBright,
      ["@markup.heading.3"] = plt.crystalBlueBright,
      ["@markup.heading.4"] = plt.arcticWhiteBright,
      ["@markup.heading.5"] = plt.frozenPurpleBright,
      ["@markup.heading.6"] = plt.iceBlueBright,
      ["@markup.quote"] = plt.permafrostGray,
      ["@markup.math"] = plt.blizzardWhite,
      ["@markup.link"] = plt.crystalBlue,
      ["@markup.link.label"] = plt.crystalBlueBright,
      ["@markup.link.url"] = plt.crystalBlue,
      ["@markup.raw"] = plt.frostCyanCore,
      ["@markup.raw.block"] = plt.frostCyanCore,
      ["@markup.list"] = plt.glacierBlueCore,
      ["@markup.list.checked"] = plt.tundraTealCore,
      ["@markup.list.unchecked"] = plt.permafrostGray,

      ["@diff.plus"] = plt.tundraTealCore,
      ["@diff.minus"] = plt.frostbiteRedCore,
      ["@diff.delta"] = plt.iceBlueBright,

      ["@none"] = "none",
      ["@conceal"] = plt.bg_lightest,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.crystalBlueCore,
      ["@constructor.javascript"] = plt.crystalBlueCore,
      ["@constructor.typescript"] = plt.crystalBlueCore,
      ["@namespace.rust"] = plt.crystalBlueCore,
      ["@type.qualifier.rust"] = plt.glacierBlueCore,
      ["@constant.macro.c"] = plt.iceBlue,
      ["@constant.macro.cpp"] = plt.iceBlue,
      ["@namespace.go"] = plt.crystalBlueCore,
      ["@property.css"] = plt.frostCyanBright,
      ["@type.css"] = plt.glacierBlueCore,
      ["@label.json"] = plt.iceBlue,
      ["@field.yaml"] = plt.frostCyanBright,
      ["@property.toml"] = plt.frostCyanBright,
      ["@function.builtin.bash"] = plt.frostCyanCore,
      ["@string.regexp"] = plt.icicleViolet,
      ["@character.special.regex"] = plt.iceBlue,
    },

    lsp = {
      ["@lsp.type.class"] = plt.crystalBlueCore,
      ["@lsp.type.interface"] = plt.crystalBlueCore,
      ["@lsp.type.struct"] = plt.crystalBlueCore,
      ["@lsp.type.enum"] = plt.crystalBlueCore,
      ["@lsp.type.enumMember"] = plt.blizzardWhiteCore,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.crystalBlueCore,

      ["@lsp.type.macro"] = plt.iceBlue,
      ["@lsp.type.decorator"] = plt.iceBlue,

      ["@lsp.type.builtinType"] = plt.crystalBlueCore,
      ["@lsp.type.selfParameter"] = plt.glacierBlueBright,
      ["@lsp.type.typeParameter"] = plt.crystalBlueCore,

      ["@lsp.type.array"] = plt.crystalBlueCore,
      ["@lsp.type.object"] = plt.crystalBlueCore,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.blizzardWhiteCore,
      ["@lsp.type.enumConstant"] = plt.blizzardWhiteCore,

      ["@lsp.type.event"] = plt.crystalBlueCore,
      ["@lsp.type.regexp"] = plt.icicleViolet,
      ["@lsp.type.unresolvedReference"] = plt.crystalBlueCore,

      ["@lsp.mod.deprecated"] = { fg = plt.voidBlack, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.blizzardWhiteCore,
      ["@lsp.mod.async"] = plt.glacierBlueCore,
      ["@lsp.mod.static"] = plt.glacierBlueBright,
      ["@lsp.mod.abstract"] = plt.crystalBlueCore,
      ["@lsp.mod.defaultLibrary"] = plt.crystalBlueCore,
      ["@lsp.mod.documentation"] = plt.permafrostGrayLight,
    },
  }
end

return {
  name = "Punk – Cryopunk",
  author = "PrismPunk.nvim",
  description = "Frozen wasteland — glacier blue, frost cyan, crystal ice, arctic white, subzero cold.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.permafrostGray,
    base04 = palette.permafrostGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.frostbiteRedCore,
    base09 = palette.iceBlueCore,
    base0A = palette.arcticWhiteCore,
    base0B = palette.frostCyanCore,
    base0C = palette.tundraTealCore,
    base0D = palette.glacierBlueCore,
    base0E = palette.frozenPurpleCore,
    base0F = palette.icicleVioletCore,
  },

  palette = palette,
  get = M.get,
}
