local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.junglepunk")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.jungleGreenCore,
      insert = plt.vineGreenCore,
      visual = plt.canopyTealCore,
      replace = plt.hibiscusRedCore,
      command = plt.sunbeamYellowCore,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.sunbeamYellowDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.currentGray,
      header1 = plt.jungleGreenBright,
      header2 = plt.vineGreenBright,
      special = plt.orchidPurple,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.currentGray,
      indent = plt.bg_lighter,
      indent_scope = plt.jungleGreenCore,
      picker = plt.tropicalOrange,
      yank = plt.sunbeamYellowBright,
      mark = plt.canopyTeal,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.jungleGreenBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.jungleGreenCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.currentGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.currentGrayLight,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.currentGray,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.jungleGreenCore,
      accent2 = plt.canopyTealCore,
      accent3 = plt.vineGreenCore,
      accent4 = plt.tropicalOrangeCore,
      accent5 = plt.orchidPurpleCore,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.jungleGreenBright,
      rainbow2 = plt.vineGreenBright,
      rainbow3 = plt.canopyTealBright,
      rainbow4 = plt.tropicalOrangeBright,
      rainbow5 = plt.orchidPurpleBright,
      rainbow6 = plt.sunbeamYellowBright,
      rainbow7 = plt.fernGreenBright,
    },

    syn = {
      attribute = plt.tropicalOrange,
      boolean = plt.canopyTeal,
      comment = plt.mossGreen,
      constant = plt.bambooBeige,
      deprecated = plt.overgrownBlack,
      func = plt.vineGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.jungleGreenCore,
      method = plt.vineGreenBright,
      number = plt.bambooBeige,
      operator = plt.sunbeamYellowCore,
      parameter = plt.fg_mid,
      preproc = plt.orchidPurpleCore,
      punct = plt.fg_dark,
      regex = plt.wildflowerViolet,
      statement = plt.jungleGreenCore,
      string = plt.vineGreenCore,
      symbol = plt.tropicalOrange,
      type = plt.canopyTealCore,
      variable = plt.fg_lightest,
      special = plt.orchidPurple,
      special2 = plt.tropicalOrange,
      special3 = plt.fernGreen,
    },

    vcs = {
      added = plt.undergrowthGreenCore,
      removed = plt.hibiscusRedCore,
      changed = plt.sunbeamYellowCore,
    },

    diff = {
      add = plt.undergrowthGreenCore,
      change = plt.sunbeamYellowCore,
      delete = plt.hibiscusRedCore,
      text = plt.orchidPurple,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.orchidPurple,
    },

    term = {
      black = plt.bg_darkest,
      red = plt.hibiscusRedCore,
      green = plt.jungleGreenCore,
      yellow = plt.sunbeamYellowCore,
      blue = plt.canopyTealCore,
      magenta = plt.orchidPurpleCore,
      cyan = plt.vineGreenCore,
      white = plt.bambooBeigeCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.hibiscusRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.jungleGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.sunbeamYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.canopyTealBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.orchidPurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.vineGreenBright):brighten(0.15):to_hex(),
      white_bright = plt.bambooBeigeBright,
      indexed1 = plt.jungleGreen,
      indexed2 = plt.tropicalOrange,
    },

    treesitter = {
      ["@comment"] = plt.mossGreen,
      ["@comment.documentation"] = plt.mossGreenLight,
      ["@comment.error"] = plt.errorRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.sunbeamYellowBright,
      ["@comment.note"] = plt.orchidPurple,

      ["@constant"] = plt.bambooBeige,
      ["@constant.builtin"] = plt.bambooBeigeCore,
      ["@constant.macro"] = plt.tropicalOrange,

      ["@string"] = plt.vineGreenCore,
      ["@string.documentation"] = plt.vineGreenCore,
      ["@string.regex"] = plt.wildflowerViolet,
      ["@string.escape"] = plt.sunbeamYellowBright,
      ["@string.special"] = plt.vineGreenBright,
      ["@string.special.symbol"] = plt.tropicalOrange,
      ["@string.special.url"] = plt.canopyTeal,
      ["@string.special.path"] = plt.vineGreenCore,

      ["@character"] = plt.vineGreenCore,
      ["@character.special"] = plt.tropicalOrange,

      ["@number"] = plt.bambooBeige,
      ["@number.float"] = plt.bambooBeigeCore,

      ["@boolean"] = plt.canopyTeal,

      ["@function"] = plt.vineGreenCore,
      ["@function.builtin"] = plt.vineGreenCore,
      ["@function.call"] = plt.vineGreenCore,
      ["@function.macro"] = plt.orchidPurpleCore,
      ["@function.method"] = plt.vineGreenBright,
      ["@function.method.call"] = plt.vineGreenBright,

      ["@constructor"] = plt.canopyTealCore,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.jungleGreenCore,
      ["@keyword.coroutine"] = plt.orchidPurpleCore,
      ["@keyword.function"] = plt.jungleGreenCore,
      ["@keyword.operator"] = plt.sunbeamYellowCore,
      ["@keyword.return"] = plt.jungleGreenCore,
      ["@keyword.import"] = plt.orchidPurpleCore,
      ["@keyword.storage"] = plt.jungleGreenCore,
      ["@keyword.repeat"] = plt.jungleGreenCore,
      ["@keyword.conditional"] = plt.jungleGreenCore,
      ["@keyword.exception"] = plt.hibiscusRedCore,
      ["@keyword.directive"] = plt.orchidPurpleCore,
      ["@keyword.directive.define"] = plt.orchidPurpleCore,

      ["@conditional"] = plt.jungleGreenCore,
      ["@conditional.ternary"] = plt.jungleGreenCore,

      ["@repeat"] = plt.jungleGreenCore,

      ["@label"] = plt.tropicalOrange,

      ["@operator"] = plt.sunbeamYellowCore,

      ["@exception"] = plt.hibiscusRedCore,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.jungleGreenBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.canopyTealCore,
      ["@type.builtin"] = plt.canopyTealCore,
      ["@type.definition"] = plt.canopyTealCore,
      ["@type.qualifier"] = plt.jungleGreenCore,

      ["@attribute"] = plt.tropicalOrange,
      ["@attribute.builtin"] = plt.tropicalOrange,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.canopyTealCore,
      ["@module.builtin"] = plt.canopyTealCore,

      ["@namespace"] = plt.canopyTealCore,
      ["@namespace.builtin"] = plt.canopyTealCore,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.sunbeamYellowCore,

      ["@tag"] = plt.jungleGreenCore,
      ["@tag.attribute"] = plt.tropicalOrange,
      ["@tag.delimiter"] = plt.sunbeamYellowCore,
      ["@tag.builtin"] = plt.jungleGreenCore,

      ["@markup.strong"] = { fg = plt.jungleGreenBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.mossGreen, strikethrough = true },
      ["@markup.underline"] = { fg = plt.orchidPurple, underline = true },
      ["@markup.heading"] = plt.jungleGreenBright,
      ["@markup.heading.1"] = plt.jungleGreenBright,
      ["@markup.heading.2"] = plt.vineGreenBright,
      ["@markup.heading.3"] = plt.canopyTealBright,
      ["@markup.heading.4"] = plt.tropicalOrangeBright,
      ["@markup.heading.5"] = plt.orchidPurpleBright,
      ["@markup.heading.6"] = plt.sunbeamYellowBright,
      ["@markup.quote"] = plt.mossGreen,
      ["@markup.math"] = plt.bambooBeige,
      ["@markup.link"] = plt.canopyTeal,
      ["@markup.link.label"] = plt.canopyTealBright,
      ["@markup.link.url"] = plt.canopyTeal,
      ["@markup.raw"] = plt.vineGreenCore,
      ["@markup.raw.block"] = plt.vineGreenCore,
      ["@markup.list"] = plt.jungleGreenCore,
      ["@markup.list.checked"] = plt.undergrowthGreenCore,
      ["@markup.list.unchecked"] = plt.mossGreen,

      ["@diff.plus"] = plt.undergrowthGreenCore,
      ["@diff.minus"] = plt.hibiscusRedCore,
      ["@diff.delta"] = plt.sunbeamYellowCore,

      ["@none"] = "none",
      ["@conceal"] = plt.bg_lightest,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.canopyTealCore,
      ["@constructor.javascript"] = plt.canopyTealCore,
      ["@constructor.typescript"] = plt.canopyTealCore,
      ["@namespace.rust"] = plt.canopyTealCore,
      ["@type.qualifier.rust"] = plt.jungleGreenCore,
      ["@constant.macro.c"] = plt.tropicalOrange,
      ["@constant.macro.cpp"] = plt.tropicalOrange,
      ["@namespace.go"] = plt.canopyTealCore,
      ["@property.css"] = plt.vineGreenBright,
      ["@type.css"] = plt.jungleGreenCore,
      ["@label.json"] = plt.tropicalOrange,
      ["@field.yaml"] = plt.vineGreenBright,
      ["@property.toml"] = plt.vineGreenBright,
      ["@function.builtin.bash"] = plt.vineGreenCore,
      ["@string.regexp"] = plt.wildflowerViolet,
      ["@character.special.regex"] = plt.tropicalOrange,
    },

    lsp = {
      ["@lsp.type.class"] = plt.canopyTealCore,
      ["@lsp.type.interface"] = plt.canopyTealCore,
      ["@lsp.type.struct"] = plt.canopyTealCore,
      ["@lsp.type.enum"] = plt.canopyTealCore,
      ["@lsp.type.enumMember"] = plt.bambooBeigeCore,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.canopyTealCore,

      ["@lsp.type.macro"] = plt.tropicalOrange,
      ["@lsp.type.decorator"] = plt.tropicalOrange,

      ["@lsp.type.builtinType"] = plt.canopyTealCore,
      ["@lsp.type.selfParameter"] = plt.jungleGreenBright,
      ["@lsp.type.typeParameter"] = plt.canopyTealCore,

      ["@lsp.type.array"] = plt.canopyTealCore,
      ["@lsp.type.object"] = plt.canopyTealCore,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.bambooBeigeCore,
      ["@lsp.type.enumConstant"] = plt.bambooBeigeCore,

      ["@lsp.type.event"] = plt.canopyTealCore,
      ["@lsp.type.regexp"] = plt.wildflowerViolet,
      ["@lsp.type.unresolvedReference"] = plt.canopyTealCore,

      ["@lsp.mod.deprecated"] = { fg = plt.overgrownBlack, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.bambooBeigeCore,
      ["@lsp.mod.async"] = plt.jungleGreenCore,
      ["@lsp.mod.static"] = plt.jungleGreenBright,
      ["@lsp.mod.abstract"] = plt.canopyTealCore,
      ["@lsp.mod.defaultLibrary"] = plt.canopyTealCore,
      ["@lsp.mod.documentation"] = plt.mossGreenLight,
    },
  }
end

return {
  name = "Punk – Junglepunk",
  author = "PrismPunk.nvim",
  description = "Dense rainforest — jungle green, vine growth, tropical canopy, wild undergrowth.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.mossGreen,
    base04 = palette.mossGreenLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.hibiscusRedCore,
    base09 = palette.tropicalOrangeCore,
    base0A = palette.sunbeamYellowCore,
    base0B = palette.vineGreenCore,
    base0C = palette.canopyTealCore,
    base0D = palette.jungleGreenCore,
    base0E = palette.orchidPurpleCore,
    base0F = palette.wildflowerVioletCore,
  },

  palette = palette,
  get = M.get,
}
