local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.1998term")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.restoreMid,
      insert = plt.restoreBright,
      visual = plt.restorePulse,
      replace = plt.restoreDeep,
      command = plt.silenceBright,
    },

    ui = {
      fg = plt.clarityCore,
      fg_dim = plt.clarityDim,
      fg_dimmer = plt.silenceLighter,
      fg_dark = plt.silenceLight,
      fg_reverse = plt.hushVoid,

      bg_m4 = plt.hushLight,
      bg_m3 = plt.hushMid,
      bg_m2 = plt.hushDeep,
      bg_m1 = plt.hushDark,
      bg_dim = plt.hushVoid,
      bg = plt.hushVoid,
      bg_p1 = plt.hushDeep,
      bg_p2 = plt.hushMid,
      bg_gutter = opts.gutter and plt.hushMid or "none",
      bg_cursorline = plt.calmLine,
      bg_cursorline_alt = plt.calmMid,
      bg_search = plt.restorePulse,
      bg_visual = plt.restoreDeep,
      bg_statusline = plt.calmMid,

      border = plt.silenceMid,
      header1 = plt.restoreBright,
      header2 = plt.restoreMid,
      special = plt.restorePulse,
      nontext = plt.hushLight,
      whitespace = plt.hushMid,
      win_separator = plt.silenceMid,
      indent = plt.hushMid,
      indent_scope = plt.silenceDeep,
      picker = plt.silenceLight,
      yank = plt.restorePulse,
      mark = plt.restoreBright,
      scrollbar = plt.hushLight,

      tabline = {
        bg = plt.hushVoid,
        fg_selected = plt.clarityCore,
        bg_selected = plt.calmMid,
        fg_inactive = plt.silenceLighter,
        bg_inactive = plt.hushVoid,
        fg_alternate = plt.restoreMid,
        bg_alternate = plt.hushVoid,
        indicator = plt.restorePulse,
      },

      pmenu = {
        fg = plt.clarityCore,
        fg_sel = "none",
        fg_border = plt.calmMid,
        bg_border = plt.calmMid,
        bg = plt.calmMid,
        bg_sel = plt.calmDeep,
        bg_sbar = plt.calmMid,
        bg_thumb = plt.silenceMid,
      },

      float = {
        fg = plt.clarityCore,
        bg = plt.hushDeep,
        fg_border = plt.calmMid,
        bg_border = plt.hushDeep,
      },
    },

    accent = {
      accent1 = plt.restoreBright,
      accent2 = plt.restoreMid,
      accent3 = plt.restoreDeep,
      accent4 = plt.silenceBright,
      accent5 = plt.restorePulse,
      invert = plt.calmMid,
    },

    rainbow = {
      rainbow1 = plt.silenceBright,
      rainbow2 = plt.silenceLight,
      rainbow3 = plt.silenceMid,
      rainbow4 = plt.restoreDeep,
      rainbow5 = plt.restoreMid,
      rainbow6 = plt.restoreBright,
      rainbow7 = plt.restorePulse,
    },

    syn = {
      attribute = plt.clarityCore,
      boolean = plt.restoreBright,
      comment = plt.silenceBright,
      constant = plt.silenceLightest,
      deprecated = plt.silenceMid,
      func = plt.clarityBright,
      identifier = plt.clarityCore,
      keyword = plt.clarityCore,
      method = plt.clarityBright,
      number = plt.silenceLightest,
      operator = plt.silenceLight,
      parameter = plt.silenceLighter,
      preproc = plt.restoreDeep,
      punct = plt.silenceMid,
      regex = plt.silenceLight,
      statement = plt.clarityCore,
      string = plt.silenceLighter,
      symbol = plt.clarityCore,
      type = plt.silenceLightest,
      variable = plt.clarityCore,
      special = plt.restorePulse,
      special2 = plt.restoreMid,
      special3 = plt.restoreBright,
    },

    vcs = { added = plt.silenceLighter, removed = plt.restoreBright, changed = plt.restoreDeep },
    diff = { add = plt.silenceLighter, change = plt.silenceLight, delete = plt.restoreBright, text = plt.restoreDeep },
    diag = {
      ok = plt.silenceLighter,
      error = plt.restoreBright,
      warning = plt.restoreMid,
      info = plt.silenceBright,
      hint = plt.silenceMid,
    },

    term = {
      black = plt.hushVoid,
      red = plt.restoreBright,
      green = plt.silenceBright,
      yellow = plt.silenceLightest,
      blue = plt.hushVoid,
      magenta = plt.restoreMid,
      cyan = plt.silenceLight,
      white = plt.clarityCore,

      black_bright = color(plt.hushVoid):brighten(0.4):to_hex(),
      red_bright = plt.restorePulse,
      green_bright = color(plt.silenceBright):brighten(0.3):to_hex(),
      yellow_bright = plt.clarityBright,
      blue_bright = color(plt.hushVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.restoreMid):brighten(0.4):to_hex(),
      cyan_bright = color(plt.silenceLight):brighten(0.3):to_hex(),
      white_bright = plt.clarityBright,
      indexed1 = plt.restoreMid,
      indexed2 = plt.restoreBright,
    },

    treesitter = {
      ["@comment"] = plt.silenceBright,
      ["@comment. documentation"] = plt.silenceLight,
      ["@comment. error"] = plt.restoreBright,
      ["@comment.warning"] = plt.restoreMid,
      ["@comment.todo"] = plt.silenceLighter,
      ["@comment. note"] = plt.silenceLight,

      ["@constant"] = plt.silenceLightest,
      ["@constant. builtin"] = plt.silenceLightest,
      ["@constant.macro"] = plt.restoreDeep,

      ["@string"] = plt.silenceLighter,
      ["@string.documentation"] = plt.silenceLighter,
      ["@string.regex"] = plt.silenceLight,
      ["@string.escape"] = plt.restoreMid,
      ["@string.special"] = plt.restoreBright,
      ["@string.special.symbol"] = plt.restoreBright,
      ["@string.special.url"] = plt.silenceLight,
      ["@string. special.path"] = plt.silenceLighter,

      ["@character"] = plt.silenceLighter,
      ["@character.special"] = plt.restoreMid,

      ["@number"] = plt.silenceLightest,
      ["@number. float"] = plt.silenceLightest,

      ["@boolean"] = plt.restoreBright,

      ["@function"] = plt.clarityBright,
      ["@function.builtin"] = plt.clarityBright,
      ["@function. call"] = plt.clarityBright,
      ["@function.macro"] = plt.restoreDeep,
      ["@function.method"] = plt.clarityBright,
      ["@function.method.call"] = plt.clarityBright,

      ["@constructor"] = plt.clarityCore,

      ["@parameter"] = plt.silenceLighter,
      ["@parameter.builtin"] = plt.silenceLightest,

      ["@keyword"] = plt.clarityCore,
      ["@keyword.coroutine"] = plt.restoreBright,
      ["@keyword.function"] = plt.clarityCore,
      ["@keyword.operator"] = plt.silenceLight,
      ["@keyword. return"] = plt.clarityCore,
      ["@keyword.import"] = plt.silenceLightest,
      ["@keyword. storage"] = plt.clarityCore,
      ["@keyword.repeat"] = plt.clarityCore,
      ["@keyword.conditional"] = plt.clarityCore,
      ["@keyword.exception"] = plt.restoreBright,
      ["@keyword.directive"] = plt.restoreDeep,
      ["@keyword.directive.define"] = plt.restoreDeep,

      ["@conditional"] = plt.clarityCore,
      ["@conditional. ternary"] = plt.clarityCore,

      ["@repeat"] = plt.clarityCore,

      ["@label"] = plt.silenceLightest,

      ["@operator"] = plt.silenceLight,

      ["@exception"] = plt.restoreBright,

      ["@variable"] = plt.clarityCore,
      ["@variable.builtin"] = plt.silenceLightest,
      ["@variable.parameter"] = plt.silenceLighter,
      ["@variable.member"] = plt.clarityCore,

      ["@type"] = plt.silenceLightest,
      ["@type.builtin"] = plt.silenceLightest,
      ["@type.definition"] = plt.silenceLightest,
      ["@type.qualifier"] = plt.clarityCore,

      ["@attribute"] = plt.clarityCore,
      ["@attribute.builtin"] = plt.silenceLightest,

      ["@property"] = plt.clarityCore,
      ["@field"] = plt.clarityCore,

      ["@module"] = plt.clarityCore,
      ["@module.builtin"] = plt.clarityCore,

      ["@namespace"] = plt.clarityCore,
      ["@namespace.builtin"] = plt.clarityCore,

      ["@punctuation. delimiter"] = plt.silenceMid,
      ["@punctuation.bracket"] = plt.silenceMid,
      ["@punctuation. special"] = plt.restoreMid,

      ["@tag"] = plt.clarityCore,
      ["@tag.attribute"] = plt.silenceLightest,
      ["@tag. delimiter"] = plt.silenceMid,
      ["@tag.builtin"] = plt.clarityCore,

      ["@markup. strong"] = { fg = plt.restoreBright, bold = true },
      ["@markup.italic"] = { fg = plt.clarityCore, italic = true },
      ["@markup.strikethrough"] = { fg = plt.silenceMid, strikethrough = true },
      ["@markup. underline"] = { fg = plt.clarityCore, underline = true },
      ["@markup.heading"] = plt.restoreBright,
      ["@markup.heading.1"] = plt.restoreBright,
      ["@markup.heading.2"] = plt.restoreMid,
      ["@markup. heading.3"] = plt.silenceLightest,
      ["@markup.heading.4"] = plt.silenceLighter,
      ["@markup.heading.5"] = plt.restoreDeep,
      ["@markup.heading.6"] = plt.restorePulse,
      ["@markup.quote"] = plt.silenceBright,
      ["@markup. math"] = plt.silenceLightest,
      ["@markup.link"] = plt.silenceLight,
      ["@markup. link.label"] = plt.restorePulse,
      ["@markup.link.url"] = plt.silenceLight,
      ["@markup.raw"] = plt.silenceLighter,
      ["@markup.raw.block"] = plt.silenceLighter,
      ["@markup.list"] = plt.clarityCore,
      ["@markup.list.checked"] = plt.silenceLighter,
      ["@markup.list.unchecked"] = plt.silenceBright,

      ["@diff. plus"] = plt.silenceLighter,
      ["@diff.minus"] = plt.restoreBright,
      ["@diff.delta"] = plt.silenceLight,

      ["@none"] = "none",
      ["@conceal"] = plt.silenceMid,
      ["@spell"] = plt.clarityCore,
      ["@nospell"] = "none",

      ["@lsp.type. property. lua"] = plt.clarityCore,
      ["@constructor.python"] = plt.clarityBright,
      ["@constructor. javascript"] = plt.clarityBright,
      ["@constructor.typescript"] = plt.clarityBright,
      ["@namespace.rust"] = plt.clarityCore,
      ["@type.qualifier.rust"] = plt.clarityCore,
      ["@constant.macro.c"] = plt.restoreDeep,
      ["@constant.macro.cpp"] = plt.restoreDeep,
      ["@namespace.go"] = plt.clarityCore,
      ["@property.css"] = plt.clarityBright,
      ["@type.css"] = plt.clarityCore,
      ["@label.json"] = plt.clarityCore,
      ["@field.yaml"] = plt.clarityCore,
      ["@property.toml"] = plt.clarityCore,
      ["@function.builtin.bash"] = plt.clarityBright,
      ["@string.regexp"] = plt.silenceLight,
      ["@character.special. regex"] = plt.restoreMid,
    },

    lsp = {
      ["@lsp.type.class"] = plt.silenceLightest,
      ["@lsp.type.interface"] = plt.silenceLightest,
      ["@lsp.type.struct"] = plt.silenceLightest,
      ["@lsp.type.enum"] = plt.silenceLightest,
      ["@lsp.type.enumMember"] = plt.silenceLightest,
      ["@lsp.type.property"] = plt.clarityCore,
      ["@lsp.type.namespace"] = plt.clarityCore,

      ["@lsp.type.macro"] = plt.restoreDeep,
      ["@lsp.type.decorator"] = plt.clarityBright,

      ["@lsp.type. builtinType"] = plt.silenceLightest,
      ["@lsp.type.selfParameter"] = plt.clarityCore,
      ["@lsp.type.typeParameter"] = plt.silenceLightest,

      ["@lsp.type. array"] = plt.silenceLightest,
      ["@lsp.type.object"] = plt.silenceLightest,
      ["@lsp.type.key"] = plt.clarityCore,
      ["@lsp.type.null"] = plt.silenceLightest,
      ["@lsp.type.enumConstant"] = plt.silenceLightest,

      ["@lsp.type. event"] = plt.silenceLightest,
      ["@lsp.type.regexp"] = plt.silenceLight,
      ["@lsp.type.unresolvedReference"] = plt.restoreBright,

      ["@lsp.mod.deprecated"] = { fg = plt.silenceMid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.silenceLightest,
      ["@lsp.mod.async"] = plt.clarityCore,
      ["@lsp. mod.static"] = plt.silenceLightest,
      ["@lsp.mod.abstract"] = plt.silenceLightest,
      ["@lsp.mod.defaultLibrary"] = plt.silenceLightest,
      ["@lsp.mod.documentation"] = plt.silenceBright,
    },
  }
end

return {
  name = "Detox: 1998 Terminal Green",
  author = "PrismPunk. nvim",
  description = "Pure 1998 CRT green phosphor.  Zero blue.  Deep readable greens.  The terminal your soul remembers.",

  base16 = {
    base00 = palette.hushVoid,
    base01 = palette.hushDark,
    base02 = palette.hushDeep,
    base03 = palette.hushMid,
    base04 = palette.silenceBright,
    base05 = palette.silenceLightest,
    base06 = palette.clarityDim,
    base07 = palette.clarityCore,
    base08 = palette.restoreBright,
    base09 = palette.restoreMid,
    base0A = palette.restoreDeep,
    base0B = palette.silenceLighter,
    base0C = palette.restorePulse,
    base0D = palette.silenceLight,
    base0E = palette.restorePulse,
    base0F = palette.silenceMid,
  },

  palette = palette,
  get = M.get,
}
