local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.bone")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.marrowBright,
      insert = plt.marrowLighter,
      visual = plt.decayPulse,
      replace = plt.marrowMid,
      command = plt.dustCore,
    },

    ui = {
      fg = plt.dustCore,
      fg_dim = plt.dustCore,
      fg_dimmer = plt.marrowLighter,
      fg_dark = plt.marrowMid,
      fg_reverse = plt.boneVoid,

      bg_m4 = plt.boneLight,
      bg_m3 = plt.boneMid,
      bg_m2 = plt.boneDeep,
      bg_m1 = plt.boneDark,
      bg_dim = plt.boneVoid,
      bg = plt.boneVoid,
      bg_p1 = plt.boneDeep,
      bg_p2 = plt.boneMid,
      bg_gutter = opts.gutter and plt.boneMid or "none",
      bg_cursorline = plt.creamLine,
      bg_cursorline_alt = plt.creamMid,
      bg_search = plt.decayPulse,
      bg_visual = plt.decayDeep,
      bg_statusline = plt.creamMid,

      border = plt.marrowMid,
      header1 = plt.dustBright,
      header2 = plt.dustCore,
      special = plt.decayBright,
      nontext = plt.boneLight,
      whitespace = plt.boneMid,
      win_separator = plt.marrowMid,
      indent = plt.boneMid,
      indent_scope = plt.marrowDeep,
      picker = plt.marrowMid,
      yank = plt.decayPulse,
      mark = plt.decayBright,
      scrollbar = plt.boneLight,

      tabline = {
        bg = plt.boneVoid,
        fg_selected = plt.dustCore,
        bg_selected = plt.creamMid,
        fg_inactive = plt.marrowLighter,
        bg_inactive = plt.boneVoid,
        fg_alternate = plt.marrowBright,
        bg_alternate = plt.boneVoid,
        indicator = plt.decayPulse,
      },

      pmenu = {
        fg = plt.dustCore,
        fg_sel = "none",
        fg_border = plt.creamMid,
        bg_border = plt.creamMid,
        bg = plt.creamMid,
        bg_sel = plt.creamDeep,
        bg_sbar = plt.creamMid,
        bg_thumb = plt.marrowMid,
      },

      float = {
        fg = plt.dustCore,
        bg = plt.boneDeep,
        fg_border = plt.creamMid,
        bg_border = plt.boneDeep,
      },
    },

    accent = {
      accent1 = plt.dustBright,
      accent2 = plt.dustCore,
      accent3 = plt.marrowLighter,
      accent4 = plt.marrowBright,
      accent5 = plt.decayPulse,
      invert = plt.creamMid,
    },

    rainbow = {
      rainbow1 = plt.marrowBright,
      rainbow2 = plt.marrowMid,
      rainbow3 = plt.marrowDeep,
      rainbow4 = plt.creamDeep,
      rainbow5 = plt.dustCore,
      rainbow6 = plt.dustBright,
      rainbow7 = plt.decayPulse,
    },

    syn = {
      attribute = plt.dustCore,
      boolean = plt.decayBright,
      comment = plt.marrowBright,
      constant = plt.marrowLightest,
      deprecated = plt.marrowMid,
      func = plt.dustBright,
      identifier = plt.dustCore,
      keyword = plt.dustCore,
      method = plt.dustBright,
      number = plt.marrowLightest,
      operator = plt.marrowMid,
      parameter = plt.marrowLighter,
      preproc = plt.decayMid,
      punct = plt.marrowDeep,
      regex = plt.marrowMid,
      statement = plt.dustCore,
      string = plt.marrowLighter,
      symbol = plt.dustCore,
      type = plt.marrowLightest,
      variable = plt.dustCore,
      special = plt.decayPulse,
      special2 = plt.decayMid,
      special3 = plt.decayBright,
    },

    vcs = { added = plt.marrowLighter, removed = plt.decayBright, changed = plt.decayDeep },
    diff = { add = plt.marrowLighter, change = plt.marrowDeep, delete = plt.decayBright, text = plt.decayMid },
    diag = {
      ok = plt.marrowLighter,
      error = plt.decayBright,
      warning = plt.decayPulse,
      info = plt.dustCore,
      hint = plt.marrowMid,
    },

    term = {
      black = plt.boneVoid,
      red = plt.decayBright,
      green = plt.marrowBright,
      yellow = plt.marrowLightest,
      blue = plt.boneVoid,
      magenta = plt.dustCore,
      cyan = plt.marrowMid,
      white = plt.dustBright,

      black_bright = color(plt.boneVoid):brighten(0.4):to_hex(),
      red_bright = plt.decayPulse,
      green_bright = color(plt.marrowBright):brighten(0.3):to_hex(),
      yellow_bright = plt.dustBright,
      blue_bright = color(plt.boneVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.dustCore):brighten(0.4):to_hex(),
      cyan_bright = color(plt.marrowMid):brighten(0.3):to_hex(),
      white_bright = plt.dustBright,
      indexed1 = plt.marrowLighter,
      indexed2 = plt.marrowBright,
    },

    treesitter = {
      ["@comment"] = plt.marrowBright,
      ["@comment.documentation"] = plt.marrowMid,
      ["@comment.error"] = plt.decayBright,
      ["@comment.warning"] = plt.decayPulse,
      ["@comment.todo"] = plt.marrowLighter,
      ["@comment.note"] = plt.marrowMid,

      ["@constant"] = plt.marrowLightest,
      ["@constant.builtin"] = plt.marrowLightest,
      ["@constant.macro"] = plt.decayMid,

      ["@string"] = plt.marrowLighter,
      ["@string.documentation"] = plt.marrowLighter,
      ["@string.regex"] = plt.marrowMid,
      ["@string.escape"] = plt.decayMid,
      ["@string.special"] = plt.decayBright,
      ["@string.special.symbol"] = plt.decayBright,
      ["@string.special.url"] = plt.marrowMid,
      ["@string.special.path"] = plt.marrowLighter,

      ["@character"] = plt.marrowLighter,
      ["@character.special"] = plt.decayMid,

      ["@number"] = plt.marrowLightest,
      ["@number.float"] = plt.marrowLightest,

      ["@boolean"] = plt.decayBright,

      ["@function"] = plt.dustBright,
      ["@function.builtin"] = plt.dustBright,
      ["@function.call"] = plt.dustBright,
      ["@function.macro"] = plt.decayMid,
      ["@function.method"] = plt.dustBright,
      ["@function.method.call"] = plt.dustBright,

      ["@constructor"] = plt.dustCore,

      ["@parameter"] = plt.marrowLighter,
      ["@parameter.builtin"] = plt.marrowLightest,

      ["@keyword"] = plt.dustCore,
      ["@keyword.coroutine"] = plt.decayBright,
      ["@keyword.function"] = plt.dustCore,
      ["@keyword.operator"] = plt.marrowMid,
      ["@keyword.return"] = plt.dustCore,
      ["@keyword.import"] = plt.marrowLightest,
      ["@keyword.storage"] = plt.dustCore,
      ["@keyword.repeat"] = plt.dustCore,
      ["@keyword.conditional"] = plt.dustCore,
      ["@keyword.exception"] = plt.decayBright,
      ["@keyword.directive"] = plt.decayMid,
      ["@keyword.directive.define"] = plt.decayMid,

      ["@conditional"] = plt.dustCore,
      ["@conditional.ternary"] = plt.dustCore,

      ["@repeat"] = plt.dustCore,

      ["@label"] = plt.marrowLightest,

      ["@operator"] = plt.marrowMid,

      ["@exception"] = plt.decayBright,

      ["@variable"] = plt.dustCore,
      ["@variable.builtin"] = plt.marrowLightest,
      ["@variable.parameter"] = plt.marrowLighter,
      ["@variable.member"] = plt.dustCore,

      ["@type"] = plt.marrowLightest,
      ["@type.builtin"] = plt.marrowLightest,
      ["@type.definition"] = plt.marrowLightest,
      ["@type.qualifier"] = plt.dustCore,

      ["@attribute"] = plt.dustCore,
      ["@attribute.builtin"] = plt.marrowLightest,

      ["@property"] = plt.dustCore,
      ["@field"] = plt.dustCore,

      ["@module"] = plt.dustCore,
      ["@module.builtin"] = plt.dustCore,

      ["@namespace"] = plt.dustCore,
      ["@namespace.builtin"] = plt.dustCore,

      ["@punctuation.delimiter"] = plt.marrowMid,
      ["@punctuation.bracket"] = plt.marrowMid,
      ["@punctuation.special"] = plt.decayMid,

      ["@tag"] = plt.dustCore,
      ["@tag.attribute"] = plt.marrowLightest,
      ["@tag.delimiter"] = plt.marrowMid,
      ["@tag.builtin"] = plt.dustCore,

      ["@markup.strong"] = { fg = plt.dustBright, bold = true },
      ["@markup.italic"] = { fg = plt.dustCore, italic = true },
      ["@markup.strikethrough"] = { fg = plt.marrowMid, strikethrough = true },
      ["@markup.underline"] = { fg = plt.dustCore, underline = true },
      ["@markup.heading"] = plt.dustBright,
      ["@markup.heading.1"] = plt.dustBright,
      ["@markup.heading.2"] = plt.dustCore,
      ["@markup.heading.3"] = plt.marrowLightest,
      ["@markup.heading.4"] = plt.marrowLighter,
      ["@markup.heading.5"] = plt.decayMid,
      ["@markup.heading.6"] = plt.decayPulse,
      ["@markup.quote"] = plt.marrowBright,
      ["@markup.math"] = plt.marrowLightest,
      ["@markup.link"] = plt.marrowMid,
      ["@markup.link.label"] = plt.decayPulse,
      ["@markup.link.url"] = plt.marrowMid,
      ["@markup.raw"] = plt.marrowLighter,
      ["@markup.raw.block"] = plt.marrowLighter,
      ["@markup.list"] = plt.dustCore,
      ["@markup.list.checked"] = plt.marrowLighter,
      ["@markup.list.unchecked"] = plt.marrowBright,

      ["@diff.plus"] = plt.marrowLighter,
      ["@diff.minus"] = plt.decayBright,
      ["@diff.delta"] = plt.marrowMid,

      ["@none"] = "none",
      ["@conceal"] = plt.marrowMid,
      ["@spell"] = plt.dustCore,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.dustCore,
      ["@constructor.python"] = plt.dustBright,
      ["@constructor.javascript"] = plt.dustBright,
      ["@constructor.typescript"] = plt.dustBright,
      ["@namespace.rust"] = plt.dustCore,
      ["@type.qualifier.rust"] = plt.dustCore,
      ["@constant.macro.c"] = plt.decayMid,
      ["@constant.macro.cpp"] = plt.decayMid,
      ["@namespace.go"] = plt.dustCore,
      ["@property.css"] = plt.dustBright,
      ["@type.css"] = plt.dustCore,
      ["@label.json"] = plt.dustCore,
      ["@field.yaml"] = plt.dustCore,
      ["@property.toml"] = plt.dustCore,
      ["@function.builtin.bash"] = plt.dustBright,
      ["@string.regexp"] = plt.marrowMid,
      ["@character.special.regex"] = plt.decayMid,
    },

    lsp = {
      ["@lsp.type.class"] = plt.marrowLightest,
      ["@lsp.type.interface"] = plt.marrowLightest,
      ["@lsp.type.struct"] = plt.marrowLightest,
      ["@lsp.type.enum"] = plt.marrowLightest,
      ["@lsp.type.enumMember"] = plt.marrowLightest,
      ["@lsp.type.property"] = plt.dustCore,
      ["@lsp.type.namespace"] = plt.dustCore,

      ["@lsp.type.macro"] = plt.decayMid,
      ["@lsp.type.decorator"] = plt.dustBright,

      ["@lsp.type.builtinType"] = plt.marrowLightest,
      ["@lsp.type.selfParameter"] = plt.dustCore,
      ["@lsp.type.typeParameter"] = plt.marrowLightest,

      ["@lsp.type.array"] = plt.marrowLightest,
      ["@lsp.type.object"] = plt.marrowLightest,
      ["@lsp.type.key"] = plt.dustCore,
      ["@lsp.type.null"] = plt.marrowLightest,
      ["@lsp.type.enumConstant"] = plt.marrowLightest,

      ["@lsp.type.event"] = plt.marrowLightest,
      ["@lsp.type.regexp"] = plt.marrowMid,
      ["@lsp.type.unresolvedReference"] = plt.decayBright,

      ["@lsp.mod.deprecated"] = { fg = plt.marrowMid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.marrowLightest,
      ["@lsp.mod.async"] = plt.dustCore,
      ["@lsp.mod.static"] = plt.marrowLightest,
      ["@lsp.mod.abstract"] = plt.marrowLightest,
      ["@lsp.mod.defaultLibrary"] = plt.marrowLightest,
      ["@lsp.mod.documentation"] = plt.marrowBright,
    },
  }
end

return {
  name = "Detox: Bone",
  author = "PrismPunk.nvim",
  description = "Skeletal bleached whites. Archaeological time. Deep earth decay. Memento mori.",

  base16 = {
    base00 = palette.boneVoid,
    base01 = palette.boneDark,
    base02 = palette.boneDeep,
    base03 = palette.boneMid,
    base04 = palette.marrowBright,
    base05 = palette.marrowLightest,
    base06 = palette.dustCore,
    base07 = palette.dustBright,
    base08 = palette.decayBright,
    base09 = palette.decayMid,
    base0A = palette.decayDeep,
    base0B = palette.marrowLighter,
    base0C = palette.decayPulse,
    base0D = palette.marrowMid,
    base0E = palette.decayPulse,
    base0F = palette.marrowMid,
  },

  palette = palette,
  get = M.get,
}
