local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.clay")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.earthBright,
      insert = plt.earthLighter,
      visual = plt.glazePulse,
      replace = plt.earthMid,
      command = plt.clayCore,
    },

    ui = {
      fg = plt.clayCore,
      fg_dim = plt.clayCore,
      fg_dimmer = plt.earthLighter,
      fg_dark = plt.earthMid,
      fg_reverse = plt.clayVoid,

      bg_m4 = plt.clayLight,
      bg_m3 = plt.clayMid,
      bg_m2 = plt.clayDeep,
      bg_m1 = plt.clayDark,
      bg_dim = plt.clayVoid,
      bg = plt.clayVoid,
      bg_p1 = plt.clayDeep,
      bg_p2 = plt.clayMid,
      bg_gutter = opts.gutter and plt.clayMid or "none",
      bg_cursorline = plt.kilnLine,
      bg_cursorline_alt = plt.kilnMid,
      bg_search = plt.glazePulse,
      bg_visual = plt.glazeDeep,
      bg_statusline = plt.kilnMid,

      border = plt.earthMid,
      header1 = plt.clayBright,
      header2 = plt.clayCore,
      special = plt.glazeBright,
      nontext = plt.clayLight,
      whitespace = plt.clayMid,
      win_separator = plt.earthMid,
      indent = plt.clayMid,
      indent_scope = plt.earthDeep,
      picker = plt.earthMid,
      yank = plt.glazePulse,
      mark = plt.glazeBright,
      scrollbar = plt.clayLight,

      tabline = {
        bg = plt.clayVoid,
        fg_selected = plt.clayCore,
        bg_selected = plt.kilnMid,
        fg_inactive = plt.earthLighter,
        bg_inactive = plt.clayVoid,
        fg_alternate = plt.earthBright,
        bg_alternate = plt.clayVoid,
        indicator = plt.glazePulse,
      },

      pmenu = {
        fg = plt.clayCore,
        fg_sel = "none",
        fg_border = plt.kilnMid,
        bg_border = plt.kilnMid,
        bg = plt.kilnMid,
        bg_sel = plt.kilnDeep,
        bg_sbar = plt.kilnMid,
        bg_thumb = plt.earthMid,
      },

      float = {
        fg = plt.clayCore,
        bg = plt.clayDeep,
        fg_border = plt.kilnMid,
        bg_border = plt.clayDeep,
      },
    },

    accent = {
      accent1 = plt.clayBright,
      accent2 = plt.clayCore,
      accent3 = plt.earthLighter,
      accent4 = plt.earthBright,
      accent5 = plt.glazePulse,
      invert = plt.kilnMid,
    },

    rainbow = {
      rainbow1 = plt.earthBright,
      rainbow2 = plt.earthMid,
      rainbow3 = plt.earthDeep,
      rainbow4 = plt.kilnDeep,
      rainbow5 = plt.clayCore,
      rainbow6 = plt.clayBright,
      rainbow7 = plt.glazePulse,
    },

    syn = {
      attribute = plt.clayCore,
      boolean = plt.glazeBright,
      comment = plt.earthBright,
      constant = plt.earthLightest,
      deprecated = plt.earthMid,
      func = plt.clayBright,
      identifier = plt.clayCore,
      keyword = plt.clayCore,
      method = plt.clayBright,
      number = plt.earthLightest,
      operator = plt.earthMid,
      parameter = plt.earthLighter,
      preproc = plt.glazeMid,
      punct = plt.earthDeep,
      regex = plt.earthMid,
      statement = plt.clayCore,
      string = plt.earthLighter,
      symbol = plt.clayCore,
      type = plt.earthLightest,
      variable = plt.clayCore,
      special = plt.glazePulse,
      special2 = plt.glazeMid,
      special3 = plt.glazeBright,
    },

    vcs = { added = plt.earthLighter, removed = plt.glazeBright, changed = plt.glazeDeep },
    diff = { add = plt.earthLighter, change = plt.earthDeep, delete = plt.glazeBright, text = plt.glazeMid },
    diag = {
      ok = plt.earthLighter,
      error = plt.glazeBright,
      warning = plt.glazePulse,
      info = plt.clayCore,
      hint = plt.earthMid,
    },

    term = {
      black = plt.clayVoid,
      red = plt.glazeBright,
      green = plt.earthBright,
      yellow = plt.earthLightest,
      blue = plt.clayVoid,
      magenta = plt.clayCore,
      cyan = plt.earthMid,
      white = plt.clayBright,

      black_bright = color(plt.clayVoid):brighten(0.4):to_hex(),
      red_bright = plt.glazePulse,
      green_bright = color(plt.earthBright):brighten(0.3):to_hex(),
      yellow_bright = plt.clayBright,
      blue_bright = color(plt.clayVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.clayCore):brighten(0.4):to_hex(),
      cyan_bright = color(plt.earthMid):brighten(0.3):to_hex(),
      white_bright = plt.clayBright,
      indexed1 = plt.earthLighter,
      indexed2 = plt.earthBright,
    },

    treesitter = {
      ["@comment"] = plt.earthBright,
      ["@comment.documentation"] = plt.earthMid,
      ["@comment.error"] = plt.glazeBright,
      ["@comment.warning"] = plt.glazePulse,
      ["@comment.todo"] = plt.earthLighter,
      ["@comment.note"] = plt.earthMid,

      ["@constant"] = plt.earthLightest,
      ["@constant.builtin"] = plt.earthLightest,
      ["@constant.macro"] = plt.glazeMid,

      ["@string"] = plt.earthLighter,
      ["@string.documentation"] = plt.earthLighter,
      ["@string.regex"] = plt.earthMid,
      ["@string.escape"] = plt.glazeMid,
      ["@string.special"] = plt.glazeBright,
      ["@string.special.symbol"] = plt.glazeBright,
      ["@string.special.url"] = plt.earthMid,
      ["@string.special.path"] = plt.earthLighter,

      ["@character"] = plt.earthLighter,
      ["@character.special"] = plt.glazeMid,

      ["@number"] = plt.earthLightest,
      ["@number.float"] = plt.earthLightest,

      ["@boolean"] = plt.glazeBright,

      ["@function"] = plt.clayBright,
      ["@function.builtin"] = plt.clayBright,
      ["@function.call"] = plt.clayBright,
      ["@function.macro"] = plt.glazeMid,
      ["@function.method"] = plt.clayBright,
      ["@function.method.call"] = plt.clayBright,

      ["@constructor"] = plt.clayCore,

      ["@parameter"] = plt.earthLighter,
      ["@parameter.builtin"] = plt.earthLightest,

      ["@keyword"] = plt.clayCore,
      ["@keyword.coroutine"] = plt.glazeBright,
      ["@keyword.function"] = plt.clayCore,
      ["@keyword.operator"] = plt.earthMid,
      ["@keyword.return"] = plt.clayCore,
      ["@keyword.import"] = plt.earthLightest,
      ["@keyword.storage"] = plt.clayCore,
      ["@keyword.repeat"] = plt.clayCore,
      ["@keyword.conditional"] = plt.clayCore,
      ["@keyword.exception"] = plt.glazeBright,
      ["@keyword.directive"] = plt.glazeMid,
      ["@keyword.directive.define"] = plt.glazeMid,

      ["@conditional"] = plt.clayCore,
      ["@conditional.ternary"] = plt.clayCore,

      ["@repeat"] = plt.clayCore,

      ["@label"] = plt.earthLightest,

      ["@operator"] = plt.earthMid,

      ["@exception"] = plt.glazeBright,

      ["@variable"] = plt.clayCore,
      ["@variable.builtin"] = plt.earthLightest,
      ["@variable.parameter"] = plt.earthLighter,
      ["@variable.member"] = plt.clayCore,

      ["@type"] = plt.earthLightest,
      ["@type.builtin"] = plt.earthLightest,
      ["@type.definition"] = plt.earthLightest,
      ["@type.qualifier"] = plt.clayCore,

      ["@attribute"] = plt.clayCore,
      ["@attribute.builtin"] = plt.earthLightest,

      ["@property"] = plt.clayCore,
      ["@field"] = plt.clayCore,

      ["@module"] = plt.clayCore,
      ["@module.builtin"] = plt.clayCore,

      ["@namespace"] = plt.clayCore,
      ["@namespace.builtin"] = plt.clayCore,

      ["@punctuation.delimiter"] = plt.earthMid,
      ["@punctuation.bracket"] = plt.earthMid,
      ["@punctuation.special"] = plt.glazeMid,

      ["@tag"] = plt.clayCore,
      ["@tag.attribute"] = plt.earthLightest,
      ["@tag.delimiter"] = plt.earthMid,
      ["@tag.builtin"] = plt.clayCore,

      ["@markup.strong"] = { fg = plt.clayBright, bold = true },
      ["@markup.italic"] = { fg = plt.clayCore, italic = true },
      ["@markup.strikethrough"] = { fg = plt.earthMid, strikethrough = true },
      ["@markup.underline"] = { fg = plt.clayCore, underline = true },
      ["@markup.heading"] = plt.clayBright,
      ["@markup.heading.1"] = plt.clayBright,
      ["@markup.heading.2"] = plt.clayCore,
      ["@markup.heading.3"] = plt.earthLightest,
      ["@markup.heading.4"] = plt.earthLighter,
      ["@markup.heading.5"] = plt.glazeMid,
      ["@markup.heading.6"] = plt.glazePulse,
      ["@markup.quote"] = plt.earthBright,
      ["@markup.math"] = plt.earthLightest,
      ["@markup.link"] = plt.earthMid,
      ["@markup.link.label"] = plt.glazePulse,
      ["@markup.link.url"] = plt.earthMid,
      ["@markup.raw"] = plt.earthLighter,
      ["@markup.raw.block"] = plt.earthLighter,
      ["@markup.list"] = plt.clayCore,
      ["@markup.list.checked"] = plt.earthLighter,
      ["@markup.list.unchecked"] = plt.earthBright,

      ["@diff.plus"] = plt.earthLighter,
      ["@diff.minus"] = plt.glazeBright,
      ["@diff.delta"] = plt.earthMid,

      ["@none"] = "none",
      ["@conceal"] = plt.earthMid,
      ["@spell"] = plt.clayCore,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.clayCore,
      ["@constructor.python"] = plt.clayBright,
      ["@constructor.javascript"] = plt.clayBright,
      ["@constructor.typescript"] = plt.clayBright,
      ["@namespace.rust"] = plt.clayCore,
      ["@type.qualifier.rust"] = plt.clayCore,
      ["@constant.macro.c"] = plt.glazeMid,
      ["@constant.macro.cpp"] = plt.glazeMid,
      ["@namespace.go"] = plt.clayCore,
      ["@property.css"] = plt.clayBright,
      ["@type.css"] = plt.clayCore,
      ["@label.json"] = plt.clayCore,
      ["@field.yaml"] = plt.clayCore,
      ["@property.toml"] = plt.clayCore,
      ["@function.builtin.bash"] = plt.clayBright,
      ["@string.regexp"] = plt.earthMid,
      ["@character.special.regex"] = plt.glazeMid,
    },

    lsp = {
      ["@lsp.type.class"] = plt.earthLightest,
      ["@lsp.type.interface"] = plt.earthLightest,
      ["@lsp.type.struct"] = plt.earthLightest,
      ["@lsp.type.enum"] = plt.earthLightest,
      ["@lsp.type.enumMember"] = plt.earthLightest,
      ["@lsp.type.property"] = plt.clayCore,
      ["@lsp.type.namespace"] = plt.clayCore,

      ["@lsp.type.macro"] = plt.glazeMid,
      ["@lsp.type.decorator"] = plt.clayBright,

      ["@lsp.type.builtinType"] = plt.earthLightest,
      ["@lsp.type.selfParameter"] = plt.clayCore,
      ["@lsp.type.typeParameter"] = plt.earthLightest,

      ["@lsp.type.array"] = plt.earthLightest,
      ["@lsp.type.object"] = plt.earthLightest,
      ["@lsp.type.key"] = plt.clayCore,
      ["@lsp.type.null"] = plt.earthLightest,
      ["@lsp.type.enumConstant"] = plt.earthLightest,

      ["@lsp.type.event"] = plt.earthLightest,
      ["@lsp.type.regexp"] = plt.earthMid,
      ["@lsp.type.unresolvedReference"] = plt.glazeBright,

      ["@lsp.mod.deprecated"] = { fg = plt.earthMid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.earthLightest,
      ["@lsp.mod.async"] = plt.clayCore,
      ["@lsp.mod.static"] = plt.earthLightest,
      ["@lsp.mod.abstract"] = plt.earthLightest,
      ["@lsp.mod.defaultLibrary"] = plt.earthLightest,
      ["@lsp.mod.documentation"] = plt.earthBright,
    },
  }
end

return {
  name = "Detox: Clay",
  author = "PrismPunk.nvim",
  description = "Fired earth pottery. Kiln-baked terracotta. Deep glaze stains. Handcrafted impermanence.",

  base16 = {
    base00 = palette.clayVoid,
    base01 = palette.clayDark,
    base02 = palette.clayDeep,
    base03 = palette.clayMid,
    base04 = palette.earthBright,
    base05 = palette.earthLightest,
    base06 = palette.clayCore,
    base07 = palette.clayBright,
    base08 = palette.glazeBright,
    base09 = palette.glazeMid,
    base0A = palette.glazeDeep,
    base0B = palette.earthLighter,
    base0C = palette.glazePulse,
    base0D = palette.earthMid,
    base0E = palette.glazePulse,
    base0F = palette.earthMid,
  },

  palette = palette,
  get = M.get,
}
