local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.ember")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.glowBright,
      insert = plt.glowLighter,
      visual = plt.flamePulse,
      replace = plt.glowMid,
      command = plt.ashCore,
    },

    ui = {
      fg = plt.ashCore,
      fg_dim = plt.ashCore,
      fg_dimmer = plt.glowLighter,
      fg_dark = plt.glowMid,
      fg_reverse = plt.coalVoid,

      bg_m4 = plt.coalLight,
      bg_m3 = plt.coalMid,
      bg_m2 = plt.coalDeep,
      bg_m1 = plt.coalDark,
      bg_dim = plt.coalVoid,
      bg = plt.coalVoid,
      bg_p1 = plt.coalDeep,
      bg_p2 = plt.coalMid,
      bg_gutter = opts.gutter and plt.coalMid or "none",
      bg_cursorline = plt.fireLine,
      bg_cursorline_alt = plt.fireMid,
      bg_search = plt.flamePulse,
      bg_visual = plt.flameDeep,
      bg_statusline = plt.fireMid,

      border = plt.glowMid,
      header1 = plt.ashBright,
      header2 = plt.ashCore,
      special = plt.flameBright,
      nontext = plt.coalLight,
      whitespace = plt.coalMid,
      win_separator = plt.glowMid,
      indent = plt.coalMid,
      indent_scope = plt.glowDeep,
      picker = plt.glowMid,
      yank = plt.flamePulse,
      mark = plt.flameBright,
      scrollbar = plt.coalLight,

      tabline = {
        bg = plt.coalVoid,
        fg_selected = plt.ashCore,
        bg_selected = plt.fireMid,
        fg_inactive = plt.glowLighter,
        bg_inactive = plt.coalVoid,
        fg_alternate = plt.glowBright,
        bg_alternate = plt.coalVoid,
        indicator = plt.flamePulse,
      },

      pmenu = {
        fg = plt.ashCore,
        fg_sel = "none",
        fg_border = plt.fireMid,
        bg_border = plt.fireMid,
        bg = plt.fireMid,
        bg_sel = plt.fireDeep,
        bg_sbar = plt.fireMid,
        bg_thumb = plt.glowMid,
      },

      float = {
        fg = plt.ashCore,
        bg = plt.coalDeep,
        fg_border = plt.fireMid,
        bg_border = plt.coalDeep,
      },
    },

    accent = {
      accent1 = plt.ashBright,
      accent2 = plt.ashCore,
      accent3 = plt.glowLighter,
      accent4 = plt.glowBright,
      accent5 = plt.flamePulse,
      invert = plt.fireMid,
    },

    rainbow = {
      rainbow1 = plt.glowBright,
      rainbow2 = plt.glowMid,
      rainbow3 = plt.glowDeep,
      rainbow4 = plt.fireDeep,
      rainbow5 = plt.ashCore,
      rainbow6 = plt.ashBright,
      rainbow7 = plt.flamePulse,
    },

    syn = {
      attribute = plt.ashCore,
      boolean = plt.flameBright,
      comment = plt.glowBright,
      constant = plt.glowLightest,
      deprecated = plt.glowMid,
      func = plt.ashBright,
      identifier = plt.ashCore,
      keyword = plt.ashCore,
      method = plt.ashBright,
      number = plt.glowLightest,
      operator = plt.glowMid,
      parameter = plt.glowLighter,
      preproc = plt.flameMid,
      punct = plt.glowDeep,
      regex = plt.glowMid,
      statement = plt.ashCore,
      string = plt.glowLighter,
      symbol = plt.ashCore,
      type = plt.glowLightest,
      variable = plt.ashCore,
      special = plt.flamePulse,
      special2 = plt.flameMid,
      special3 = plt.flameBright,
    },

    vcs = { added = plt.glowLighter, removed = plt.flameBright, changed = plt.flameDeep },
    diff = { add = plt.glowLighter, change = plt.glowDeep, delete = plt.flameBright, text = plt.flameMid },
    diag = {
      ok = plt.glowLighter,
      error = plt.flameBright,
      warning = plt.flamePulse,
      info = plt.ashCore,
      hint = plt.glowMid,
    },

    term = {
      black = plt.coalVoid,
      red = plt.flameBright,
      green = plt.glowBright,
      yellow = plt.glowLightest,
      blue = plt.coalVoid,
      magenta = plt.ashCore,
      cyan = plt.glowMid,
      white = plt.ashBright,

      black_bright = color(plt.coalVoid):brighten(0.4):to_hex(),
      red_bright = plt.flamePulse,
      green_bright = color(plt.glowBright):brighten(0.3):to_hex(),
      yellow_bright = plt.ashBright,
      blue_bright = color(plt.coalVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.ashCore):brighten(0.4):to_hex(),
      cyan_bright = color(plt.glowMid):brighten(0.3):to_hex(),
      white_bright = plt.ashBright,
      indexed1 = plt.glowLighter,
      indexed2 = plt.glowBright,
    },

    treesitter = {
      ["@comment"] = plt.glowBright,
      ["@comment.documentation"] = plt.glowMid,
      ["@comment.error"] = plt.flameBright,
      ["@comment.warning"] = plt.flamePulse,
      ["@comment.todo"] = plt.glowLighter,
      ["@comment.note"] = plt.glowMid,

      ["@constant"] = plt.glowLightest,
      ["@constant.builtin"] = plt.glowLightest,
      ["@constant.macro"] = plt.flameMid,

      ["@string"] = plt.glowLighter,
      ["@string.documentation"] = plt.glowLighter,
      ["@string.regex"] = plt.glowMid,
      ["@string.escape"] = plt.flameMid,
      ["@string.special"] = plt.flameBright,
      ["@string.special.symbol"] = plt.flameBright,
      ["@string.special.url"] = plt.glowMid,
      ["@string.special.path"] = plt.glowLighter,

      ["@character"] = plt.glowLighter,
      ["@character.special"] = plt.flameMid,

      ["@number"] = plt.glowLightest,
      ["@number.float"] = plt.glowLightest,

      ["@boolean"] = plt.flameBright,

      ["@function"] = plt.ashBright,
      ["@function.builtin"] = plt.ashBright,
      ["@function.call"] = plt.ashBright,
      ["@function.macro"] = plt.flameMid,
      ["@function.method"] = plt.ashBright,
      ["@function.method.call"] = plt.ashBright,

      ["@constructor"] = plt.ashCore,

      ["@parameter"] = plt.glowLighter,
      ["@parameter.builtin"] = plt.glowLightest,

      ["@keyword"] = plt.ashCore,
      ["@keyword.coroutine"] = plt.flameBright,
      ["@keyword.function"] = plt.ashCore,
      ["@keyword.operator"] = plt.glowMid,
      ["@keyword.return"] = plt.ashCore,
      ["@keyword.import"] = plt.glowLightest,
      ["@keyword.storage"] = plt.ashCore,
      ["@keyword.repeat"] = plt.ashCore,
      ["@keyword.conditional"] = plt.ashCore,
      ["@keyword.exception"] = plt.flameBright,
      ["@keyword.directive"] = plt.flameMid,
      ["@keyword.directive.define"] = plt.flameMid,

      ["@conditional"] = plt.ashCore,
      ["@conditional.ternary"] = plt.ashCore,

      ["@repeat"] = plt.ashCore,

      ["@label"] = plt.glowLightest,

      ["@operator"] = plt.glowMid,

      ["@exception"] = plt.flameBright,

      ["@variable"] = plt.ashCore,
      ["@variable.builtin"] = plt.glowLightest,
      ["@variable.parameter"] = plt.glowLighter,
      ["@variable.member"] = plt.ashCore,

      ["@type"] = plt.glowLightest,
      ["@type.builtin"] = plt.glowLightest,
      ["@type.definition"] = plt.glowLightest,
      ["@type.qualifier"] = plt.ashCore,

      ["@attribute"] = plt.ashCore,
      ["@attribute.builtin"] = plt.glowLightest,

      ["@property"] = plt.ashCore,
      ["@field"] = plt.ashCore,

      ["@module"] = plt.ashCore,
      ["@module.builtin"] = plt.ashCore,

      ["@namespace"] = plt.ashCore,
      ["@namespace.builtin"] = plt.ashCore,

      ["@punctuation.delimiter"] = plt.glowMid,
      ["@punctuation.bracket"] = plt.glowMid,
      ["@punctuation.special"] = plt.flameMid,

      ["@tag"] = plt.ashCore,
      ["@tag.attribute"] = plt.glowLightest,
      ["@tag.delimiter"] = plt.glowMid,
      ["@tag.builtin"] = plt.ashCore,

      ["@markup.strong"] = { fg = plt.ashBright, bold = true },
      ["@markup.italic"] = { fg = plt.ashCore, italic = true },
      ["@markup.strikethrough"] = { fg = plt.glowMid, strikethrough = true },
      ["@markup.underline"] = { fg = plt.ashCore, underline = true },
      ["@markup.heading"] = plt.ashBright,
      ["@markup.heading.1"] = plt.ashBright,
      ["@markup.heading.2"] = plt.ashCore,
      ["@markup.heading.3"] = plt.glowLightest,
      ["@markup.heading.4"] = plt.glowLighter,
      ["@markup.heading.5"] = plt.flameMid,
      ["@markup.heading.6"] = plt.flamePulse,
      ["@markup.quote"] = plt.glowBright,
      ["@markup.math"] = plt.glowLightest,
      ["@markup.link"] = plt.glowMid,
      ["@markup.link.label"] = plt.flamePulse,
      ["@markup.link.url"] = plt.glowMid,
      ["@markup.raw"] = plt.glowLighter,
      ["@markup.raw.block"] = plt.glowLighter,
      ["@markup.list"] = plt.ashCore,
      ["@markup.list.checked"] = plt.glowLighter,
      ["@markup.list.unchecked"] = plt.glowBright,

      ["@diff.plus"] = plt.glowLighter,
      ["@diff.minus"] = plt.flameBright,
      ["@diff.delta"] = plt.glowMid,

      ["@none"] = "none",
      ["@conceal"] = plt.glowMid,
      ["@spell"] = plt.ashCore,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.ashCore,
      ["@constructor.python"] = plt.ashBright,
      ["@constructor.javascript"] = plt.ashBright,
      ["@constructor.typescript"] = plt.ashBright,
      ["@namespace.rust"] = plt.ashCore,
      ["@type.qualifier.rust"] = plt.ashCore,
      ["@constant.macro.c"] = plt.flameMid,
      ["@constant.macro.cpp"] = plt.flameMid,
      ["@namespace.go"] = plt.ashCore,
      ["@property.css"] = plt.ashBright,
      ["@type.css"] = plt.ashCore,
      ["@label.json"] = plt.ashCore,
      ["@field.yaml"] = plt.ashCore,
      ["@property.toml"] = plt.ashCore,
      ["@function.builtin.bash"] = plt.ashBright,
      ["@string.regexp"] = plt.glowMid,
      ["@character.special.regex"] = plt.flameMid,
    },

    lsp = {
      ["@lsp.type.class"] = plt.glowLightest,
      ["@lsp.type.interface"] = plt.glowLightest,
      ["@lsp.type.struct"] = plt.glowLightest,
      ["@lsp.type.enum"] = plt.glowLightest,
      ["@lsp.type.enumMember"] = plt.glowLightest,
      ["@lsp.type.property"] = plt.ashCore,
      ["@lsp.type.namespace"] = plt.ashCore,

      ["@lsp.type.macro"] = plt.flameMid,
      ["@lsp.type.decorator"] = plt.ashBright,

      ["@lsp.type.builtinType"] = plt.glowLightest,
      ["@lsp.type.selfParameter"] = plt.ashCore,
      ["@lsp.type.typeParameter"] = plt.glowLightest,

      ["@lsp.type.array"] = plt.glowLightest,
      ["@lsp.type.object"] = plt.glowLightest,
      ["@lsp.type.key"] = plt.ashCore,
      ["@lsp.type.null"] = plt.glowLightest,
      ["@lsp.type.enumConstant"] = plt.glowLightest,

      ["@lsp.type.event"] = plt.glowLightest,
      ["@lsp.type.regexp"] = plt.glowMid,
      ["@lsp.type.unresolvedReference"] = plt.flameBright,

      ["@lsp.mod.deprecated"] = { fg = plt.glowMid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.glowLightest,
      ["@lsp.mod.async"] = plt.ashCore,
      ["@lsp.mod.static"] = plt.glowLightest,
      ["@lsp.mod.abstract"] = plt.glowLightest,
      ["@lsp.mod.defaultLibrary"] = plt.glowLightest,
      ["@lsp.mod.documentation"] = plt.glowBright,
    },
  }
end

return {
  name = "Detox: Ember",
  author = "PrismPunk.nvim",
  description = "Fading fire. Cooling coals. Pale yellow last flames. Peaceful dying intensity.",

  base16 = {
    base00 = palette.coalVoid,
    base01 = palette.coalDark,
    base02 = palette.coalDeep,
    base03 = palette.coalMid,
    base04 = palette.glowBright,
    base05 = palette.glowLightest,
    base06 = palette.ashCore,
    base07 = palette.ashBright,
    base08 = palette.flameBright,
    base09 = palette.flameMid,
    base0A = palette.flameDeep,
    base0B = palette.glowLighter,
    base0C = palette.flamePulse,
    base0D = palette.glowMid,
    base0E = palette.flamePulse,
    base0F = palette.glowMid,
  },

  palette = palette,
  get = M.get,
}
