local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.moth")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.dustBright,
      insert = plt.dustLighter,
      visual = plt.lampPulse,
      replace = plt.dustMid,
      command = plt.moonCore,
    },

    ui = {
      fg = plt.moonCore,
      fg_dim = plt.moonCore,
      fg_dimmer = plt.dustLighter,
      fg_dark = plt.dustMid,
      fg_reverse = plt.nightVoid,

      bg_m4 = plt.nightLight,
      bg_m3 = plt.nightMid,
      bg_m2 = plt.nightDeep,
      bg_m1 = plt.nightDark,
      bg_dim = plt.nightVoid,
      bg = plt.nightVoid,
      bg_p1 = plt.nightDeep,
      bg_p2 = plt.nightMid,
      bg_gutter = opts.gutter and plt.nightMid or "none",
      bg_cursorline = plt.silverLine,
      bg_cursorline_alt = plt.silverMid,
      bg_search = plt.lampPulse,
      bg_visual = plt.lampDeep,
      bg_statusline = plt.silverMid,

      border = plt.dustMid,
      header1 = plt.moonBright,
      header2 = plt.moonCore,
      special = plt.lampBright,
      nontext = plt.nightLight,
      whitespace = plt.nightMid,
      win_separator = plt.dustMid,
      indent = plt.nightMid,
      indent_scope = plt.dustDeep,
      picker = plt.dustMid,
      yank = plt.lampPulse,
      mark = plt.lampBright,
      scrollbar = plt.nightLight,

      tabline = {
        bg = plt.nightVoid,
        fg_selected = plt.moonCore,
        bg_selected = plt.silverMid,
        fg_inactive = plt.dustLighter,
        bg_inactive = plt.nightVoid,
        fg_alternate = plt.dustBright,
        bg_alternate = plt.nightVoid,
        indicator = plt.lampPulse,
      },

      pmenu = {
        fg = plt.moonCore,
        fg_sel = "none",
        fg_border = plt.silverMid,
        bg_border = plt.silverMid,
        bg = plt.silverMid,
        bg_sel = plt.silverDeep,
        bg_sbar = plt.silverMid,
        bg_thumb = plt.dustMid,
      },

      float = {
        fg = plt.moonCore,
        bg = plt.nightDeep,
        fg_border = plt.silverMid,
        bg_border = plt.nightDeep,
      },
    },

    accent = {
      accent1 = plt.moonBright,
      accent2 = plt.moonCore,
      accent3 = plt.dustLighter,
      accent4 = plt.dustBright,
      accent5 = plt.lampPulse,
      invert = plt.silverMid,
    },

    rainbow = {
      rainbow1 = plt.dustBright,
      rainbow2 = plt.dustMid,
      rainbow3 = plt.dustDeep,
      rainbow4 = plt.silverDeep,
      rainbow5 = plt.moonCore,
      rainbow6 = plt.moonBright,
      rainbow7 = plt.lampPulse,
    },

    syn = {
      attribute = plt.moonCore,
      boolean = plt.lampBright,
      comment = plt.dustBright,
      constant = plt.dustLightest,
      deprecated = plt.dustMid,
      func = plt.moonBright,
      identifier = plt.moonCore,
      keyword = plt.moonCore,
      method = plt.moonBright,
      number = plt.dustLightest,
      operator = plt.dustMid,
      parameter = plt.dustLighter,
      preproc = plt.lampMid,
      punct = plt.dustDeep,
      regex = plt.dustMid,
      statement = plt.moonCore,
      string = plt.dustLighter,
      symbol = plt.moonCore,
      type = plt.dustLightest,
      variable = plt.moonCore,
      special = plt.lampPulse,
      special2 = plt.lampMid,
      special3 = plt.lampBright,
    },

    vcs = { added = plt.dustLighter, removed = plt.lampBright, changed = plt.lampDeep },
    diff = { add = plt.dustLighter, change = plt.dustDeep, delete = plt.lampBright, text = plt.lampMid },
    diag = {
      ok = plt.dustLighter,
      error = plt.lampBright,
      warning = plt.lampPulse,
      info = plt.moonCore,
      hint = plt.dustMid,
    },

    term = {
      black = plt.nightVoid,
      red = plt.lampBright,
      green = plt.dustBright,
      green = plt.dustBright,
      yellow = plt.dustLightest,
      blue = plt.nightVoid,
      magenta = plt.moonCore,
      cyan = plt.dustMid,
      white = plt.moonBright,

      black_bright = color(plt.nightVoid):brighten(0.4):to_hex(),
      red_bright = plt.lampPulse,
      green_bright = color(plt.dustBright):brighten(0.3):to_hex(),
      yellow_bright = plt.moonBright,
      blue_bright = color(plt.nightVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.moonCore):brighten(0.4):to_hex(),
      cyan_bright = color(plt.dustMid):brighten(0.3):to_hex(),
      white_bright = plt.moonBright,
      indexed1 = plt.dustLighter,
      indexed2 = plt.dustBright,
    },

    treesitter = {
      ["@comment"] = plt.dustBright,
      ["@comment.documentation"] = plt.dustMid,
      ["@comment.error"] = plt.lampBright,
      ["@comment.warning"] = plt.lampPulse,
      ["@comment.todo"] = plt.dustLighter,
      ["@comment.note"] = plt.dustMid,

      ["@constant"] = plt.dustLightest,
      ["@constant.builtin"] = plt.dustLightest,
      ["@constant.macro"] = plt.lampMid,

      ["@string"] = plt.dustLighter,
      ["@string.documentation"] = plt.dustLighter,
      ["@string.regex"] = plt.dustMid,
      ["@string.escape"] = plt.lampMid,
      ["@string.special"] = plt.lampBright,
      ["@string.special.symbol"] = plt.lampBright,
      ["@string.special.url"] = plt.dustMid,
      ["@string.special.path"] = plt.dustLighter,

      ["@character"] = plt.dustLighter,
      ["@character.special"] = plt.lampMid,

      ["@number"] = plt.dustLightest,
      ["@number.float"] = plt.dustLightest,

      ["@boolean"] = plt.lampBright,

      ["@function"] = plt.moonBright,
      ["@function.builtin"] = plt.moonBright,
      ["@function.call"] = plt.moonBright,
      ["@function.macro"] = plt.lampMid,
      ["@function.method"] = plt.moonBright,
      ["@function.method.call"] = plt.moonBright,

      ["@constructor"] = plt.moonCore,

      ["@parameter"] = plt.dustLighter,
      ["@parameter.builtin"] = plt.dustLightest,

      ["@keyword"] = plt.moonCore,
      ["@keyword.coroutine"] = plt.lampBright,
      ["@keyword.function"] = plt.moonCore,
      ["@keyword.operator"] = plt.dustMid,
      ["@keyword.return"] = plt.moonCore,
      ["@keyword.import"] = plt.dustLightest,
      ["@keyword.storage"] = plt.moonCore,
      ["@keyword.repeat"] = plt.moonCore,
      ["@keyword.conditional"] = plt.moonCore,
      ["@keyword.exception"] = plt.lampBright,
      ["@keyword.directive"] = plt.lampMid,
      ["@keyword.directive.define"] = plt.lampMid,

      ["@conditional"] = plt.moonCore,
      ["@conditional.ternary"] = plt.moonCore,

      ["@repeat"] = plt.moonCore,

      ["@label"] = plt.dustLightest,

      ["@operator"] = plt.dustMid,

      ["@exception"] = plt.lampBright,

      ["@variable"] = plt.moonCore,
      ["@variable.builtin"] = plt.dustLightest,
      ["@variable.parameter"] = plt.dustLighter,
      ["@variable.member"] = plt.moonCore,

      ["@type"] = plt.dustLightest,
      ["@type.builtin"] = plt.dustLightest,
      ["@type.definition"] = plt.dustLightest,
      ["@type.qualifier"] = plt.moonCore,

      ["@attribute"] = plt.moonCore,
      ["@attribute.builtin"] = plt.dustLightest,

      ["@property"] = plt.moonCore,
      ["@field"] = plt.moonCore,

      ["@module"] = plt.moonCore,
      ["@module.builtin"] = plt.moonCore,

      ["@namespace"] = plt.moonCore,
      ["@namespace.builtin"] = plt.moonCore,

      ["@punctuation.delimiter"] = plt.dustMid,
      ["@punctuation.bracket"] = plt.dustMid,
      ["@punctuation.special"] = plt.lampMid,

      ["@tag"] = plt.moonCore,
      ["@tag.attribute"] = plt.dustLightest,
      ["@tag.delimiter"] = plt.dustMid,
      ["@tag.builtin"] = plt.moonCore,

      ["@markup.strong"] = { fg = plt.moonBright, bold = true },
      ["@markup.italic"] = { fg = plt.moonCore, italic = true },
      ["@markup.strikethrough"] = { fg = plt.dustMid, strikethrough = true },
      ["@markup.underline"] = { fg = plt.moonCore, underline = true },
      ["@markup.heading"] = plt.moonBright,
      ["@markup.heading.1"] = plt.moonBright,
      ["@markup.heading.2"] = plt.moonCore,
      ["@markup.heading.3"] = plt.dustLightest,
      ["@markup.heading.4"] = plt.dustLighter,
      ["@markup.heading.5"] = plt.lampMid,
      ["@markup.heading.6"] = plt.lampPulse,
      ["@markup.quote"] = plt.dustBright,
      ["@markup.math"] = plt.dustLightest,
      ["@markup.link"] = plt.dustMid,
      ["@markup.link.label"] = plt.lampPulse,
      ["@markup.link.url"] = plt.dustMid,
      ["@markup.raw"] = plt.dustLighter,
      ["@markup.raw.block"] = plt.dustLighter,
      ["@markup.list"] = plt.moonCore,
      ["@markup.list.checked"] = plt.dustLighter,
      ["@markup.list.unchecked"] = plt.dustBright,

      ["@diff.plus"] = plt.dustLighter,
      ["@diff.minus"] = plt.lampBright,
      ["@diff.delta"] = plt.dustMid,

      ["@none"] = "none",
      ["@conceal"] = plt.dustMid,
      ["@spell"] = plt.moonCore,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.moonCore,
      ["@constructor.python"] = plt.moonBright,
      ["@constructor.javascript"] = plt.moonBright,
      ["@constructor.typescript"] = plt.moonBright,
      ["@namespace.rust"] = plt.moonCore,
      ["@type.qualifier.rust"] = plt.moonCore,
      ["@constant.macro.c"] = plt.lampMid,
      ["@constant.macro.cpp"] = plt.lampMid,
      ["@namespace.go"] = plt.moonCore,
      ["@property.css"] = plt.moonBright,
      ["@type.css"] = plt.moonCore,
      ["@label.json"] = plt.moonCore,
      ["@field.yaml"] = plt.moonCore,
      ["@property.toml"] = plt.moonCore,
      ["@function.builtin.bash"] = plt.moonBright,
      ["@string.regexp"] = plt.dustMid,
      ["@character.special.regex"] = plt.lampMid,
    },

    lsp = {
      ["@lsp.type.class"] = plt.dustLightest,
      ["@lsp.type.interface"] = plt.dustLightest,
      ["@lsp.type.struct"] = plt.dustLightest,
      ["@lsp.type.enum"] = plt.dustLightest,
      ["@lsp.type.enumMember"] = plt.dustLightest,
      ["@lsp.type.property"] = plt.moonCore,
      ["@lsp.type.namespace"] = plt.moonCore,

      ["@lsp.type.macro"] = plt.lampMid,
      ["@lsp.type.decorator"] = plt.moonBright,

      ["@lsp.type.builtinType"] = plt.dustLightest,
      ["@lsp.type.selfParameter"] = plt.moonCore,
      ["@lsp.type.typeParameter"] = plt.dustLightest,

      ["@lsp.type.array"] = plt.dustLightest,
      ["@lsp.type.object"] = plt.dustLightest,
      ["@lsp.type.key"] = plt.moonCore,
      ["@lsp.type.null"] = plt.dustLightest,
      ["@lsp.type.enumConstant"] = plt.dustLightest,

      ["@lsp.type.event"] = plt.dustLightest,
      ["@lsp.type.regexp"] = plt.dustMid,
      ["@lsp.type.unresolvedReference"] = plt.lampBright,

      ["@lsp.mod.deprecated"] = { fg = plt.dustMid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.dustLightest,
      ["@lsp.mod.async"] = plt.moonCore,
      ["@lsp.mod.static"] = plt.dustLightest,
      ["@lsp.mod.abstract"] = plt.dustLightest,
      ["@lsp.mod.defaultLibrary"] = plt.dustLightest,
      ["@lsp.mod.documentation"] = plt.dustBright,
    },
  }
end

return {
  name = "Detox: Moth",
  author = "PrismPunk.nvim",
  description = "Nocturnal pale blues. Moonlit silvers. Soft lamplight warmth. Night-adapted focus. Gentle darkness.",

  base16 = {
    base00 = palette.nightVoid,
    base01 = palette.nightDark,
    base02 = palette.nightDeep,
    base03 = palette.nightMid,
    base04 = palette.dustBright,
    base05 = palette.dustLightest,
    base06 = palette.moonCore,
    base07 = palette.moonBright,
    base08 = palette.lampBright,
    base09 = palette.lampMid,
    base0A = palette.lampDeep,
    base0B = palette.dustLighter,
    base0C = palette.lampPulse,
    base0D = palette.dustMid,
    base0E = palette.lampPulse,
    base0F = palette.dustMid,
  },

  palette = palette,
  get = M.get,
}
