local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.mute")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.muteBright,
      insert = plt.muteLighter,
      visual = plt.hushPulse,
      replace = plt.muteMid,
      command = plt.whisperCore,
    },

    ui = {
      fg = plt.whisperCore,
      fg_dim = plt.whisperCore,
      fg_dimmer = plt.muteLighter,
      fg_dark = plt.muteMid,
      fg_reverse = plt.quietVoid,

      bg_m4 = plt.quietLight,
      bg_m3 = plt.quietMid,
      bg_m2 = plt.quietDeep,
      bg_m1 = plt.quietDark,
      bg_dim = plt.quietVoid,
      bg = plt.quietVoid,
      bg_p1 = plt.quietDeep,
      bg_p2 = plt.quietMid,
      bg_gutter = opts.gutter and plt.quietMid or "none",
      bg_cursorline = plt.dampLine,
      bg_cursorline_alt = plt.dampMid,
      bg_search = plt.hushPulse,
      bg_visual = plt.hushDeep,
      bg_statusline = plt.dampMid,

      border = plt.muteMid,
      header1 = plt.whisperBright,
      header2 = plt.whisperCore,
      special = plt.hushBright,
      nontext = plt.quietLight,
      whitespace = plt.quietMid,
      win_separator = plt.muteMid,
      indent = plt.quietMid,
      indent_scope = plt.muteDeep,
      picker = plt.muteMid,
      yank = plt.hushPulse,
      mark = plt.hushBright,
      scrollbar = plt.quietLight,

      tabline = {
        bg = plt.quietVoid,
        fg_selected = plt.whisperCore,
        bg_selected = plt.dampMid,
        fg_inactive = plt.muteLighter,
        bg_inactive = plt.quietVoid,
        fg_alternate = plt.muteBright,
        bg_alternate = plt.quietVoid,
        indicator = plt.hushPulse,
      },

      pmenu = {
        fg = plt.whisperCore,
        fg_sel = "none",
        fg_border = plt.dampMid,
        bg_border = plt.dampMid,
        bg = plt.dampMid,
        bg_sel = plt.dampDeep,
        bg_sbar = plt.dampMid,
        bg_thumb = plt.muteMid,
      },

      float = {
        fg = plt.whisperCore,
        bg = plt.quietDeep,
        fg_border = plt.dampMid,
        bg_border = plt.quietDeep,
      },
    },

    accent = {
      accent1 = plt.whisperBright,
      accent2 = plt.whisperCore,
      accent3 = plt.muteLighter,
      accent4 = plt.muteBright,
      accent5 = plt.hushPulse,
      invert = plt.dampMid,
    },

    rainbow = {
      rainbow1 = plt.muteBright,
      rainbow2 = plt.muteMid,
      rainbow3 = plt.muteDeep,
      rainbow4 = plt.dampDeep,
      rainbow5 = plt.whisperCore,
      rainbow6 = plt.whisperBright,
      rainbow7 = plt.hushPulse,
    },

    syn = {
      attribute = plt.whisperCore,
      boolean = plt.hushBright,
      comment = plt.muteBright,
      constant = plt.muteLightest,
      deprecated = plt.muteMid,
      func = plt.whisperBright,
      identifier = plt.whisperCore,
      keyword = plt.whisperCore,
      method = plt.whisperBright,
      number = plt.muteLightest,
      operator = plt.muteMid,
      parameter = plt.muteLighter,
      preproc = plt.hushMid,
      punct = plt.muteDeep,
      regex = plt.muteMid,
      statement = plt.whisperCore,
      string = plt.muteLighter,
      symbol = plt.whisperCore,
      type = plt.muteLightest,
      variable = plt.whisperCore,
      special = plt.hushPulse,
      special2 = plt.hushMid,
      special3 = plt.hushBright,
    },

    vcs = { added = plt.muteLighter, removed = plt.hushBright, changed = plt.hushDeep },
    diff = { add = plt.muteLighter, change = plt.muteDeep, delete = plt.hushBright, text = plt.hushMid },
    diag = {
      ok = plt.muteLighter,
      error = plt.hushBright,
      warning = plt.hushPulse,
      info = plt.whisperCore,
      hint = plt.muteMid,
    },

    term = {
      black = plt.quietVoid,
      red = plt.hushBright,
      green = plt.muteBright,
      yellow = plt.muteLightest,
      blue = plt.quietVoid,
      magenta = plt.whisperCore,
      cyan = plt.muteMid,
      white = plt.whisperBright,

      black_bright = color(plt.quietVoid):brighten(0.4):to_hex(),
      red_bright = plt.hushPulse,
      green_bright = color(plt.muteBright):brighten(0.3):to_hex(),
      yellow_bright = plt.whisperBright,
      blue_bright = color(plt.quietVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.whisperCore):brighten(0.4):to_hex(),
      cyan_bright = color(plt.muteMid):brighten(0.3):to_hex(),
      white_bright = plt.whisperBright,
      indexed1 = plt.muteLighter,
      indexed2 = plt.muteBright,
    },

    treesitter = {
      ["@comment"] = plt.muteBright,
      ["@comment.documentation"] = plt.muteMid,
      ["@comment.error"] = plt.hushBright,
      ["@comment.warning"] = plt.hushPulse,
      ["@comment.todo"] = plt.muteLighter,
      ["@comment.note"] = plt.muteMid,

      ["@constant"] = plt.muteLightest,
      ["@constant.builtin"] = plt.muteLightest,
      ["@constant.macro"] = plt.hushMid,

      ["@string"] = plt.muteLighter,
      ["@string.documentation"] = plt.muteLighter,
      ["@string.regex"] = plt.muteMid,
      ["@string.escape"] = plt.hushMid,
      ["@string.special"] = plt.hushBright,
      ["@string.special.symbol"] = plt.hushBright,
      ["@string.special.url"] = plt.muteMid,
      ["@string.special.path"] = plt.muteLighter,

      ["@character"] = plt.muteLighter,
      ["@character.special"] = plt.hushMid,

      ["@number"] = plt.muteLightest,
      ["@number.float"] = plt.muteLightest,

      ["@boolean"] = plt.hushBright,

      ["@function"] = plt.whisperBright,
      ["@function.builtin"] = plt.whisperBright,
      ["@function.call"] = plt.whisperBright,
      ["@function.macro"] = plt.hushMid,
      ["@function.method"] = plt.whisperBright,
      ["@function.method.call"] = plt.whisperBright,

      ["@constructor"] = plt.whisperCore,

      ["@parameter"] = plt.muteLighter,
      ["@parameter.builtin"] = plt.muteLightest,

      ["@keyword"] = plt.whisperCore,
      ["@keyword.coroutine"] = plt.hushBright,
      ["@keyword.function"] = plt.whisperCore,
      ["@keyword.operator"] = plt.muteMid,
      ["@keyword.return"] = plt.whisperCore,
      ["@keyword.import"] = plt.muteLightest,
      ["@keyword.storage"] = plt.whisperCore,
      ["@keyword.repeat"] = plt.whisperCore,
      ["@keyword.conditional"] = plt.whisperCore,
      ["@keyword.exception"] = plt.hushBright,
      ["@keyword.directive"] = plt.hushMid,
      ["@keyword.directive.define"] = plt.hushMid,

      ["@conditional"] = plt.whisperCore,
      ["@conditional.ternary"] = plt.whisperCore,

      ["@repeat"] = plt.whisperCore,

      ["@label"] = plt.muteLightest,

      ["@operator"] = plt.muteMid,

      ["@exception"] = plt.hushBright,

      ["@variable"] = plt.whisperCore,
      ["@variable.builtin"] = plt.muteLightest,
      ["@variable.parameter"] = plt.muteLighter,
      ["@variable.member"] = plt.whisperCore,

      ["@type"] = plt.muteLightest,
      ["@type.builtin"] = plt.muteLightest,
      ["@type.definition"] = plt.muteLightest,
      ["@type.qualifier"] = plt.whisperCore,

      ["@attribute"] = plt.whisperCore,
      ["@attribute.builtin"] = plt.muteLightest,

      ["@property"] = plt.whisperCore,
      ["@field"] = plt.whisperCore,

      ["@module"] = plt.whisperCore,
      ["@module.builtin"] = plt.whisperCore,

      ["@namespace"] = plt.whisperCore,
      ["@namespace.builtin"] = plt.whisperCore,

      ["@punctuation.delimiter"] = plt.muteMid,
      ["@punctuation.bracket"] = plt.muteMid,
      ["@punctuation.special"] = plt.hushMid,

      ["@tag"] = plt.whisperCore,
      ["@tag.attribute"] = plt.muteLightest,
      ["@tag.delimiter"] = plt.muteMid,
      ["@tag.builtin"] = plt.whisperCore,

      ["@markup.strong"] = { fg = plt.whisperBright, bold = true },
      ["@markup.italic"] = { fg = plt.whisperCore, italic = true },
      ["@markup.strikethrough"] = { fg = plt.muteMid, strikethrough = true },
      ["@markup.underline"] = { fg = plt.whisperCore, underline = true },
      ["@markup.heading"] = plt.whisperBright,
      ["@markup.heading.1"] = plt.whisperBright,
      ["@markup.heading.2"] = plt.whisperCore,
      ["@markup.heading.3"] = plt.muteLightest,
      ["@markup.heading.4"] = plt.muteLighter,
      ["@markup.heading.5"] = plt.hushMid,
      ["@markup.heading.6"] = plt.hushPulse,
      ["@markup.quote"] = plt.muteBright,
      ["@markup.math"] = plt.muteLightest,
      ["@markup.link"] = plt.muteMid,
      ["@markup.link.label"] = plt.hushPulse,
      ["@markup.link.url"] = plt.muteMid,
      ["@markup.raw"] = plt.muteLighter,
      ["@markup.raw.block"] = plt.muteLighter,
      ["@markup.list"] = plt.whisperCore,
      ["@markup.list.checked"] = plt.muteLighter,
      ["@markup.list.unchecked"] = plt.muteBright,

      ["@diff.plus"] = plt.muteLighter,
      ["@diff.minus"] = plt.hushBright,
      ["@diff.delta"] = plt.muteMid,

      ["@none"] = "none",
      ["@conceal"] = plt.muteMid,
      ["@spell"] = plt.whisperCore,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.whisperCore,
      ["@constructor.python"] = plt.whisperBright,
      ["@constructor.javascript"] = plt.whisperBright,
      ["@constructor.typescript"] = plt.whisperBright,
      ["@namespace.rust"] = plt.whisperCore,
      ["@type.qualifier.rust"] = plt.whisperCore,
      ["@constant.macro.c"] = plt.hushMid,
      ["@constant.macro.cpp"] = plt.hushMid,
      ["@namespace.go"] = plt.whisperCore,
      ["@property.css"] = plt.whisperBright,
      ["@type.css"] = plt.whisperCore,
      ["@label.json"] = plt.whisperCore,
      ["@field.yaml"] = plt.whisperCore,
      ["@property.toml"] = plt.whisperCore,
      ["@function.builtin.bash"] = plt.whisperBright,
      ["@string.regexp"] = plt.muteMid,
      ["@character.special.regex"] = plt.hushMid,
    },

    lsp = {
      ["@lsp.type.class"] = plt.muteLightest,
      ["@lsp.type.interface"] = plt.muteLightest,
      ["@lsp.type.struct"] = plt.muteLightest,
      ["@lsp.type.enum"] = plt.muteLightest,
      ["@lsp.type.enumMember"] = plt.muteLightest,
      ["@lsp.type.property"] = plt.whisperCore,
      ["@lsp.type.namespace"] = plt.whisperCore,

      ["@lsp.type.macro"] = plt.hushMid,
      ["@lsp.type.decorator"] = plt.whisperBright,

      ["@lsp.type.builtinType"] = plt.muteLightest,
      ["@lsp.type.selfParameter"] = plt.whisperCore,
      ["@lsp.type.typeParameter"] = plt.muteLightest,

      ["@lsp.type.array"] = plt.muteLightest,
      ["@lsp.type.object"] = plt.muteLightest,
      ["@lsp.type.key"] = plt.whisperCore,
      ["@lsp.type.null"] = plt.muteLightest,
      ["@lsp.type.enumConstant"] = plt.muteLightest,

      ["@lsp.type.event"] = plt.muteLightest,
      ["@lsp.type.regexp"] = plt.muteMid,
      ["@lsp.type.unresolvedReference"] = plt.hushBright,

      ["@lsp.mod.deprecated"] = { fg = plt.muteMid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.muteLightest,
      ["@lsp.mod.async"] = plt.whisperCore,
      ["@lsp.mod.static"] = plt.muteLightest,
      ["@lsp.mod.abstract"] = plt.muteLightest,
      ["@lsp.mod.defaultLibrary"] = plt.muteLightest,
      ["@lsp.mod.documentation"] = plt.muteBright,
    },
  }
end

return {
  name = "Detox: Mute",
  author = "PrismPunk.nvim",
  description = "Soundless silence. Barely-distinguishable grays. Single whispered accent. Extreme minimalism.",

  base16 = {
    base00 = palette.quietVoid,
    base01 = palette.quietDark,
    base02 = palette.quietDeep,
    base03 = palette.quietMid,
    base04 = palette.muteBright,
    base05 = palette.muteLightest,
    base06 = palette.whisperCore,
    base07 = palette.whisperBright,
    base08 = palette.hushBright,
    base09 = palette.hushMid,
    base0A = palette.hushDeep,
    base0B = palette.muteLighter,
    base0C = palette.hushPulse,
    base0D = palette.muteMid,
    base0E = palette.hushPulse,
    base0F = palette.muteMid,
  },

  palette = palette,
  get = M.get,
}
