local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.paper")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.sheetBright,
      insert = plt.sheetLighter,
      visual = plt.inkPulse,
      replace = plt.sheetMid,
      command = plt.pageCore,
    },

    ui = {
      fg = plt.pageCore,
      fg_dim = plt.pageCore,
      fg_dimmer = plt.sheetLighter,
      fg_dark = plt.sheetMid,
      fg_reverse = plt.paperVoid,

      bg_m4 = plt.paperLight,
      bg_m3 = plt.paperMid,
      bg_m2 = plt.paperDeep,
      bg_m1 = plt.paperDark,
      bg_dim = plt.paperVoid,
      bg = plt.paperVoid,
      bg_p1 = plt.paperDeep,
      bg_p2 = plt.paperMid,
      bg_gutter = opts.gutter and plt.paperMid or "none",
      bg_cursorline = plt.pulpLine,
      bg_cursorline_alt = plt.pulpMid,
      bg_search = plt.inkPulse,
      bg_visual = plt.inkDeep,
      bg_statusline = plt.pulpMid,

      border = plt.sheetMid,
      header1 = plt.pageBright,
      header2 = plt.pageCore,
      special = plt.inkBright,
      nontext = plt.paperLight,
      whitespace = plt.paperMid,
      win_separator = plt.sheetMid,
      indent = plt.paperMid,
      indent_scope = plt.sheetDeep,
      picker = plt.sheetMid,
      yank = plt.inkPulse,
      mark = plt.inkBright,
      scrollbar = plt.paperLight,

      tabline = {
        bg = plt.paperVoid,
        fg_selected = plt.pageCore,
        bg_selected = plt.pulpMid,
        fg_inactive = plt.sheetLighter,
        bg_inactive = plt.paperVoid,
        fg_alternate = plt.sheetBright,
        bg_alternate = plt.paperVoid,
        indicator = plt.inkPulse,
      },

      pmenu = {
        fg = plt.pageCore,
        fg_sel = "none",
        fg_border = plt.pulpMid,
        bg_border = plt.pulpMid,
        bg = plt.pulpMid,
        bg_sel = plt.pulpDeep,
        bg_sbar = plt.pulpMid,
        bg_thumb = plt.sheetMid,
      },

      float = {
        fg = plt.pageCore,
        bg = plt.paperDeep,
        fg_border = plt.pulpMid,
        bg_border = plt.paperDeep,
      },
    },

    accent = {
      accent1 = plt.pageBright,
      accent2 = plt.pageCore,
      accent3 = plt.sheetLighter,
      accent4 = plt.sheetBright,
      accent5 = plt.inkPulse,
      invert = plt.pulpMid,
    },

    rainbow = {
      rainbow1 = plt.sheetBright,
      rainbow2 = plt.sheetMid,
      rainbow3 = plt.sheetDeep,
      rainbow4 = plt.pulpDeep,
      rainbow5 = plt.pageCore,
      rainbow6 = plt.pageBright,
      rainbow7 = plt.inkPulse,
    },

    syn = {
      attribute = plt.pageCore,
      boolean = plt.inkBright,
      comment = plt.sheetBright,
      constant = plt.sheetLightest,
      deprecated = plt.sheetMid,
      func = plt.pageBright,
      identifier = plt.pageCore,
      keyword = plt.pageCore,
      method = plt.pageBright,
      number = plt.sheetLightest,
      operator = plt.sheetMid,
      parameter = plt.sheetLighter,
      preproc = plt.inkMid,
      punct = plt.sheetDeep,
      regex = plt.sheetMid,
      statement = plt.pageCore,
      string = plt.sheetLighter,
      symbol = plt.pageCore,
      type = plt.sheetLightest,
      variable = plt.pageCore,
      special = plt.inkPulse,
      special2 = plt.inkMid,
      special3 = plt.inkBright,
    },

    vcs = { added = plt.sheetLighter, removed = plt.inkBright, changed = plt.inkDeep },
    diff = { add = plt.sheetLighter, change = plt.sheetDeep, delete = plt.inkBright, text = plt.inkMid },
    diag = {
      ok = plt.sheetLighter,
      error = plt.inkBright,
      warning = plt.inkPulse,
      info = plt.pageCore,
      hint = plt.sheetMid,
    },

    term = {
      black = plt.paperVoid,
      red = plt.inkBright,
      green = plt.sheetBright,
      yellow = plt.sheetLightest,
      blue = plt.paperVoid,
      magenta = plt.pageCore,
      cyan = plt.sheetMid,
      white = plt.pageBright,

      black_bright = color(plt.paperVoid):brighten(0.4):to_hex(),
      red_bright = plt.inkPulse,
      green_bright = color(plt.sheetBright):brighten(0.3):to_hex(),
      yellow_bright = plt.pageBright,
      blue_bright = color(plt.paperVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.pageCore):brighten(0.4):to_hex(),
      cyan_bright = color(plt.sheetMid):brighten(0.3):to_hex(),
      white_bright = plt.pageBright,
      indexed1 = plt.sheetLighter,
      indexed2 = plt.sheetBright,
    },

    treesitter = {
      ["@comment"] = plt.sheetBright,
      ["@comment.documentation"] = plt.sheetMid,
      ["@comment.error"] = plt.inkBright,
      ["@comment.warning"] = plt.inkPulse,
      ["@comment.todo"] = plt.sheetLighter,
      ["@comment.note"] = plt.sheetMid,

      ["@constant"] = plt.sheetLightest,
      ["@constant.builtin"] = plt.sheetLightest,
      ["@constant.macro"] = plt.inkMid,

      ["@string"] = plt.sheetLighter,
      ["@string.documentation"] = plt.sheetLighter,
      ["@string.regex"] = plt.sheetMid,
      ["@string.escape"] = plt.inkMid,
      ["@string.special"] = plt.inkBright,
      ["@string.special.symbol"] = plt.inkBright,
      ["@string.special.url"] = plt.sheetMid,
      ["@string.special.path"] = plt.sheetLighter,

      ["@character"] = plt.sheetLighter,
      ["@character.special"] = plt.inkMid,

      ["@number"] = plt.sheetLightest,
      ["@number.float"] = plt.sheetLightest,

      ["@boolean"] = plt.inkBright,

      ["@function"] = plt.pageBright,
      ["@function.builtin"] = plt.pageBright,
      ["@function.call"] = plt.pageBright,
      ["@function.macro"] = plt.inkMid,
      ["@function.method"] = plt.pageBright,
      ["@function.method.call"] = plt.pageBright,

      ["@constructor"] = plt.pageCore,

      ["@parameter"] = plt.sheetLighter,
      ["@parameter.builtin"] = plt.sheetLightest,

      ["@keyword"] = plt.pageCore,
      ["@keyword.coroutine"] = plt.inkBright,
      ["@keyword.function"] = plt.pageCore,
      ["@keyword.operator"] = plt.sheetMid,
      ["@keyword.return"] = plt.pageCore,
      ["@keyword.import"] = plt.sheetLightest,
      ["@keyword.storage"] = plt.pageCore,
      ["@keyword.repeat"] = plt.pageCore,
      ["@keyword.conditional"] = plt.pageCore,
      ["@keyword.exception"] = plt.inkBright,
      ["@keyword.directive"] = plt.inkMid,
      ["@keyword.directive.define"] = plt.inkMid,

      ["@conditional"] = plt.pageCore,
      ["@conditional.ternary"] = plt.pageCore,

      ["@repeat"] = plt.pageCore,

      ["@label"] = plt.sheetLightest,

      ["@operator"] = plt.sheetMid,

      ["@exception"] = plt.inkBright,

      ["@variable"] = plt.pageCore,
      ["@variable.builtin"] = plt.sheetLightest,
      ["@variable.parameter"] = plt.sheetLighter,
      ["@variable.member"] = plt.pageCore,

      ["@type"] = plt.sheetLightest,
      ["@type.builtin"] = plt.sheetLightest,
      ["@type.definition"] = plt.sheetLightest,
      ["@type.qualifier"] = plt.pageCore,

      ["@attribute"] = plt.pageCore,
      ["@attribute.builtin"] = plt.sheetLightest,

      ["@property"] = plt.pageCore,
      ["@field"] = plt.pageCore,

      ["@module"] = plt.pageCore,
      ["@module.builtin"] = plt.pageCore,

      ["@namespace"] = plt.pageCore,
      ["@namespace.builtin"] = plt.pageCore,

      ["@punctuation.delimiter"] = plt.sheetMid,
      ["@punctuation.bracket"] = plt.sheetMid,
      ["@punctuation.special"] = plt.inkMid,

      ["@tag"] = plt.pageCore,
      ["@tag.attribute"] = plt.sheetLightest,
      ["@tag.delimiter"] = plt.sheetMid,
      ["@tag.builtin"] = plt.pageCore,

      ["@markup.strong"] = { fg = plt.pageBright, bold = true },
      ["@markup.italic"] = { fg = plt.pageCore, italic = true },
      ["@markup.strikethrough"] = { fg = plt.sheetMid, strikethrough = true },
      ["@markup.underline"] = { fg = plt.pageCore, underline = true },
      ["@markup.heading"] = plt.pageBright,
      ["@markup.heading.1"] = plt.pageBright,
      ["@markup.heading.2"] = plt.pageCore,
      ["@markup.heading.3"] = plt.sheetLightest,
      ["@markup.heading.4"] = plt.sheetLighter,
      ["@markup.heading.5"] = plt.inkMid,
      ["@markup.heading.6"] = plt.inkPulse,
      ["@markup.quote"] = plt.sheetBright,
      ["@markup.math"] = plt.sheetLightest,
      ["@markup.link"] = plt.sheetMid,
      ["@markup.link.label"] = plt.inkPulse,
      ["@markup.link.url"] = plt.sheetMid,
      ["@markup.raw"] = plt.sheetLighter,
      ["@markup.raw.block"] = plt.sheetLighter,
      ["@markup.list"] = plt.pageCore,
      ["@markup.list.checked"] = plt.sheetLighter,
      ["@markup.list.unchecked"] = plt.sheetBright,

      ["@diff.plus"] = plt.sheetLighter,
      ["@diff.minus"] = plt.inkBright,
      ["@diff.delta"] = plt.sheetMid,

      ["@none"] = "none",
      ["@conceal"] = plt.sheetMid,
      ["@spell"] = plt.pageCore,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.pageCore,
      ["@constructor.python"] = plt.pageBright,
      ["@constructor.javascript"] = plt.pageBright,
      ["@constructor.typescript"] = plt.pageBright,
      ["@namespace.rust"] = plt.pageCore,
      ["@type.qualifier.rust"] = plt.pageCore,
      ["@constant.macro.c"] = plt.inkMid,
      ["@constant.macro.cpp"] = plt.inkMid,
      ["@namespace.go"] = plt.pageCore,
      ["@property.css"] = plt.pageBright,
      ["@type.css"] = plt.pageCore,
      ["@label.json"] = plt.pageCore,
      ["@field.yaml"] = plt.pageCore,
      ["@property.toml"] = plt.pageCore,
      ["@function.builtin.bash"] = plt.pageBright,
      ["@string.regexp"] = plt.sheetMid,
      ["@character.special.regex"] = plt.inkMid,
    },

    lsp = {
      ["@lsp.type.class"] = plt.sheetLightest,
      ["@lsp.type.interface"] = plt.sheetLightest,
      ["@lsp.type.struct"] = plt.sheetLightest,
      ["@lsp.type.enum"] = plt.sheetLightest,
      ["@lsp.type.enumMember"] = plt.sheetLightest,
      ["@lsp.type.property"] = plt.pageCore,
      ["@lsp.type.namespace"] = plt.pageCore,

      ["@lsp.type.macro"] = plt.inkMid,
      ["@lsp.type.decorator"] = plt.pageBright,

      ["@lsp.type.builtinType"] = plt.sheetLightest,
      ["@lsp.type.selfParameter"] = plt.pageCore,
      ["@lsp.type.typeParameter"] = plt.sheetLightest,

      ["@lsp.type.array"] = plt.sheetLightest,
      ["@lsp.type.object"] = plt.sheetLightest,
      ["@lsp.type.key"] = plt.pageCore,
      ["@lsp.type.null"] = plt.sheetLightest,
      ["@lsp.type.enumConstant"] = plt.sheetLightest,

      ["@lsp.type.event"] = plt.sheetLightest,
      ["@lsp.type.regexp"] = plt.sheetMid,
      ["@lsp.type.unresolvedReference"] = plt.inkBright,

      ["@lsp.mod.deprecated"] = { fg = plt.sheetMid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.sheetLightest,
      ["@lsp.mod.async"] = plt.pageCore,
      ["@lsp.mod.static"] = plt.sheetLightest,
      ["@lsp.mod.abstract"] = plt.sheetLightest,
      ["@lsp.mod.defaultLibrary"] = plt.sheetLightest,
      ["@lsp.mod.documentation"] = plt.sheetBright,
    },
  }
end

return {
  name = "Detox: Paper",
  author = "PrismPunk.nvim",
  description = "Aged pulp sheets. Cellulose fiber texture. Ink stain marks. Handmade documentation.",

  base16 = {
    base00 = palette.paperVoid,
    base01 = palette.paperDark,
    base02 = palette.paperDeep,
    base03 = palette.paperMid,
    base04 = palette.sheetBright,
    base05 = palette.sheetLightest,
    base06 = palette.pageCore,
    base07 = palette.pageBright,
    base08 = palette.inkBright,
    base09 = palette.inkMid,
    base0A = palette.inkDeep,
    base0B = palette.sheetLighter,
    base0C = palette.inkPulse,
    base0D = palette.sheetMid,
    base0E = palette.inkPulse,
    base0F = palette.sheetMid,
  },

  palette = palette,
  get = M.get,
}
