local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.plaster")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.crackBright,
      insert = plt.crackLighter,
      visual = plt.stainPulse,
      replace = plt.crackMid,
      command = plt.dustCore,
    },

    ui = {
      fg = plt.dustCore,
      fg_dim = plt.dustCore,
      fg_dimmer = plt.crackLighter,
      fg_dark = plt.crackMid,
      fg_reverse = plt.plasterVoid,

      bg_m4 = plt.plasterLight,
      bg_m3 = plt.plasterMid,
      bg_m2 = plt.plasterDeep,
      bg_m1 = plt.plasterDark,
      bg_dim = plt.plasterVoid,
      bg = plt.plasterVoid,
      bg_p1 = plt.plasterDeep,
      bg_p2 = plt.plasterMid,
      bg_gutter = opts.gutter and plt.plasterMid or "none",
      bg_cursorline = plt.paintLine,
      bg_cursorline_alt = plt.paintMid,
      bg_search = plt.stainPulse,
      bg_visual = plt.stainDeep,
      bg_statusline = plt.paintMid,

      border = plt.crackMid,
      header1 = plt.dustBright,
      header2 = plt.dustCore,
      special = plt.stainBright,
      nontext = plt.plasterLight,
      whitespace = plt.plasterMid,
      win_separator = plt.crackMid,
      indent = plt.plasterMid,
      indent_scope = plt.crackDeep,
      picker = plt.crackMid,
      yank = plt.stainPulse,
      mark = plt.stainBright,
      scrollbar = plt.plasterLight,

      tabline = {
        bg = plt.plasterVoid,
        fg_selected = plt.dustCore,
        bg_selected = plt.paintMid,
        fg_inactive = plt.crackLighter,
        bg_inactive = plt.plasterVoid,
        fg_alternate = plt.crackBright,
        bg_alternate = plt.plasterVoid,
        indicator = plt.stainPulse,
      },

      pmenu = {
        fg = plt.dustCore,
        fg_sel = "none",
        fg_border = plt.paintMid,
        bg_border = plt.paintMid,
        bg = plt.paintMid,
        bg_sel = plt.paintDeep,
        bg_sbar = plt.paintMid,
        bg_thumb = plt.crackMid,
      },

      float = {
        fg = plt.dustCore,
        bg = plt.plasterDeep,
        fg_border = plt.paintMid,
        bg_border = plt.plasterDeep,
      },
    },

    accent = {
      accent1 = plt.dustBright,
      accent2 = plt.dustCore,
      accent3 = plt.crackLighter,
      accent4 = plt.crackBright,
      accent5 = plt.stainPulse,
      invert = plt.paintMid,
    },

    rainbow = {
      rainbow1 = plt.crackBright,
      rainbow2 = plt.crackMid,
      rainbow3 = plt.crackDeep,
      rainbow4 = plt.paintDeep,
      rainbow5 = plt.dustCore,
      rainbow6 = plt.dustBright,
      rainbow7 = plt.stainPulse,
    },

    syn = {
      attribute = plt.dustCore,
      boolean = plt.stainBright,
      comment = plt.crackBright,
      constant = plt.crackLightest,
      deprecated = plt.crackMid,
      func = plt.dustBright,
      identifier = plt.dustCore,
      keyword = plt.dustCore,
      method = plt.dustBright,
      number = plt.crackLightest,
      operator = plt.crackMid,
      parameter = plt.crackLighter,
      preproc = plt.stainMid,
      punct = plt.crackDeep,
      regex = plt.crackMid,
      statement = plt.dustCore,
      string = plt.crackLighter,
      symbol = plt.dustCore,
      type = plt.crackLightest,
      variable = plt.dustCore,
      special = plt.stainPulse,
      special2 = plt.stainMid,
      special3 = plt.stainBright,
    },

    vcs = { added = plt.crackLighter, removed = plt.stainBright, changed = plt.stainDeep },
    diff = { add = plt.crackLighter, change = plt.crackDeep, delete = plt.stainBright, text = plt.stainMid },
    diag = {
      ok = plt.crackLighter,
      error = plt.stainBright,
      warning = plt.stainPulse,
      info = plt.dustCore,
      hint = plt.crackMid,
    },

    term = {
      black = plt.plasterVoid,
      red = plt.stainBright,
      green = plt.crackBright,
      yellow = plt.crackLightest,
      blue = plt.plasterVoid,
      magenta = plt.dustCore,
      cyan = plt.crackMid,
      white = plt.dustBright,

      black_bright = color(plt.plasterVoid):brighten(0.4):to_hex(),
      red_bright = plt.stainPulse,
      green_bright = color(plt.crackBright):brighten(0.3):to_hex(),
      yellow_bright = plt.dustBright,
      blue_bright = color(plt.plasterVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.dustCore):brighten(0.4):to_hex(),
      cyan_bright = color(plt.crackMid):brighten(0.3):to_hex(),
      white_bright = plt.dustBright,
      indexed1 = plt.crackLighter,
      indexed2 = plt.crackBright,
    },

    treesitter = {
      ["@comment"] = plt.crackBright,
      ["@comment.documentation"] = plt.crackMid,
      ["@comment.error"] = plt.stainBright,
      ["@comment.warning"] = plt.stainPulse,
      ["@comment.todo"] = plt.crackLighter,
      ["@comment.note"] = plt.crackMid,

      ["@constant"] = plt.crackLightest,
      ["@constant.builtin"] = plt.crackLightest,
      ["@constant.macro"] = plt.stainMid,

      ["@string"] = plt.crackLighter,
      ["@string.documentation"] = plt.crackLighter,
      ["@string.regex"] = plt.crackMid,
      ["@string.escape"] = plt.stainMid,
      ["@string.special"] = plt.stainBright,
      ["@string.special.symbol"] = plt.stainBright,
      ["@string.special.url"] = plt.crackMid,
      ["@string.special.path"] = plt.crackLighter,

      ["@character"] = plt.crackLighter,
      ["@character.special"] = plt.stainMid,

      ["@number"] = plt.crackLightest,
      ["@number.float"] = plt.crackLightest,

      ["@boolean"] = plt.stainBright,

      ["@function"] = plt.dustBright,
      ["@function.builtin"] = plt.dustBright,
      ["@function.call"] = plt.dustBright,
      ["@function.macro"] = plt.stainMid,
      ["@function.method"] = plt.dustBright,
      ["@function.method.call"] = plt.dustBright,

      ["@constructor"] = plt.dustCore,

      ["@parameter"] = plt.crackLighter,
      ["@parameter.builtin"] = plt.crackLightest,

      ["@keyword"] = plt.dustCore,
      ["@keyword.coroutine"] = plt.stainBright,
      ["@keyword.function"] = plt.dustCore,
      ["@keyword.operator"] = plt.crackMid,
      ["@keyword.return"] = plt.dustCore,
      ["@keyword.import"] = plt.crackLightest,
      ["@keyword.storage"] = plt.dustCore,
      ["@keyword.repeat"] = plt.dustCore,
      ["@keyword.conditional"] = plt.dustCore,
      ["@keyword.exception"] = plt.stainBright,
      ["@keyword.directive"] = plt.stainMid,
      ["@keyword.directive.define"] = plt.stainMid,

      ["@conditional"] = plt.dustCore,
      ["@conditional.ternary"] = plt.dustCore,

      ["@repeat"] = plt.dustCore,

      ["@label"] = plt.crackLightest,

      ["@operator"] = plt.crackMid,

      ["@exception"] = plt.stainBright,

      ["@variable"] = plt.dustCore,
      ["@variable.builtin"] = plt.crackLightest,
      ["@variable.parameter"] = plt.crackLighter,
      ["@variable.member"] = plt.dustCore,

      ["@type"] = plt.crackLightest,
      ["@type.builtin"] = plt.crackLightest,
      ["@type.definition"] = plt.crackLightest,
      ["@type.qualifier"] = plt.dustCore,

      ["@attribute"] = plt.dustCore,
      ["@attribute.builtin"] = plt.crackLightest,

      ["@property"] = plt.dustCore,
      ["@field"] = plt.dustCore,

      ["@module"] = plt.dustCore,
      ["@module.builtin"] = plt.dustCore,

      ["@namespace"] = plt.dustCore,
      ["@namespace.builtin"] = plt.dustCore,

      ["@punctuation.delimiter"] = plt.crackMid,
      ["@punctuation.bracket"] = plt.crackMid,
      ["@punctuation.special"] = plt.stainMid,

      ["@tag"] = plt.dustCore,
      ["@tag.attribute"] = plt.crackLightest,
      ["@tag.delimiter"] = plt.crackMid,
      ["@tag.builtin"] = plt.dustCore,

      ["@markup.strong"] = { fg = plt.dustBright, bold = true },
      ["@markup.italic"] = { fg = plt.dustCore, italic = true },
      ["@markup.strikethrough"] = { fg = plt.crackMid, strikethrough = true },
      ["@markup.underline"] = { fg = plt.dustCore, underline = true },
      ["@markup.heading"] = plt.dustBright,
      ["@markup.heading.1"] = plt.dustBright,
      ["@markup.heading.2"] = plt.dustCore,
      ["@markup.heading.3"] = plt.crackLightest,
      ["@markup.heading.4"] = plt.crackLighter,
      ["@markup.heading.5"] = plt.stainMid,
      ["@markup.heading.6"] = plt.stainPulse,
      ["@markup.quote"] = plt.crackBright,
      ["@markup.math"] = plt.crackLightest,
      ["@markup.link"] = plt.crackMid,
      ["@markup.link.label"] = plt.stainPulse,
      ["@markup.link.url"] = plt.crackMid,
      ["@markup.raw"] = plt.crackLighter,
      ["@markup.raw.block"] = plt.crackLighter,
      ["@markup.list"] = plt.dustCore,
      ["@markup.list.checked"] = plt.crackLighter,
      ["@markup.list.unchecked"] = plt.crackBright,

      ["@diff.plus"] = plt.crackLighter,
      ["@diff.minus"] = plt.stainBright,
      ["@diff.delta"] = plt.crackMid,

      ["@none"] = "none",
      ["@conceal"] = plt.crackMid,
      ["@spell"] = plt.dustCore,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.dustCore,
      ["@constructor.python"] = plt.dustBright,
      ["@constructor.javascript"] = plt.dustBright,
      ["@constructor.typescript"] = plt.dustBright,
      ["@namespace.rust"] = plt.dustCore,
      ["@type.qualifier.rust"] = plt.dustCore,
      ["@constant.macro.c"] = plt.stainMid,
      ["@constant.macro.cpp"] = plt.stainMid,
      ["@namespace.go"] = plt.dustCore,
      ["@property.css"] = plt.dustBright,
      ["@type.css"] = plt.dustCore,
      ["@label.json"] = plt.dustCore,
      ["@field.yaml"] = plt.dustCore,
      ["@property.toml"] = plt.dustCore,
      ["@function.builtin.bash"] = plt.dustBright,
      ["@string.regexp"] = plt.crackMid,
      ["@character.special.regex"] = plt.stainMid,
    },

    lsp = {
      ["@lsp.type.class"] = plt.crackLightest,
      ["@lsp.type.interface"] = plt.crackLightest,
      ["@lsp.type.struct"] = plt.crackLightest,
      ["@lsp.type.enum"] = plt.crackLightest,
      ["@lsp.type.enumMember"] = plt.crackLightest,
      ["@lsp.type.property"] = plt.dustCore,
      ["@lsp.type.namespace"] = plt.dustCore,

      ["@lsp.type.macro"] = plt.stainMid,
      ["@lsp.type.decorator"] = plt.dustBright,

      ["@lsp.type.builtinType"] = plt.crackLightest,
      ["@lsp.type.selfParameter"] = plt.dustCore,
      ["@lsp.type.typeParameter"] = plt.crackLightest,

      ["@lsp.type.array"] = plt.crackLightest,
      ["@lsp.type.object"] = plt.crackLightest,
      ["@lsp.type.key"] = plt.dustCore,
      ["@lsp.type.null"] = plt.crackLightest,
      ["@lsp.type.enumConstant"] = plt.crackLightest,

      ["@lsp.type.event"] = plt.crackLightest,
      ["@lsp.type.regexp"] = plt.crackMid,
      ["@lsp.type.unresolvedReference"] = plt.stainBright,

      ["@lsp.mod.deprecated"] = { fg = plt.crackMid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.crackLightest,
      ["@lsp.mod.async"] = plt.dustCore,
      ["@lsp.mod.static"] = plt.crackLightest,
      ["@lsp.mod.abstract"] = plt.crackLightest,
      ["@lsp.mod.defaultLibrary"] = plt.crackLightest,
      ["@lsp.mod.documentation"] = plt.crackBright,
    },
  }
end

return {
  name = "Detox: Plaster",
  author = "PrismPunk.nvim",
  description = "Crumbling faded walls. Aging architectural surfaces. Rust stain decay. Abandonment aesthetic.",

  base16 = {
    base00 = palette.plasterVoid,
    base01 = palette.plasterDark,
    base02 = palette.plasterDeep,
    base03 = palette.plasterMid,
    base04 = palette.crackBright,
    base05 = palette.crackLightest,
    base06 = palette.dustCore,
    base07 = palette.dustBright,
    base08 = palette.stainBright,
    base09 = palette.stainMid,
    base0A = palette.stainDeep,
    base0B = palette.crackLighter,
    base0C = palette.stainPulse,
    base0D = palette.crackMid,
    base0E = palette.stainPulse,
    base0F = palette.crackMid,
  },

  palette = palette,
  get = M.get,
}
