local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.sepia")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.archiveBright,
      insert = plt.archiveLighter,
      visual = plt.fadeblackPulse,
      replace = plt.archiveMid,
      command = plt.photoCore,
    },

    ui = {
      fg = plt.photoCore,
      fg_dim = plt.photoCore,
      fg_dimmer = plt.archiveLighter,
      fg_dark = plt.archiveMid,
      fg_reverse = plt.sepiaVoid,

      bg_m4 = plt.sepiaLight,
      bg_m3 = plt.sepiaMid,
      bg_m2 = plt.sepiaDeep,
      bg_m1 = plt.sepiaDark,
      bg_dim = plt.sepiaVoid,
      bg = plt.sepiaVoid,
      bg_p1 = plt.sepiaDeep,
      bg_p2 = plt.sepiaMid,
      bg_gutter = opts.gutter and plt.sepiaMid or "none",
      bg_cursorline = plt.vintageLine,
      bg_cursorline_alt = plt.vintageMid,
      bg_search = plt.fadeblackPulse,
      bg_visual = plt.fadeblackDeep,
      bg_statusline = plt.vintageMid,

      border = plt.archiveMid,
      header1 = plt.photoBright,
      header2 = plt.photoCore,
      special = plt.fadeblackBright,
      nontext = plt.sepiaLight,
      whitespace = plt.sepiaMid,
      win_separator = plt.archiveMid,
      indent = plt.sepiaMid,
      indent_scope = plt.archiveDeep,
      picker = plt.archiveMid,
      yank = plt.fadeblackPulse,
      mark = plt.fadeblackBright,
      scrollbar = plt.sepiaLight,

      tabline = {
        bg = plt.sepiaVoid,
        fg_selected = plt.photoCore,
        bg_selected = plt.vintageMid,
        fg_inactive = plt.archiveLighter,
        bg_inactive = plt.sepiaVoid,
        fg_alternate = plt.archiveBright,
        bg_alternate = plt.sepiaVoid,
        indicator = plt.fadeblackPulse,
      },

      pmenu = {
        fg = plt.photoCore,
        fg_sel = "none",
        fg_border = plt.vintageMid,
        bg_border = plt.vintageMid,
        bg = plt.vintageMid,
        bg_sel = plt.vintageDeep,
        bg_sbar = plt.vintageMid,
        bg_thumb = plt.archiveMid,
      },

      float = {
        fg = plt.photoCore,
        bg = plt.sepiaDeep,
        fg_border = plt.vintageMid,
        bg_border = plt.sepiaDeep,
      },
    },

    accent = {
      accent1 = plt.photoBright,
      accent2 = plt.photoCore,
      accent3 = plt.archiveLighter,
      accent4 = plt.archiveBright,
      accent5 = plt.fadeblackPulse,
      invert = plt.vintageMid,
    },

    rainbow = {
      rainbow1 = plt.archiveBright,
      rainbow2 = plt.archiveMid,
      rainbow3 = plt.archiveDeep,
      rainbow4 = plt.vintageDeep,
      rainbow5 = plt.photoCore,
      rainbow6 = plt.photoBright,
      rainbow7 = plt.fadeblackPulse,
    },

    syn = {
      attribute = plt.photoCore,
      boolean = plt.fadeblackBright,
      comment = plt.archiveBright,
      constant = plt.archiveLightest,
      deprecated = plt.archiveMid,
      func = plt.photoBright,
      identifier = plt.photoCore,
      keyword = plt.photoCore,
      method = plt.photoBright,
      number = plt.archiveLightest,
      operator = plt.archiveMid,
      parameter = plt.archiveLighter,
      preproc = plt.fadeblackMid,
      punct = plt.archiveDeep,
      regex = plt.archiveMid,
      statement = plt.photoCore,
      string = plt.archiveLighter,
      symbol = plt.photoCore,
      type = plt.archiveLightest,
      variable = plt.photoCore,
      special = plt.fadeblackPulse,
      special2 = plt.fadeblackMid,
      special3 = plt.fadeblackBright,
    },

    vcs = { added = plt.archiveLighter, removed = plt.fadeblackBright, changed = plt.fadeblackDeep },
    diff = {
      add = plt.archiveLighter,
      change = plt.archiveDeep,
      delete = plt.fadeblackBright,
      text = plt.fadeblackMid,
    },
    diag = {
      ok = plt.archiveLighter,
      error = plt.fadeblackBright,
      warning = plt.fadeblackPulse,
      info = plt.photoCore,
      hint = plt.archiveMid,
    },

    term = {
      black = plt.sepiaVoid,
      red = plt.fadeblackBright,
      green = plt.archiveBright,
      yellow = plt.archiveLightest,
      blue = plt.sepiaVoid,
      magenta = plt.photoCore,
      cyan = plt.archiveMid,
      white = plt.photoBright,

      black_bright = color(plt.sepiaVoid):brighten(0.4):to_hex(),
      red_bright = plt.fadeblackPulse,
      green_bright = color(plt.archiveBright):brighten(0.3):to_hex(),
      yellow_bright = plt.photoBright,
      blue_bright = color(plt.sepiaVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.photoCore):brighten(0.4):to_hex(),
      cyan_bright = color(plt.archiveMid):brighten(0.3):to_hex(),
      white_bright = plt.photoBright,
      indexed1 = plt.archiveLighter,
      indexed2 = plt.archiveBright,
    },

    treesitter = {
      ["@comment"] = plt.archiveBright,
      ["@comment.documentation"] = plt.archiveMid,
      ["@comment.error"] = plt.fadeblackBright,
      ["@comment.warning"] = plt.fadeblackPulse,
      ["@comment.todo"] = plt.archiveLighter,
      ["@comment.note"] = plt.archiveMid,

      ["@constant"] = plt.archiveLightest,
      ["@constant.builtin"] = plt.archiveLightest,
      ["@constant.macro"] = plt.fadeblackMid,

      ["@string"] = plt.archiveLighter,
      ["@string.documentation"] = plt.archiveLighter,
      ["@string.regex"] = plt.archiveMid,
      ["@string.escape"] = plt.fadeblackMid,
      ["@string.special"] = plt.fadeblackBright,
      ["@string.special.symbol"] = plt.fadeblackBright,
      ["@string.special.url"] = plt.archiveMid,
      ["@string.special.path"] = plt.archiveLighter,

      ["@character"] = plt.archiveLighter,
      ["@character.special"] = plt.fadeblackMid,

      ["@number"] = plt.archiveLightest,
      ["@number.float"] = plt.archiveLightest,

      ["@boolean"] = plt.fadeblackBright,

      ["@function"] = plt.photoBright,
      ["@function.builtin"] = plt.photoBright,
      ["@function.call"] = plt.photoBright,
      ["@function.macro"] = plt.fadeblackMid,
      ["@function.method"] = plt.photoBright,
      ["@function.method.call"] = plt.photoBright,

      ["@constructor"] = plt.photoCore,

      ["@parameter"] = plt.archiveLighter,
      ["@parameter.builtin"] = plt.archiveLightest,

      ["@keyword"] = plt.photoCore,
      ["@keyword.coroutine"] = plt.fadeblackBright,
      ["@keyword.function"] = plt.photoCore,
      ["@keyword.operator"] = plt.archiveMid,
      ["@keyword.return"] = plt.photoCore,
      ["@keyword.import"] = plt.archiveLightest,
      ["@keyword.storage"] = plt.photoCore,
      ["@keyword.repeat"] = plt.photoCore,
      ["@keyword.conditional"] = plt.photoCore,
      ["@keyword.exception"] = plt.fadeblackBright,
      ["@keyword.directive"] = plt.fadeblackMid,
      ["@keyword.directive.define"] = plt.fadeblackMid,

      ["@conditional"] = plt.photoCore,
      ["@conditional.ternary"] = plt.photoCore,

      ["@repeat"] = plt.photoCore,

      ["@label"] = plt.archiveLightest,

      ["@operator"] = plt.archiveMid,

      ["@exception"] = plt.fadeblackBright,

      ["@variable"] = plt.photoCore,
      ["@variable.builtin"] = plt.archiveLightest,
      ["@variable.parameter"] = plt.archiveLighter,
      ["@variable.member"] = plt.photoCore,

      ["@type"] = plt.archiveLightest,
      ["@type.builtin"] = plt.archiveLightest,
      ["@type.definition"] = plt.archiveLightest,
      ["@type.qualifier"] = plt.photoCore,

      ["@attribute"] = plt.photoCore,
      ["@attribute.builtin"] = plt.archiveLightest,

      ["@property"] = plt.photoCore,
      ["@field"] = plt.photoCore,

      ["@module"] = plt.photoCore,
      ["@module.builtin"] = plt.photoCore,

      ["@namespace"] = plt.photoCore,
      ["@namespace.builtin"] = plt.photoCore,

      ["@punctuation.delimiter"] = plt.archiveMid,
      ["@punctuation.bracket"] = plt.archiveMid,
      ["@punctuation.special"] = plt.fadeblackMid,

      ["@tag"] = plt.photoCore,
      ["@tag.attribute"] = plt.archiveLightest,
      ["@tag.delimiter"] = plt.archiveMid,
      ["@tag.builtin"] = plt.photoCore,

      ["@markup.strong"] = { fg = plt.photoBright, bold = true },
      ["@markup.italic"] = { fg = plt.photoCore, italic = true },
      ["@markup.strikethrough"] = { fg = plt.archiveMid, strikethrough = true },
      ["@markup.underline"] = { fg = plt.photoCore, underline = true },
      ["@markup.heading"] = plt.photoBright,
      ["@markup.heading.1"] = plt.photoBright,
      ["@markup.heading.2"] = plt.photoCore,
      ["@markup.heading.3"] = plt.archiveLightest,
      ["@markup.heading.4"] = plt.archiveLighter,
      ["@markup.heading.5"] = plt.fadeblackMid,
      ["@markup.heading.6"] = plt.fadeblackPulse,
      ["@markup.quote"] = plt.archiveBright,
      ["@markup.math"] = plt.archiveLightest,
      ["@markup.link"] = plt.archiveMid,
      ["@markup.link.label"] = plt.fadeblackPulse,
      ["@markup.link.url"] = plt.archiveMid,
      ["@markup.raw"] = plt.archiveLighter,
      ["@markup.raw.block"] = plt.archiveLighter,
      ["@markup.list"] = plt.photoCore,
      ["@markup.list.checked"] = plt.archiveLighter,
      ["@markup.list.unchecked"] = plt.archiveBright,

      ["@diff.plus"] = plt.archiveLighter,
      ["@diff.minus"] = plt.fadeblackBright,
      ["@diff.delta"] = plt.archiveMid,

      ["@none"] = "none",
      ["@conceal"] = plt.archiveMid,
      ["@spell"] = plt.photoCore,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.photoCore,
      ["@constructor.python"] = plt.photoBright,
      ["@constructor.javascript"] = plt.photoBright,
      ["@constructor.typescript"] = plt.photoBright,
      ["@namespace.rust"] = plt.photoCore,
      ["@type.qualifier.rust"] = plt.photoCore,
      ["@constant.macro.c"] = plt.fadeblackMid,
      ["@constant.macro.cpp"] = plt.fadeblackMid,
      ["@namespace.go"] = plt.photoCore,
      ["@property.css"] = plt.photoBright,
      ["@type.css"] = plt.photoCore,
      ["@label.json"] = plt.photoCore,
      ["@field.yaml"] = plt.photoCore,
      ["@property.toml"] = plt.photoCore,
      ["@function.builtin.bash"] = plt.photoBright,
      ["@string.regexp"] = plt.archiveMid,
      ["@character.special.regex"] = plt.fadeblackMid,
    },

    lsp = {
      ["@lsp.type.class"] = plt.archiveLightest,
      ["@lsp.type.interface"] = plt.archiveLightest,
      ["@lsp.type.struct"] = plt.archiveLightest,
      ["@lsp.type.enum"] = plt.archiveLightest,
      ["@lsp.type.enumMember"] = plt.archiveLightest,
      ["@lsp.type.property"] = plt.photoCore,
      ["@lsp.type.namespace"] = plt.photoCore,

      ["@lsp.type.macro"] = plt.fadeblackMid,
      ["@lsp.type.decorator"] = plt.photoBright,

      ["@lsp.type.builtinType"] = plt.archiveLightest,
      ["@lsp.type.selfParameter"] = plt.photoCore,
      ["@lsp.type.typeParameter"] = plt.archiveLightest,

      ["@lsp.type.array"] = plt.archiveLightest,
      ["@lsp.type.object"] = plt.archiveLightest,
      ["@lsp.type.key"] = plt.photoCore,
      ["@lsp.type.null"] = plt.archiveLightest,
      ["@lsp.type.enumConstant"] = plt.archiveLightest,

      ["@lsp.type.event"] = plt.archiveLightest,
      ["@lsp.type.regexp"] = plt.archiveMid,
      ["@lsp.type.unresolvedReference"] = plt.fadeblackBright,

      ["@lsp.mod.deprecated"] = { fg = plt.archiveMid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.archiveLightest,
      ["@lsp.mod.async"] = plt.photoCore,
      ["@lsp.mod.static"] = plt.archiveLightest,
      ["@lsp.mod.abstract"] = plt.archiveLightest,
      ["@lsp.mod.defaultLibrary"] = plt.archiveLightest,
      ["@lsp.mod.documentation"] = plt.archiveBright,
    },
  }
end

return {
  name = "Detox: Sepia",
  author = "PrismPunk.nvim",
  description = "Vintage aged photographs. Faded sepia tones. Historical nostalgia. Without dopamine.",

  base16 = {
    base00 = palette.sepiaVoid,
    base01 = palette.sepiaDark,
    base02 = palette.sepiaDeep,
    base03 = palette.sepiaMid,
    base04 = palette.archiveBright,
    base05 = palette.archiveLightest,
    base06 = palette.photoCore,
    base07 = palette.photoBright,
    base08 = palette.fadeblackBright,
    base09 = palette.fadeblackMid,
    base0A = palette.fadeblackDeep,
    base0B = palette.archiveLighter,
    base0C = palette.fadeblackPulse,
    base0D = palette.archiveMid,
    base0E = palette.fadeblackPulse,
    base0F = palette.archiveMid,
  },

  palette = palette,
  get = M.get,
}
