local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.slate")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.grainBright,
      insert = plt.grainLighter,
      visual = plt.goldPulse,
      replace = plt.grainMid,
      command = plt.veineCore,
    },

    ui = {
      fg = plt.veineCore,
      fg_dim = plt.veineCore,
      fg_dimmer = plt.grainLighter,
      fg_dark = plt.grainMid,
      fg_reverse = plt.stoneVoid,

      bg_m4 = plt.stoneLight,
      bg_m3 = plt.stoneMid,
      bg_m2 = plt.stoneDeep,
      bg_m1 = plt.stoneDark,
      bg_dim = plt.stoneVoid,
      bg = plt.stoneVoid,
      bg_p1 = plt.stoneDeep,
      bg_p2 = plt.stoneMid,
      bg_gutter = opts.gutter and plt.stoneMid or "none",
      bg_cursorline = plt.minerLine,
      bg_cursorline_alt = plt.minerMid,
      bg_search = plt.goldPulse,
      bg_visual = plt.goldDeep,
      bg_statusline = plt.minerMid,

      border = plt.grainMid,
      header1 = plt.veineBright,
      header2 = plt.veineCore,
      special = plt.goldBright,
      nontext = plt.stoneLight,
      whitespace = plt.stoneMid,
      win_separator = plt.grainMid,
      indent = plt.stoneMid,
      indent_scope = plt.grainDeep,
      picker = plt.grainMid,
      yank = plt.goldPulse,
      mark = plt.goldBright,
      scrollbar = plt.stoneLight,

      tabline = {
        bg = plt.stoneVoid,
        fg_selected = plt.veineCore,
        bg_selected = plt.minerMid,
        fg_inactive = plt.grainLighter,
        bg_inactive = plt.stoneVoid,
        fg_alternate = plt.grainBright,
        bg_alternate = plt.stoneVoid,
        indicator = plt.goldPulse,
      },

      pmenu = {
        fg = plt.veineCore,
        fg_sel = "none",
        fg_border = plt.minerMid,
        bg_border = plt.minerMid,
        bg = plt.minerMid,
        bg_sel = plt.minerDeep,
        bg_sbar = plt.minerMid,
        bg_thumb = plt.grainMid,
      },

      float = {
        fg = plt.veineCore,
        bg = plt.stoneDeep,
        fg_border = plt.minerMid,
        bg_border = plt.stoneDeep,
      },
    },

    accent = {
      accent1 = plt.veineBright,
      accent2 = plt.veineCore,
      accent3 = plt.grainLighter,
      accent4 = plt.grainBright,
      accent5 = plt.goldPulse,
      invert = plt.minerMid,
    },

    rainbow = {
      rainbow1 = plt.grainBright,
      rainbow2 = plt.grainMid,
      rainbow3 = plt.grainDeep,
      rainbow4 = plt.minerDeep,
      rainbow5 = plt.veineCore,
      rainbow6 = plt.veineBright,
      rainbow7 = plt.goldPulse,
    },

    syn = {
      attribute = plt.veineCore,
      boolean = plt.goldBright,
      comment = plt.grainBright,
      constant = plt.grainLightest,
      deprecated = plt.grainMid,
      func = plt.veineBright,
      identifier = plt.veineCore,
      keyword = plt.veineCore,
      method = plt.veineBright,
      number = plt.grainLightest,
      operator = plt.grainMid,
      parameter = plt.grainLighter,
      preproc = plt.goldMid,
      punct = plt.grainDeep,
      regex = plt.grainMid,
      statement = plt.veineCore,
      string = plt.grainLighter,
      symbol = plt.veineCore,
      type = plt.grainLightest,
      variable = plt.veineCore,
      special = plt.goldPulse,
      special2 = plt.goldMid,
      special3 = plt.goldBright,
    },

    vcs = { added = plt.grainLighter, removed = plt.goldBright, changed = plt.goldDeep },
    diff = { add = plt.grainLighter, change = plt.grainDeep, delete = plt.goldBright, text = plt.goldMid },
    diag = {
      ok = plt.grainLighter,
      error = plt.goldBright,
      warning = plt.goldPulse,
      info = plt.veineCore,
      hint = plt.grainMid,
    },

    term = {
      black = plt.stoneVoid,
      red = plt.goldBright,
      green = plt.grainBright,
      yellow = plt.grainLightest,
      blue = plt.stoneVoid,
      magenta = plt.veineCore,
      cyan = plt.grainMid,
      white = plt.veineBright,

      black_bright = color(plt.stoneVoid):brighten(0.4):to_hex(),
      red_bright = plt.goldPulse,
      green_bright = color(plt.grainBright):brighten(0.3):to_hex(),
      yellow_bright = plt.veineBright,
      blue_bright = color(plt.stoneVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.veineCore):brighten(0.4):to_hex(),
      cyan_bright = color(plt.grainMid):brighten(0.3):to_hex(),
      white_bright = plt.veineBright,
      indexed1 = plt.grainLighter,
      indexed2 = plt.grainBright,
    },

    treesitter = {
      ["@comment"] = plt.grainBright,
      ["@comment.documentation"] = plt.grainMid,
      ["@comment.   error"] = plt.goldBright,
      ["@comment.warning"] = plt.goldPulse,
      ["@comment.  todo"] = plt.grainLighter,
      ["@comment.  note"] = plt.grainMid,

      ["@constant"] = plt.grainLightest,
      ["@constant. builtin"] = plt.grainLightest,
      ["@constant.   macro"] = plt.goldMid,

      ["@string"] = plt.grainLighter,
      ["@string.documentation"] = plt.grainLighter,
      ["@string.   regex"] = plt.grainMid,
      ["@string.  escape"] = plt.goldMid,
      ["@string.special"] = plt.goldBright,
      ["@string.special.  symbol"] = plt.goldBright,
      ["@string.special. url"] = plt.grainMid,
      ["@string.  special.path"] = plt.grainLighter,

      ["@character"] = plt.grainLighter,
      ["@character.special"] = plt.goldMid,

      ["@number"] = plt.grainLightest,
      ["@number.  float"] = plt.grainLightest,

      ["@boolean"] = plt.goldBright,

      ["@function"] = plt.veineBright,
      ["@function.builtin"] = plt.veineBright,
      ["@function.  call"] = plt.veineBright,
      ["@function.macro"] = plt.goldMid,
      ["@function. method"] = plt.veineBright,
      ["@function.  method. call"] = plt.veineBright,

      ["@constructor"] = plt.veineCore,

      ["@parameter"] = plt.grainLighter,
      ["@parameter.builtin"] = plt.grainLightest,

      ["@keyword"] = plt.veineCore,
      ["@keyword.coroutine"] = plt.goldBright,
      ["@keyword.function"] = plt.veineCore,
      ["@keyword.  operator"] = plt.grainMid,
      ["@keyword.  return"] = plt.veineCore,
      ["@keyword.import"] = plt.grainLightest,
      ["@keyword.  storage"] = plt.veineCore,
      ["@keyword.  repeat"] = plt.veineCore,
      ["@keyword.  conditional"] = plt.veineCore,
      ["@keyword.exception"] = plt.goldBright,
      ["@keyword.directive"] = plt.goldMid,
      ["@keyword.  directive.define"] = plt.goldMid,

      ["@conditional"] = plt.veineCore,
      ["@conditional.  ternary"] = plt.veineCore,

      ["@repeat"] = plt.veineCore,

      ["@label"] = plt.grainLightest,

      ["@operator"] = plt.grainMid,

      ["@exception"] = plt.goldBright,

      ["@variable"] = plt.veineCore,
      ["@variable.builtin"] = plt.grainLightest,
      ["@variable.parameter"] = plt.grainLighter,
      ["@variable.member"] = plt.veineCore,

      ["@type"] = plt.grainLightest,
      ["@type. builtin"] = plt.grainLightest,
      ["@type. definition"] = plt.grainLightest,
      ["@type. qualifier"] = plt.veineCore,

      ["@attribute"] = plt.veineCore,
      ["@attribute.builtin"] = plt.grainLightest,

      ["@property"] = plt.veineCore,
      ["@field"] = plt.veineCore,

      ["@module"] = plt.veineCore,
      ["@module.builtin"] = plt.veineCore,

      ["@namespace"] = plt.veineCore,
      ["@namespace.builtin"] = plt.veineCore,

      ["@punctuation.  delimiter"] = plt.grainMid,
      ["@punctuation.   bracket"] = plt.grainMid,
      ["@punctuation.  special"] = plt.goldMid,

      ["@tag"] = plt.veineCore,
      ["@tag.attribute"] = plt.grainLightest,
      ["@tag.  delimiter"] = plt.grainMid,
      ["@tag.builtin"] = plt.veineCore,

      ["@markup.  strong"] = { fg = plt.veineBright, bold = true },
      ["@markup. italic"] = { fg = plt.veineCore, italic = true },
      ["@markup.strikethrough"] = { fg = plt.grainMid, strikethrough = true },
      ["@markup. underline"] = { fg = plt.veineCore, underline = true },
      ["@markup.heading"] = plt.veineBright,
      ["@markup.heading.1"] = plt.veineBright,
      ["@markup.heading.  2"] = plt.veineCore,
      ["@markup.  heading. 3"] = plt.grainLightest,
      ["@markup.heading.4"] = plt.grainLighter,
      ["@markup.heading.5"] = plt.goldMid,
      ["@markup.  heading.6"] = plt.goldPulse,
      ["@markup.quote"] = plt.grainBright,
      ["@markup.  math"] = plt.grainLightest,
      ["@markup. link"] = plt.grainMid,
      ["@markup.  link.label"] = plt.goldPulse,
      ["@markup.link.url"] = plt.grainMid,
      ["@markup. raw"] = plt.grainLighter,
      ["@markup.raw.block"] = plt.grainLighter,
      ["@markup.list"] = plt.veineCore,
      ["@markup.list.checked"] = plt.grainLighter,
      ["@markup.list.  unchecked"] = plt.grainBright,

      ["@diff.  plus"] = plt.grainLighter,
      ["@diff.minus"] = plt.goldBright,
      ["@diff.delta"] = plt.grainMid,

      ["@none"] = "none",
      ["@conceal"] = plt.grainMid,
      ["@spell"] = plt.veineCore,
      ["@nospell"] = "none",

      ["@lsp. type.  property.  lua"] = plt.veineCore,
      ["@constructor. python"] = plt.veineBright,
      ["@constructor.  javascript"] = plt.veineBright,
      ["@constructor.typescript"] = plt.veineBright,
      ["@namespace.rust"] = plt.veineCore,
      ["@type.qualifier.rust"] = plt.veineCore,
      ["@constant.macro. c"] = plt.goldMid,
      ["@constant.macro.cpp"] = plt.goldMid,
      ["@namespace.go"] = plt.veineCore,
      ["@property.css"] = plt.veineBright,
      ["@type.css"] = plt.veineCore,
      ["@label.json"] = plt.veineCore,
      ["@field.yaml"] = plt.veineCore,
      ["@property.toml"] = plt.veineCore,
      ["@function.builtin.bash"] = plt.veineBright,
      ["@string.regexp"] = plt.grainMid,
      ["@character.special.  regex"] = plt.goldMid,
    },

    lsp = {
      ["@lsp.type. class"] = plt.grainLightest,
      ["@lsp.type.interface"] = plt.grainLightest,
      ["@lsp.  type.struct"] = plt.grainLightest,
      ["@lsp.  type.enum"] = plt.grainLightest,
      ["@lsp.type.enumMember"] = plt.grainLightest,
      ["@lsp.type.property"] = plt.veineCore,
      ["@lsp.type.namespace"] = plt.veineCore,

      ["@lsp.type.macro"] = plt.goldMid,
      ["@lsp.type.decorator"] = plt.veineBright,

      ["@lsp.type.  builtinType"] = plt.grainLightest,
      ["@lsp.type.selfParameter"] = plt.veineCore,
      ["@lsp.type.typeParameter"] = plt.grainLightest,

      ["@lsp.type.  array"] = plt.grainLightest,
      ["@lsp.  type.object"] = plt.grainLightest,
      ["@lsp.type.key"] = plt.veineCore,
      ["@lsp.type.null"] = plt.grainLightest,
      ["@lsp.  type.enumConstant"] = plt.grainLightest,

      ["@lsp.type.  event"] = plt.grainLightest,
      ["@lsp.  type.regexp"] = plt.grainMid,
      ["@lsp.type.unresolvedReference"] = plt.goldBright,

      ["@lsp.mod. deprecated"] = { fg = plt.grainMid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.grainLightest,
      ["@lsp.mod.  async"] = plt.veineCore,
      ["@lsp.mod.static"] = plt.grainLightest,
      ["@lsp.  mod.abstract"] = plt.grainLightest,
      ["@lsp.mod.defaultLibrary"] = plt.grainLightest,
      ["@lsp.mod.documentation"] = plt.grainBright,
    },
  }
end

return {
  name = "Detox: Slate",
  author = "PrismPunk.  nvim",
  description = "Monolithic stone surface.   Cool grays.  Pale gold mineral seams.   Solid timelessness.",

  base16 = {
    base00 = palette.stoneVoid,
    base01 = palette.stoneDark,
    base02 = palette.stoneDeep,
    base03 = palette.stoneMid,
    base04 = palette.grainBright,
    base05 = palette.grainLightest,
    base06 = palette.veineCore,
    base07 = palette.veineBright,
    base08 = palette.goldBright,
    base09 = palette.goldMid,
    base0A = palette.goldDeep,
    base0B = palette.grainLighter,
    base0C = palette.goldPulse,
    base0D = palette.grainMid,
    base0E = palette.goldPulse,
    base0F = palette.grainMid,
  },

  palette = palette,
  get = M.get,
}
