local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.void")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.nullBright,
      insert = plt.nullLighter,
      visual = plt.focusPulse,
      replace = plt.nullMid,
      command = plt.singleCore,
    },

    ui = {
      fg = plt.singleCore,
      fg_dim = plt.singleCore,
      fg_dimmer = plt.nullLighter,
      fg_dark = plt.nullMid,
      fg_reverse = plt.voidVoid,

      bg_m4 = plt.voidLight,
      bg_m3 = plt.voidMid,
      bg_m2 = plt.voidDeep,
      bg_m1 = plt.voidDark,
      bg_dim = plt.voidVoid,
      bg = plt.voidVoid,
      bg_p1 = plt.voidDeep,
      bg_p2 = plt.voidMid,
      bg_gutter = opts.gutter and plt.voidMid or "none",
      bg_cursorline = plt.nothingLine,
      bg_cursorline_alt = plt.nothingMid,
      bg_search = plt.focusPulse,
      bg_visual = plt.focusDeep,
      bg_statusline = plt.nothingMid,

      border = plt.nullMid,
      header1 = plt.singleBright,
      header2 = plt.singleCore,
      special = plt.focusBright,
      nontext = plt.voidLight,
      whitespace = plt.voidMid,
      win_separator = plt.nullMid,
      indent = plt.voidMid,
      indent_scope = plt.nullDeep,
      picker = plt.nullMid,
      yank = plt.focusPulse,
      mark = plt.focusBright,
      scrollbar = plt.voidLight,

      tabline = {
        bg = plt.voidVoid,
        fg_selected = plt.singleCore,
        bg_selected = plt.nothingMid,
        fg_inactive = plt.nullLighter,
        bg_inactive = plt.voidVoid,
        fg_alternate = plt.nullBright,
        bg_alternate = plt.voidVoid,
        indicator = plt.focusPulse,
      },

      pmenu = {
        fg = plt.singleCore,
        fg_sel = "none",
        fg_border = plt.nothingMid,
        bg_border = plt.nothingMid,
        bg = plt.nothingMid,
        bg_sel = plt.nothingDeep,
        bg_sbar = plt.nothingMid,
        bg_thumb = plt.nullMid,
      },

      float = {
        fg = plt.singleCore,
        bg = plt.voidDeep,
        fg_border = plt.nothingMid,
        bg_border = plt.voidDeep,
      },
    },

    accent = {
      accent1 = plt.singleBright,
      accent2 = plt.singleCore,
      accent3 = plt.nullLighter,
      accent4 = plt.nullBright,
      accent5 = plt.focusPulse,
      invert = plt.nothingMid,
    },

    rainbow = {
      rainbow1 = plt.nullBright,
      rainbow2 = plt.nullMid,
      rainbow3 = plt.nullDeep,
      rainbow4 = plt.nothingDeep,
      rainbow5 = plt.singleCore,
      rainbow6 = plt.singleBright,
      rainbow7 = plt.focusPulse,
    },

    syn = {
      attribute = plt.singleCore,
      boolean = plt.focusBright,
      comment = plt.nullBright,
      constant = plt.nullLightest,
      deprecated = plt.nullMid,
      func = plt.singleBright,
      identifier = plt.singleCore,
      keyword = plt.singleCore,
      method = plt.singleBright,
      number = plt.nullLightest,
      operator = plt.nullMid,
      parameter = plt.nullLighter,
      preproc = plt.focusMid,
      punct = plt.nullDeep,
      regex = plt.nullMid,
      statement = plt.singleCore,
      string = plt.nullLighter,
      symbol = plt.singleCore,
      type = plt.nullLightest,
      variable = plt.singleCore,
      special = plt.focusPulse,
      special2 = plt.focusMid,
      special3 = plt.focusBright,
    },

    vcs = { added = plt.nullLighter, removed = plt.focusBright, changed = plt.focusDeep },
    diff = { add = plt.nullLighter, change = plt.nullDeep, delete = plt.focusBright, text = plt.focusMid },
    diag = {
      ok = plt.nullLighter,
      error = plt.focusBright,
      warning = plt.focusPulse,
      info = plt.singleCore,
      hint = plt.nullMid,
    },

    term = {
      black = plt.voidVoid,
      red = plt.focusBright,
      green = plt.nullBright,
      yellow = plt.nullLightest,
      blue = plt.voidVoid,
      magenta = plt.singleCore,
      cyan = plt.nullMid,
      white = plt.singleBright,

      black_bright = color(plt.voidVoid):brighten(0.4):to_hex(),
      red_bright = plt.focusPulse,
      green_bright = color(plt.nullBright):brighten(0.3):to_hex(),
      yellow_bright = plt.singleBright,
      blue_bright = color(plt.voidVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.singleCore):brighten(0.4):to_hex(),
      cyan_bright = color(plt.nullMid):brighten(0.3):to_hex(),
      white_bright = plt.singleBright,
      indexed1 = plt.nullLighter,
      indexed2 = plt.nullBright,
    },

    treesitter = {
      ["@comment"] = plt.nullBright,
      ["@comment.documentation"] = plt.nullMid,
      ["@comment.error"] = plt.focusBright,
      ["@comment.warning"] = plt.focusPulse,
      ["@comment.todo"] = plt.nullLighter,
      ["@comment.note"] = plt.nullMid,

      ["@constant"] = plt.nullLightest,
      ["@constant.builtin"] = plt.nullLightest,
      ["@constant.macro"] = plt.focusMid,

      ["@string"] = plt.nullLighter,
      ["@string.documentation"] = plt.nullLighter,
      ["@string.regex"] = plt.nullMid,
      ["@string.escape"] = plt.focusMid,
      ["@string.special"] = plt.focusBright,
      ["@string.special.symbol"] = plt.focusBright,
      ["@string.special.url"] = plt.nullMid,
      ["@string.special.path"] = plt.nullLighter,

      ["@character"] = plt.nullLighter,
      ["@character.special"] = plt.focusMid,

      ["@number"] = plt.nullLightest,
      ["@number.float"] = plt.nullLightest,

      ["@boolean"] = plt.focusBright,

      ["@function"] = plt.singleBright,
      ["@function.builtin"] = plt.singleBright,
      ["@function.call"] = plt.singleBright,
      ["@function.macro"] = plt.focusMid,
      ["@function.method"] = plt.singleBright,
      ["@function.method.call"] = plt.singleBright,

      ["@constructor"] = plt.singleCore,

      ["@parameter"] = plt.nullLighter,
      ["@parameter.builtin"] = plt.nullLightest,

      ["@keyword"] = plt.singleCore,
      ["@keyword.coroutine"] = plt.focusBright,
      ["@keyword.function"] = plt.singleCore,
      ["@keyword.operator"] = plt.nullMid,
      ["@keyword.return"] = plt.singleCore,
      ["@keyword.import"] = plt.nullLightest,
      ["@keyword.storage"] = plt.singleCore,
      ["@keyword.repeat"] = plt.singleCore,
      ["@keyword.conditional"] = plt.singleCore,
      ["@keyword.exception"] = plt.focusBright,
      ["@keyword.directive"] = plt.focusMid,
      ["@keyword.directive.define"] = plt.focusMid,

      ["@conditional"] = plt.singleCore,
      ["@conditional.ternary"] = plt.singleCore,

      ["@repeat"] = plt.singleCore,

      ["@label"] = plt.nullLightest,

      ["@operator"] = plt.nullMid,

      ["@exception"] = plt.focusBright,

      ["@variable"] = plt.singleCore,
      ["@variable.builtin"] = plt.nullLightest,
      ["@variable.parameter"] = plt.nullLighter,
      ["@variable.member"] = plt.singleCore,

      ["@type"] = plt.nullLightest,
      ["@type.builtin"] = plt.nullLightest,
      ["@type.definition"] = plt.nullLightest,
      ["@type.qualifier"] = plt.singleCore,

      ["@attribute"] = plt.singleCore,
      ["@attribute.builtin"] = plt.nullLightest,

      ["@property"] = plt.singleCore,
      ["@field"] = plt.singleCore,

      ["@module"] = plt.singleCore,
      ["@module.builtin"] = plt.singleCore,

      ["@namespace"] = plt.singleCore,
      ["@namespace.builtin"] = plt.singleCore,

      ["@punctuation.delimiter"] = plt.nullMid,
      ["@punctuation.bracket"] = plt.nullMid,
      ["@punctuation.special"] = plt.focusMid,

      ["@tag"] = plt.singleCore,
      ["@tag.attribute"] = plt.nullLightest,
      ["@tag.delimiter"] = plt.nullMid,
      ["@tag.builtin"] = plt.singleCore,

      ["@markup.strong"] = { fg = plt.singleBright, bold = true },
      ["@markup.italic"] = { fg = plt.singleCore, italic = true },
      ["@markup.strikethrough"] = { fg = plt.nullMid, strikethrough = true },
      ["@markup.underline"] = { fg = plt.singleCore, underline = true },
      ["@markup.heading"] = plt.singleBright,
      ["@markup.heading.1"] = plt.singleBright,
      ["@markup.heading.2"] = plt.singleCore,
      ["@markup.heading.3"] = plt.nullLightest,
      ["@markup.heading.4"] = plt.nullLighter,
      ["@markup.heading.5"] = plt.focusMid,
      ["@markup.heading.6"] = plt.focusPulse,
      ["@markup.quote"] = plt.nullBright,
      ["@markup.math"] = plt.nullLightest,
      ["@markup.link"] = plt.nullMid,
      ["@markup.link.label"] = plt.focusPulse,
      ["@markup.link.url"] = plt.nullMid,
      ["@markup.raw"] = plt.nullLighter,
      ["@markup.raw.block"] = plt.nullLighter,
      ["@markup.list"] = plt.singleCore,
      ["@markup.list.checked"] = plt.nullLighter,
      ["@markup.list.unchecked"] = plt.nullBright,

      ["@diff.plus"] = plt.nullLighter,
      ["@diff.minus"] = plt.focusBright,
      ["@diff.delta"] = plt.nullMid,

      ["@none"] = "none",
      ["@conceal"] = plt.nullMid,
      ["@spell"] = plt.singleCore,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.singleCore,
      ["@constructor.python"] = plt.singleBright,
      ["@constructor.javascript"] = plt.singleBright,
      ["@constructor.typescript"] = plt.singleBright,
      ["@namespace.rust"] = plt.singleCore,
      ["@type.qualifier.rust"] = plt.singleCore,
      ["@constant.macro.c"] = plt.focusMid,
      ["@constant.macro.cpp"] = plt.focusMid,
      ["@namespace.go"] = plt.singleCore,
      ["@property.css"] = plt.singleBright,
      ["@type.css"] = plt.singleCore,
      ["@label.json"] = plt.singleCore,
      ["@field.yaml"] = plt.singleCore,
      ["@property.toml"] = plt.singleCore,
      ["@function.builtin.bash"] = plt.singleBright,
      ["@string.regexp"] = plt.nullMid,
      ["@character.special.regex"] = plt.focusMid,
    },

    lsp = {
      ["@lsp.type.class"] = plt.nullLightest,
      ["@lsp.type.interface"] = plt.nullLightest,
      ["@lsp.type.struct"] = plt.nullLightest,
      ["@lsp.type.enum"] = plt.nullLightest,
      ["@lsp.type.enumMember"] = plt.nullLightest,
      ["@lsp.type.property"] = plt.singleCore,
      ["@lsp.type.namespace"] = plt.singleCore,

      ["@lsp.type.macro"] = plt.focusMid,
      ["@lsp.type.decorator"] = plt.singleBright,

      ["@lsp.type.builtinType"] = plt.nullLightest,
      ["@lsp.type.selfParameter"] = plt.singleCore,
      ["@lsp.type.typeParameter"] = plt.nullLightest,

      ["@lsp.type.array"] = plt.nullLightest,
      ["@lsp.type.object"] = plt.nullLightest,
      ["@lsp.type.key"] = plt.singleCore,
      ["@lsp.type.null"] = plt.nullLightest,
      ["@lsp.type.enumConstant"] = plt.nullLightest,

      ["@lsp.type.event"] = plt.nullLightest,
      ["@lsp.type.regexp"] = plt.nullMid,
      ["@lsp.type.unresolvedReference"] = plt.focusBright,

      ["@lsp.mod.deprecated"] = { fg = plt.nullMid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.nullLightest,
      ["@lsp.mod.async"] = plt.singleCore,
      ["@lsp.mod.static"] = plt.nullLightest,
      ["@lsp.mod.abstract"] = plt.nullLightest,
      ["@lsp.mod.defaultLibrary"] = plt.nullLightest,
      ["@lsp.mod.documentation"] = plt.nullBright,
    },
  }
end

return {
  name = "Detox: Void",
  author = "PrismPunk.nvim",
  description = "True sensory deprivation. Monochrome nothingness. Single cyan focus. Extreme minimalism.",

  base16 = {
    base00 = palette.voidVoid,
    base01 = palette.voidDark,
    base02 = palette.voidDeep,
    base03 = palette.voidMid,
    base04 = palette.nullBright,
    base05 = palette.nullLightest,
    base06 = palette.singleCore,
    base07 = palette.singleBright,
    base08 = palette.focusBright,
    base09 = palette.focusMid,
    base0A = palette.focusDeep,
    base0B = palette.nullLighter,
    base0C = palette.focusPulse,
    base0D = palette.nullMid,
    base0E = palette.focusPulse,
    base0F = palette.nullMid,
  },

  palette = palette,
  get = M.get,
}
