local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.zenpaper")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.brushMid,
      insert = plt.scrollBright,
      visual = plt.brushPulse,
      replace = plt.brushDeep,
      command = plt.scrollBright,
    },

    ui = {
      fg = plt.pensiveCore,
      fg_dim = plt.pensiveCore,
      fg_dimmer = plt.scrollLighter,
      fg_dark = plt.scrollMid,
      fg_reverse = plt.paperVoid,

      bg_m4 = plt.paperLight,
      bg_m3 = plt.paperMid,
      bg_m2 = plt.paperDeep,
      bg_m1 = plt.paperDark,
      bg_dim = plt.paperVoid,
      bg = plt.paperVoid,
      bg_p1 = plt.paperDeep,
      bg_p2 = plt.paperMid,
      bg_gutter = opts.gutter and plt.paperMid or "none",
      bg_cursorline = plt.inkLine,
      bg_cursorline_alt = plt.inkMid,
      bg_search = plt.brushPulse,
      bg_visual = plt.brushDeep,
      bg_statusline = plt.inkMid,

      border = plt.scrollMid,
      header1 = plt.pensiveBright,
      header2 = plt.pensiveCore,
      special = plt.brushBright,
      nontext = plt.paperLight,
      whitespace = plt.paperMid,
      win_separator = plt.scrollMid,
      indent = plt.paperMid,
      indent_scope = plt.scrollDeep,
      picker = plt.scrollMid,
      yank = plt.brushPulse,
      mark = plt.brushBright,
      scrollbar = plt.paperLight,

      tabline = {
        bg = plt.paperVoid,
        fg_selected = plt.pensiveCore,
        bg_selected = plt.inkMid,
        fg_inactive = plt.scrollLighter,
        bg_inactive = plt.paperVoid,
        fg_alternate = plt.scrollBright,
        bg_alternate = plt.paperVoid,
        indicator = plt.brushPulse,
      },

      pmenu = {
        fg = plt.pensiveCore,
        fg_sel = "none",
        fg_border = plt.inkMid,
        bg_border = plt.inkMid,
        bg = plt.inkMid,
        bg_sel = plt.inkDeep,
        bg_sbar = plt.inkMid,
        bg_thumb = plt.scrollMid,
      },

      float = {
        fg = plt.pensiveCore,
        bg = plt.paperDeep,
        fg_border = plt.inkMid,
        bg_border = plt.paperDeep,
      },
    },

    accent = {
      accent1 = plt.pensiveBright,
      accent2 = plt.pensiveCore,
      accent3 = plt.scrollLighter,
      accent4 = plt.scrollBright,
      accent5 = plt.brushPulse,
      invert = plt.inkMid,
    },

    rainbow = {
      rainbow1 = plt.scrollBright,
      rainbow2 = plt.scrollMid,
      rainbow3 = plt.scrollDeep,
      rainbow4 = plt.inkDeep,
      rainbow5 = plt.pensiveCore,
      rainbow6 = plt.pensiveBright,
      rainbow7 = plt.brushPulse,
    },

    syn = {
      attribute = plt.pensiveCore,
      boolean = plt.brushBright,
      comment = plt.scrollBright,
      constant = plt.scrollLightest,
      deprecated = plt.scrollMid,
      func = plt.pensiveBright,
      identifier = plt.pensiveCore,
      keyword = plt.pensiveCore,
      method = plt.pensiveBright,
      number = plt.scrollLightest,
      operator = plt.scrollMid,
      parameter = plt.scrollLighter,
      preproc = plt.brushMid,
      punct = plt.scrollDeep,
      regex = plt.scrollMid,
      statement = plt.pensiveCore,
      string = plt.scrollLighter,
      symbol = plt.pensiveCore,
      type = plt.scrollLightest,
      variable = plt.pensiveCore,
      special = plt.brushPulse,
      special2 = plt.brushMid,
      special3 = plt.brushBright,
    },

    vcs = { added = plt.scrollLighter, removed = plt.brushBright, changed = plt.brushDeep },
    diff = { add = plt.scrollLighter, change = plt.scrollDeep, delete = plt.brushBright, text = plt.brushMid },
    diag = {
      ok = plt.scrollLighter,
      error = plt.brushBright,
      warning = plt.brushPulse,
      info = plt.pensiveCore,
      hint = plt.scrollMid,
    },

    term = {
      black = plt.paperVoid,
      red = plt.brushBright,
      green = plt.scrollBright,
      yellow = plt.scrollLightest,
      blue = plt.paperVoid,
      magenta = plt.pensiveCore,
      cyan = plt.scrollMid,
      white = plt.pensiveBright,

      black_bright = color(plt.paperVoid):brighten(0.4):to_hex(),
      red_bright = plt.brushPulse,
      green_bright = color(plt.scrollBright):brighten(0.3):to_hex(),
      yellow_bright = plt.pensiveBright,
      blue_bright = color(plt.paperVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.pensiveCore):brighten(0.4):to_hex(),
      cyan_bright = color(plt.scrollMid):brighten(0.3):to_hex(),
      white_bright = plt.pensiveBright,
      indexed1 = plt.scrollLighter,
      indexed2 = plt.scrollBright,
    },

    treesitter = {
      ["@comment"] = plt.scrollBright,
      ["@comment. documentation"] = plt.scrollMid,
      ["@comment. error"] = plt.brushBright,
      ["@comment.warning"] = plt.brushPulse,
      ["@comment.todo"] = plt.scrollLighter,
      ["@comment.note"] = plt.scrollMid,

      ["@constant"] = plt.scrollLightest,
      ["@constant.builtin"] = plt.scrollLightest,
      ["@constant. macro"] = plt.brushMid,

      ["@string"] = plt.scrollLighter,
      ["@string.documentation"] = plt.scrollLighter,
      ["@string. regex"] = plt.scrollMid,
      ["@string. escape"] = plt.brushMid,
      ["@string.special"] = plt.brushBright,
      ["@string.special.symbol"] = plt.brushBright,
      ["@string.special.url"] = plt.scrollMid,
      ["@string.special.path"] = plt.scrollLighter,

      ["@character"] = plt.scrollLighter,
      ["@character.special"] = plt.brushMid,

      ["@number"] = plt.scrollLightest,
      ["@number. float"] = plt.scrollLightest,

      ["@boolean"] = plt.brushBright,

      ["@function"] = plt.pensiveBright,
      ["@function.builtin"] = plt.pensiveBright,
      ["@function. call"] = plt.pensiveBright,
      ["@function.macro"] = plt.brushMid,
      ["@function.method"] = plt.pensiveBright,
      ["@function.method.call"] = plt.pensiveBright,

      ["@constructor"] = plt.pensiveCore,

      ["@parameter"] = plt.scrollLighter,
      ["@parameter.builtin"] = plt.scrollLightest,

      ["@keyword"] = plt.pensiveCore,
      ["@keyword.coroutine"] = plt.brushBright,
      ["@keyword.function"] = plt.pensiveCore,
      ["@keyword. operator"] = plt.scrollMid,
      ["@keyword. return"] = plt.pensiveCore,
      ["@keyword.import"] = plt.scrollLightest,
      ["@keyword. storage"] = plt.pensiveCore,
      ["@keyword.repeat"] = plt.pensiveCore,
      ["@keyword.conditional"] = plt.pensiveCore,
      ["@keyword.exception"] = plt.brushBright,
      ["@keyword.directive"] = plt.brushMid,
      ["@keyword. directive.define"] = plt.brushMid,

      ["@conditional"] = plt.pensiveCore,
      ["@conditional. ternary"] = plt.pensiveCore,

      ["@repeat"] = plt.pensiveCore,

      ["@label"] = plt.scrollLightest,

      ["@operator"] = plt.scrollMid,

      ["@exception"] = plt.brushBright,

      ["@variable"] = plt.pensiveCore,
      ["@variable.builtin"] = plt.scrollLightest,
      ["@variable.parameter"] = plt.scrollLighter,
      ["@variable.member"] = plt.pensiveCore,

      ["@type"] = plt.scrollLightest,
      ["@type. builtin"] = plt.scrollLightest,
      ["@type.definition"] = plt.scrollLightest,
      ["@type.qualifier"] = plt.pensiveCore,

      ["@attribute"] = plt.pensiveCore,
      ["@attribute.builtin"] = plt.scrollLightest,

      ["@property"] = plt.pensiveCore,
      ["@field"] = plt.pensiveCore,

      ["@module"] = plt.pensiveCore,
      ["@module.builtin"] = plt.pensiveCore,

      ["@namespace"] = plt.pensiveCore,
      ["@namespace.builtin"] = plt.pensiveCore,

      ["@punctuation. delimiter"] = plt.scrollMid,
      ["@punctuation.bracket"] = plt.scrollMid,
      ["@punctuation.special"] = plt.brushMid,

      ["@tag"] = plt.pensiveCore,
      ["@tag.attribute"] = plt.scrollLightest,
      ["@tag. delimiter"] = plt.scrollMid,
      ["@tag.builtin"] = plt.pensiveCore,

      ["@markup. strong"] = { fg = plt.pensiveBright, bold = true },
      ["@markup.italic"] = { fg = plt.pensiveCore, italic = true },
      ["@markup.strikethrough"] = { fg = plt.scrollMid, strikethrough = true },
      ["@markup.underline"] = { fg = plt.pensiveCore, underline = true },
      ["@markup.heading"] = plt.pensiveBright,
      ["@markup.heading.1"] = plt.pensiveBright,
      ["@markup.heading.2"] = plt.pensiveCore,
      ["@markup. heading.3"] = plt.scrollLightest,
      ["@markup.heading.4"] = plt.scrollLighter,
      ["@markup.heading.5"] = plt.brushMid,
      ["@markup.heading.6"] = plt.brushPulse,
      ["@markup.quote"] = plt.scrollBright,
      ["@markup. math"] = plt.scrollLightest,
      ["@markup. link"] = plt.scrollMid,
      ["@markup. link.label"] = plt.brushPulse,
      ["@markup.link.url"] = plt.scrollMid,
      ["@markup. raw"] = plt.scrollLighter,
      ["@markup.raw.block"] = plt.scrollLighter,
      ["@markup.list"] = plt.pensiveCore,
      ["@markup.list.checked"] = plt.scrollLighter,
      ["@markup.list.unchecked"] = plt.scrollBright,

      ["@diff. plus"] = plt.scrollLighter,
      ["@diff.minus"] = plt.brushBright,
      ["@diff.delta"] = plt.scrollMid,

      ["@none"] = "none",
      ["@conceal"] = plt.scrollMid,
      ["@spell"] = plt.pensiveCore,
      ["@nospell"] = "none",

      ["@lsp.type. property. lua"] = plt.pensiveCore,
      ["@constructor.python"] = plt.pensiveBright,
      ["@constructor.javascript"] = plt.pensiveBright,
      ["@constructor.typescript"] = plt.pensiveBright,
      ["@namespace.rust"] = plt.pensiveCore,
      ["@type.qualifier.rust"] = plt.pensiveCore,
      ["@constant.macro.c"] = plt.brushMid,
      ["@constant.macro.cpp"] = plt.brushMid,
      ["@namespace.go"] = plt.pensiveCore,
      ["@property.css"] = plt.pensiveBright,
      ["@type.css"] = plt.pensiveCore,
      ["@label.json"] = plt.pensiveCore,
      ["@field.yaml"] = plt.pensiveCore,
      ["@property.toml"] = plt.pensiveCore,
      ["@function.builtin.bash"] = plt.pensiveBright,
      ["@string.regexp"] = plt.scrollMid,
      ["@character.special. regex"] = plt.brushMid,
    },

    lsp = {
      ["@lsp.type.class"] = plt.scrollLightest,
      ["@lsp.type.interface"] = plt.scrollLightest,
      ["@lsp. type.struct"] = plt.scrollLightest,
      ["@lsp. type.enum"] = plt.scrollLightest,
      ["@lsp.type.enumMember"] = plt.scrollLightest,
      ["@lsp.type.property"] = plt.pensiveCore,
      ["@lsp.type.namespace"] = plt.pensiveCore,

      ["@lsp.type.macro"] = plt.brushMid,
      ["@lsp.type.decorator"] = plt.pensiveBright,

      ["@lsp.type. builtinType"] = plt.scrollLightest,
      ["@lsp.type.selfParameter"] = plt.pensiveCore,
      ["@lsp.type.typeParameter"] = plt.scrollLightest,

      ["@lsp.type.array"] = plt.scrollLightest,
      ["@lsp. type.object"] = plt.scrollLightest,
      ["@lsp.type.key"] = plt.pensiveCore,
      ["@lsp.type.null"] = plt.scrollLightest,
      ["@lsp. type.enumConstant"] = plt.scrollLightest,

      ["@lsp.type. event"] = plt.scrollLightest,
      ["@lsp. type.regexp"] = plt.scrollMid,
      ["@lsp.type.unresolvedReference"] = plt.brushBright,

      ["@lsp.mod.deprecated"] = { fg = plt.scrollMid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.scrollLightest,
      ["@lsp.mod.async"] = plt.pensiveCore,
      ["@lsp.mod.static"] = plt.scrollLightest,
      ["@lsp. mod.abstract"] = plt.scrollLightest,
      ["@lsp.mod.defaultLibrary"] = plt.scrollLightest,
      ["@lsp.mod.documentation"] = plt.scrollBright,
    },
  }
end

return {
  name = "Detox: Zenpaper",
  author = "PrismPunk. nvim",
  description = "Warm paper tones.  Natural ink warmth.  Contemplative browns. The journal beneath dopamine.",

  base16 = {
    base00 = palette.paperVoid,
    base01 = palette.paperDark,
    base02 = palette.paperDeep,
    base03 = palette.paperMid,
    base04 = palette.scrollBright,
    base05 = palette.scrollLightest,
    base06 = palette.pensiveCore,
    base07 = palette.pensiveBright,
    base08 = palette.brushBright,
    base09 = palette.brushMid,
    base0A = palette.brushDeep,
    base0B = palette.scrollLighter,
    base0C = palette.brushPulse,
    base0D = palette.scrollMid,
    base0E = palette.brushPulse,
    base0F = palette.scrollMid,
  },

  palette = palette,
  get = M.get,
}
