local palette = {
  paperWhite = "#F2EBD9",
  lightBeige = "#EAE3D2",
  warmIvory = "#E2DAC7",
  shadowBeige = "#D8D0BC",
  inkGray = "#A8A29E",
  graphiteGray = "#6E6A67",
  sumiInkSoft = "#4C4945",

  autumnRed = "#B4637A",
  autumnYellow = "#DFA000",
  autumnGreen = "#6B8E23",
  waveBlue1 = "#446488",
  waveAqua1 = "#4FA6A1",
  springViolet1 = "#8A77B7",
  springViolet2 = "#9C88C8",
  sandTan = "#CBBE9F",
  roseDust = "#C47F8E",

  morningSky = "#A3BCE2",
  paleCoral = "#E99B8F",
  mellowGold = "#E4B564",
  blushPink = "#E5A4A2",
  earlyMist = "#B4ADA4",
  amberDawn = "#FFD58A",
}

return {
  name = "Kanagawa Paper – Dawn",
  author = "PrismPunk.nvim",
  description = "Light mode – serene parchment with soft warmth and subtle ink contrast.",

  base16 = {
    base00 = palette.paperWhite,
    base01 = palette.lightBeige,
    base02 = palette.warmIvory,
    base03 = palette.shadowBeige,
    base04 = palette.inkGray,
    base05 = palette.graphiteGray,
    base06 = palette.sumiInkSoft,
    base07 = palette.springViolet2,
    base08 = palette.autumnRed,
    base09 = palette.mellowGold,
    base0A = palette.amberDawn,
    base0B = palette.autumnGreen,
    base0C = palette.waveAqua1,
    base0D = palette.waveBlue1,
    base0E = palette.springViolet1,
    base0F = palette.sandTan,
  },

  palette = palette,

  semantic = {
    syn = {
      string = palette.paleCoral,
      number = palette.mellowGold,
      boolean = palette.waveAqua1,
      keyword = palette.autumnRed,
      operator = palette.mellowGold,
      func = palette.waveBlue1,
      type = palette.springViolet1,
      variable = palette.graphiteGray,
      comment = palette.earlyMist,
      constant = palette.sandTan,
      special = palette.blushPink,
      string_escape = palette.mellowGold,
      type_builtin = palette.springViolet2,
      method = palette.waveBlue1,
      attribute = palette.sandTan,
      punctuation = palette.blushPink,
    },

    ui = {
      bg = palette.paperWhite,
      bg_dim = palette.lightBeige,
      bg_highlight = palette.warmIvory,
      fg = palette.graphiteGray,
      fg_dim = palette.earlyMist,
      fg_bright = palette.sumiInkSoft,
      border = palette.sandTan,
      float = palette.warmIvory,
      selection = palette.shadowBeige,
      cursorline = palette.lightBeige,
      line_nr = palette.earlyMist,
      line_nr_active = palette.waveBlue1,
      line_nr_dim = palette.inkGray,
      nontext = palette.shadowBeige,
      msg_area = palette.lightBeige,
      mode_msg = palette.waveAqua1,
      title = palette.springViolet2,
      spell_bad = palette.autumnRed,
      spell_cap = palette.mellowGold,
      spell_rare = palette.morningSky,
      spell_local = palette.autumnGreen,
      folded = palette.earlyMist,
      fold_column = palette.inkGray,
    },

    diag = {
      error = palette.autumnRed,
      warning = palette.mellowGold,
      info = palette.morningSky,
      hint = palette.autumnGreen,
      ok = palette.waveAqua1,
      virtual_text_error = palette.autumnRed,
      virtual_text_warning = palette.mellowGold,
      virtual_text_info = palette.morningSky,
      virtual_text_hint = palette.autumnGreen,
      virtual_text_ok = palette.waveAqua1,
    },

    git = {
      add = palette.autumnGreen,
      change = palette.mellowGold,
      delete = palette.autumnRed,
      add_inline = palette.autumnGreen,
      change_inline = palette.mellowGold,
      delete_inline = palette.autumnRed,
    },

    diff = {
      add = palette.autumnGreen,
      change = palette.mellowGold,
      delete = palette.autumnRed,
      text = palette.morningSky,
    },
  },
}
