local colors_util = require("pantheon.utils.colors")

local palette = {
    cosmicBlack = "#060609",
    voidBlack = "#0b0b0f",
    starlightGray = "#121218",
    nebulaGray = "#1a1a23",
    suitPurple = "#5b2c6f",
    beltGold = "#d4af37",
    glovesGray = "#1a1a1a",
    bootsGray = "#1a1a1a",
    shadowGray = "#3a3f4c",
    dimGray = "#565c64",
    stoneGray = "#abb2bf",
    lightGray = "#c8ccd4",
    dangerRed = "#e06c75",
    infoBlue = "#61afef",
    tealGlow = "#00ddaa",
}

return {
    name = "Batgirl",
    author = "Pantheon.nvim",
    palette = palette,

    base16 = {
        base00 = palette.cosmicBlack,
        base01 = palette.voidBlack,
        base02 = palette.starlightGray,
        base03 = palette.shadowGray,
        base04 = palette.dimGray,
        base05 = palette.stoneGray,
        base06 = palette.lightGray,
        base07 = palette.beltGold,
        base08 = palette.dangerRed,
        base09 = palette.beltGold,
        base0A = palette.beltGold,
        base0B = palette.tealGlow,
        base0C = palette.tealGlow,
        base0D = palette.infoBlue,
        base0E = palette.glovesGray,
        base0F = palette.suitPurple,
    },

    semantic = {
        syn = {
            string = palette.suitPurple,
            number = palette.beltGold,
            boolean = palette.beltGold,
            keyword = palette.suitPurple,
            operator = palette.tealGlow,
            func = palette.infoBlue,
            type = palette.beltGold,
            variable = palette.stoneGray,
            comment = palette.shadowGray,
            constant = palette.beltGold,
            special = palette.suitPurple,
        },
        ui = {
            bg = palette.cosmicBlack,
            bg_dim = palette.voidBlack,
            bg_highlight = palette.starlightGray,
            fg = palette.stoneGray,
            fg_dim = palette.dimGray,
            fg_bright = palette.beltGold,
            border = palette.suitPurple,
            float = palette.voidBlack,
            selection = palette.nebulaGray,
            cursorline = palette.voidBlack,
            line_nr = palette.shadowGray,
            line_nr_active = palette.beltGold,
        },
        diag = {
            error = palette.dangerRed,
            warning = palette.beltGold,
            info = palette.infoBlue,
            hint = palette.tealGlow,
        },
        git = {
            add = palette.beltGold,
            change = palette.suitPurple,
            delete = palette.dangerRed,
        },
        diff = {
            add = palette.beltGold,
            change = palette.suitPurple,
            delete = palette.dangerRed,
            text = palette.infoBlue,
        },
    },
}
