local colors_util = require("pantheon.utils.colors")

local palette = {
    cosmicBlack = "#0b0604",
    voidBlack = "#130d0a",
    starlightGray = "#1a1410",
    nebulaGray = "#241e1a",
    jacketBrown = "#5c4033",
    vestBurgundy = "#6b1e23",
    shirtCream = "#d6c5a1",
    tieGold = "#bfa334",
    trousersCharcoal = "#2b2b2b",
    shoesBlack = "#111111",
    shadowGray = "#3a3f4c",
    dimGray = "#565c64",
    stoneGray = "#abb2bf",
    lightGray = "#c8ccd4",
    dangerRed = "#e06c75",
    infoBlue = "#61afef",
    tealGlow = "#00ddaa",
}

return {
    name = "Bruce Wayne",
    author = "Pantheon.nvim",
    palette = palette,

    base16 = {
        base00 = palette.cosmicBlack,
        base01 = palette.voidBlack,
        base02 = palette.starlightGray,
        base03 = palette.shadowGray,
        base04 = palette.dimGray,
        base05 = palette.stoneGray,
        base06 = palette.lightGray,
        base07 = palette.tieGold,
        base08 = palette.dangerRed,
        base09 = palette.vestBurgundy,
        base0A = palette.tieGold,
        base0B = palette.tealGlow,
        base0C = palette.tealGlow,
        base0D = palette.infoBlue,
        base0E = palette.jacketBrown,
        base0F = palette.shoesBlack,
    },

    semantic = {
        syn = {
            string = palette.jacketBrown,
            number = palette.tieGold,
            boolean = palette.vestBurgundy,
            keyword = palette.trousersCharcoal,
            operator = palette.tealGlow,
            func = palette.infoBlue,
            type = palette.tieGold,
            variable = palette.stoneGray,
            comment = palette.shadowGray,
            constant = palette.tieGold,
            special = palette.jacketBrown,
        },
        ui = {
            bg = palette.cosmicBlack,
            bg_dim = palette.voidBlack,
            bg_highlight = palette.starlightGray,
            fg = palette.stoneGray,
            fg_dim = palette.dimGray,
            fg_bright = palette.tieGold,
            border = palette.trousersCharcoal,
            float = palette.voidBlack,
            selection = palette.nebulaGray,
            cursorline = palette.voidBlack,
            line_nr = palette.shadowGray,
            line_nr_active = palette.jacketBrown,
        },
        diag = {
            error = palette.dangerRed,
            warning = palette.tieGold,
            info = palette.infoBlue,
            hint = palette.tealGlow,
        },
        git = {
            add = palette.tieGold,
            change = palette.jacketBrown,
            delete = palette.dangerRed,
        },
        diff = {
            add = palette.tieGold,
            change = palette.trousersCharcoal,
            delete = palette.dangerRed,
            text = palette.infoBlue,
        },
    },
}
