local colors_util = require("pantheon.utils.colors")

local palette = {
  cosmicBlack = "#060609",
  voidBlack = "#0b0b0f",
  starlightGray = "#121218",
  nebulaGray = "#1a1a23",
  trenchBrown = "#4b3621",
  coatGray = "#2b2b2b",
  tieDarkRed = "#8b0000",
  glovesGray = "#1a1a1a",
  bootsBlack = "#0e0e0e",
  shadowGray = "#3a3f4c",
  dimGray = "#565c64",
  stoneGray = "#abb2bf",
  lightGray = "#c8ccd4",
  dangerRed = "#e06c75",
  infoBlue = "#61afef",
  tealGlow = "#00ddaa",
}

return {
  name = "James Gordon",
  author = "Pantheon.nvim",
  palette = palette,

  base16 = {
    base00 = palette.cosmicBlack,
    base01 = palette.voidBlack,
    base02 = palette.starlightGray,
    base03 = palette.shadowGray,
    base04 = palette.dimGray,
    base05 = palette.stoneGray,
    base06 = palette.lightGray,
    base07 = palette.tieDarkRed,
    base08 = palette.dangerRed,
    base09 = palette.trenchBrown,
    base0A = palette.tieDarkRed,
    base0B = palette.tealGlow,
    base0C = palette.tealGlow,
    base0D = palette.infoBlue,
    base0E = palette.coatGray,
    base0F = palette.glovesGray,
  },

  semantic = {
    syn = {
      string = palette.coatGray,
      number = palette.trenchBrown,
      boolean = palette.tieDarkRed,
      keyword = palette.coatGray,
      operator = palette.tealGlow,
      func = palette.infoBlue,
      type = palette.trenchBrown,
      variable = palette.stoneGray,
      comment = palette.shadowGray,
      constant = palette.tieDarkRed,
      special = palette.coatGray,
    },
    ui = {
      bg = palette.cosmicBlack,
      bg_dim = palette.voidBlack,
      bg_highlight = palette.starlightGray,
      fg = palette.stoneGray,
      fg_dim = palette.dimGray,
      fg_bright = palette.tieDarkRed,
      border = palette.coatGray,
      float = palette.voidBlack,
      selection = palette.nebulaGray,
      cursorline = palette.voidBlack,
      line_nr = palette.shadowGray,
      line_nr_active = palette.trenchBrown,
    },
    diag = {
      error = palette.dangerRed,
      warning = palette.tieDarkRed,
      info = palette.infoBlue,
      hint = palette.tealGlow,
    },
    git = {
      add = palette.trenchBrown,
      change = palette.coatGray,
      delete = palette.dangerRed,
    },
    diff = {
      add = palette.trenchBrown,
      change = palette.coatGray,
      delete = palette.dangerRed,
      text = palette.infoBlue,
    },
  },
}
