local colors_util = require("pantheon.utils.colors")

local palette = {
    cosmicBlack = "#060608",
    voidBlack = "#0b0b0f",
    starlightGray = "#121218",
    nebulaGray = "#1a1a23",
    dressBurgundy = "#800020",
    glovesGray = "#1a1a1a",
    bootsBlack = "#0e0e0e",
    shadowGray = "#3a3f4c",
    dimGray = "#565c64",
    stoneGray = "#abb2bf",
    lightGray = "#c8ccd4",
    accentGold = "#d4af37",
    dangerRed = "#e06c75",
    infoBlue = "#61afef",
    tealGlow = "#00ddaa",
}

return {
    name = "Martha Wayne",
    author = "Pantheon.nvim",
    palette = palette,
    base16 = {
        base00 = palette.cosmicBlack,
        base01 = palette.voidBlack,
        base02 = palette.starlightGray,
        base03 = palette.shadowGray,
        base04 = palette.dimGray,
        base05 = palette.stoneGray,
        base06 = palette.lightGray,
        base07 = palette.dressBurgundy,
        base08 = palette.dangerRed,
        base09 = palette.accentGold,
        base0A = palette.dressBurgundy,
        base0B = palette.tealGlow,
        base0C = palette.tealGlow,
        base0D = palette.infoBlue,
        base0E = palette.glovesGray,
        base0F = palette.bootsBlack,
    },
    semantic = {
        syn = {
            string = palette.dressBurgundy,
            number = palette.accentGold,
            boolean = palette.dressBurgundy,
            keyword = palette.dressBurgundy,
            operator = palette.tealGlow,
            func = palette.infoBlue,
            type = palette.accentGold,
            variable = palette.stoneGray,
            comment = palette.shadowGray,
            constant = palette.accentGold,
            special = palette.dressBurgundy,
        },
        ui = {
            bg = palette.cosmicBlack,
            bg_dim = palette.voidBlack,
            bg_highlight = palette.starlightGray,
            fg = palette.stoneGray,
            fg_dim = palette.dimGray,
            fg_bright = palette.accentGold,
            border = palette.dressBurgundy,
            float = palette.voidBlack,
            selection = palette.nebulaGray,
            cursorline = palette.voidBlack,
            line_nr = palette.shadowGray,
            line_nr_active = palette.accentGold,
        },
        diag = {
            error = palette.dangerRed,
            warning = palette.accentGold,
            info = palette.infoBlue,
            hint = palette.tealGlow,
        },
        git = {
            add = palette.accentGold,
            change = palette.dressBurgundy,
            delete = palette.dangerRed,
        },
        diff = {
            add = palette.accentGold,
            change = palette.dressBurgundy,
            delete = palette.dangerRed,
            text = palette.infoBlue,
        },
    },
}
