local colors_util = require("pantheon.utils.colors")

local palette = {
  cosmicBlack = "#060609",
  voidBlack = "#0b0b0f",
  starlightGray = "#121218",
  nebulaGray = "#1a1a23",
  suitBlack = "#0e0e0e",
  electricBlue = "#1e90ff",
  glovesGray = "#1a1a1a",
  bootsGray = "#1a1a1a",
  beltSilver = "#c0c0c0",
  shadowGray = "#3a3f4c",
  dimGray = "#565c64",
  stoneGray = "#abb2bf",
  lightGray = "#c8ccd4",
  dangerRed = "#e06c75",
  infoBlue = "#61afef",
  tealGlow = "#00ddaa",
}

return {
  name = "Nightwing",
  author = "Pantheon.nvim",
  palette = palette,

  base16 = {
    base00 = palette.cosmicBlack,
    base01 = palette.voidBlack,
    base02 = palette.starlightGray,
    base03 = palette.shadowGray,
    base04 = palette.dimGray,
    base05 = palette.stoneGray,
    base06 = palette.lightGray,
    base07 = palette.electricBlue,
    base08 = palette.dangerRed,
    base09 = palette.beltSilver,
    base0A = palette.electricBlue,
    base0B = palette.tealGlow,
    base0C = palette.tealGlow,
    base0D = palette.infoBlue,
    base0E = palette.glovesGray,
    base0F = palette.suitBlack,
  },

  semantic = {
    syn = {
      string = palette.suitBlack,
      number = palette.beltSilver,
      boolean = palette.electricBlue,
      keyword = palette.suitBlack,
      operator = palette.tealGlow,
      func = palette.infoBlue,
      type = palette.beltSilver,
      variable = palette.stoneGray,
      comment = palette.shadowGray,
      constant = palette.electricBlue,
      special = palette.suitBlack,
    },
    ui = {
      bg = palette.cosmicBlack,
      bg_dim = palette.voidBlack,
      bg_highlight = palette.starlightGray,
      fg = palette.stoneGray,
      fg_dim = palette.dimGray,
      fg_bright = palette.electricBlue,
      border = palette.suitBlack,
      float = palette.voidBlack,
      selection = palette.nebulaGray,
      cursorline = palette.voidBlack,
      line_nr = palette.shadowGray,
      line_nr_active = palette.electricBlue,
    },
    diag = {
      error = palette.dangerRed,
      warning = palette.beltSilver,
      info = palette.infoBlue,
      hint = palette.tealGlow,
    },
    git = {
      add = palette.electricBlue,
      change = palette.suitBlack,
      delete = palette.dangerRed,
    },
    diff = {
      add = palette.electricBlue,
      change = palette.suitBlack,
      delete = palette.dangerRed,
      text = palette.infoBlue,
    },
  },
}
