local colors_util = require("pantheon.utils.colors")

local palette = {
  cosmicBlack = "#050609",
  voidBlack = "#0a0d13",
  starlightGray = "#12151f",
  nebulaGray = "#1a1e28",
  suitBlack = "#0e0e0e",
  techBlue = "#00aaff",
  techRed = "#ff1a1a",
  glovesGray = "#1f1f1f",
  bootsGray = "#1f1f1f",
  beltMetal = "#bfa334",
  shadowGray = "#3a3f4c",
  dimGray = "#565c64",
  stoneGray = "#abb2bf",
  lightGray = "#c8ccd4",
  dangerRed = "#e06c75",
  infoBlue = "#61afef",
  tealGlow = "#00ddaa",
}

return {
  name = "Terry McGinnis",
  author = "Pantheon.nvim",
  palette = palette,
  base16 = {
    base00 = palette.cosmicBlack,
    base01 = palette.voidBlack,
    base02 = palette.starlightGray,
    base03 = palette.shadowGray,
    base04 = palette.dimGray,
    base05 = palette.stoneGray,
    base06 = palette.lightGray,
    base07 = palette.techRed,
    base08 = palette.dangerRed,
    base09 = palette.beltMetal,
    base0A = palette.techRed,
    base0B = palette.tealGlow,
    base0C = palette.tealGlow,
    base0D = palette.infoBlue,
    base0E = palette.techBlue,
    base0F = palette.glovesGray,
  },
  semantic = {
    syn = {
      string = palette.techBlue,
      number = palette.beltMetal,
      boolean = palette.techRed,
      keyword = palette.suitBlack,
      operator = palette.tealGlow,
      func = palette.infoBlue,
      type = palette.beltMetal,
      variable = palette.stoneGray,
      comment = palette.shadowGray,
      constant = palette.techRed,
      special = palette.techBlue,
    },
    ui = {
      bg = palette.cosmicBlack,
      bg_dim = palette.voidBlack,
      bg_highlight = palette.starlightGray,
      fg = palette.stoneGray,
      fg_dim = palette.dimGray,
      fg_bright = palette.techRed,
      border = palette.suitBlack,
      float = palette.voidBlack,
      selection = palette.nebulaGray,
      cursorline = palette.voidBlack,
      line_nr = palette.shadowGray,
      line_nr_active = palette.techBlue,
    },
    diag = {
      error = palette.dangerRed,
      warning = palette.beltMetal,
      info = palette.infoBlue,
      hint = palette.tealGlow,
    },
    git = {
      add = palette.techRed,
      change = palette.techBlue,
      delete = palette.dangerRed,
    },
    diff = {
      add = palette.techRed,
      change = palette.suitBlack,
      delete = palette.dangerRed,
      text = palette.infoBlue,
    },
  },
}
