-- lua/prismpunk/core/terminal/alacritty.lua
local M = {}

--- Generate alacritty YAML TOML-like (simple) output
--- @param theme table
function M.generate(theme)
  local t = theme and theme.term or {}
  local function s(k) return t[k] or "NONE" end
  local lines = {
    "# Generated by prismpunk.nvim",
    "colors:",
    "  primary:",
    ("    background: \"%s\""):format(s("black")),
    ("    foreground: \"%s\""):format(s("white")),
    "  normal:",
    ("    black: \"%s\""):format(s("black")),
    ("    red: \"%s\""):format(s("red")),
    ("    green: \"%s\""):format(s("green")),
    ("    yellow: \"%s\""):format(s("yellow")),
    ("    blue: \"%s\""):format(s("blue")),
    ("    magenta: \"%s\""):format(s("magenta")),
    ("    cyan: \"%s\""):format(s("cyan")),
    ("    white: \"%s\""):format(s("white")),
  }
  return table.concat(lines, "\n")
end

function M.write(theme, path)
  assert(path, "alacritty.write path required")
  local f, err = io.open(path, "w")
  if not f then error(("alacritty: failed to open %s: %s"):format(path, err)) end
  f:write(M.generate(theme))
  f:close()
end

return M
