-- lua/prismpunk/core/terminal/ghostty.lua
local M = {}

--- Generate a ghostty TOML theme string from theme.term or palette
--- @param theme table
function M.generate(theme)
  local t = theme and theme.term or {}
  -- minimal ghostty toml output - extend as needed
  local function z(k) return t[k] or "none" end
  local lines = {
    "# Generated by prismpunk.nvim",
    ("foreground = \"%s\""):format(t.white or z("white") or "NONE"),
    ("background = \"%s\""):format(t.black or z("black") or "NONE"),
    ("red = \"%s\""):format(t.red or "NONE"),
    ("green = \"%s\""):format(t.green or "NONE"),
    ("yellow = \"%s\""):format(t.yellow or "NONE"),
    ("blue = \"%s\""):format(t.blue or "NONE"),
    ("magenta = \"%s\""):format(t.magenta or "NONE"),
    ("cyan = \"%s\""):format(t.cyan or "NONE"),
    ("white = \"%s\""):format(t.white or "NONE"),
  }
  return table.concat(lines, "\n")
end

function M.write(theme, path)
  assert(path, "ghostty.write path required")
  local content = M.generate(theme)
  local f, err = io.open(path, "w")
  if not f then error(("ghostty: failed to open %s: %s"):format(path, err)) end
  f:write(content)
  f:close()
end

return M
