local M = {}

local punkpalette = require("prismpunk.palette")
local punkconf = require("prismpunk.config")

M.export_toml = function(theme)
  local c = theme.colors
  local lines = {
    "# " .. theme.name,
    "# Generated by prismpunk.nvim",
    "# " .. os.date("%Y-%m-%d %H:%M:%S"),
    "",
    "palette = 0=" .. c.base00,
    "palette = 1=" .. c.base08,
    "palette = 2=" .. c.base0B,
    "palette = 3=" .. c.base0A,
    "palette = 4=" .. c.base0D,
    "palette = 5=" .. c.base0E,
    "palette = 6=" .. c.base0C,
    "palette = 7=" .. c.base05,
    "palette = 8=" .. c.base03,
    "palette = 9=" .. c.base08,
    "palette = 10=" .. c.base0B,
    "palette = 11=" .. c.base0A,
    "palette = 12=" .. c.base0D,
    "palette = 13=" .. c.base0E,
    "palette = 14=" .. c.base0C,
    "palette = 15=" .. c.base07,
    "background = " .. c.base00,
    "foreground = " .. c.base05,
    "cursor-color = " .. c.base05,
    "cursor-text = " .. c.base00,
    "selection-background = " .. c.base02,
    "selection-foreground = " .. c.base05,
  }
  return table.concat(lines, "\n")
end

M.write_config = function(theme, path)
  local content = M.export_toml(theme)
  path = vim.fn.expand(path)
  vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
  local file = io.open(path, "w")
  if not file then
    vim.notify("Prismpunk: Failed to write " .. path, vim.log.levels.ERROR)
    return false
  end
  file:write(content)
  file:close()
  return true
end

M.reload = function()
  vim.fn.system("pgrep -x ghostty | xargs -r kill -USR2")
  if vim.v.shell_error == 0 then return true end
  vim.fn.system("pkill -USR2 ghostty")
  return vim.v.shell_error == 0
end

M.export_and_reload = function(theme, conf)
  local success = M.write_config(theme, conf.config_path)
  if success and conf.auto_reload then
    if not M.reload() then
      vim.notify("Prismpunk: Failed to reload Ghostty automatically", vim.log.levels.WARN)
    end
  end
end

M.export = function(theme_name)
  local universe, variant = punkconf.parse_theme(theme_name)
  local ok, spec = pcall(require, "prismpunk.themes." .. universe:gsub("%-", "%.") .. "." .. variant)
  if not ok then
    vim.notify("Failed to load theme: " .. theme_name, vim.log.levels.ERROR)
    return nil
  end
  return M.export_toml(punkpalette.create_theme(spec))
end

M.save = function(theme_name, output_path)
  output_path = output_path or vim.fn.expand("~/.config/ghostty/themes/prismpunk.toml")
  local universe, variant = punkconf.parse_theme(theme_name)
  local ok, spec = pcall(require, "prismpunk.themes." .. universe:gsub("%-", "%.") .. "." .. variant)
  if not ok then
    vim.notify("Failed to load theme: " .. theme_name, vim.log.levels.ERROR)
    return
  end
  local success = M.write_config(punkpalette.create_theme(spec), output_path)
  if success then vim.notify("Exported to: " .. output_path, vim.log.levels.INFO) end
end

return M
