-- lua/prismpunk/core/terminal/kitty.lua
local M = {}

function M.generate(theme)
  local t = theme and theme.term or {}
  local function s(k) return t[k] or "NONE" end
  local lines = {
    "# Generated by prismpunk.nvim",
    ("foreground %s"):format(s("white")),
    ("background %s"):format(s("black")),
    ("color0 %s"):format(s("black")),
    ("color1 %s"):format(s("red")),
    ("color2 %s"):format(s("green")),
    ("color3 %s"):format(s("yellow")),
    ("color4 %s"):format(s("blue")),
    ("color5 %s"):format(s("magenta")),
    ("color6 %s"):format(s("cyan")),
    ("color7 %s"):format(s("white")),
  }
  return table.concat(lines, "\n")
end

function M.write(theme, path)
  assert(path, "kitty.write path required")
  local f, err = io.open(path, "w")
  if not f then error(("kitty: failed to open %s: %s"):format(path, err)) end
  f:write(M.generate(theme))
  f:close()
end

return M
